/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.GaugeAlgebra.Basic
public import Physlib.Particles.StandardModel.GaugeAlgebra.Basis
public import Physlib.Relativity.IsLorentzDeriv
public import Mathlib.Algebra.Polynomial.AlgebraMap
/-!
# The gauge sector

The field-strength symbol family `F`, indexed by ordered tuples of
covariant-derivative directions and two covector indices, forms a *gauge sector* of
the algebra `B` when: it transforms under the global gauge group through the adjoint
action on its dual value index, under the Lorentz group as the covariant derivatives
of a two-index Lorentz tensor, and each tower is a `massWeightPoly`-eigenvector of
weight `2 * (2 + n)` (mass dimension `2 + n`).

-/

@[expose] public section

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz

/-- The field strength and its covariant derivatives as a sector of the algebra `B`:
  gauge transformation through the adjoint action, the Lorentz transformation of the
  towers with two explicit covector indices, and the mass weights `2 * (2 + n)`. -/
structure IsGaugeSector (B : Type) [Ring B] [Algebra ℂ B]
    (repGauge : Representation ℂ GaugeGroupI B)
    (repGauge_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B),
      repGauge g (b₁ * b₂) = repGauge g b₁ * repGauge g b₂)
    (repLorentz : Representation ℂ SL(2,ℂ) B)
    (repLorentz_mul : ∀ (Λ : SL(2,ℂ)) (b₁ b₂ : B),
      repLorentz Λ (b₁ * b₂) = repLorentz Λ b₁ * repLorentz Λ b₂)
    (F : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) →
      Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (massWeightPoly : B →ₐ[ℂ] Polynomial B) : Prop where
  repGauge_F : ∀ (g : GaugeGroupI) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
      (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra),
    repGauge g (F l μ ν φ) = F l μ ν ((GaugeAlgebra.adjointMap g⁻¹).dualMap φ)
  repLorentz_F : ∀ (Λ : SL(2,ℂ)) (n : ℕ) (l : Fin n → (Fin 1 ⊕ Fin 3))
      (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra),
    repLorentz Λ (F l μ ν φ) =
      ∑ p : Fin n → (Fin 1 ⊕ Fin 3),
        (∏ i, (((SL2C.toLorentzGroup Λ).1 (p i) (l i) : ℝ) : ℂ)) •
      ∑ a, (((SL2C.toLorentzGroup Λ).1 a μ : ℝ) : ℂ) •
      ∑ b, (((SL2C.toLorentzGroup Λ).1 b ν : ℝ) : ℂ) • F p a b φ
  massWeight_F : ∀ {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3) (μ ν : Fin 1 ⊕ Fin 3) φ,
    massWeightPoly (F l μ ν φ) = Polynomial.monomial (2 * (2 + n)) (F l μ ν φ)
  -- The gauge sector is bosonic: any two field-strength towers commute.
  F_comm_F : ∀ {n m : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3) (μ ν : Fin 1 ⊕ Fin 3)
      (ψ : Module.Dual ℝ GaugeAlgebra) (l' : Fin m → Fin 1 ⊕ Fin 3)
      (μ' ν' : Fin 1 ⊕ Fin 3) (ψ' : Module.Dual ℝ GaugeAlgebra),
    Commute (F l μ ν ψ) (F l' μ' ν' ψ')
  -- The field strength is antisymmetric in its two covector indices.
  F_antisymm : ∀ {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3) (μ ν : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra),
    F l ν μ φ = - F l μ ν φ

namespace IsGaugeSector

variable {B : Type} [Ring B] [Algebra ℂ B]
  {repGauge : Representation ℂ GaugeGroupI B}
  {hrepGauge_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B),
    repGauge g (b₁ * b₂) = repGauge g b₁ * repGauge g b₂}
  {repLorentz : Representation ℂ SL(2,ℂ) B}
  {hrepLorentz_mul : ∀ (Λ : SL(2,ℂ)) (b₁ b₂ : B),
    repLorentz Λ (b₁ * b₂) = repLorentz Λ b₁ * repLorentz Λ b₂}
  {F : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) →
    Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  (h : IsGaugeSector B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
      F massWeightPoly)

/-- The algebra generated by the field strength and all its covariant derivatives. -/
def gaugeAlgebra (h : IsGaugeSector B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
      F massWeightPoly) : Subalgebra ℂ B :=
  Algebra.adjoin ℂ
    (⋃ (n : ℕ) (l : Fin n → Fin 1 ⊕ Fin 3) (μ : Fin 1 ⊕ Fin 3) (ν : Fin 1 ⊕ Fin 3),
      Set.range (F l μ ν))

/-!

## The individual gauge-group contributions to the field strength

The field-strength symbol family `F` packages together the contributions of the three
factors of the gauge group. Evaluating it on the coordinate of `GaugeAlgebra.stdBasis`
dual to a Gell-Mann direction, a Pauli direction, or the `u(1)` direction isolates the
gluon, `W`-boson, and hypercharge contributions individually.

-/

set_option linter.unusedVariables false in
/-- The gluon contribution to the field strength (and its covariant derivatives): the
  field-strength symbol evaluated on the coordinate dual to the `a`-th Gell-Mann
  direction of the standard basis of the gauge algebra, i.e. the `su(3)` factor. -/
noncomputable def gluonField (h : IsGaugeSector B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
      F massWeightPoly) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3) (μ ν : Fin 1 ⊕ Fin 3)
    (a : Fin 8) : B :=
  F l μ ν (GaugeAlgebra.stdBasis.coord (Sum.inl a))

@[inherit_doc gluonField]
scoped[StandardModel.IsGaugeSector] notation "𝐆" => gluonField

set_option linter.unusedVariables false in
/-- The `W`-boson contribution to the field strength (and its covariant derivatives):
  the field-strength symbol evaluated on the coordinate dual to the `i`-th Pauli
  direction of the standard basis of the gauge algebra, i.e. the `su(2)` factor. -/
noncomputable def wField (h : IsGaugeSector B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
      F massWeightPoly) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3) (μ ν : Fin 1 ⊕ Fin 3)
    (i : Fin 3) : B :=
  F l μ ν (GaugeAlgebra.stdBasis.coord (Sum.inr (Sum.inl i)))

@[inherit_doc wField]
scoped[StandardModel.IsGaugeSector] notation "𝐖" => wField

set_option linter.unusedVariables false in
/-- The hypercharge contribution to the field strength (and its covariant derivatives),
  i.e. the `B`-boson contribution: the field-strength symbol evaluated on the coordinate
  dual to the single basis direction of the `u(1)` factor of the standard basis of the
  gauge algebra. -/
noncomputable def hyperchargeField (h : IsGaugeSector B repGauge hrepGauge_mul repLorentz
      hrepLorentz_mul F massWeightPoly) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (μ ν : Fin 1 ⊕ Fin 3) : B :=
  F l μ ν (GaugeAlgebra.stdBasis.coord (Sum.inr (Sum.inr 0)))

@[inherit_doc hyperchargeField]
scoped[StandardModel.IsGaugeSector] notation "𝐁" => hyperchargeField

/-!

## The field-strength derivative submodules

-/

set_option linter.unusedVariables false in
/-- The submodule of `B` generated by the field-strength symbols carrying exactly `n`
  covariant derivatives: the join, over the derivative slots and the two covector
  indices, of the ranges of the symbol maps. -/
def derivSubmodule (h : IsGaugeSector B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
      F massWeightPoly) (n : ℕ) : Submodule ℂ B :=
  ⨆ (l : Fin n → Fin 1 ⊕ Fin 3) (μ : Fin 1 ⊕ Fin 3) (ν : Fin 1 ⊕ Fin 3),
    Submodule.span ℂ (Set.range (F l μ ν))

/-!

### Commutativity of the derivative submodules

-/

/-- The gauge sector is bosonic: any element of a derivative-`n` submodule commutes with any
  element of a derivative-`m` submodule. This extends `F_comm_F` from generators to the
  submodules that they span. -/
lemma commute_of_mem_derivSubmodule {n m : ℕ} {x y : B}
    (hx : x ∈ h.derivSubmodule n) (hy : y ∈ h.derivSubmodule m) : Commute x y := by
  have gen : ∀ (l : Fin n → Fin 1 ⊕ Fin 3) (μ ν : Fin 1 ⊕ Fin 3) (ψ : Module.Dual ℝ GaugeAlgebra),
      h.derivSubmodule m ≤ LinearMap.ker
        (LinearMap.mulLeft ℂ (F l μ ν ψ) - LinearMap.mulRight ℂ (F l μ ν ψ)) := by
    intro l μ ν ψ
    rw [derivSubmodule]
    refine iSup_le fun l' => iSup_le fun μ' => iSup_le fun ν' => Submodule.span_le.mpr ?_
    rintro _ ⟨ψ', rfl⟩
    simp only [SetLike.mem_coe, LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
      LinearMap.mulRight_apply, sub_eq_zero]
    exact (h.F_comm_F l μ ν ψ l' μ' ν' ψ').eq
  have key : ∀ x ∈ h.derivSubmodule n, ∀ y ∈ h.derivSubmodule m, x * y = y * x := by
    intro x hx y hy
    have step : h.derivSubmodule n ≤
        LinearMap.ker (LinearMap.mulRight ℂ y - LinearMap.mulLeft ℂ y) := by
      rw [derivSubmodule]
      refine iSup_le fun l => iSup_le fun μ => iSup_le fun ν => Submodule.span_le.mpr ?_
      rintro _ ⟨ψ, rfl⟩
      simp only [SetLike.mem_coe, LinearMap.mem_ker, LinearMap.sub_apply,
        LinearMap.mulRight_apply, LinearMap.mulLeft_apply, sub_eq_zero]
      have := gen l μ ν ψ hy
      simpa only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
        LinearMap.mulRight_apply, sub_eq_zero] using this
    have := step hx
    simpa only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulRight_apply,
      LinearMap.mulLeft_apply, sub_eq_zero] using this
  exact key x hx y hy

/-- The derivative-`n` and derivative-`m` submodules commute with one another as submodules
  of `B`, since every pair of their elements commute. -/
lemma derivSubmodule_mul_comm (n m : ℕ) :
    h.derivSubmodule n * h.derivSubmodule m = h.derivSubmodule m * h.derivSubmodule n := by
  refine le_antisymm (Submodule.mul_le.mpr fun x hx y hy => ?_)
    (Submodule.mul_le.mpr fun x hx y hy => ?_)
  · rw [(h.commute_of_mem_derivSubmodule hx hy).eq]
    exact Submodule.mul_mem_mul hy hx
  · rw [← (h.commute_of_mem_derivSubmodule hy hx).eq]
    exact Submodule.mul_mem_mul hy hx

/-!

### Closure of the derivative submodules under the gauge and Lorentz groups

-/

/-- The image of a derivative-`n` submodule under a gauge transformation lies inside the
  same submodule: each generator `F l μ ν φ` is sent by `repGauge_F` to another generator
  `F l μ ν φ'` with the same derivative slots and covector indices. -/
lemma derivSubmodule_map_repGauge_le (n : ℕ) (g : GaugeGroupI) :
    (h.derivSubmodule n).map (repGauge g) ≤ h.derivSubmodule n := by
  rw [derivSubmodule, Submodule.map_iSup]
  refine iSup_le fun l => ?_
  rw [Submodule.map_iSup]
  refine iSup_le fun μ => ?_
  rw [Submodule.map_iSup]
  refine iSup_le fun ν => ?_
  rw [Submodule.map_span_le]
  rintro _ ⟨φ, rfl⟩
  rw [h.repGauge_F]
  exact Submodule.mem_iSup_of_mem l (Submodule.mem_iSup_of_mem μ
    (Submodule.mem_iSup_of_mem ν (Submodule.subset_span ⟨_, rfl⟩)))

/-- The derivative-`n` submodule is invariant, as a set, under the gauge group. -/
lemma derivSubmodule_map_repGauge (n : ℕ) (g : GaugeGroupI) :
    (h.derivSubmodule n).map (repGauge g) = h.derivSubmodule n :=
  le_antisymm (h.derivSubmodule_map_repGauge_le n g) fun b hb =>
    ⟨repGauge g⁻¹ b, h.derivSubmodule_map_repGauge_le n g⁻¹ ⟨b, hb, rfl⟩,
      repGauge.self_inv_apply g b⟩

/-- The image of a derivative-`n` submodule under a Lorentz transformation lies inside the
  same submodule: `repLorentz_F` expands each generator into a finite linear combination of
  generators with the same number `n` of derivative slots. -/
lemma derivSubmodule_map_repLorentz_le (n : ℕ) (Λ : SL(2,ℂ)) :
    (h.derivSubmodule n).map (repLorentz Λ) ≤ h.derivSubmodule n := by
  rw [derivSubmodule, Submodule.map_iSup]
  refine iSup_le fun l => ?_
  rw [Submodule.map_iSup]
  refine iSup_le fun μ => ?_
  rw [Submodule.map_iSup]
  refine iSup_le fun ν => ?_
  rw [Submodule.map_span_le]
  rintro _ ⟨φ, rfl⟩
  rw [h.repLorentz_F]
  refine Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _ ?_
  refine Submodule.sum_mem _ fun a _ => Submodule.smul_mem _ _ ?_
  refine Submodule.sum_mem _ fun b _ => Submodule.smul_mem _ _ ?_
  exact Submodule.mem_iSup_of_mem p (Submodule.mem_iSup_of_mem a
    (Submodule.mem_iSup_of_mem b (Submodule.subset_span ⟨_, rfl⟩)))

/-- The derivative-`n` submodule is invariant, as a set, under the Lorentz group. -/
lemma derivSubmodule_map_repLorentz (n : ℕ) (Λ : SL(2,ℂ)) :
    (h.derivSubmodule n).map (repLorentz Λ) = h.derivSubmodule n :=
  le_antisymm (h.derivSubmodule_map_repLorentz_le n Λ) fun b hb =>
    ⟨repLorentz Λ⁻¹ b, h.derivSubmodule_map_repLorentz_le n Λ⁻¹ ⟨b, hb, rfl⟩,
      repLorentz.self_inv_apply Λ b⟩

end IsGaugeSector

end StandardModel
