/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.ProbabilisticTheory.Composite.TensorCone

/-!
# The square

## i. Overview

The square is the simplest state space that is not a simplex: it has four pure states, the
vertices, and the two diagonals of the square have the same midpoint. Its observables are the affine
functions on the square, recorded by their values at the four vertices `0, 1, 2, 3`, with the
diagonal relation `v 0 + v 3 = v 1 + v 2`. An observable is nonnegative when all four values are.

The nonnegative observables are generated by the four facets: the affine functions that vanish on
one side of the square. An observable of the composite of `E` with the square is recorded by its
four vertex values in `E`, which again satisfy the diagonal relation.

## ii. Key results

- `Square` : the observables of the square, an order-unit space.
- `Square.facet` : the four facets.
- `Square.exists_eq_sum_facet` : every nonnegative observable is a nonnegative combination of
  facets.
- `Square.vals` : the vertex values of an observable of `E ⊗ Square`.
- `Square.vals_injective` : vertex values determine the observable.

## iii. Table of contents

- A. The square
- B. Facets
- C. Vertex values of composite observables

-/

@[expose] public section

namespace ProbabilisticTheory

open TensorProduct

/-! ## A. The square -/

/-- Vertex values `v 0, v 1, v 2, v 3` satisfying the diagonal relation `v 0 + v 3 = v 1 + v 2`. -/
def squareSubmodule : Submodule ℝ (Fin 4 → ℝ) where
  carrier := {v | v 0 + v 3 = v 1 + v 2}
  add_mem' {v w} hv hw := by simp only [Set.mem_ofPred_eq, Pi.add_apply] at *; linarith
  zero_mem' := by simp
  smul_mem' c v hv := by
    simp only [Set.mem_ofPred_eq, Pi.smul_apply, smul_eq_mul] at *; rw [← mul_add, hv, mul_add]

/-- The observables of the square: affine functions, recorded by their values at the vertices. -/
def Square : Type := squareSubmodule

namespace Square

instance : AddCommGroup Square := inferInstanceAs (AddCommGroup squareSubmodule)

instance : Module ℝ Square := inferInstanceAs (Module ℝ squareSubmodule)

/-- The value at the `i`-th vertex. -/
def val (q : Square) (i : Fin 4) : ℝ := (show squareSubmodule from q).1 i

/-- The observable with the given vertex values. -/
def mk (v : Fin 4 → ℝ) (h : v 0 + v 3 = v 1 + v 2) : Square := (⟨v, h⟩ : squareSubmodule)

@[simp] lemma val_mk (v : Fin 4 → ℝ) (h) (i : Fin 4) : (mk v h).val i = v i := rfl

@[ext]
lemma ext {q r : Square} (h : ∀ i, q.val i = r.val i) : q = r :=
  Subtype.ext (funext h)

lemma diagonal (q : Square) : q.val 0 + q.val 3 = q.val 1 + q.val 2 :=
  (show squareSubmodule from q).2

@[simp] lemma val_add (q r : Square) (i : Fin 4) : (q + r).val i = q.val i + r.val i := rfl
@[simp] lemma val_smul (c : ℝ) (q : Square) (i : Fin 4) : (c • q).val i = c * q.val i := rfl
@[simp] lemma val_zero (i : Fin 4) : (0 : Square).val i = 0 := rfl

instance : PartialOrder Square :=
  PartialOrder.lift (fun q : Square => q.val) fun _ _ h => ext (congrFun h)

lemma le_def {q r : Square} : q ≤ r ↔ ∀ i, q.val i ≤ r.val i := Iff.rfl

instance : IsOrderedAddMonoid Square where
  add_le_add_left _ _ h s i := by simpa using add_le_add_right (h i) (s.val i)

instance : PosSMulMono ℝ Square :=
  ⟨fun _ hc _ _ h i => by simpa using mul_le_mul_of_nonneg_left (h i) hc⟩

/-- The unit: the constant function `1`. -/
instance : One Square := ⟨mk (fun _ => 1) (by norm_num)⟩

@[simp] lemma val_one (i : Fin 4) : (1 : Square).val i = 1 := rfl

instance : OrderUnitSpace Square where
  one_nonneg _ := zero_le_one
  exists_nsmul_one_le q := by
    obtain ⟨n, hn⟩ := exists_nat_ge (∑ i, |q.val i|)
    refine ⟨n, fun i => ?_⟩
    show q.val i ≤ (n • (1 : Square)).val i
    rw [← Nat.cast_smul_eq_nsmul ℝ, val_smul, val_one, mul_one]
    exact (le_abs_self _).trans ((Finset.single_le_sum (fun j _ => abs_nonneg (q.val j))
      (Finset.mem_univ i)).trans hn)

instance : ArchimedeanOrderUnitSpace Square where
  le_zero_of_forall_pos_smul_one_le q h i := le_of_forall_pos_le_add fun ε hε => by
    simpa using h ε hε i

/-- Evaluation at the `i`-th vertex: a pure state of the square. -/
def ev (i : Fin 4) : Square →ₚ[ℝ] ℝ :=
  .mk₀ { toFun q := q.val i, map_add' _ _ := rfl, map_smul' _ _ := rfl } fun _ hq => hq i

@[simp] lemma ev_apply (i : Fin 4) (q : Square) : ev i q = q.val i := rfl

/-! ## B. Facets -/

/-- The four facets: `facet 0` vanishes on vertices `0, 2`, `facet 1` on `0, 1`, `facet 2` on
`1, 3`, and `facet 3` on `2, 3`. -/
def facet : Fin 4 → Square
  | 0 => mk ![0, 1, 0, 1] (by simp)
  | 1 => mk ![0, 0, 1, 1] (by simp)
  | 2 => mk ![1, 0, 1, 0] (by simp)
  | 3 => mk ![1, 1, 0, 0] (by simp)

lemma facet_nonneg (j : Fin 4) : 0 ≤ facet j := fun i => by
  fin_cases j <;> fin_cases i <;> simp [facet]

lemma val_sum (q : Fin 4 → Square) (i : Fin 4) : (∑ j, q j).val i = ∑ j, (q j).val i := by
  rw [← ev_apply, map_sum]; rfl

/-- Every nonnegative observable of the square is a nonnegative combination of the facets. -/
lemma exists_eq_sum_facet {q : Square} (hq : 0 ≤ q) :
    ∃ c : Fin 4 → ℝ, (∀ j, 0 ≤ c j) ∧ q = ∑ j, c j • facet j := by
  have h := q.diagonal
  have h₀ := hq 0; have h₁ := hq 1; have h₂ := hq 2; have h₃ := hq 3
  simp only [val_zero] at h₀ h₁ h₂ h₃
  rcases min_cases (q.val 0) (q.val 1) with ⟨-, hle⟩ | ⟨-, hlt⟩
  · refine ⟨![q.val 1 - q.val 0, q.val 2, 0, q.val 0], fun j => ?_, ext fun i => ?_⟩
    · fin_cases j <;> simp <;> linarith
    · rw [val_sum]; fin_cases i <;> simp [Fin.sum_univ_four, facet]; linarith
  · refine ⟨![0, q.val 3, q.val 0 - q.val 1, q.val 1], fun j => ?_, ext fun i => ?_⟩
    · fin_cases j <;> simp <;> linarith
    · rw [val_sum]; fin_cases i <;> simp [Fin.sum_univ_four, facet]; linarith

/-- An observable of the square is determined by its values at the vertices `0, 1, 2`. -/
lemma eq_add_facet (q : Square) :
    q = q.val 0 • 1 + (q.val 1 - q.val 0) • facet 0 + (q.val 2 - q.val 0) • facet 1 := by
  have h := q.diagonal
  ext i
  fin_cases i <;> simp [facet]; linarith

end Square

/-! ## C. Vertex values of composite observables -/

namespace Square

open PositiveLinearMap

variable {E : Type*} [OrderUnitSpace E]

/-- The vertex values of an observable of the composite with the square. -/
noncomputable def vals : E ⊗[ℝ] Square →ₗ[ℝ] (Fin 4 → E) :=
  LinearMap.pi fun i => rslice (ev i)

@[simp]
lemma vals_tmul (x : E) (q : Square) : vals (x ⊗ₜ[ℝ] q) = fun i => q.val i • x := by
  ext i; simp [vals]

/-- The vertex values of a composite observable satisfy the diagonal relation. -/
lemma vals_diagonal (z : E ⊗[ℝ] Square) : vals z 0 + vals z 3 = vals z 1 + vals z 2 := by
  induction z using TensorProduct.inductionOn with
  | tmul x q => simp only [vals_tmul, ← add_smul, q.diagonal]
  | add z z' hz hz' =>
    simp only [map_add, Pi.add_apply]
    rw [add_add_add_comm, hz, hz', add_add_add_comm]

/-- The composite observable with the given vertex values, where only `A 0, A 1, A 2` matter. -/
noncomputable def ofVals (A : Fin 4 → E) : E ⊗[ℝ] Square :=
  A 0 ⊗ₜ[ℝ] 1 + (A 1 - A 0) ⊗ₜ[ℝ] facet 0 + (A 2 - A 0) ⊗ₜ[ℝ] facet 1

lemma ofVals_add (A B : Fin 4 → E) : ofVals (A + B) = ofVals A + ofVals B := by
  simp only [ofVals, Pi.add_apply, add_tmul, sub_tmul]
  abel

lemma ofVals_vals (z : E ⊗[ℝ] Square) : ofVals (vals z) = z := by
  induction z using TensorProduct.inductionOn with
  | tmul x q =>
    conv_rhs => rw [eq_add_facet q]
    simp only [ofVals, vals_tmul, ← sub_smul, smul_tmul, tmul_add]
  | add z z' hz hz' => rw [map_add, ofVals_add, hz, hz']

/-- Vertex values satisfying the diagonal relation are the vertex values of a composite
observable. -/
lemma vals_ofVals {A : Fin 4 → E} (hA : A 0 + A 3 = A 1 + A 2) : vals (ofVals A) = A := by
  ext i
  fin_cases i <;> simp [ofVals, facet]
  rw [← add_sub_assoc, ← hA]; abel

/-- Vertex values determine the composite observable. -/
lemma vals_injective : Function.Injective (vals : E ⊗[ℝ] Square →ₗ[ℝ] (Fin 4 → E)) :=
  Function.LeftInverse.injective ofVals_vals

/-- Applying a positive functional to the `E` factor gives the observable of the square whose
vertex values are the values of the functional on the vertex values. -/
lemma val_lslice (φ : E →ₚ[ℝ] ℝ) (z : E ⊗[ℝ] Square) (i : Fin 4) :
    (lslice φ z).val i = φ (vals z i) := by
  change (ev i).toLinearMap.comp (lslice φ) z =
    (φ.toLinearMap.comp ((LinearMap.proj i).comp vals)) z
  congr 1
  exact TensorProduct.ext' fun x q => by simp [mul_comm]

/-- A composite observable whose vertex values are nonnegative is in the maximal cone. -/
lemma mem_maxTensorCone_of_vals_nonneg {z : E ⊗[ℝ] Square} (h : ∀ i, 0 ≤ vals z i) :
    z ∈ maxTensorCone E Square := mem_maxTensorCone.2 fun φ ψ => by
  rw [tensor_apply_eq_lslice]
  exact map_nonneg ψ fun i => by simpa [val_lslice] using map_nonneg φ (h i)

/-- For Archimedean `E`, the maximal cone of the composite with the square consists of the
observables with nonnegative vertex values. -/
lemma mem_maxTensorCone_iff {E : Type*} [ArchimedeanOrderUnitSpace E] {z : E ⊗[ℝ] Square} :
    z ∈ maxTensorCone E Square ↔ ∀ i, 0 ≤ vals z i :=
  ⟨fun h i => by simpa [vals] using mem_maxTensorCone_iff_rslice.1 h (ev i),
    mem_maxTensorCone_of_vals_nonneg⟩

end Square

end ProbabilisticTheory
