/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.IsHiggsSector.Basic
/-!
# The derivative submodules of the Higgs sector

The Higgs symbols and their conjugates carrying a fixed number `n` of derivatives span
the submodule `derivSubmodule n`.  The Higgs is bosonic, so these submodules commute
with one another, and since neither the gauge nor the Lorentz action changes the number
of derivatives they are closed under both.

The gauge and boost weight decompositions of these submodules live in
`GaugeWeightDecomposition.lean` and `BoostWeightDecomposition.lean`.

-/

@[expose] public section

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz

namespace IsHiggsSector

set_option linter.unusedVariables false

variable {B : Type} [Ring B] [Algebra ℂ B]
  {rep : Representation ℂ GaugeGroupI B}
  {hrep_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B), rep g (b₁ * b₂) = rep g b₁ * rep g b₂}
  {repLorentz : Representation ℂ SL(2,ℂ) B}
  {hrepLorentz_mul : ∀ (Λ : SL(2,ℂ)) (b₁ b₂ : B),
    repLorentz Λ (b₁ * b₂) = repLorentz Λ b₁ * repLorentz Λ b₂}
  {H : (n : ℕ) → (Fin n → (Fin 1 ⊕ Fin 3)) → Module.Dual ℂ HiggsVec →ₗ[ℂ] B}
  {barH : (n : ℕ) → (Fin n → (Fin 1 ⊕ Fin 3)) →
    Module.Dual ℂ (ConjModule HiggsVec) →ₗ[ℂ] B}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  (h : IsHiggsSector B rep hrep_mul repLorentz hrepLorentz_mul H barH
      massWeightPoly)

/-- The submodule of `B` generated by the Higgs symbols and their conjugates carrying
  `n` derivatives. -/
def derivSubmodule (h : IsHiggsSector B rep hrep_mul repLorentz hrepLorentz_mul H barH
      massWeightPoly) (n : ℕ) : Submodule ℂ B :=
  h.higgsSubmodule n ⊔ h.barHiggsSubmodule n

/-- Every element of a derivative submodule commutes with a fixed Higgs symbol. -/
lemma derivSubmodule_le_ker_H {n k : ℕ} (d : Fin k → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ HiggsVec) :
    h.derivSubmodule n
      ≤ LinearMap.ker (LinearMap.mulLeft ℂ (H k d φ) - LinearMap.mulRight ℂ (H k d φ)) := by
  rw [derivSubmodule]
  refine sup_le ?_ ?_
  · rw [higgsSubmodule]
    refine iSup_le fun d' => ?_
    rintro _ ⟨ψ, rfl⟩
    simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
      LinearMap.mulRight_apply, sub_eq_zero]
    exact (h.H_comm_H φ ψ k n d d').eq
  · rw [barHiggsSubmodule]
    refine iSup_le fun d' => ?_
    rintro _ ⟨ψ, rfl⟩
    simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
      LinearMap.mulRight_apply, sub_eq_zero]
    exact (h.H_comm_barH φ ψ k n d d').eq

/-- Every element of a derivative submodule commutes with a fixed conjugate-Higgs
  symbol. -/
lemma derivSubmodule_le_ker_barH {n k : ℕ} (d : Fin k → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule HiggsVec)) :
    h.derivSubmodule n
      ≤ LinearMap.ker (LinearMap.mulLeft ℂ (barH k d φ)
        - LinearMap.mulRight ℂ (barH k d φ)) := by
  rw [derivSubmodule]
  refine sup_le ?_ ?_
  · rw [higgsSubmodule]
    refine iSup_le fun d' => ?_
    rintro _ ⟨ψ, rfl⟩
    simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
      LinearMap.mulRight_apply, sub_eq_zero]
    exact ((h.H_comm_barH ψ φ n k d' d).symm).eq
  · rw [barHiggsSubmodule]
    refine iSup_le fun d' => ?_
    rintro _ ⟨ψ, rfl⟩
    simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
      LinearMap.mulRight_apply, sub_eq_zero]
    exact (h.barH_comm_barH φ ψ k n d d').eq

/-- Any element of a derivative submodule commutes with any element of any derivative
  submodule: the Higgs is bosonic. -/
lemma commute_of_mem_derivSubmodule {n m : ℕ} {x y : B}
    (hx : x ∈ h.derivSubmodule n) (hy : y ∈ h.derivSubmodule m) : Commute x y := by
  have step : h.derivSubmodule n
      ≤ LinearMap.ker (LinearMap.mulRight ℂ y - LinearMap.mulLeft ℂ y) := by
    rw [derivSubmodule]
    refine sup_le ?_ ?_
    · rw [higgsSubmodule]
      refine iSup_le fun d => ?_
      rintro _ ⟨φ, rfl⟩
      have := h.derivSubmodule_le_ker_H (n := m) d φ hy
      simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
        LinearMap.mulRight_apply, sub_eq_zero] at this ⊢
      exact this
    · rw [barHiggsSubmodule]
      refine iSup_le fun d => ?_
      rintro _ ⟨φ, rfl⟩
      have := h.derivSubmodule_le_ker_barH (n := m) d φ hy
      simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
        LinearMap.mulRight_apply, sub_eq_zero] at this ⊢
      exact this
  have hxy := step hx
  simp only [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulRight_apply,
    LinearMap.mulLeft_apply, sub_eq_zero] at hxy
  exact hxy

/-- Derivative submodules commute with one another at the level of submodule
  products. -/
lemma derivSubmodule_mul_comm (n m : ℕ) :
    h.derivSubmodule n * h.derivSubmodule m = h.derivSubmodule m * h.derivSubmodule n := by
  refine le_antisymm (Submodule.mul_le.mpr fun x hx y hy => ?_)
    (Submodule.mul_le.mpr fun y hy x hx => ?_)
  · rw [(h.commute_of_mem_derivSubmodule hx hy).eq]
    exact Submodule.mul_mem_mul hy hx
  · rw [← (h.commute_of_mem_derivSubmodule hx hy).eq]
    exact Submodule.mul_mem_mul hx hy

/-- The derivative submodules are closed under the gauge action: each symbol is carried
  to a symbol with the same number of derivatives. -/
lemma derivSubmodule_map_rep_le (n : ℕ) (g : GaugeGroupI) :
    (h.derivSubmodule n).map (rep g) ≤ h.derivSubmodule n := by
  rw [derivSubmodule, Submodule.map_sup]
  refine sup_le_sup ?_ ?_
  · rw [higgsSubmodule, Submodule.map_iSup]
    refine iSup_le fun d => ?_
    rintro _ ⟨_, ⟨φ, rfl⟩, rfl⟩
    rw [h.H_equivariant]
    exact Submodule.mem_iSup_of_mem d ⟨_, rfl⟩
  · rw [barHiggsSubmodule, Submodule.map_iSup]
    refine iSup_le fun d => ?_
    rintro _ ⟨_, ⟨φ, rfl⟩, rfl⟩
    rw [h.barH_equivariant]
    exact Submodule.mem_iSup_of_mem d ⟨_, rfl⟩

/-- The derivative submodules are closed under the gauge action. -/
lemma derivSubmodule_map_rep (n : ℕ) (g : GaugeGroupI) :
    (h.derivSubmodule n).map (rep g) = h.derivSubmodule n :=
  le_antisymm (h.derivSubmodule_map_rep_le n g) fun b hb =>
    ⟨rep g⁻¹ b, h.derivSubmodule_map_rep_le n g⁻¹ ⟨b, hb, rfl⟩,
      rep.self_inv_apply g b⟩

/-- The derivative submodules are closed under the Lorentz action: the Lorentz group
  only mixes the derivative indices within a fixed number of derivatives. -/
lemma derivSubmodule_map_repLorentz_le (n : ℕ) (Λ : SL(2,ℂ)) :
    (h.derivSubmodule n).map (repLorentz Λ) ≤ h.derivSubmodule n := by
  rw [derivSubmodule, Submodule.map_sup]
  refine sup_le_sup ?_ ?_
  · rw [higgsSubmodule, Submodule.map_iSup]
    refine iSup_le fun d => ?_
    rintro _ ⟨_, ⟨φ, rfl⟩, rfl⟩
    rw [h.repLorentz_H_apply]
    exact Submodule.sum_mem _ fun a _ =>
      Submodule.smul_mem _ _ (Submodule.mem_iSup_of_mem a ⟨φ, rfl⟩)
  · rw [barHiggsSubmodule, Submodule.map_iSup]
    refine iSup_le fun d => ?_
    rintro _ ⟨_, ⟨φ, rfl⟩, rfl⟩
    rw [h.repLorentz_barH_apply]
    exact Submodule.sum_mem _ fun a _ =>
      Submodule.smul_mem _ _ (Submodule.mem_iSup_of_mem a ⟨φ, rfl⟩)

/-- The derivative submodules are closed under the Lorentz action. -/
lemma derivSubmodule_map_repLorentz (n : ℕ) (Λ : SL(2,ℂ)) :
    (h.derivSubmodule n).map (repLorentz Λ) = h.derivSubmodule n :=
  le_antisymm (h.derivSubmodule_map_repLorentz_le n Λ) fun b hb =>
    ⟨repLorentz Λ⁻¹ b, h.derivSubmodule_map_repLorentz_le n Λ⁻¹ ⟨b, hb, rfl⟩,
      repLorentz.self_inv_apply Λ b⟩

end IsHiggsSector

end StandardModel
