/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Mathematics.HomogeneousGenerators
public import Physlib.Particles.StandardModel.IsGaugeSector.Basic
/-!
# The mass-weight grading of the gauge sector

## i. Overview

The elements of the gauge algebra of a given mass weight form a submodule. Mass weight is
twice the mass dimension: a field-strength tower `∇ⁿF` with `n` covariant derivatives has
mass dimension `2 + n` and mass weight `2 * (2 + n)`, and a term of mass dimension four, as
in the Lagrangian, has mass weight eight.

The field-strength towers generate the gauge algebra, and `massWeightPoly` is a monomial on
each of them. The results of `Physlib.Mathematics.HomogeneousGenerators` then describe
every mass-weight submodule. The submodules of weight at most eight are found by removing
the leftmost tower of each product; weight eight is the `∇∇F` and `F · F` sectors.

## ii. Key results

- `massWeightSubmodule_eq_iSup_mul` : removing the leftmost field-strength tower.
- `massWeightSubmodule_eq` : the binary weight recursion.
- `massWeightSubmodule_eq_bot` : the odd weights and the weight two are empty.
- `massWeightSubmodule_four_eq` to `massWeightSubmodule_eight_eq` : the mass weights up to eight.

## iii. Table of contents

- A. The mass-weight submodules
- B. The field-strength towers generate and have weight `2 * (2 + n)`
- C. The weight decompositions
- D. Mass weights up to eight

-/

@[expose] public section

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz

namespace IsGaugeSector

variable {B : Type} [Ring B] [Algebra ℂ B]
  {repGauge : Representation ℂ GaugeGroupI B}
  {hrepGauge_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B),
    repGauge g (b₁ * b₂) = repGauge g b₁ * repGauge g b₂}
  {repLorentz : Representation ℂ SL(2,ℂ) B}
  {hrepLorentz_mul : ∀ (Λ : SL(2,ℂ)) (b₁ b₂ : B),
    repLorentz Λ (b₁ * b₂) = repLorentz Λ b₁ * repLorentz Λ b₂}
  {F : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) →
    Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  (h : IsGaugeSector B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
      F massWeightPoly)
/-!

## A. The mass-weight submodules

-/

/-- All elements of the gauge algebra of mass weight exactly `w`: the intersection of
  the algebra generated by the field-strength towers with the part on which
  `massWeightPoly` is the monomial `X ^ w`. -/
noncomputable def massWeightSubmodule (h : IsGaugeSector B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
      F massWeightPoly) (w : ℕ) :
    Submodule ℂ B :=
  (h.gaugeAlgebra).toSubmodule
    ⊓ LinearMap.ker (massWeightPoly.toLinearMap
      - (Polynomial.monomial w : B →ₗ[B] Polynomial B).restrictScalars ℂ)

lemma massWeightPoly_of_mem_massWeightSubmodule {w : ℕ} {x : B}
    (hx : x ∈ h.massWeightSubmodule w) :
    massWeightPoly x = Polynomial.monomial w x :=
  (Subalgebra.mem_homogeneousSubmodule_iff.mp hx).2

lemma mem_gaugeAlgebra_of_mem_massWeightSubmodule {w : ℕ} {x : B}
    (hx : x ∈ h.massWeightSubmodule w) : x ∈ h.gaugeAlgebra :=
  (Subalgebra.mem_homogeneousSubmodule_iff.mp hx).1

lemma one_le_massWeightSubmodule_zero : (1 : Submodule ℂ B) ≤ h.massWeightSubmodule 0 :=
  Subalgebra.one_le_homogeneousSubmodule_zero

lemma massWeightSubmodule_mul_le (m n : ℕ) :
    h.massWeightSubmodule m * h.massWeightSubmodule n ≤ h.massWeightSubmodule (m + n) :=
  Subalgebra.homogeneousSubmodule_mul_le m n

/-!

## B. The field-strength towers generate and have weight `2 * (2 + n)`

-/

/-- The gauge algebra is generated by the field-strength towers of every derivative
  order. -/
lemma gaugeAlgebra_eq_adjoin_derivSubmodule :
    h.gaugeAlgebra = Algebra.adjoin ℂ (⋃ n, (h.derivSubmodule n : Set B)) := by
  simp only [derivSubmodule, ← Submodule.span_iUnion, Algebra.adjoin_iUnion,
    Algebra.adjoin_span, gaugeAlgebra]

/-- `massWeightPoly` is the monomial `X ^ (2 * (2 + n))` on the field-strength towers with
  `n` covariant derivatives. -/
lemma massWeightPoly_of_mem_derivSubmodule (n : ℕ) :
    ∀ x ∈ h.derivSubmodule n, massWeightPoly x = Polynomial.monomial (2 * (2 + n)) x := by
  intro x hx
  have hle : h.derivSubmodule n ≤ LinearMap.ker (massWeightPoly.toLinearMap
      - (Polynomial.monomial (2 * (2 + n)) : B →ₗ[B] Polynomial B).restrictScalars ℂ) :=
    iSup_le fun l => iSup_le fun μ => iSup_le fun ν => Submodule.span_le.mpr <| by
      rintro _ ⟨φ, rfl⟩
      simp [h.massWeight_F]
  simpa [sub_eq_zero] using hle hx

/-- A field-strength tower with `n` covariant derivatives has mass weight
  `2 * (2 + n)`. -/
lemma derivSubmodule_le_massWeightSubmodule (n : ℕ) :
    h.derivSubmodule n ≤ h.massWeightSubmodule (2 * (2 + n)) :=
  Subalgebra.le_homogeneousSubmodule h.gaugeAlgebra_eq_adjoin_derivSubmodule
    h.massWeightPoly_of_mem_derivSubmodule n

/-!

## C. The weight decompositions

Every result here is a spanning statement: a submodule is a join of products of
field-strength towers, in the order written.

-/

/-- Weight zero is the scalars: every field-strength tower has positive weight. -/
lemma massWeightSubmodule_zero_eq : h.massWeightSubmodule 0 = 1 :=
  Subalgebra.homogeneousSubmodule_zero_eq_one h.gaugeAlgebra_eq_adjoin_derivSubmodule
    h.massWeightPoly_of_mem_derivSubmodule (fun n => by omega)

/-- The weight recursion: an element of positive mass weight `i` is a sum of single
  field-strength towers of weight `i` and of products of two elements of lower positive
  weights summing to `i`. -/
lemma massWeightSubmodule_eq (i : ℕ) (hi : 0 < i) :
    h.massWeightSubmodule i
      = (⨆ k ∈ Finset.univ.filter (fun k : Fin i => 2 * (2 + (k : ℕ)) = i),
          h.derivSubmodule (k : ℕ))
        ⊔ (⨆ p ∈ Finset.univ.filter (fun p : Fin i × Fin i => (p.1 : ℕ) + (p.2 : ℕ) = i),
            h.massWeightSubmodule (p.1 : ℕ) * h.massWeightSubmodule (p.2 : ℕ)) :=
  Subalgebra.homogeneousSubmodule_eq_sup_iSup_mul (deg := fun n => 2 * (2 + n))
    h.gaugeAlgebra_eq_adjoin_derivSubmodule h.massWeightPoly_of_mem_derivSubmodule
    (fun n => by omega) i hi

/-- Removing the leftmost field-strength tower: an element of positive weight `w` is a sum
  of products of a tower `∇ⁿF` of weight `2 * (2 + n) ≤ w` with an element of the
  remaining weight. -/
lemma massWeightSubmodule_eq_iSup_mul (w : ℕ) (hw : 0 < w) :
    h.massWeightSubmodule w
      = ⨆ n ∈ (Finset.range (w + 1)).filter (fun n => 2 * (2 + n) ≤ w),
          h.derivSubmodule n * h.massWeightSubmodule (w - 2 * (2 + n)) :=
  Subalgebra.homogeneousSubmodule_eq_iSup_mul (deg := fun n => 2 * (2 + n))
    h.gaugeAlgebra_eq_adjoin_derivSubmodule h.massWeightPoly_of_mem_derivSubmodule
    (fun n => by omega) hw

/-- The weights `1`, `2`, `3`, `5` and `7` are empty: the tower weights `4, 6, 8, …` and
  their sums only reach `0` and the even weights from `4` on. -/
lemma massWeightSubmodule_eq_bot {w : ℕ} (hw : ¬ (w = 0 ∨ (4 ≤ w ∧ w % 2 = 0))) :
    h.massWeightSubmodule w = ⊥ :=
  Subalgebra.homogeneousSubmodule_eq_bot h.gaugeAlgebra_eq_adjoin_derivSubmodule
    h.massWeightPoly_of_mem_derivSubmodule (fun w => w = 0 ∨ (4 ≤ w ∧ w % 2 = 0))
    (by omega) (fun n => by omega) (fun a b ha hb => by omega) hw

/-!

## D. Mass weights up to eight

Each case removes the leftmost tower. The towers `F`, `∇F` and `∇∇F` have weights `4`, `6`
and `8`; the remaining weight is then read off from a smaller weight.

-/

/-- There is nothing of weight one. -/
lemma massWeightSubmodule_one_eq : h.massWeightSubmodule 1 = ⊥ :=
  h.massWeightSubmodule_eq_bot (by omega)

/-- There is nothing of weight two. -/
lemma massWeightSubmodule_two_eq : h.massWeightSubmodule 2 = ⊥ :=
  h.massWeightSubmodule_eq_bot (by omega)

/-- There is nothing of weight three. -/
lemma massWeightSubmodule_three_eq : h.massWeightSubmodule 3 = ⊥ :=
  h.massWeightSubmodule_eq_bot (by omega)

/-- Weight four is the underived field-strength towers: `F` leaves weight zero. -/
lemma massWeightSubmodule_four_eq :
    h.massWeightSubmodule 4 = h.derivSubmodule 0 := by
  rw [h.massWeightSubmodule_eq_iSup_mul 4 (by norm_num),
    show (Finset.range 5).filter (fun n => 2 * (2 + n) ≤ 4) = {0} from by decide,
    Finset.iSup_singleton]
  simp [h.massWeightSubmodule_zero_eq]

/-- There is nothing of weight five. -/
lemma massWeightSubmodule_five_eq : h.massWeightSubmodule 5 = ⊥ :=
  h.massWeightSubmodule_eq_bot (by omega)

/-- Weight six is the once-derived field-strength towers: `F` would leave weight two,
  which is empty, and `∇F` leaves weight zero. -/
lemma massWeightSubmodule_six_eq :
    h.massWeightSubmodule 6 = h.derivSubmodule 1 := by
  rw [h.massWeightSubmodule_eq_iSup_mul 6 (by norm_num),
    show (Finset.range 7).filter (fun n => 2 * (2 + n) ≤ 6) = {0, 1} from by decide,
    Finset.iSup_insert, Finset.iSup_singleton]
  simp [h.massWeightSubmodule_two_eq, h.massWeightSubmodule_zero_eq]

/-- There is nothing of weight seven. -/
lemma massWeightSubmodule_seven_eq : h.massWeightSubmodule 7 = ⊥ :=
  h.massWeightSubmodule_eq_bot (by omega)

/-- Weight eight is the twice-derived field-strength towers together with the products
  of two underived ones, the `∇∇F` and `F · F` sectors: `F` leaves weight four, which is
  `F`, `∇F` would leave weight two, which is empty, and `∇∇F` leaves weight zero. -/
lemma massWeightSubmodule_eight_eq :
    h.massWeightSubmodule 8 = h.derivSubmodule 2 ⊔ h.derivSubmodule 0 * h.derivSubmodule 0 := by
  rw [h.massWeightSubmodule_eq_iSup_mul 8 (by norm_num),
    show (Finset.range 9).filter (fun n => 2 * (2 + n) ≤ 8) = {0, 1, 2} from by decide,
    Finset.iSup_insert, Finset.iSup_insert, Finset.iSup_singleton]
  simp [h.massWeightSubmodule_four_eq, h.massWeightSubmodule_two_eq,
    h.massWeightSubmodule_zero_eq, sup_comm]

end IsGaugeSector

end StandardModel
