/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.IsGaugeSector.Basic
/-!
# The mass-weight grading of the gauge sector

The elements of the gauge algebra of a given mass weight form a submodule; a
field-strength tower with `n` covariant derivatives has weight `2 * (2 + n)`, an
element of positive weight decomposes into towers of that weight and products of
elements of lower weight (`massWeightSubmodule_eq`), and the submodules of weight at
most eight are written out explicitly — weight eight being the `∇∇F` and `F · F`
sectors.

-/

@[expose] public section

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz

namespace IsGaugeSector

variable {B : Type} [Ring B] [Algebra ℂ B]
  {repGauge : Representation ℂ GaugeGroupI B}
  {hrepGauge_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B),
    repGauge g (b₁ * b₂) = repGauge g b₁ * repGauge g b₂}
  {repLorentz : Representation ℂ SL(2,ℂ) B}
  {hrepLorentz_mul : ∀ (Λ : SL(2,ℂ)) (b₁ b₂ : B),
    repLorentz Λ (b₁ * b₂) = repLorentz Λ b₁ * repLorentz Λ b₂}
  {F : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) →
    Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  (h : IsGaugeSector B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
      F massWeightPoly)

/-- All elements of the gauge algebra of mass weight exactly `w`: the intersection of
  the algebra generated by the field-strength towers with the part on which
  `massWeightPoly` is the monomial `X ^ w`. -/
noncomputable def massWeightSubmodule (h : IsGaugeSector B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
      F massWeightPoly) (w : ℕ) :
    Submodule ℂ B :=
  (h.gaugeAlgebra).toSubmodule
    ⊓ LinearMap.ker (massWeightPoly.toLinearMap
      - (Polynomial.monomial w : B →ₗ[B] Polynomial B).restrictScalars ℂ)

lemma massWeightPoly_of_mem_massWeightSubmodule {w : ℕ} {x : B}
    (hx : x ∈ h.massWeightSubmodule w) :
    massWeightPoly x = Polynomial.monomial w x := by
  rw [massWeightSubmodule, Submodule.mem_inf] at hx
  rcases hx with ⟨-, hx'⟩
  rw [LinearMap.mem_ker] at hx'
  simp only [LinearMap.sub_apply, AlgHom.toLinearMap_apply, LinearMap.coe_restrictScalars,
    sub_eq_zero] at hx'
  exact hx'

lemma mem_gaugeAlgebra_of_mem_massWeightSubmodule {w : ℕ} {x : B}
    (hx : x ∈ h.massWeightSubmodule w) : x ∈ h.gaugeAlgebra := by
  rw [massWeightSubmodule, Submodule.mem_inf] at hx
  exact hx.1

/-- A field-strength tower with `n` covariant derivatives has mass weight
  `2 * (2 + n)`. -/
lemma derivSubmodule_le_massWeightSubmodule (n : ℕ) :
    h.derivSubmodule n ≤ h.massWeightSubmodule (2 * (2 + n)) := by
  rw [derivSubmodule]
  refine iSup_le fun l => iSup_le fun μ => iSup_le fun ν => ?_
  rw [Submodule.span_le]
  rintro x ⟨φ, rfl⟩
  rw [massWeightSubmodule, SetLike.mem_coe, Submodule.mem_inf]
  refine ⟨Algebra.subset_adjoin (Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l,
    Set.mem_iUnion.mpr ⟨μ, Set.mem_iUnion.mpr ⟨ν, ⟨φ, rfl⟩⟩⟩⟩⟩), ?_⟩
  rw [LinearMap.mem_ker]
  simp only [LinearMap.sub_apply, AlgHom.toLinearMap_apply, LinearMap.coe_restrictScalars,
    sub_eq_zero]
  rw [h.massWeight_F l μ ν]

lemma one_le_massWeightSubmodule_zero : (1 : Submodule ℂ B) ≤ h.massWeightSubmodule 0 := by
  rw [Submodule.one_eq_span, Submodule.span_le, Set.singleton_subset_iff, SetLike.mem_coe,
    massWeightSubmodule, Submodule.mem_inf]
  refine ⟨Subalgebra.one_mem _, ?_⟩
  rw [LinearMap.mem_ker]
  simp only [LinearMap.sub_apply, AlgHom.toLinearMap_apply, LinearMap.coe_restrictScalars,
    sub_eq_zero, map_one]
  simp

lemma massWeightSubmodule_mul_le (m n : ℕ) :
    h.massWeightSubmodule m * h.massWeightSubmodule n ≤ h.massWeightSubmodule (m + n) := by
  rw [Submodule.mul_le]
  intro x hx y hy
  have hx' := hx
  have hy' := hy
  rw [massWeightSubmodule, Submodule.mem_inf] at hx hy
  rw [massWeightSubmodule, Submodule.mem_inf]
  refine ⟨Subalgebra.mul_mem _ hx.1 hy.1, ?_⟩
  rw [LinearMap.mem_ker]
  simp only [LinearMap.sub_apply, AlgHom.toLinearMap_apply, LinearMap.coe_restrictScalars,
    sub_eq_zero]
  rw [map_mul, h.massWeightPoly_of_mem_massWeightSubmodule hx',
    h.massWeightPoly_of_mem_massWeightSubmodule hy', Polynomial.monomial_mul_monomial]

/-- **The weight recursion**: an element of positive mass weight `i` is a sum of
  single field-strength towers of weight `i` and of products of two elements of lower
  positive weights summing to `i`. -/
lemma massWeightSubmodule_eq (i : ℕ) (hi : 0 < i) :
    h.massWeightSubmodule i
      = (⨆ k ∈ Finset.univ.filter (fun k : Fin i => 2 * (2 + (k : ℕ)) = i),
          h.derivSubmodule (k : ℕ))
        ⊔ (⨆ p ∈ Finset.univ.filter (fun p : Fin i × Fin i => (p.1 : ℕ) + (p.2 : ℕ) = i),
            h.massWeightSubmodule (p.1 : ℕ) * h.massWeightSubmodule (p.2 : ℕ)) := by
  refine le_antisymm (fun b hb => ?_) (sup_le ?_ ?_)
  · -- the weight-zero component of an element of the algebra is a scalar
    have hzero : ∀ x ∈ h.gaugeAlgebra, (massWeightPoly x).coeff 0 ∈ (1 : Submodule ℂ B) := by
      intro x hx
      rw [gaugeAlgebra] at hx
      induction hx using Algebra.adjoin_induction with
      | mem y hy =>
        simp only [Set.mem_iUnion, Set.mem_range] at hy
        obtain ⟨k, l, μ, ν, φ, rfl⟩ := hy
        rw [h.massWeight_F, Polynomial.coeff_monomial, if_neg (by omega)]
        exact zero_mem _
      | algebraMap r =>
        rw [AlgHom.commutes]
        simp only [Polynomial.algebraMap_apply, Polynomial.coeff_C]
        exact Submodule.mem_one.mpr ⟨r, rfl⟩
      | add x y hx hy ihx ihy =>
        rw [map_add, Polynomial.coeff_add]
        exact Submodule.add_mem _ ihx ihy
      | mul x y hx hy ihx ihy =>
        rw [map_mul, Polynomial.mul_coeff_zero]
        have hmem := Submodule.mul_mem_mul ihx ihy
        rwa [Submodule.one_mul] at hmem
    -- the components of an element of the algebra are homogeneous
    have hcomp : ∀ x ∈ h.gaugeAlgebra, ∀ m, (massWeightPoly x).coeff m
        ∈ h.massWeightSubmodule m := by
      intro x hx
      rw [gaugeAlgebra] at hx
      induction hx using Algebra.adjoin_induction with
      | mem y hy =>
        simp only [Set.mem_iUnion, Set.mem_range] at hy
        obtain ⟨k, l, μ, ν, φ, rfl⟩ := hy
        intro m
        rw [h.massWeight_F, Polynomial.coeff_monomial]
        split_ifs with hw
        · subst hw
          exact h.derivSubmodule_le_massWeightSubmodule k
            (Submodule.mem_iSup_of_mem l (Submodule.mem_iSup_of_mem μ
                (Submodule.mem_iSup_of_mem ν (Submodule.subset_span ⟨φ, rfl⟩))))
        · exact zero_mem _
      | algebraMap r =>
        intro m
        rw [AlgHom.commutes]
        simp only [Polynomial.algebraMap_apply, Polynomial.coeff_C]
        split_ifs with hm
        · subst hm
          exact h.one_le_massWeightSubmodule_zero (Submodule.mem_one.mpr ⟨r, rfl⟩)
        · exact zero_mem _
      | add x y hx hy ihx ihy =>
        intro m
        rw [map_add, Polynomial.coeff_add]
        exact Submodule.add_mem _ (ihx m) (ihy m)
      | mul x y hx hy ihx ihy =>
        intro m
        rw [map_mul, Polynomial.coeff_mul]
        refine Submodule.sum_mem _ fun p hp => ?_
        have hsum := Finset.mem_antidiagonal.mp hp
        subst hsum
        exact h.massWeightSubmodule_mul_le _ _ (Submodule.mul_mem_mul (ihx p.1) (ihy p.2))
    -- the weight-`m` component lands in the right-hand side, for every positive `m`
    have main : ∀ x ∈ h.gaugeAlgebra, ∀ m, 0 < m → (massWeightPoly x).coeff m
        ∈ (⨆ k ∈ Finset.univ.filter (fun k : Fin m => 2 * (2 + (k : ℕ)) = m),
            h.derivSubmodule (k : ℕ))
          ⊔ (⨆ p ∈ Finset.univ.filter (fun p : Fin m × Fin m => (p.1 : ℕ) + (p.2 : ℕ) = m),
              h.massWeightSubmodule (p.1 : ℕ) * h.massWeightSubmodule (p.2 : ℕ)) := by
      intro x hx
      rw [gaugeAlgebra] at hx
      induction hx using Algebra.adjoin_induction with
      | mem y hy =>
        simp only [Set.mem_iUnion, Set.mem_range] at hy
        obtain ⟨k, l, μ, ν, φ, rfl⟩ := hy
        intro m _
        rw [h.massWeight_F, Polynomial.coeff_monomial]
        split_ifs with hw
        · exact Submodule.mem_sup_left (Submodule.mem_iSup_of_mem ⟨k, by omega⟩
            (Submodule.mem_iSup_of_mem (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hw⟩)
              (Submodule.mem_iSup_of_mem l (Submodule.mem_iSup_of_mem μ
                (Submodule.mem_iSup_of_mem ν (Submodule.subset_span ⟨φ, rfl⟩))))))
        · exact zero_mem _
      | algebraMap r =>
        intro m hm
        rw [AlgHom.commutes]
        simp only [Polynomial.algebraMap_apply, Polynomial.coeff_C, if_neg (by omega : ¬ m = 0)]
        exact zero_mem _
      | add x y hx hy ihx ihy =>
        intro m hm
        rw [map_add, Polynomial.coeff_add]
        exact Submodule.add_mem _ (ihx m hm) (ihy m hm)
      | mul x y hx hy ihx ihy =>
        intro m hm
        rw [map_mul, Polynomial.coeff_mul]
        refine Submodule.sum_mem _ fun p hp => ?_
        obtain ⟨j, l⟩ := p
        have hsum := Finset.mem_antidiagonal.mp hp
        simp only at hsum ⊢
        rcases Nat.eq_zero_or_pos j with rfl | hj
        · have hlm : l = m := by omega
          rw [hlm]
          have hmem := Submodule.mul_mem_mul (hzero x hx) (ihy m hm)
          rwa [Submodule.one_mul] at hmem
        · rcases Nat.eq_zero_or_pos l with rfl | hl
          · have hjm : j = m := by omega
            rw [hjm]
            have hmem := Submodule.mul_mem_mul (ihx m hm) (hzero y hy)
            rwa [Submodule.mul_one] at hmem
          · refine Submodule.mem_sup_right (Submodule.mem_iSup_of_mem
              ((⟨⟨j, by omega⟩, ⟨l, by omega⟩⟩ : Fin m × Fin m))
              (Submodule.mem_iSup_of_mem (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hsum⟩) ?_))
            exact Submodule.mul_mem_mul (hcomp x hx j) (hcomp y hy l)
    have hb' := hb
    rw [massWeightSubmodule, Submodule.mem_inf] at hb
    have hmain := main b hb.1 i hi
    rwa [h.massWeightPoly_of_mem_massWeightSubmodule hb', Polynomial.coeff_monomial,
      if_pos rfl] at hmain
  · refine iSup_le fun k => iSup_le fun hk => ?_
    have hk' := (Finset.mem_filter.mp hk).2
    exact (h.derivSubmodule_le_massWeightSubmodule (k : ℕ)).trans (le_of_eq (by rw [hk']))
  · refine iSup_le fun p => iSup_le fun hp => ?_
    have hp' := (Finset.mem_filter.mp hp).2
    exact (h.massWeightSubmodule_mul_le (p.1 : ℕ) (p.2 : ℕ)).trans (le_of_eq (by rw [hp']))

/-!

## The mass-weight submodules in low weight

-/

/-- There is nothing of weight one. -/
lemma massWeightSubmodule_one_eq :
    h.massWeightSubmodule 1 = ⊥ := by
  rw [h.massWeightSubmodule_eq 1 (by norm_num)]
  rw [show (Finset.univ.filter (fun k : Fin 1 => 2 * (2 + (k : ℕ)) = 1)) = ∅
      from by decide,
    show (Finset.univ.filter (fun p : Fin 1 × Fin 1 => (p.1 : ℕ) + (p.2 : ℕ) = 1))
      = ∅ from by decide]
  simp

/-- There is nothing of weight two. -/
lemma massWeightSubmodule_two_eq :
    h.massWeightSubmodule 2 = ⊥ := by
  rw [h.massWeightSubmodule_eq 2 (by norm_num)]
  rw [show (Finset.univ.filter (fun k : Fin 2 => 2 * (2 + (k : ℕ)) = 2)) = ∅
      from by decide,
    show (Finset.univ.filter (fun p : Fin 2 × Fin 2 => (p.1 : ℕ) + (p.2 : ℕ) = 2))
      = {(1, 1)} from by decide]
  simp [Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.mod_succ,
    h.massWeightSubmodule_one_eq]

/-- There is nothing of weight three. -/
lemma massWeightSubmodule_three_eq :
    h.massWeightSubmodule 3 = ⊥ := by
  rw [h.massWeightSubmodule_eq 3 (by norm_num)]
  rw [show (Finset.univ.filter (fun k : Fin 3 => 2 * (2 + (k : ℕ)) = 3)) = ∅
      from by decide,
    show (Finset.univ.filter (fun p : Fin 3 × Fin 3 => (p.1 : ℕ) + (p.2 : ℕ) = 3))
      = {(1, 2), (2, 1)} from by decide]
  simp [Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.mod_succ,
    h.massWeightSubmodule_one_eq,
    h.massWeightSubmodule_two_eq]

/-- Weight four is the underived field-strength towers. -/
lemma massWeightSubmodule_four_eq :
    h.massWeightSubmodule 4 = h.derivSubmodule 0 := by
  rw [h.massWeightSubmodule_eq 4 (by norm_num)]
  rw [show (Finset.univ.filter (fun k : Fin 4 => 2 * (2 + (k : ℕ)) = 4)) = {0}
      from by decide,
    show (Finset.univ.filter (fun p : Fin 4 × Fin 4 => (p.1 : ℕ) + (p.2 : ℕ) = 4))
      = {(1, 3), (2, 2), (3, 1)} from by decide]
  simp [Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.mod_succ,
    h.massWeightSubmodule_one_eq,
    h.massWeightSubmodule_two_eq]

/-- There is nothing of weight five. -/
lemma massWeightSubmodule_five_eq :
    h.massWeightSubmodule 5 = ⊥ := by
  rw [h.massWeightSubmodule_eq 5 (by norm_num)]
  rw [show (Finset.univ.filter (fun k : Fin 5 => 2 * (2 + (k : ℕ)) = 5)) = ∅
      from by decide,
    show (Finset.univ.filter (fun p : Fin 5 × Fin 5 => (p.1 : ℕ) + (p.2 : ℕ) = 5))
      = {(1, 4), (2, 3), (3, 2), (4, 1)} from by decide]
  simp [Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.mod_succ,
    h.massWeightSubmodule_one_eq,
    h.massWeightSubmodule_two_eq]

/-- Weight six is the once-derived field-strength towers. -/
lemma massWeightSubmodule_six_eq :
    h.massWeightSubmodule 6 = h.derivSubmodule 1 := by
  rw [h.massWeightSubmodule_eq 6 (by norm_num)]
  rw [show (Finset.univ.filter (fun k : Fin 6 => 2 * (2 + (k : ℕ)) = 6)) = {1}
      from by decide,
    show (Finset.univ.filter (fun p : Fin 6 × Fin 6 => (p.1 : ℕ) + (p.2 : ℕ) = 6))
      = {(1, 5), (2, 4), (3, 3), (4, 2), (5, 1)} from by decide]
  simp [Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.mod_succ,
    h.massWeightSubmodule_one_eq,
    h.massWeightSubmodule_two_eq,
    h.massWeightSubmodule_three_eq]

/-- There is nothing of weight seven. -/
lemma massWeightSubmodule_seven_eq :
    h.massWeightSubmodule 7 = ⊥ := by
  rw [h.massWeightSubmodule_eq 7 (by norm_num)]
  rw [show (Finset.univ.filter (fun k : Fin 7 => 2 * (2 + (k : ℕ)) = 7)) = ∅
      from by decide,
    show (Finset.univ.filter (fun p : Fin 7 × Fin 7 => (p.1 : ℕ) + (p.2 : ℕ) = 7))
      = {(1, 6), (2, 5), (3, 4), (4, 3), (5, 2), (6, 1)} from by decide]
  simp [Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.mod_succ,
    h.massWeightSubmodule_one_eq,
    h.massWeightSubmodule_two_eq,
    h.massWeightSubmodule_three_eq]

/-- Weight eight is the twice-derived field-strength towers together with the
  products of two underived ones — the `∇∇F` and `F · F` sectors. -/
lemma massWeightSubmodule_eight_eq :
    h.massWeightSubmodule 8 = h.derivSubmodule 2 ⊔ h.derivSubmodule 0 * h.derivSubmodule 0 := by
  rw [h.massWeightSubmodule_eq 8 (by norm_num)]
  rw [show (Finset.univ.filter (fun k : Fin 8 => 2 * (2 + (k : ℕ)) = 8)) = {2}
      from by decide,
    show (Finset.univ.filter (fun p : Fin 8 × Fin 8 => (p.1 : ℕ) + (p.2 : ℕ) = 8))
      = {(4, 4), (1, 7), (2, 6), (3, 5), (5, 3), (6, 2), (7, 1)} from by decide]
  simp (disch := decide) [Fin.isValue, Finset.mem_singleton, iSup_iSup_eq_left,
    Fin.coe_ofNat_eq_mod, Nat.one_mod, - Finset.mem_insert, Finset.iSup_insert,
    h.massWeightSubmodule_one_eq,
    h.massWeightSubmodule_two_eq,
    h.massWeightSubmodule_three_eq,
    h.massWeightSubmodule_four_eq,
    bot_sup_eq, sup_bot_eq]

end IsGaugeSector

end StandardModel
