/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.ProbabilisticTheory.CStarAlgebra.Automorphism
public import Physlib.Mathematics.ForMathlib.OneParameterSubgroups.Unitary
public import Mathlib.Analysis.Normed.Operator.ContinuousAlgEquiv
public import Mathlib.Analysis.CStarAlgebra.Hom
public import Mathlib.Analysis.InnerProductSpace.StarOrder
public import Mathlib.Algebra.Lie.OfAssociative

/-!

# Automorphisms of the bounded operators

⋆-automorphisms of bounded operators are unitary conjugations; conjugation flows are unique.

## i. Overview

Every `⋆`-automorphism of the bounded operators on a Hilbert space is conjugation `A ↦ U A U⋆` by a
unitary, and two unitaries give the same automorphism exactly when they differ by a phase. So the
automorphism group is the projective unitary group.

A norm-continuous unitary one-parameter group `U` acts by `αₜ(a) = U(t) a U(t)⋆`. This flow is the
unique solution of the Heisenberg equation `d/dt αₜ(a) = ⁅αₜ(a), i G⁆` with `α₀ = id`, where `G` is
the generator of `U` and the bracket is the ring commutator.

## ii. Key results

- `conjStarAlgAut_surjective` : every `⋆`-automorphism is unitary conjugation.
- `conjStarAlgAut_eq_iff` : two unitaries give the same automorphism iff they differ by a phase.
- `projectiveUnitaryEquivStarAlgAut` : the automorphism group is the projective unitary group.
- `UnitaryOneParameterGroup.toAutomorphism_unique` : the conjugation flow is the unique solution of
  the Heisenberg equation.

## iii. Table of contents

- A. Every ⋆-automorphism is unitary conjugation
- B. The automorphism group generated by unitary conjugation
- C. Differential characterization

## iv. References

* None.

-/

@[expose] public section

namespace ProbabilisticTheory

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-! ## A. Every ⋆-automorphism is unitary conjugation -/

/-- Every ⋆-automorphism of `H →L[ℂ] H` is implemented by unitary conjugation. -/
lemma conjStarAlgAut_surjective :
    Function.Surjective (Unitary.conjStarAlgAut ℂ (H →L[ℂ] H)) := by
  intro φ
  obtain ⟨U, hU⟩ :=
    φ.eq_linearIsometryEquivConjStarAlgEquiv
      (NonUnitalStarAlgHom.isometry φ φ.injective).continuous
  refine ⟨Unitary.linearIsometryEquiv.symm U, ?_⟩
  rw [Unitary.conjStarAlgAut_symm_unitaryLinearIsometryEquiv]
  exact hU.symm

/-- Two unitaries implement the same ⋆-automorphism of `H →L[ℂ] H` exactly when they differ by a
scalar phase. -/
lemma conjStarAlgAut_eq_iff (u v : unitary (H →L[ℂ] H)) :
    Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) u =
        Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) v ↔
      ∃ c : unitary ℂ, u = c • v :=
  Unitary.conjStarAlgAut_ext_iff' u v

/-- The projective unitary group of `H`, obtained by quotienting out scalar phases. -/
def ProjectiveUnitary (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] :=
  unitary (H →L[ℂ] H) ⧸ MonoidHom.ker (Unitary.conjStarAlgAut ℂ (H →L[ℂ] H))

noncomputable instance : Group (ProjectiveUnitary H) := QuotientGroup.Quotient.group _

/-- Reversible transformations of `H →L[ℂ] H` are precisely projective unitaries. -/
noncomputable def projectiveUnitaryEquivStarAlgAut :
    ProjectiveUnitary H ≃* ((H →L[ℂ] H) ≃⋆ₐ[ℂ] (H →L[ℂ] H)) :=
  QuotientGroup.quotientKerEquivOfSurjective _ conjStarAlgAut_surjective

/-! ## B. The automorphism group generated by unitary conjugation -/

end ProbabilisticTheory

namespace UnitaryOneParameterGroup
open ProbabilisticTheory
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The reversible dynamics `a ↦ U(t) a U(t)⋆` induced by a unitary one-parameter group. -/
noncomputable def toAutomorphism (U : UnitaryOneParameterGroup H) :
    AutomorphismGroup (H →L[ℂ] H) where
  toFun t :=
    Unitary.conjStarAlgAut ℂ (H →L[ℂ] H)
      (⟨U t, U.mem_unitary t⟩ : unitary (H →L[ℂ] H))
  map_zero_apply a := by
    simp
  map_add_apply s t a := by
    let Us : unitary (H →L[ℂ] H) := ⟨U s, U.mem_unitary s⟩
    let Ut : unitary (H →L[ℂ] H) := ⟨U t, U.mem_unitary t⟩
    let Ust : unitary (H →L[ℂ] H) := ⟨U (s + t), U.mem_unitary (s + t)⟩
    have hU : Ust = Us * Ut := by
      apply Subtype.ext
      exact AddChar.map_add_eq_mul U.toAddChar s t
    change
      (Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) Ust) a =
        ((Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) Us) *
          (Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) Ut)) a
    rw [hU, map_mul]

/-- The induced automorphism is unitary conjugation. -/
@[simp]
lemma toAutomorphism_apply (U : UnitaryOneParameterGroup H) (t : ℝ) (a : H →L[ℂ] H) :
    (toAutomorphism U).toFun t a = U t * a * star (U t) := by
  rfl

/-! ## C. Differential characterization -/

/-- The conjugation flow satisfies the Heisenberg equation
`d/dt αₜ(a) = ⁅αₜ(a), i • generator⁆`. -/
lemma hasDerivAt_toAutomorphism (U : UnitaryOneParameterGroup H) (a : H →L[ℂ] H) (t : ℝ) :
    HasDerivAt (fun s : ℝ => (toAutomorphism U).toFun s a)
      ⁅(toAutomorphism U).toFun t a, Complex.I • U.generator⁆ t := by
  simp only [toAutomorphism_apply, LieRing.of_associative_ring_bracket]
  have hcomm := (U.commute_generator t).smul_left Complex.I
  have hd := ((U.hasDerivAt t).mul_const a).mul (U.hasDerivAt_star t)
  convert hd using 1; try rfl
  simp only [mul_neg]
  rw [← hcomm.eq]
  noncomm_ring

omit [CompleteSpace H] in
/-- A function on `ℝ` with everywhere-zero derivative is constant. -/
lemma const_of_hasDerivAt_zero {f : ℝ → H →L[ℂ] H} (hf : ∀ s, HasDerivAt f 0 s) (t : ℝ) :
    f t = f 0 := by
  apply isOpen_univ.is_const_of_deriv_eq_zero isPreconnected_univ
    (fun s _ => (hf s).differentiableAt.differentiableWithinAt)
  · intro s _
    exact (hf s).deriv
  · exact Set.mem_univ t
  · exact Set.mem_univ 0

/-- Along a solution `α` of the Heisenberg equation, the conjugated path
`s ↦ U(s)⋆ αₛ(a) U(s)` has zero derivative. -/
lemma hasDerivAt_conj_zero (U : UnitaryOneParameterGroup H)
    (α : ℝ → (H →L[ℂ] H) → H →L[ℂ] H) (a : H →L[ℂ] H)
    (hα : ∀ t, HasDerivAt (fun s => α s a) ⁅α t a, Complex.I • U.generator⁆ t)
    (s : ℝ) :
    HasDerivAt (fun r => star (U r) * α r a * U r) 0 s := by
  simp only [LieRing.of_associative_ring_bracket] at hα
  have hcomm := (U.commute_generator s).smul_left Complex.I
  have hd := ((U.hasDerivAt_star s).mul (hα s)).mul (U.hasDerivAt s)
  convert hd using 1; try rfl
  simp only [Pi.mul_apply, mul_neg]
  rw [← hcomm.eq]
  noncomm_ring

/-- The conjugation flow is the unique solution of its Heisenberg initial-value problem. -/
lemma toAutomorphism_unique (U : UnitaryOneParameterGroup H)
    (α : ℝ → (H →L[ℂ] H) → H →L[ℂ] H) (hα0 : α 0 = id)
    (hα : ∀ a t, HasDerivAt (fun s : ℝ => α s a) ⁅α t a, Complex.I • U.generator⁆ t) :
    α = fun t a => (toAutomorphism U).toFun t a := by
  funext t a
  have hβ := const_of_hasDerivAt_zero (hasDerivAt_conj_zero U α a (hα a)) t
  rw [congrFun hα0 a] at hβ
  simp only [id_eq, AddChar.map_zero_eq_one, star_one, one_mul, mul_one] at hβ
  rw [toAutomorphism_apply]
  have hmul : U t * star (U t) = 1 := Unitary.mul_star_self_of_mem (U.mem_unitary t)
  have h := congrArg (fun x : H →L[ℂ] H => U t * x * star (U t)) hβ
  rwa [show U t * (star (U t) * α t a * U t) * star (U t) =
      (U t * star (U t)) * α t a * (U t * star (U t)) by noncomm_ring, hmul, one_mul, mul_one] at h

end UnitaryOneParameterGroup

