/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.GaugeBosons.AlgebraValued.Basic
public import Physlib.Particles.StandardModel.GaugeBosons.AlgebraValued.TransformsInAdjoint
public import Physlib.Particles.StandardModel.GaugeBosons.AlgebraValued.FieldStrength
public import Physlib.Particles.StandardModel.GaugeGroup.MaurerCartan.Truncation
public import Mathlib.LinearAlgebra.Basis.Defs
public import Mathlib.LinearAlgebra.Dimension.Free
/-!

# The symmetrized field strength tensor

We define the symmetrized derivatives of the gauge field as
`sym(d_s A^a_μ) := (1/(|s|+1)) ∑_{ν ∈ s+μ} d_{(s+μ)−ν} A^a_ν`
The reason for this is two fold.

Firstly, the algebra generated by `d_s A^a_μ` is the same as the algebra generated by
`sym(d_s A^a_μ)` and `𝒟_s F^a_{μν}`.

Secondly, while the `0`th-truncated ker gauge group acts
trivially on `𝒟_s F^a_{μν}` and all other covariant derivatives it acts freely on `sym(d_s A^a_μ)`.
This means that this group can be used to gauge away the `sym(d_s A^a_μ)`.
This free action results from the map `symmetrizedMaurerCartanCoeff` which
is itself a bijection.

-/

@[expose] public section

namespace StandardModel
namespace IsGaugeField
open Matrix MatrixGroups TensorProduct MvPowerSeries
variable {B : Type} [Ring B] [Algebra ℂ B]

variable {repLorentz : Representation ℂ SL(2,ℂ) B}
variable {repGauge : Representation ℂ JetGaugeGroupI B}
variable {A : Multiset (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}

/-- The symmetrized derivative symbol `sym(d_s A)^φ`: the average over the directions
  `μ ∈ s` of the symbols `d_{s−μ} A_μ^φ`, so that the direction of the gauge field is
  symmetrized into the derivative multiset. -/
noncomputable def symmetrizedDeriv (s : Multiset (Fin 1 ⊕ Fin 3))
    (A : Multiset (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (φ : Module.Dual ℝ GaugeAlgebra) : B :=
  ((1/(s.card : ℝ) : ℝ) • (s.map fun μ => A (s - {μ}) μ φ).sum)

@[simp]
lemma symmetrizedDeriv_singleton (μ : Fin 1 ⊕ Fin 3)
    (A : Multiset (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    symmetrizedDeriv ({μ}) A φ = A 0 μ φ := by
  simp [symmetrizedDeriv]

@[simp]
lemma symmetrizedDeriv_empty
    (A : Multiset (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    symmetrizedDeriv 0 A φ = 0 := by
  simp [symmetrizedDeriv]

lemma deriv_sub_symmetrizedDeriv_eq_sum (s : Multiset (Fin 1 ⊕ Fin 3))
    (A : Multiset (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (φ : Module.Dual ℝ GaugeAlgebra)
    (μ : Fin 1 ⊕ Fin 3) :
    A s μ φ - symmetrizedDeriv (μ ::ₘ s) A φ =
      ((1/(s.card + 1 : ℝ)) • ((s.map fun ν => A s μ φ -
        A (μ ::ₘ s - {ν}) ν φ).sum)) := by
  have hn1 : (s.card : ℝ) + 1 ≠ 0 := by positivity
  rw [symmetrizedDeriv, Multiset.map_cons, Multiset.sum_cons, Multiset.card_cons,
    Multiset.sub_singleton, Multiset.erase_cons_head, Multiset.sum_map_sub,
    Multiset.map_const', Multiset.sum_replicate,
    ← Nat.cast_smul_eq_nsmul ℝ s.card,
    show ((s.card + 1 : ℕ) : ℝ) = (s.card : ℝ) + 1 by push_cast; ring]
  match_scalars <;> (field_simp; try ring)

/-!

## The generation theorem: symbols = symmetrized symbols + field strength

The chain of lemmas below implements the outline in the module docstring, leading to

  `adjoin({ d_p A }) = adjoin({ sym(d_p A) } ∪ { 𝒟_q F })`.

With the derivative symbols as primitives no Leibniz hypothesis is needed: the
covariant derivative of a family shifts the derivative index and adds a bracket
convolution, both of which stay inside the symbol subalgebras by construction.

-/

/-- The iterated covariant derivative `𝒟_l F` of an adjoint family of derivative
  symbols along a *list* of directions: covariant derivatives do not commute (their
  commutator is an `ad F` term), so the iteration is order-dependent and indexed by a
  list. The result is again a family of derivative symbols; the underived covariant
  tower is its value at the empty multiset. -/
noncomputable def iteratedCovDerivAdjoint
    (A : Multiset (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B) :
    List (Fin 1 ⊕ Fin 3) →
      (Multiset (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B) →
      Multiset (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B
  | [], F => F
  | ρ :: l, F => covDerivAdjoint A (iteratedCovDerivAdjoint A l F) ρ

/-- Symbol subalgebras are monotone in the order bound. -/
lemma adjoin_symbols_mono {n m : ℕ} (hnm : n ≤ m) :
    Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧ b = A p μ φ} ≤
      Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ m ∧ b = A p μ φ} := by
  refine Algebra.adjoin_mono fun b => ?_
  rintro ⟨p, μ, φ, h, rfl⟩
  exact ⟨p, μ, φ, h.trans hnm, rfl⟩

/-- The bracket of two component families whose components are order-`n` symbol
  polynomials is again an order-`n` symbol polynomial, componentwise. -/
lemma bracketFam_mem_adjoin_symbols {n : ℕ}
    {f g : Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
    (hf : ∀ ψ, f ψ ∈ Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
      b = A p μ φ})
    (hg : ∀ ψ, g ψ ∈ Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
      b = A p μ φ})
    (φ : Module.Dual ℝ GaugeAlgebra) :
    bracketFam f g φ ∈ Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
      b = A p μ φ} := by
  rw [bracketFam_apply_eq_sum]
  refine Subalgebra.sum_mem _ fun j _ => Subalgebra.sum_mem _ fun k _ => ?_
  rw [← algebraMap_smul ℂ]
  exact Subalgebra.smul_mem _ (mul_mem (hf _) (hg _)) _

/-- Every derivative symbol of the field strength is a symbol polynomial of order
  one higher than the number of derivatives. -/
lemma fieldStrength_mem_adjoin_symbols
    (q : Multiset (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    fieldStrength A ν lam q φ ∈
      Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ q.card + 1 ∧
        b = A p μ φ} := by
  rw [fieldStrength_apply]
  refine add_mem (sub_mem ?_ ?_) ?_
  · exact Algebra.subset_adjoin ⟨ν ::ₘ q, lam, φ, by simp, rfl⟩
  · exact Algebra.subset_adjoin ⟨lam ::ₘ q, ν, φ, by simp, rfl⟩
  · exact adjoin_symbols_mono (Nat.le_succ q.card)
      (commutatorFam_mem A q ν lam φ)

/-- **Outline step 6** (unitriangularity of the covariant tower): the covariant and
  plain derivative symbols of the field strength differ by an element of the
  subalgebra generated by lower-order symbols; consequently the two towers generate
  the same subalgebras. Stated at every derivative multiset `s`, as needed for the
  induction: the covariant derivative shifts the family index. -/
lemma iteratedCovDerivAdjoint_sub_mem
    (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra) :
    iteratedCovDerivAdjoint A l (fieldStrength A ν lam) s φ -
        fieldStrength A ν lam (Multiset.ofList l + s) φ ∈
      Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ l.length + s.card ∧
        b = A p μ φ} := by
  induction l generalizing s φ with
  | nil =>
      simp only [iteratedCovDerivAdjoint,
        show (Multiset.ofList ([] : List (Fin 1 ⊕ Fin 3))) = 0 from rfl, zero_add,
        sub_self]
      exact zero_mem _
  | cons ρ l ih =>
      have hms : Multiset.ofList (ρ :: l) + s = Multiset.ofList l + (ρ ::ₘ s) := by
        rw [show Multiset.ofList (ρ :: l) = ρ ::ₘ Multiset.ofList l from rfl,
          Multiset.cons_add, Multiset.add_cons]
      have hsplit : iteratedCovDerivAdjoint A (ρ :: l) (fieldStrength A ν lam) s φ -
          fieldStrength A ν lam (Multiset.ofList (ρ :: l) + s) φ =
        (iteratedCovDerivAdjoint A l (fieldStrength A ν lam) (ρ ::ₘ s) φ -
            fieldStrength A ν lam (Multiset.ofList l + (ρ ::ₘ s)) φ) +
          bracketFamConv A ρ (iteratedCovDerivAdjoint A l (fieldStrength A ν lam)) s φ := by
        rw [show iteratedCovDerivAdjoint A (ρ :: l) (fieldStrength A ν lam) s φ =
              iteratedCovDerivAdjoint A l (fieldStrength A ν lam) (ρ ::ₘ s) φ +
                bracketFamConv A ρ
                  (iteratedCovDerivAdjoint A l (fieldStrength A ν lam)) s φ
            from rfl, hms]
        abel
      rw [hsplit]
      refine add_mem ?_ ?_
      · refine adjoin_symbols_mono ?_ (ih (ρ ::ₘ s) φ)
        simp only [List.length_cons, Multiset.card_cons]
        omega
      · rw [bracketFamConv, Multiset.sum_linearMap_apply, Multiset.map_map]
        refine multiset_sum_mem _ fun x hx => ?_
        obtain ⟨p, hp, rfl⟩ := Multiset.mem_map.mp hx
        have hle := Multiset.mem_antidiagonal.mp hp
        have h1 : p.1.card ≤ s.card :=
          hle ▸ Multiset.card_le_card (Multiset.le_add_right _ _)
        have h2 : p.2.card ≤ s.card :=
          hle ▸ Multiset.card_le_card (Multiset.le_add_left _ _)
        refine bracketFam_mem_adjoin_symbols (fun ψ => ?_) (fun ψ => ?_) _
        · refine Algebra.subset_adjoin ⟨p.1, ρ, ψ, ?_, rfl⟩
          simp only [List.length_cons]
          omega
        · have h3 : iteratedCovDerivAdjoint A l (fieldStrength A ν lam) p.2 ψ =
              (iteratedCovDerivAdjoint A l (fieldStrength A ν lam) p.2 ψ -
                fieldStrength A ν lam (Multiset.ofList l + p.2) ψ) +
              fieldStrength A ν lam (Multiset.ofList l + p.2) ψ := by abel
          rw [h3]
          refine add_mem (adjoin_symbols_mono ?_ (ih p.2 ψ))
            (adjoin_symbols_mono ?_
              (fieldStrength_mem_adjoin_symbols (Multiset.ofList l + p.2) ν lam ψ))
          · simp only [List.length_cons]
            omega
          · simp only [Multiset.card_add, Multiset.coe_card, List.length_cons]
            omega

/-- **Outline step 7** (chaining the memberships): every derivative symbol of order
  `n + 1` lies in the subalgebra generated by its symmetrization, the covariant
  derivatives of the field strength of order `n`, and the symbols of order at most
  `n`. This is the inductive step of the generation theorem. -/
lemma symbol_mem_symFieldAdjoin_sup
    (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    A s μ φ ∈
      Algebra.adjoin ℂ
        ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
            r ≠ 0 ∧ r.card ≤ s.card + 1 ∧ b = symmetrizedDeriv r A φ} ∪
          {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
            (φ : Module.Dual ℝ GaugeAlgebra), l.length < s.card ∧
            b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ}) ⊔
      Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ (s.card - 1) ∧
        b = A p μ φ} := by
  rw [sub_eq_iff_eq_add.mp (deriv_sub_symmetrizedDeriv_eq_sum s A φ μ)]
  refine add_mem ?_ ?_
  · -- the antisymmetric remainder: field strength plus lower-order terms
    rw [← algebraMap_smul ℂ ((1 : ℝ)/(s.card + 1 : ℝ))]
    refine Subalgebra.smul_mem _ ?_ _
    refine multiset_sum_mem _ fun x hx => ?_
    obtain ⟨ν, hν, rfl⟩ := Multiset.mem_map.mp hx
    have hpos : 0 < s.card :=
      Multiset.card_pos.mpr fun h => Multiset.notMem_zero ν (h ▸ hν)
    have hcard : (s - {ν}).card = s.card - 1 := by
      rw [Multiset.sub_singleton, Multiset.card_erase_of_mem hν, Nat.pred_eq_sub_one]
    have hνs : ν ::ₘ (s - {ν}) = s := by
      rw [Multiset.sub_singleton, Multiset.cons_erase hν]
    have hμs : μ ::ₘ (s - {ν}) = μ ::ₘ s - {ν} := by
      rw [Multiset.sub_singleton, Multiset.sub_singleton]
      rcases eq_or_ne ν μ with rfl | h
      · rw [Multiset.erase_cons_head, Multiset.cons_erase hν]
      · rw [Multiset.erase_cons_tail _ h.symm]
    have hpair : A s μ φ - A (μ ::ₘ s - {ν}) ν φ =
        fieldStrength A ν μ (s - {ν}) φ - commutatorFam A ν μ (s - {ν}) φ := by
      have h := congrArg (fun f : Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B => f φ)
        (pair_eq_fieldStrength_sub_commutatorFam A ν μ (s - {ν}))
      simp only [LinearMap.sub_apply] at h
      rw [← h, hνs, hμs]
    rw [hpair]
    refine sub_mem ?_ ?_
    · -- the field-strength part, through the covariant tower
      set l := (s - {ν}).toList with hl'
      have hl : (Multiset.ofList l) = s - {ν} := Multiset.coe_toList _
      have hlen : l.length = s.card - 1 := by rw [← Multiset.coe_card, hl, hcard]
      rw [show fieldStrength A ν μ (s - {ν}) φ =
          iteratedCovDerivAdjoint A l (fieldStrength A ν μ) 0 φ -
            (iteratedCovDerivAdjoint A l (fieldStrength A ν μ) 0 φ -
              fieldStrength A ν μ (Multiset.ofList l + 0) φ)
          from by rw [add_zero, hl]; abel]
      refine sub_mem ?_ ?_
      · refine SetLike.le_def.mp le_sup_left
          (Algebra.subset_adjoin (Or.inr ⟨l, ν, μ, φ, ?_, rfl⟩))
        omega
      · refine SetLike.le_def.mp le_sup_right (adjoin_symbols_mono ?_
          (iteratedCovDerivAdjoint_sub_mem l ν μ 0 φ))
        simp only [Multiset.card_zero]
        omega
    · -- the commutator part is strictly lower order
      refine SetLike.le_def.mp le_sup_right (adjoin_symbols_mono ?_
        (commutatorFam_mem A (s - {ν}) ν μ φ))
      omega
  · -- the symmetrized symbol is a generator
    exact SetLike.le_def.mp le_sup_left
      (Algebra.subset_adjoin (Or.inl ⟨μ ::ₘ s, φ, Multiset.cons_ne_zero, by simp, rfl⟩))

/-- **The generation theorem** (outline final step, by strong induction on the
  order): the derivative symbols of order at most `n` and the symmetrized symbols
  together with the covariant field-strength tower generate the same subalgebra,

  `adjoin({ d_p A : |p| ≤ n }) = adjoin({ sym(d_p A) : |p| ≤ n } ∪ { 𝒟_q F : |q| < n })`. -/
theorem symbolAdjoin_eq_symFieldAdjoin (n : ℕ) :
    Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧ b = A p μ φ} =
      Algebra.adjoin ℂ
        ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
            r ≠ 0 ∧ r.card ≤ n + 1 ∧ b = symmetrizedDeriv r A φ} ∪
          {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
            (φ : Module.Dual ℝ GaugeAlgebra), l.length < n ∧
            b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ}) := by
  refine le_antisymm ?_ ?_
  · -- symbols are generated by symmetrized symbols and the covariant tower,
    -- by strong induction on the order
    have main : ∀ m, ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ m → m ≤ n →
        A p μ φ ∈ Algebra.adjoin ℂ
          ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
              r ≠ 0 ∧ r.card ≤ n + 1 ∧ b = symmetrizedDeriv r A φ} ∪
            {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
              (φ : Module.Dual ℝ GaugeAlgebra), l.length < n ∧
              b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ}) := by
      intro m
      induction m using Nat.strong_induction_on with
      | _ m ih =>
        intro p μ φ hpm hmn
        have hSF : Algebra.adjoin ℂ
            ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
                r ≠ 0 ∧ r.card ≤ p.card + 1 ∧ b = symmetrizedDeriv r A φ} ∪
              {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
                (φ : Module.Dual ℝ GaugeAlgebra), l.length < p.card ∧
                b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ}) ≤
            Algebra.adjoin ℂ
              ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
                  r ≠ 0 ∧ r.card ≤ n + 1 ∧ b = symmetrizedDeriv r A φ} ∪
                {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
                  (φ : Module.Dual ℝ GaugeAlgebra), l.length < n ∧
                  b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ}) := by
          refine Algebra.adjoin_mono ?_
          rintro b (⟨r, ψ, h0, hc, rfl⟩ | ⟨l, ν, lam, ψ, hl, rfl⟩)
          · exact Or.inl ⟨r, ψ, h0, by omega, rfl⟩
          · exact Or.inr ⟨l, ν, lam, ψ, by omega, rfl⟩
        have hAdj : Algebra.adjoin ℂ {b : B | ∃ (q : Multiset (Fin 1 ⊕ Fin 3))
            (κ : Fin 1 ⊕ Fin 3) (ψ : Module.Dual ℝ GaugeAlgebra), q.card ≤ (p.card - 1) ∧
            b = A q κ ψ} ≤
            Algebra.adjoin ℂ
              ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
                  r ≠ 0 ∧ r.card ≤ n + 1 ∧ b = symmetrizedDeriv r A φ} ∪
                {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
                  (φ : Module.Dual ℝ GaugeAlgebra), l.length < n ∧
                  b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ}) := by
          refine Algebra.adjoin_le ?_
          rintro b ⟨q, κ, ψ, hqc, rfl⟩
          rcases Nat.eq_zero_or_pos q.card with hq0 | hqpos
          · obtain rfl : q = 0 := Multiset.card_eq_zero.mp hq0
            refine Algebra.subset_adjoin (Or.inl ⟨{κ}, ψ, by simp, by simp, ?_⟩)
            rw [symmetrizedDeriv_singleton]
          · exact ih q.card (by omega) q κ ψ (le_refl _) (by omega)
        exact sup_le hSF hAdj (symbol_mem_symFieldAdjoin_sup p μ φ)
    refine Algebra.adjoin_le ?_
    rintro b ⟨p, μ, φ, hpc, rfl⟩
    exact main n p μ φ hpc (le_refl n)
  · -- symmetrized symbols and the covariant tower are symbol polynomials
    refine Algebra.adjoin_le ?_
    rintro b (⟨r, φ, hr0, hrc, rfl⟩ | ⟨l, ν, lam, φ, hl, rfl⟩)
    · rw [symmetrizedDeriv, ← algebraMap_smul ℂ ((1 : ℝ)/(r.card : ℝ))]
      refine Subalgebra.smul_mem _ ?_ _
      refine multiset_sum_mem _ fun x hx => ?_
      obtain ⟨ν, hν, rfl⟩ := Multiset.mem_map.mp hx
      refine Algebra.subset_adjoin ⟨r - {ν}, ν, φ, ?_, rfl⟩
      have : (r - {ν}).card = r.card - 1 := by
        rw [Multiset.sub_singleton, Multiset.card_erase_of_mem hν, Nat.pred_eq_sub_one]
      omega
    · have h6 := iteratedCovDerivAdjoint_sub_mem (A := A) l ν lam 0 φ
      have hF := fieldStrength_mem_adjoin_symbols (A := A) (Multiset.ofList l + 0) ν lam φ
      rw [show iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ =
          (iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ -
            fieldStrength A ν lam (Multiset.ofList l + 0) φ) +
          fieldStrength A ν lam (Multiset.ofList l + 0) φ
          from by abel]
      refine add_mem (adjoin_symbols_mono ?_ h6) (adjoin_symbols_mono ?_ hF)
      · simp only [Multiset.card_zero]
        omega
      · simp only [Multiset.card_add, Multiset.coe_card, Multiset.card_zero]
        omega

/-- **The generation theorem, unbounded version**: the derivative symbols of the gauge
  field of all orders, and the symmetrized symbols together with the full covariant
  field-strength tower, generate the same subalgebra of local expressions,

  `adjoin({ d_p A }) = adjoin({ sym(d_p A) } ∪ { 𝒟_q F })`.

  It follows from the graded version `symbolAdjoin_eq_symFieldAdjoin` since every
  generator on either side appears at some finite order. -/
theorem symbolAdjoin_eq_symFieldAdjoin_top :
    Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), b = A p μ φ} =
      Algebra.adjoin ℂ
        ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
            r ≠ 0 ∧ b = symmetrizedDeriv r A φ} ∪
          {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
            (φ : Module.Dual ℝ GaugeAlgebra),
            b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ}) := by
  refine le_antisymm (Algebra.adjoin_le ?_) (Algebra.adjoin_le ?_)
  · rintro b ⟨p, μ, φ, rfl⟩
    have h := (symbolAdjoin_eq_symFieldAdjoin (A := A) p.card).le
      (Algebra.subset_adjoin ⟨p, μ, φ, le_refl _, rfl⟩)
    refine Algebra.adjoin_mono ?_ h
    rintro b (⟨r, ψ, h0, _, rfl⟩ | ⟨l, ν, lam, ψ, _, rfl⟩)
    · exact Or.inl ⟨r, ψ, h0, rfl⟩
    · exact Or.inr ⟨l, ν, lam, ψ, rfl⟩
  · have hmono : ∀ n : ℕ, Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
        (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
        b = A p μ φ} ≤
        Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
          (φ : Module.Dual ℝ GaugeAlgebra), b = A p μ φ} := by
      intro n
      refine Algebra.adjoin_mono ?_
      rintro b ⟨p, μ, ψ, _, rfl⟩
      exact ⟨p, μ, ψ, rfl⟩
    rintro b (⟨r, φ, hr0, rfl⟩ | ⟨l, ν, lam, φ, rfl⟩)
    · have hcard : 1 ≤ r.card :=
        Nat.one_le_iff_ne_zero.mpr fun h => hr0 (Multiset.card_eq_zero.mp h)
      exact hmono (r.card - 1)
        ((symbolAdjoin_eq_symFieldAdjoin (A := A) (r.card - 1)).ge
          (Algebra.subset_adjoin (Or.inl ⟨r, φ, hr0, by omega, rfl⟩)))
    · exact hmono (l.length + 1)
        ((symbolAdjoin_eq_symFieldAdjoin (A := A) (l.length + 1)).ge
          (Algebra.subset_adjoin (Or.inr ⟨l, ν, lam, φ, by omega, rfl⟩)))

/-!

## The gauge action on the symmetrized derivatives

-/

/-- **The gauge transformation of the symmetrized derivatives**: averaging the
  transformation law `gauge_apply_deriv` of the individual derivative symbols over
  the multiset `s`, the homogeneous part is the symmetrized adjoint convolution and
  the inhomogeneous Maurer–Cartan shifts average to exactly the base-point value of
  the *symmetrized Maurer–Cartan form* of `U⁻¹`:

  `U • sym(d_s A)^φ = (1/|s|) ∑_{μ ∈ s} ∑_{x+y=s−μ} d_y A_μ^{∂_x Ad*(U⁻¹) φ}`
  `                   + φ( sym(mc(U⁻¹))_s |₀ )`.

  This is the symbol-level counterpart of `symmetrizedMaurerCartanForm`: the gauge
  group acts on the symmetrized derivative coordinates through the symmetrized
  Maurer–Cartan data. -/
lemma repGauge_symmetrizedDeriv (hA : IsGaugeField repLorentz repGauge A)
    (U : JetGaugeGroupI) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℝ GaugeAlgebra) :
    repGauge U (symmetrizedDeriv s A φ) =
      (1/(s.card : ℝ)) • (s.map fun μ =>
        ((s - {μ}).antidiagonal.map fun p =>
          A p.2 μ (adjointDualCoeff U⁻¹ p.1 φ)).sum).sum
      + algebraMap ℂ B (φ (JetGaugeAlgebra.eval (symmetrizedMaurerCartanForm U⁻¹ s))) := by
  set L : JetGaugeAlgebra →ₗ[ℝ] B :=
    (Algebra.linearMap ℂ B).restrictScalars ℝ ∘ₗ Algebra.linearMap ℝ ℂ ∘ₗ
      φ ∘ₗ JetGaugeAlgebra.eval.toLinearMap with hL
  rw [symmetrizedDeriv, LinearMap.map_smul_of_tower, map_multiset_sum, Multiset.map_map]
  simp only [Function.comp_def]
  rw [Multiset.map_congr rfl (fun μ _ => hA.gauge_apply_deriv U (s - {μ}) μ φ),
    Multiset.sum_map_add, smul_add]
  congr 1
  calc (1/(s.card : ℝ)) • (s.map fun μ => algebraMap ℂ B (φ (JetGaugeAlgebra.eval
        (JetGaugeAlgebra.iteratedDeriv (s - {μ}) (maurerCartanForm U⁻¹ μ))))).sum
      = (1/(s.card : ℝ)) • (s.map fun μ =>
          L (JetGaugeAlgebra.iteratedDeriv (s - {μ}) (maurerCartanForm U⁻¹ μ))).sum := rfl
    _ = L ((1/(s.card : ℝ)) • (s.map fun μ =>
          JetGaugeAlgebra.iteratedDeriv (s - {μ}) (maurerCartanForm U⁻¹ μ)).sum) := by
        rw [map_smul, map_multiset_sum, Multiset.map_map]
        simp only [Function.comp_def]
    _ = algebraMap ℂ B (φ (JetGaugeAlgebra.eval (symmetrizedMaurerCartanForm U⁻¹ s))) := by
        rw [symmetrizedMaurerCartanForm]
        rfl

/-- **The action of the truncation kernel on the symmetrized derivatives is through
  the symmetrized Maurer–Cartan coefficients**: for a gauge jet `U` whose value at
  the base point is the identity, the inhomogeneous shift of `sym(d_s A)^φ` is the
  pairing of `φ` with the symmetrized Maurer–Cartan coefficient of `U⁻¹` at `s` —
  the very data that classifies pure jets (`symmetrizedMaurerCartanCoeff_injective`).
  This is the mechanism by which the truncation kernel can be used to gauge away the
  symmetrized derivative coordinates. -/
lemma repGauge_symmetrizedDeriv_truncationKer
    (hA : IsGaugeField repLorentz repGauge A)
    (U : JetGaugeGroupI.truncationKer 0) (s : Multiset (Fin 1 ⊕ Fin 3)) (hs : s ≠ 0)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    repGauge U.1 (symmetrizedDeriv s A φ) =
      (1/(s.card : ℝ)) • (s.map fun μ =>
        ((s - {μ}).antidiagonal.map fun p =>
          A p.2 μ (adjointDualCoeff (U.1)⁻¹ p.1 φ)).sum).sum
      + algebraMap ℂ B (φ (symmetrizedMaurerCartanCoeff U⁻¹ ⟨s, hs⟩)) := by
  rw [repGauge_symmetrizedDeriv hA U.1 s φ]
  rfl

/-- **The truncation kernel realizes arbitrary translations of the symmetrized
  derivative coordinates**: for any prescribed family `c` of gauge-algebra values,
  there is a gauge jet `U` in the kernel of the zeroth truncation whose action shifts
  every symmetrized derivative symbol by exactly `φ (c s)` — by the surjectivity of
  the symmetrized Maurer–Cartan coefficients.

  This is the freeness/transitivity statement behind "gauging away" the symmetrized
  coordinates: since the action of `U` is invertible on `B`, no symbol is literally
  sent to zero, but on any fixed field configuration (a point of `Spec B`) the shift
  `c` can be chosen to cancel the configuration's symmetrized derivative values. -/
lemma exists_repGauge_symmetrizedDeriv_shift
    (hA : IsGaugeField repLorentz repGauge A)
    (c : {r : Multiset (Fin 1 ⊕ Fin 3) // r ≠ 0} → GaugeAlgebra) :
    ∃ U : JetGaugeGroupI.truncationKer 0,
      ∀ (s : Multiset (Fin 1 ⊕ Fin 3)) (hs : s ≠ 0) (φ : Module.Dual ℝ GaugeAlgebra),
        repGauge U.1 (symmetrizedDeriv s A φ) =
          (1/(s.card : ℝ)) • (s.map fun μ =>
            ((s - {μ}).antidiagonal.map fun p =>
              A p.2 μ (adjointDualCoeff (U.1)⁻¹ p.1 φ)).sum).sum
          + algebraMap ℂ B (φ (c ⟨s, hs⟩)) := by
  obtain ⟨V, hV⟩ := symmetrizedMaurerCartanCoeff_surjective c
  refine ⟨V⁻¹, fun s hs φ => ?_⟩
  rw [repGauge_symmetrizedDeriv_truncationKer hA V⁻¹ s hs φ, inv_inv, hV]

/-!

## Centrality of the gauge-field symbols, and invariants of the truncation kernel

Throughout, `hc` is the hypothesis that all derivative symbols of the gauge field are
central in `B` — the statement that the gauge field is bosonic. Everything built from
the symbols by the bracket is then central as well.

-/

/-- Scalars are central. -/
lemma algebraMap_mem_center (c : ℂ) : algebraMap ℂ B c ∈ Subring.center B :=
  Subring.mem_center_iff.mpr fun b => (Algebra.commutes c b).symm

/-- Real multiples of central elements are central. -/
lemma smul_mem_center (r : ℝ) {x : B} (hx : x ∈ Subring.center B) :
    r • x ∈ Subring.center B := by
  rw [← algebraMap_smul ℂ r x, Algebra.smul_def]
  exact Subring.mul_mem _ (algebraMap_mem_center _) hx

/-- The bracket of component families with central components is central. -/
lemma bracketFam_mem_center {f g : Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
    (hf : ∀ ψ, f ψ ∈ Subring.center B) (hg : ∀ ψ, g ψ ∈ Subring.center B)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    bracketFam f g φ ∈ Subring.center B := by
  rw [bracketFam_apply_eq_sum]
  refine Subring.sum_mem _ fun j _ => Subring.sum_mem _ fun k _ => ?_
  exact smul_mem_center _ (Subring.mul_mem _ (hf _) (hg _))

/-- The derived commutator terms of central symbols are central. -/
lemma commutatorFam_mem_center
    (hc : ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra), A p μ φ ∈ Subring.center B)
    (ν lam : Fin 1 ⊕ Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℝ GaugeAlgebra) :
    commutatorFam A ν lam s φ ∈ Subring.center B := by
  rw [commutatorFam, Multiset.sum_linearMap_apply, Multiset.map_map]
  refine multiset_sum_mem _ fun x hx => ?_
  obtain ⟨p, hp, rfl⟩ := Multiset.mem_map.mp hx
  exact bracketFam_mem_center (fun ψ => hc _ _ _) (fun ψ => hc _ _ _) φ

/-- **1.** If the derivative symbols of the gauge field are central, so are all
  derivative symbols of the covariant derivatives of the field strength. -/
lemma iteratedCovDerivAdjoint_fieldStrength_mem_center
    (hc : ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra), A p μ φ ∈ Subring.center B)
    (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra) :
    iteratedCovDerivAdjoint A l (fieldStrength A ν lam) s φ ∈ Subring.center B := by
  induction l generalizing s φ with
  | nil =>
      show fieldStrength A ν lam s φ ∈ Subring.center B
      rw [fieldStrength_apply]
      exact Subring.add_mem _
        (Subring.sub_mem _ (hc _ _ _) (hc _ _ _))
        (commutatorFam_mem_center hc ν lam s φ)
  | cons ρ l ih =>
      rw [show iteratedCovDerivAdjoint A (ρ :: l) (fieldStrength A ν lam) s φ =
          iteratedCovDerivAdjoint A l (fieldStrength A ν lam) (ρ ::ₘ s) φ +
            bracketFamConv A ρ
              (iteratedCovDerivAdjoint A l (fieldStrength A ν lam)) s φ
          from rfl]
      refine Subring.add_mem _ (ih (ρ ::ₘ s) φ) ?_
      rw [bracketFamConv, Multiset.sum_linearMap_apply, Multiset.map_map]
      refine multiset_sum_mem _ fun x hx => ?_
      obtain ⟨p, hp, rfl⟩ := Multiset.mem_map.mp hx
      exact bracketFam_mem_center (fun ψ => hc _ _ _) (fun ψ => ih p.2 ψ) φ

/-- **2.** If the derivative symbols of the gauge field are central, so are the
  symmetrized derivative symbols. -/
lemma symmetrizedDeriv_mem_center
    (hc : ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra), A p μ φ ∈ Subring.center B)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra) :
    symmetrizedDeriv s A φ ∈ Subring.center B := by
  rw [symmetrizedDeriv]
  refine smul_mem_center _ (multiset_sum_mem _ fun x hx => ?_)
  obtain ⟨μ, hμ, rfl⟩ := Multiset.mem_map.mp hx
  exact hc _ _ _

/-- **3.** Anything that transforms in the adjoint is invariant under the kernel of
  the zeroth truncation: at `s = 0` the transformation law is the dual adjoint action
  of the base-point value `U₀⁻¹ = 1`, which is trivial. -/
lemma TransformsInAdjoint.repGauge_eq_of_mem_truncationKer_zero
    {F : Multiset (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
    (hF : TransformsInAdjoint repGauge F)
    (U : JetGaugeGroupI.truncationKer 0) (φ : Module.Dual ℝ GaugeAlgebra) :
    repGauge U.1 (F 0 φ) = F 0 φ := by
  have hinv : ((U.1)⁻¹).eval = 1 := by
    rw [map_inv, JetGaugeGroupI.mem_truncationKer_zero_iff.mp U.2, inv_one]
  simpa [adjointDualCoeff_zero_of_eval_eq_one hinv] using hF U.1 φ 0

/-- **Every iterated covariant derivative of the field strength is an adjoint gauge
  tensor**: the recursion of `TransformsInAdjoint.covDerivAdjoint` over the list of
  directions, from the base case `transformsInAdjoint_fieldStrength`. -/
theorem transformsInAdjoint_iteratedCovDerivAdjoint
    (hA : IsGaugeField repLorentz repGauge A) (l : List (Fin 1 ⊕ Fin 3))
    (ν lam : Fin 1 ⊕ Fin 3) :
    TransformsInAdjoint repGauge
      (iteratedCovDerivAdjoint A l (fieldStrength A ν lam)) := by
  induction l with
  | nil => exact transformsInAdjoint_fieldStrength hA ν lam
  | cons ρ l ih => exact TransformsInAdjoint.covDerivAdjoint hA ih ρ

/-- **4.** The covariant derivatives of the field strength are invariant under the
  kernel of the zeroth truncation: they transform in the adjoint, and the truncation
  kernel acts through the trivial base-point adjoint. -/
lemma repGauge_iteratedCovDerivAdjoint_fieldStrength_of_mem_truncationKer_zero
    (hA : IsGaugeField repLorentz repGauge A)
    (U : JetGaugeGroupI.truncationKer 0) (l : List (Fin 1 ⊕ Fin 3))
    (ν lam : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra) :
    repGauge U.1 (iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ) =
      iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ :=
  (transformsInAdjoint_iteratedCovDerivAdjoint hA l ν
    lam).repGauge_eq_of_mem_truncationKer_zero U φ

/-!

## The classification of invariants

The goal of this section is the classification theorem: a gauge-invariant element of
the subalgebra generated by the gauge-field symbols together with a set `S` of
`truncationKer 0`-fixed elements lies in the subalgebra generated by the covariant
field-strength tower together with `S` — assuming only that the gauge-field symbols
are central (bosonic), with **no algebraic-independence hypothesis**.

The strategy, by downward induction on the top symbol order `N` present in `x`:

* By the generation theorem (relativized to `S`), `x` is a polynomial expression in
  the symmetrized symbols of order `≤ N`, the covariant field-strength tower, and `S`.
* Using the surjectivity of the symmetrized Maurer–Cartan coefficients, choose gauge
  jets whose coefficients are supported at exactly order `N`. The Maurer–Cartan
  triangularity places such jets in the deep truncation kernel `truncationKer (N-1)`,
  which kills all dual adjoint coefficients of positive order `< N`. Consequently
  such a jet fixes every generator of order `< N`, fixes the covariant tower and `S`,
  and acts on the order-`N` symmetrized symbols by a *pure translation* with an
  arbitrary prescribable scalar family.
* The extraction step needs no independence: pick *any* representation of `x` as a
  polynomial in the top symbols over the fixed subalgebra. Invariance under all
  translations gives, for every shift vector, a polynomial identity; evaluating at
  sufficiently many shifts (a Vandermonde argument — pure linear algebra in `B`, no
  freeness) forces the top coefficient of *the chosen representation* to vanish, and
  downward induction kills every nonconstant coefficient. Hence `x` lies in the fixed
  subalgebra, completing the induction step.

-/

/-- The generation theorem relativized to an arbitrary set `S` of extra generators:
  a corollary of `symbolAdjoin_eq_symFieldAdjoin` since `adjoin (X ∪ S)` is
  determined by `adjoin X` and `S`. -/
theorem symbolAdjoin_union_eq_symFieldAdjoin_union (n : ℕ) (S : Set B) :
    Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
        b = A p μ φ} ∪ S) =
      Algebra.adjoin ℂ
        (({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
            r ≠ 0 ∧ r.card ≤ n + 1 ∧ b = symmetrizedDeriv r A φ} ∪
          {b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
            (φ : Module.Dual ℝ GaugeAlgebra), l.length < n ∧
            b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ}) ∪ S) := by
  rw [Algebra.adjoin_union, Algebra.adjoin_union,
    symbolAdjoin_eq_symFieldAdjoin (A := A) n]

/-- Finite order bound: membership in the subalgebra generated by all symbols and `S`
  uses only finitely many generators, hence symbols of some bounded order. -/
lemma exists_le_of_mem_adjoin_symbols_union (S : Set B) {x : B}
    (hx : x ∈ Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra),
      b = A p μ φ} ∪ S)) :
    ∃ n : ℕ, x ∈ Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
      b = A p μ φ} ∪ S) := by
  have hmono : ∀ {n m : ℕ}, n ≤ m →
      Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ n ∧
        b = A p μ φ} ∪ S) ≤
      Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ m ∧
        b = A p μ φ} ∪ S) := by
    intro n m hnm
    refine Algebra.adjoin_mono (Set.union_subset_union_left S ?_)
    rintro b ⟨p, μ, φ, h, rfl⟩
    exact ⟨p, μ, φ, h.trans hnm, rfl⟩
  induction hx using Algebra.adjoin_induction with
  | mem b hb =>
      rcases hb with ⟨p, μ, φ, rfl⟩ | hbS
      · exact ⟨p.card, Algebra.subset_adjoin (Or.inl ⟨p, μ, φ, le_refl _, rfl⟩)⟩
      · exact ⟨0, Algebra.subset_adjoin (Or.inr hbS)⟩
  | algebraMap c => exact ⟨0, Subalgebra.algebraMap_mem _ c⟩
  | add u v hu hv ihu ihv =>
      obtain ⟨n₁, h₁⟩ := ihu
      obtain ⟨n₂, h₂⟩ := ihv
      exact ⟨max n₁ n₂, add_mem (hmono (le_max_left _ _) h₁) (hmono (le_max_right _ _) h₂)⟩
  | mul u v hu hv ihu ihv =>
      obtain ⟨n₁, h₁⟩ := ihu
      obtain ⟨n₂, h₂⟩ := ihv
      exact ⟨max n₁ n₂, mul_mem (hmono (le_max_left _ _) h₁) (hmono (le_max_right _ _) h₂)⟩

/-- **Pure translation**: when all positive dual adjoint coefficients of `U⁻¹` below
  the order of `s` vanish, the adjoint convolution in the transformation of the
  symmetrized symbol collapses to the symbol itself, and the action is an honest
  translation by the symmetrized Maurer–Cartan coefficient. -/
theorem repGauge_symmetrizedDeriv_translation
    (hA : IsGaugeField repLorentz repGauge A)
    (U : JetGaugeGroupI.truncationKer 0) (s : Multiset (Fin 1 ⊕ Fin 3)) (hs : s ≠ 0)
    (hU : ∀ x : Multiset (Fin 1 ⊕ Fin 3), x ≠ 0 → x.card < s.card →
      adjointDualCoeff (U.1)⁻¹ x = 0)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    repGauge U.1 (symmetrizedDeriv s A φ) =
      symmetrizedDeriv s A φ +
        algebraMap ℂ B (φ (symmetrizedMaurerCartanCoeff U⁻¹ ⟨s, hs⟩)) := by
  -- collapsing principle: a sum over the antidiagonal whose terms vanish off the
  -- `(0, t)` splitting reduces to the `(0, t)` term
  have hcollapse : ∀ (t : Multiset (Fin 1 ⊕ Fin 3))
      (g : Multiset (Fin 1 ⊕ Fin 3) × Multiset (Fin 1 ⊕ Fin 3) → B),
      (∀ p : Multiset (Fin 1 ⊕ Fin 3) × Multiset (Fin 1 ⊕ Fin 3),
        p.1 + p.2 = t → p.1 ≠ 0 → g p = 0) →
      (t.antidiagonal.map g).sum = g (0, t) := by
    intro t
    induction t using Multiset.induction_on with
    | empty =>
        intro g hg
        simp [Multiset.antidiagonal_zero]
    | cons a t ih =>
        intro g hg
        rw [Multiset.antidiagonal_cons, Multiset.map_add, Multiset.sum_add,
          Multiset.map_map, Multiset.map_map]
        have h1 : ((t.antidiagonal.map (g ∘ Prod.map (a ::ₘ ·) id)).sum) = 0 := by
          refine Multiset.sum_eq_zero fun z hz => ?_
          obtain ⟨q, hq, rfl⟩ := Multiset.mem_map.mp hz
          have hq' := Multiset.mem_antidiagonal.mp hq
          refine hg _ ?_ (Multiset.cons_ne_zero)
          show (a ::ₘ q.1) + q.2 = a ::ₘ t
          rw [Multiset.cons_add, hq']
        have h2 : ((t.antidiagonal.map (g ∘ Prod.map id (a ::ₘ ·))).sum) =
            g (0, a ::ₘ t) := by
          rw [ih (g ∘ Prod.map id (a ::ₘ ·)) fun p hp hp1 => ?_]
          · rfl
          · refine hg _ ?_ hp1
            show p.1 + (a ::ₘ p.2) = a ::ₘ t
            rw [Multiset.add_cons, hp]
        rw [h1, h2, add_zero]
  rw [repGauge_symmetrizedDeriv_truncationKer hA U s hs φ]
  congr 1
  have hinv1 : ((U.1)⁻¹).eval = 1 := by
    rw [map_inv, JetGaugeGroupI.eval_coe_of_mem_truncationKer_zero U, inv_one]
  have hid := adjointDualCoeff_zero_of_eval_eq_one hinv1
  rw [symmetrizedDeriv]
  congr 1
  refine congrArg Multiset.sum (Multiset.map_congr rfl fun μ hμ => ?_)
  have hvan : ∀ p : Multiset (Fin 1 ⊕ Fin 3) × Multiset (Fin 1 ⊕ Fin 3),
      p.1 + p.2 = s - {μ} → p.1 ≠ 0 →
      A p.2 μ (adjointDualCoeff (U.1)⁻¹ p.1 φ) = 0 := by
    intro p hp hp1
    have hcard : p.1.card < s.card := by
      have h1 : p.1.card + p.2.card = (s - {μ}).card := by rw [← Multiset.card_add, hp]
      have h2 : (s - {μ}).card = s.card - 1 := by
        rw [Multiset.sub_singleton, Multiset.card_erase_of_mem hμ, Nat.pred_eq_sub_one]
      have h3 : s.card ≠ 0 := fun h => hs (Multiset.card_eq_zero.mp h)
      omega
    rw [hU p.1 hp1 hcard]
    simp
  rw [hcollapse (s - {μ}) _ hvan, hid]
  rfl

/-- **Realization of top-order translations**: any coefficient family supported at
  exactly order `N` is realized by a jet in the deep truncation kernel — surjectivity
  of the symmetrized Maurer–Cartan coefficients together with the triangularity and
  vanishing theorems above. -/
theorem exists_translation_of_support
    (N : ℕ) (c : {r : Multiset (Fin 1 ⊕ Fin 3) // r ≠ 0} → GaugeAlgebra)
    (hcN : ∀ r, r.1.card ≠ N → c r = 0) :
    ∃ U : JetGaugeGroupI.truncationKer 0,
      symmetrizedMaurerCartanCoeff U⁻¹ = c ∧
      ∀ x : Multiset (Fin 1 ⊕ Fin 3), x ≠ 0 → x.card < N →
        adjointDualCoeff (U.1)⁻¹ x = 0 := by
  obtain ⟨V, hV⟩ := symmetrizedMaurerCartanCoeff_surjective c
  -- the realizing jet is deep in the truncation filtration, by triangularity
  have hVmem : V.1 ∈ JetGaugeGroupI.truncationKer (N - 1) := by
    refine mem_truncationKer_of_symmetrizedMaurerCartanCoeff_eq_zero V (N - 1) ?_
    intro r hr hrcard
    rw [hV]
    refine hcN ⟨r, hr⟩ ?_
    show r.card ≠ N
    have hne : r.card ≠ 0 := fun h => hr (Multiset.card_eq_zero.mp h)
    omega
  refine ⟨V⁻¹, by rw [inv_inv, hV], fun x hx hxN => ?_⟩
  have hcoe : ((V⁻¹ : JetGaugeGroupI.truncationKer 0).1)⁻¹ = V.1 := by simp
  rw [hcoe]
  exact adjointDualCoeff_eq_zero_of_mem_truncationKer hVmem hx (by omega)

/-- A `B`-valued polynomial function of one real variable that vanishes identically
  has vanishing coefficients: pair with real-linear functionals, which separate
  points, and use that a real polynomial vanishing everywhere is zero. -/
lemma eq_zero_of_forall_sum_smul_pow_eq_zero {n : ℕ} {b : ℕ → B}
    (h : ∀ t : ℝ, ∑ m ∈ Finset.range n, t ^ m • b m = 0) :
    ∀ m ∈ Finset.range n, b m = 0 := by
  intro m hm
  rw [← Module.forall_dual_apply_eq_zero_iff ℝ]
  intro f
  have hpz : (∑ j ∈ Finset.range n, Polynomial.C (f (b j)) * Polynomial.X ^ j :
      Polynomial ℝ) = 0 := by
    refine Polynomial.zero_of_eval_zero _ fun t => ?_
    have h1 := congrArg f (h t)
    rw [map_sum, map_zero] at h1
    rw [Polynomial.eval_finsetSum]
    simp only [Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_pow,
      Polynomial.eval_X]
    rw [← h1]
    exact Finset.sum_congr rfl fun j _ => by rw [map_smul, smul_eq_mul, mul_comm]
  have hcoeff := congrArg (fun q => Polynomial.coeff q m) hpz
  simp only [Polynomial.finsetSum_coeff, Polynomial.coeff_C_mul, Polynomial.coeff_X_pow,
    Polynomial.coeff_zero, mul_ite, mul_one, mul_zero] at hcoeff
  rwa [Finset.sum_ite_eq (Finset.range n) m (fun j => f (b j)), if_pos hm] at hcoeff

/-- Any element of the subalgebra generated by a subalgebra `R` and a single central
  element `y` is a polynomial in `y` with coefficients in `R`. -/
lemma exists_polynomial_rep (R : Subalgebra ℂ B) (y : B)
    (hy : ∀ r ∈ R, Commute r y)
    {x : B} (hx : x ∈ R ⊔ Algebra.adjoin ℂ {y}) :
    ∃ (n : ℕ) (r : ℕ → B), (∀ k, r k ∈ R) ∧ x = ∑ k ∈ Finset.range n, r k * y ^ k := by
  classical
  have hx' : x ∈ Algebra.adjoin ℂ (↑R ∪ {y}) := by
    rw [Algebra.adjoin_union, Algebra.adjoin_eq]
    exact hx
  clear hx
  -- single monomials are representable
  have hmono : ∀ z : B, z ∈ R → ∀ k : ℕ, ∃ (n : ℕ) (r : ℕ → B), (∀ j, r j ∈ R) ∧
      z * y ^ k = ∑ j ∈ Finset.range n, r j * y ^ j := by
    intro z hz k
    refine ⟨k + 1, fun j => if j = k then z else 0,
      fun j => by show (if j = k then z else 0) ∈ R; split_ifs; exacts [hz, zero_mem R], ?_⟩
    rw [Finset.sum_congr rfl fun j _ => by rw [ite_mul, zero_mul],
      Finset.sum_ite_eq' (Finset.range (k + 1)) k (fun j => z * y ^ j),
      if_pos (Finset.self_mem_range_succ k)]
  -- representability is closed under addition
  have hadd : ∀ x₁ x₂ : B,
      (∃ (n : ℕ) (r : ℕ → B), (∀ j, r j ∈ R) ∧ x₁ = ∑ j ∈ Finset.range n, r j * y ^ j) →
      (∃ (n : ℕ) (r : ℕ → B), (∀ j, r j ∈ R) ∧ x₂ = ∑ j ∈ Finset.range n, r j * y ^ j) →
      ∃ (n : ℕ) (r : ℕ → B), (∀ j, r j ∈ R) ∧
        x₁ + x₂ = ∑ j ∈ Finset.range n, r j * y ^ j := by
    rintro x₁ x₂ ⟨n₁, r₁, h₁, rfl⟩ ⟨n₂, r₂, h₂, rfl⟩
    have hext : ∀ (n m : ℕ) (r : ℕ → B), n ≤ m →
        (∑ j ∈ Finset.range n, r j * y ^ j) =
          ∑ j ∈ Finset.range m, (if j < n then r j else 0) * y ^ j :=
      fun n m r hnm =>
        (Finset.sum_congr rfl fun j hj => by
            rw [if_pos (Finset.mem_range.mp hj)]).trans
          (Finset.sum_subset (Finset.range_subset_range.mpr hnm) fun j _ hj => by
            rw [if_neg fun h => hj (Finset.mem_range.mpr h), zero_mul])
    refine ⟨max n₁ n₂,
      fun j => (if j < n₁ then r₁ j else 0) + (if j < n₂ then r₂ j else 0),
      fun j => add_mem (by split_ifs; exacts [h₁ j, zero_mem R])
        (by split_ifs; exacts [h₂ j, zero_mem R]), ?_⟩
    rw [hext n₁ (max n₁ n₂) r₁ (le_max_left _ _), hext n₂ (max n₁ n₂) r₂ (le_max_right _ _),
      ← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl fun j _ => by rw [add_mul]
  -- representability is closed under finite sums
  have hsum : ∀ (κ : Type) (s : Finset κ) (f : κ → B),
      (∀ i ∈ s, ∃ (n : ℕ) (r : ℕ → B), (∀ j, r j ∈ R) ∧
        f i = ∑ j ∈ Finset.range n, r j * y ^ j) →
      ∃ (n : ℕ) (r : ℕ → B), (∀ j, r j ∈ R) ∧
        (∑ i ∈ s, f i) = ∑ j ∈ Finset.range n, r j * y ^ j := by
    intro κ s f hf
    classical
    induction s using Finset.induction_on with
    | empty => exact ⟨0, fun _ => 0, fun _ => zero_mem R, by simp⟩
    | insert i s his ih =>
        rw [Finset.sum_insert his]
        exact hadd _ _ (hf i (Finset.mem_insert_self i s))
          (ih fun i' hi' => hf i' (Finset.mem_insert_of_mem hi'))
  induction hx' using Algebra.adjoin_induction with
  | mem b hb =>
      rcases hb with hbR | hby
      · obtain ⟨n, r, hr, hrep⟩ := hmono b hbR 0
        exact ⟨n, r, hr, by rw [← hrep, pow_zero, mul_one]⟩
      · rw [Set.mem_singleton_iff] at hby
        subst hby
        obtain ⟨n, r, hr, hrep⟩ := hmono 1 (one_mem R) 1
        exact ⟨n, r, hr, by rw [← hrep, pow_one, one_mul]⟩
  | algebraMap c =>
      obtain ⟨n, r, hr, hrep⟩ := hmono (algebraMap ℂ B c) (Subalgebra.algebraMap_mem R c) 0
      exact ⟨n, r, hr, by rw [← hrep, pow_zero, mul_one]⟩
  | add u v hu hv ihu ihv => exact hadd u v ihu ihv
  | mul u v hu hv ihu ihv =>
      obtain ⟨n₁, r₁, h₁, rfl⟩ := ihu
      obtain ⟨n₂, r₂, h₂, rfl⟩ := ihv
      rw [Finset.sum_mul_sum]
      refine hsum _ _ _ fun k _ => hsum _ _ _ fun l _ => ?_
      have hcomm : y ^ k * r₂ l = r₂ l * y ^ k :=
        ((hy _ (h₂ l)).pow_right k).eq.symm
      have hterm : (r₁ k * y ^ k) * (r₂ l * y ^ l) = (r₁ k * r₂ l) * y ^ (k + l) := by
        rw [← mul_assoc, mul_assoc (r₁ k), hcomm, ← mul_assoc, mul_assoc, ← pow_add]
      rw [hterm]
      exact hmono _ (mul_mem (h₁ k) (h₂ l)) (k + l)

/-- The single-variable extraction: an element of `R[y]` invariant under a family of
  ring endomorphisms fixing `R` pointwise and translating the central element `y` by
  arbitrary prescribable real scalars lies in `R`. Invariance forces the top
  coefficient of any chosen polynomial representation to vanish, by expanding the
  translated polynomial and extracting the top power of the shift. -/
lemma mem_of_translationInvariant_single (R : Subalgebra ℂ B) (y : B)
    (hy : ∀ r ∈ R, Commute r y) (Φ : ℝ → B →+* B)
    (hΦR : ∀ t : ℝ, ∀ z ∈ R, Φ t z = z)
    (hΦy : ∀ t : ℝ, Φ t y = y + algebraMap ℂ B (t : ℂ))
    {x : B} (hx : x ∈ R ⊔ Algebra.adjoin ℂ {y}) (hinv : ∀ t, Φ t x = x) : x ∈ R := by
  -- scalars pull out of products against the algebra
  have hpull : ∀ (z : ℂ) (w : B), w * algebraMap ℂ B z = z • w := fun z w => by
    rw [← Algebra.commutes z w, ← Algebra.smul_def]
  -- the binomial expansion of the translate of a single monomial
  have hterm : ∀ (r : ℕ → B), (∀ k, r k ∈ R) → ∀ (t : ℝ) (k : ℕ), Φ t (r k * y ^ k) =
      ∑ j ∈ Finset.range (k + 1), t ^ j • ((k.choose j : ℂ) • (r k * y ^ (k - j))) := by
    intro r hrR t k
    rw [map_mul, map_pow, hΦR t _ (hrR k), hΦy t,
      Commute.add_pow ((Algebra.commute_algebraMap_left ((t : ℝ) : ℂ) y).symm) k,
      Finset.mul_sum]
    conv_rhs => rw [← Finset.sum_range_reflect]
    simp only [Nat.add_sub_cancel]
    refine Finset.sum_congr rfl fun i hi => ?_
    have hik : i ≤ k := Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)
    rw [Nat.choose_symm hik, Nat.sub_sub_self hik, ← map_pow,
      ← map_natCast (algebraMap ℂ B) (k.choose i), mul_assoc (y ^ i), ← map_mul,
      ← mul_assoc, hpull, mul_smul, ← Complex.ofReal_pow, Complex.coe_smul]
  suffices h : ∀ (n : ℕ) (r : ℕ → B), (∀ k, r k ∈ R) →
      (∀ t, Φ t (∑ k ∈ Finset.range n, r k * y ^ k) = ∑ k ∈ Finset.range n, r k * y ^ k) →
      (∑ k ∈ Finset.range n, r k * y ^ k) ∈ R by
    obtain ⟨n, r, hrR, rfl⟩ := exists_polynomial_rep R y hy hx
    exact h n r hrR hinv
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro r hrR hinv
    rcases n with _ | n
    · simp
    rcases n with _ | m
    · have h1 : (∑ k ∈ Finset.range 1, r k * y ^ k) = r 0 := by
        rw [Finset.sum_range_one, pow_zero, mul_one]
      rw [h1]
      exact hrR 0
    -- top order `m + 1 ≥ 1`: the collected coefficients of the shift powers
    set b : ℕ → B := fun j => ∑ k ∈ Finset.range (m + 2),
      if j ≤ k then (k.choose j : ℂ) • (r k * y ^ (k - j)) else 0 with hbdef
    have hexp : ∀ t : ℝ, Φ t (∑ k ∈ Finset.range (m + 2), r k * y ^ k) =
        ∑ j ∈ Finset.range (m + 2), t ^ j • b j := by
      intro t
      calc Φ t (∑ k ∈ Finset.range (m + 2), r k * y ^ k)
          = ∑ k ∈ Finset.range (m + 2), Φ t (r k * y ^ k) := map_sum _ _ _
        _ = ∑ k ∈ Finset.range (m + 2), ∑ j ∈ Finset.range (k + 1),
              t ^ j • ((k.choose j : ℂ) • (r k * y ^ (k - j))) :=
            Finset.sum_congr rfl fun k _ => hterm r hrR t k
        _ = ∑ k ∈ Finset.range (m + 2), ∑ j ∈ Finset.range (m + 2),
              (if j ≤ k then t ^ j • ((k.choose j : ℂ) • (r k * y ^ (k - j))) else 0) := by
            refine Finset.sum_congr rfl fun k hk => ?_
            refine ((Finset.sum_congr rfl fun j hj => ?_).trans
              (Finset.sum_subset (Finset.range_subset_range.mpr
                (Nat.succ_le_succ (Nat.lt_succ_iff.mp (Finset.mem_range.mp hk))))
                fun j _ hj => if_neg fun h =>
                  hj (Finset.mem_range.mpr (Nat.lt_succ_of_le h))))
            rw [if_pos (Nat.lt_succ_iff.mp (Finset.mem_range.mp hj))]
        _ = ∑ j ∈ Finset.range (m + 2), ∑ k ∈ Finset.range (m + 2),
              (if j ≤ k then t ^ j • ((k.choose j : ℂ) • (r k * y ^ (k - j))) else 0) :=
            Finset.sum_comm
        _ = ∑ j ∈ Finset.range (m + 2), t ^ j • b j := by
            refine Finset.sum_congr rfl fun j _ => ?_
            rw [hbdef]
            dsimp only
            rw [Finset.smul_sum]
            exact Finset.sum_congr rfl fun k _ => (smul_ite_zero _ _ _).symm
    have hconst : ∀ t : ℝ, ∑ j ∈ Finset.range (m + 2), t ^ j • b j =
        ∑ k ∈ Finset.range (m + 2), r k * y ^ k := fun t => by rw [← hexp t, hinv t]
    -- evaluate at zero to identify the constant coefficient
    have hb0 : b 0 = ∑ k ∈ Finset.range (m + 2), r k * y ^ k := by
      have h := hconst 0
      rwa [Finset.sum_eq_single 0 (fun j _ hj => by rw [zero_pow hj, zero_smul])
        (fun h0 => absurd (Finset.mem_range.mpr (Nat.succ_pos _)) h0), pow_zero,
        one_smul] at h
    -- all positive-order coefficients vanish
    have hvan : ∀ j ∈ Finset.range (m + 2), (if j = 0 then 0 else b j) = 0 := by
      refine eq_zero_of_forall_sum_smul_pow_eq_zero fun t => ?_
      rw [Finset.sum_range_succ'
        (fun j => t ^ j • (if j = 0 then (0 : B) else b j)) (m + 1)]
      simp only [Nat.succ_ne_zero, ite_false, ite_true, smul_zero, add_zero]
      have h := hconst t
      rw [Finset.sum_range_succ' (fun j => t ^ j • b j) (m + 1), pow_zero, one_smul,
        ← hb0] at h
      have h2 := congrArg (fun z => z - b 0) h
      simpa using h2
    -- the top coefficient of the representation is the top `b`
    have hbtop : b (m + 1) = r (m + 1) := by
      have h1 : ∀ k ∈ Finset.range (m + 2),
          (if m + 1 ≤ k then (k.choose (m + 1) : ℂ) • (r k * y ^ (k - (m + 1))) else 0) =
          (if k = m + 1 then (k.choose (m + 1) : ℂ) • (r k * y ^ (k - (m + 1))) else 0) := by
        intro k hk
        have hk' := Finset.mem_range.mp hk
        simp only [show (m + 1 ≤ k) ↔ k = m + 1 by omega]
      rw [hbdef]
      dsimp only
      rw [Finset.sum_congr rfl h1,
        Finset.sum_ite_eq' (Finset.range (m + 2)) (m + 1)
          (fun k => (k.choose (m + 1) : ℂ) • (r k * y ^ (k - (m + 1)))),
        if_pos (Finset.self_mem_range_succ _), Nat.choose_self, Nat.sub_self, pow_zero,
        mul_one, Nat.cast_one, one_smul]
    have hrtop : r (m + 1) = 0 := by
      have h := hvan (m + 1) (Finset.self_mem_range_succ _)
      rwa [if_neg (Nat.succ_ne_zero m), hbtop] at h
    -- strip the top term and recurse
    have hstrip : (∑ k ∈ Finset.range (m + 2), r k * y ^ k) =
        ∑ k ∈ Finset.range (m + 1), r k * y ^ k := by
      rw [Finset.sum_range_succ, hrtop, zero_mul, add_zero]
    rw [hstrip] at hinv ⊢
    exact ih (m + 1) (Nat.lt_succ_self _) r hrR hinv

/-- **The abstract extraction theorem** — pure ring theory, no gauge input and no
  independence hypothesis: if a family of unital ring endomorphisms fixes a
  subalgebra `R` pointwise and translates finitely many central elements `y i` by
  arbitrary prescribable scalars, then any element of the subalgebra generated by
  `R` and the `y i` that is invariant under the whole family lies in `R`.

  Proof idea: choose any representation of `x` as a polynomial in the `y i` over `R`;
  invariance at sufficiently many shift vectors and a Vandermonde argument force the
  nonconstant coefficients of the chosen representation to vanish, top degree first. -/
theorem mem_of_translationInvariant {ι : Type} [Fintype ι]
    (R : Subalgebra ℂ B) (y : ι → B)
    (hyR : ∀ i, ∀ r ∈ R, Commute r (y i))
    (hyy : ∀ i j, Commute (y i) (y j))
    (Φ : (ι → ℝ) → (B →+* B))
    (hΦR : ∀ t, ∀ z ∈ R, Φ t z = z)
    (hΦy : ∀ t i, Φ t (y i) = y i + algebraMap ℂ B (t i))
    {x : B} (hx : x ∈ R ⊔ Algebra.adjoin ℂ (Set.range y))
    (hinv : ∀ t, Φ t x = x) :
    x ∈ R := by
  classical
  suffices h : ∀ s : Finset ι, ∀ x : B, x ∈ R ⊔ Algebra.adjoin ℂ (y '' ↑s) →
      (∀ t, Φ t x = x) → x ∈ R by
    refine h Finset.univ x ?_ hinv
    rwa [Finset.coe_univ, Set.image_univ]
  intro s
  induction s using Finset.induction_on with
  | empty =>
      intro x hx hinv
      simpa [Algebra.adjoin_empty] using hx
  | insert i s his ih =>
      intro x hx hinv
      -- rearrange the generators: the coordinate `i` is adjoined last
      have hxR' : x ∈ (R ⊔ Algebra.adjoin ℂ (y '' ↑s)) ⊔ Algebra.adjoin ℂ {y i} := by
        have hset : (y '' ↑(insert i s) : Set B) = {y i} ∪ y '' ↑s := by
          rw [Finset.coe_insert, Set.image_insert_eq, Set.insert_eq]
        rwa [hset, Algebra.adjoin_union, sup_comm (Algebra.adjoin ℂ {y i}),
          ← sup_assoc] at hx
      -- the single-coordinate translations fix the enlarged base subalgebra
      have hfix : ∀ u : ℝ, ∀ z ∈ R ⊔ Algebra.adjoin ℂ (y '' ↑s),
          Φ (Pi.single i u) z = z := by
        intro u z hz
        rw [← Algebra.adjoin_eq R, ← Algebra.adjoin_union] at hz
        induction hz using Algebra.adjoin_induction with
        | mem b hb =>
            rcases hb with hbR | ⟨j, hj, rfl⟩
            · exact hΦR _ b hbR
            · have hji : j ≠ i := fun h => his (by rw [← h]; exact Finset.mem_coe.mp hj)
              rw [hΦy (Pi.single i u) j, Pi.single_eq_of_ne hji]
              simp
        | algebraMap c => exact hΦR _ _ (Subalgebra.algebraMap_mem R c)
        | add a b _ _ iha ihb => rw [map_add, iha, ihb]
        | mul a b _ _ iha ihb => rw [map_mul, iha, ihb]
      have hy' : ∀ r ∈ R ⊔ Algebra.adjoin ℂ (y '' ↑s), Commute r (y i) := by
        intro r hr
        rw [← Algebra.adjoin_eq R, ← Algebra.adjoin_union] at hr
        induction hr using Algebra.adjoin_induction with
        | mem b hb =>
            rcases hb with hbR | ⟨j, hj, rfl⟩
            · exact hyR i b hbR
            · exact hyy j i
        | algebraMap c => exact Algebra.commutes c (y i)
        | add a b _ _ iha ihb => exact iha.add_left ihb
        | mul a b _ _ iha ihb => exact iha.mul_left ihb
      have hxmid : x ∈ R ⊔ Algebra.adjoin ℂ (y '' ↑s) :=
        mem_of_translationInvariant_single (R ⊔ Algebra.adjoin ℂ (y '' ↑s)) (y i) hy'
          (fun u => Φ (Pi.single i u)) hfix
          (fun u => by rw [hΦy (Pi.single i u) i, Pi.single_eq_same])
          hxR' (fun u => hinv _)
      exact ih x hxmid hinv

/-- Commutation with a generating set extends to the generated subalgebra. -/
lemma commute_of_mem_adjoin {X : Set B} {y : B} (hX : ∀ x ∈ X, Commute x y)
    {r : B} (hr : r ∈ Algebra.adjoin ℂ X) : Commute r y := by
  induction hr using Algebra.adjoin_induction with
  | mem b hb => exact hX b hb
  | algebraMap c => exact Algebra.commutes c y
  | add a b _ _ iha ihb => exact iha.add_left ihb
  | mul a b _ _ iha ihb => exact iha.mul_left ihb

/-- Anything commuting with all gauge-field symbols commutes with the symmetrized
  symbols. -/
lemma commute_symmetrizedDeriv_right {y : B}
    (hy : ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra), Commute y (A p μ φ))
    (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra) :
    Commute y (symmetrizedDeriv r A φ) := by
  rw [symmetrizedDeriv, ← algebraMap_smul ℂ ((1 : ℝ)/(r.card : ℝ))]
  refine Commute.smul_right ?_ _
  refine Commute.multiset_sum_right _ _ fun x hx => ?_
  obtain ⟨μ, hμ, rfl⟩ := Multiset.mem_map.mp hx
  exact hy _ _ _

/-- The underived covariant field-strength tower consists of polynomials in the
  gauge-field symbols. -/
lemma iteratedCovDerivAdjoint_fieldStrength_mem_adjoin_symbols
    (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ ∈
      Algebra.adjoin ℂ {b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (ψ : Module.Dual ℝ GaugeAlgebra), b = A p μ ψ} := by
  rw [show iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ =
      (iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ -
        fieldStrength A ν lam (Multiset.ofList l + 0) φ) +
      fieldStrength A ν lam (Multiset.ofList l + 0) φ from by abel]
  refine add_mem
    (SetLike.le_def.mp (Algebra.adjoin_mono ?_)
      (iteratedCovDerivAdjoint_sub_mem l ν lam 0 φ))
    (SetLike.le_def.mp (Algebra.adjoin_mono ?_)
      (fieldStrength_mem_adjoin_symbols _ ν lam φ))
  · rintro b ⟨p, μ, ψ, _, rfl⟩
    exact ⟨p, μ, ψ, rfl⟩
  · rintro b ⟨p, μ, ψ, _, rfl⟩
    exact ⟨p, μ, ψ, rfl⟩

set_option maxHeartbeats 1000000 in
/-- **The classification of invariants**: a gauge-invariant element of the subalgebra
  generated by the gauge-field symbols and a set `S` of `truncationKer 0`-fixed
  elements is a polynomial in the covariant derivatives of the field strength and the
  elements of `S`. Requires only that the gauge-field symbols commute with each other
  (the gauge field is bosonic) and with the elements of `S` — nothing about the rest
  of `B`; no independence hypothesis. -/
theorem invariant_mem_adjoin_fieldStrength
    (hA : IsGaugeField repLorentz repGauge A)
    (hcomm : ∀ (p q : Multiset (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
      (φ ψ : Module.Dual ℝ GaugeAlgebra), Commute (A p μ φ) (A q ν ψ))
    (S : Set B)
    (hcS : ∀ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra), ∀ y ∈ S, Commute y (A p μ φ))
    (hS : ∀ y ∈ S, ∀ U : JetGaugeGroupI.truncationKer 0, repGauge U.1 y = y)
    {x : B}
    (hx : x ∈ Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra),
      b = A p μ φ} ∪ S))
    (hinv : ∀ U : JetGaugeGroupI, repGauge U x = x) :
    x ∈ Algebra.adjoin ℂ ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra),
      b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ} ∪ S) := by
  classical
  -- every element of the covariant tower together with `S` is fixed by the
  -- truncation kernel
  have hS' : ∀ y ∈ ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra),
      b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ} ∪ S),
      ∀ U : JetGaugeGroupI.truncationKer 0, repGauge U.1 y = y := by
    rintro y (⟨l, ν, lam, φ, rfl⟩ | hyS) U
    · exact repGauge_iteratedCovDerivAdjoint_fieldStrength_of_mem_truncationKer_zero
        hA U l ν lam φ
    · exact hS y hyS U
  -- the gauge action preserves the unit, hence acts by ring endomorphisms
  have hone : ∀ U : JetGaugeGroupI, repGauge U (1 : B) = 1 := by
    intro U
    have h2 : repGauge U (repGauge U⁻¹ (1 : B)) = 1 := by
      have h3 : repGauge U * repGauge U⁻¹ = 1 := by
        rw [← map_mul, mul_inv_cancel, map_one]
      calc repGauge U (repGauge U⁻¹ (1 : B)) = (repGauge U * repGauge U⁻¹) (1 : B) := rfl
        _ = 1 := by rw [h3]; rfl
    have h1 := hA.gauge_mul U (repGauge U⁻¹ (1 : B)) 1
    rw [mul_one, h2, one_mul] at h1
    exact h1.symm
  -- the descent: invariance strips the top symmetrized order
  have hdescent : ∀ (m : ℕ) (z : B),
      z ∈ Algebra.adjoin ℂ
        ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
            r ≠ 0 ∧ r.card ≤ m + 1 ∧ b = symmetrizedDeriv r A φ} ∪
          ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
            (φ : Module.Dual ℝ GaugeAlgebra),
            b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ} ∪ S)) →
      (∀ U : JetGaugeGroupI.truncationKer 0, repGauge U.1 z = z) →
      z ∈ Algebra.adjoin ℂ
        ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
            r ≠ 0 ∧ r.card ≤ m ∧ b = symmetrizedDeriv r A φ} ∪
          ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
            (φ : Module.Dual ℝ GaugeAlgebra),
            b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ} ∪ S)) := by
    intro m z hz hzinv
    set bv := Module.Free.chooseBasis ℝ GaugeAlgebra with hbv
    set R₀ : Subalgebra ℂ B := Algebra.adjoin ℂ
      ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
          r ≠ 0 ∧ r.card ≤ m ∧ b = symmetrizedDeriv r A φ} ∪
        ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
          (φ : Module.Dual ℝ GaugeAlgebra),
          b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ} ∪ S)) with hR₀
    set Y : Sym (Fin 1 ⊕ Fin 3) (m + 1) × Module.Free.ChooseBasisIndex ℝ GaugeAlgebra → B :=
      fun p => symmetrizedDeriv (p.1 : Multiset (Fin 1 ⊕ Fin 3)) A (bv.coord p.2)
      with hYdef
    -- the translating jets realizing an arbitrary top-order shift
    have hUt' : ∀ t : Sym (Fin 1 ⊕ Fin 3) (m + 1) ×
        Module.Free.ChooseBasisIndex ℝ GaugeAlgebra → ℝ,
        ∃ U : JetGaugeGroupI.truncationKer 0,
          symmetrizedMaurerCartanCoeff U⁻¹ = (fun r =>
            if h : Multiset.card r.1 = m + 1 then ∑ j, t (⟨r.1, h⟩, j) • bv j else 0) ∧
          ∀ x' : Multiset (Fin 1 ⊕ Fin 3), x' ≠ 0 → x'.card < m + 1 →
            adjointDualCoeff (U.1)⁻¹ x' = 0 :=
      fun t => exists_translation_of_support (m + 1) _ (fun r hr => dif_neg hr)
    choose Ut hUt1 hUt2 using hUt'
    -- the family of ring endomorphisms
    set Φ : (Sym (Fin 1 ⊕ Fin 3) (m + 1) ×
        Module.Free.ChooseBasisIndex ℝ GaugeAlgebra → ℝ) → B →+* B :=
      fun t =>
        { toFun := repGauge (Ut t).1
          map_one' := hone (Ut t).1
          map_mul' := hA.gauge_mul (Ut t).1
          map_zero' := map_zero _
          map_add' := fun a b => map_add _ a b } with hΦdef
    -- the endomorphisms fix the lower-order subalgebra pointwise
    have hfixR₀ : ∀ t, ∀ w ∈ R₀, Φ t w = w := by
      intro t w hw
      rw [hR₀] at hw
      induction hw using Algebra.adjoin_induction with
      | mem b hb =>
          show repGauge (Ut t).1 b = b
          rcases hb with ⟨r, φ, hr0, hrm, rfl⟩ | hb'
          · have hUvan : ∀ x' : Multiset (Fin 1 ⊕ Fin 3), x' ≠ 0 → x'.card < r.card →
                adjointDualCoeff ((Ut t).1)⁻¹ x' = 0 :=
              fun x' hx' hxc => hUt2 t x' hx' (by omega)
            rw [repGauge_symmetrizedDeriv_translation hA (Ut t) r hr0 hUvan φ]
            have hshift : symmetrizedMaurerCartanCoeff (Ut t)⁻¹ ⟨r, hr0⟩ = 0 := by
              simp only [hUt1 t]
              exact dif_neg (show ¬ Multiset.card r = m + 1 by omega)
            rw [hshift, map_zero]
            simp
          · exact hS' b hb' (Ut t)
      | algebraMap c =>
          show repGauge (Ut t).1 (algebraMap ℂ B c) = algebraMap ℂ B c
          rw [Algebra.algebraMap_eq_smul_one, map_smul, hone]
      | add a b _ _ iha ihb => rw [map_add, iha, ihb]
      | mul a b _ _ iha ihb => rw [map_mul, iha, ihb]
    -- the endomorphisms translate the top-order coordinates by the prescribed shifts
    have hΦy : ∀ t p, Φ t (Y p) = Y p + algebraMap ℂ B ((t p : ℝ) : ℂ) := by
      rintro t ⟨ps, j⟩
      have hps : Multiset.card (ps : Multiset (Fin 1 ⊕ Fin 3)) = m + 1 :=
        Sym.card_coe (s := ps)
      have hp0 : (ps : Multiset (Fin 1 ⊕ Fin 3)) ≠ 0 := by
        intro h
        rw [h] at hps
        simp at hps
      have hUvan : ∀ x' : Multiset (Fin 1 ⊕ Fin 3), x' ≠ 0 →
          x'.card < (ps : Multiset (Fin 1 ⊕ Fin 3)).card →
          adjointDualCoeff ((Ut t).1)⁻¹ x' = 0 :=
        fun x' hx' hxc => hUt2 t x' hx' (by omega)
      have hval : bv.coord j (symmetrizedMaurerCartanCoeff (Ut t)⁻¹
          ⟨(ps : Multiset (Fin 1 ⊕ Fin 3)), hp0⟩) = t (ps, j) := by
        have hcoeff : symmetrizedMaurerCartanCoeff (Ut t)⁻¹
            ⟨(ps : Multiset (Fin 1 ⊕ Fin 3)), hp0⟩ = ∑ j', t (ps, j') • bv j' := by
          simp only [hUt1 t]
          rw [dif_pos hps]
          exact Finset.sum_congr rfl fun j' _ =>
            congrArg (fun q : Sym (Fin 1 ⊕ Fin 3) (m + 1) => t (q, j') • bv j')
              (Sym.ext rfl)
        rw [hcoeff, map_sum]
        simp only [map_smul, Module.Basis.coord_apply, Module.Basis.repr_self,
          Finsupp.single_apply, smul_eq_mul, mul_ite, mul_one, mul_zero]
        rw [Finset.sum_ite_eq' Finset.univ j (fun j' => t (ps, j'))]
        simp
      show repGauge (Ut t).1 (symmetrizedDeriv (ps : Multiset (Fin 1 ⊕ Fin 3)) A
          (bv.coord j)) = symmetrizedDeriv (ps : Multiset (Fin 1 ⊕ Fin 3)) A
          (bv.coord j) + algebraMap ℂ B ((t (ps, j) : ℝ) : ℂ)
      rw [repGauge_symmetrizedDeriv_translation hA (Ut t) _ hp0 hUvan (bv.coord j), hval]
    -- the coordinate expansion of a top-order symmetrized symbol in the chosen basis
    have hdual : ∀ ψ : Module.Dual ℝ GaugeAlgebra, ∑ j, ψ (bv j) • bv.coord j = ψ := by
      intro ψ
      refine LinearMap.ext fun v => ?_
      conv_rhs => rw [← bv.sum_repr v, map_sum]
      simp only [LinearMap.sum_apply, LinearMap.smul_apply, Module.Basis.coord_apply,
        smul_eq_mul, map_smul]
      exact Finset.sum_congr rfl fun j _ => mul_comm _ _
    have hexpand : ∀ (r : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℝ GaugeAlgebra),
        symmetrizedDeriv r A φ =
          ∑ j, φ (bv j) • symmetrizedDeriv r A (bv.coord j) := by
      intro r φ
      set L : Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B :=
        { toFun := fun ψ => symmetrizedDeriv r A ψ,
          map_add' := fun ψ ψ' => by
            simp only [symmetrizedDeriv, map_add]
            rw [← smul_add, ← Multiset.sum_map_add]
          map_smul' := fun c ψ => by
            simp only [symmetrizedDeriv, map_smul, RingHom.id_apply]
            rw [show (r.map fun μ => c • A (r - {μ}) μ ψ) =
                (r.map fun μ => A (r - {μ}) μ ψ).map (fun w => c • w) from
                (Multiset.map_map _ _ _).symm,
              ← Multiset.smul_sum, smul_comm] } with hL
      have hLcalc : L φ = ∑ j, φ (bv j) • L (bv.coord j) := by
        conv_lhs => rw [← hdual φ, map_sum]
        exact Finset.sum_congr rfl fun j _ => by rw [map_smul]
      exact hLcalc
    -- the invariant lies in the sup of the lower-order subalgebra and the coordinates
    have hzsup : z ∈ R₀ ⊔ Algebra.adjoin ℂ (Set.range Y) := by
      refine Algebra.adjoin_le ?_ hz
      rintro b (⟨r, φ, hr0, hrm1, rfl⟩ | hb)
      · by_cases hcm : r.card ≤ m
        · exact SetLike.le_def.mp le_sup_left
            (Algebra.subset_adjoin (Or.inl ⟨r, φ, hr0, hcm, rfl⟩))
        · have hcard : Multiset.card r = m + 1 := by omega
          rw [hexpand r φ]
          refine Subalgebra.sum_mem _ fun j _ => ?_
          rw [← algebraMap_smul ℂ (φ (bv j))]
          refine Subalgebra.smul_mem _ ?_ _
          exact SetLike.le_def.mp le_sup_right
            (Algebra.subset_adjoin ⟨(⟨r, hcard⟩, j), rfl⟩)
      · exact SetLike.le_def.mp le_sup_left (Algebra.subset_adjoin (Or.inr hb))
    -- the commutation data: symbols commute with each other, the tower, and `S`
    have hsymbSD : ∀ (a : Multiset (Fin 1 ⊕ Fin 3)) (b : Fin 1 ⊕ Fin 3)
        (c : Module.Dual ℝ GaugeAlgebra) (r : Multiset (Fin 1 ⊕ Fin 3))
        (φ : Module.Dual ℝ GaugeAlgebra),
        Commute (A a b c) (symmetrizedDeriv r A φ) :=
      fun a b c r φ => commute_symmetrizedDeriv_right
        (fun p' μ' φ' => hcomm a p' b μ' c φ') r φ
    have hsymbY : ∀ (a : Multiset (Fin 1 ⊕ Fin 3)) (b : Fin 1 ⊕ Fin 3)
        (c : Module.Dual ℝ GaugeAlgebra) (p), Commute (A a b c) (Y p) :=
      fun a b c p => hsymbSD a b c (p.1 : Multiset (Fin 1 ⊕ Fin 3)) (bv.coord p.2)
    have hYY : ∀ p q, Commute (Y p) (Y q) :=
      fun p q => commute_symmetrizedDeriv_right
        (fun p' μ' φ' => (hsymbSD p' μ' φ' (p.1 : Multiset (Fin 1 ⊕ Fin 3))
          (bv.coord p.2)).symm) (q.1 : Multiset (Fin 1 ⊕ Fin 3)) (bv.coord q.2)
    have hRY : ∀ p, ∀ r ∈ R₀, Commute r (Y p) := by
      intro p r hr
      rw [hR₀] at hr
      refine commute_of_mem_adjoin ?_ hr
      rintro b (⟨r', φ', hr0, hrm, rfl⟩ | (⟨l, ν, lam, φ', rfl⟩ | hbS))
      · exact commute_symmetrizedDeriv_right
          (fun p' μ' φ'' => (hsymbSD p' μ' φ'' r' φ').symm)
          (p.1 : Multiset (Fin 1 ⊕ Fin 3)) (bv.coord p.2)
      · exact commute_of_mem_adjoin
          (fun x hx => by
            obtain ⟨a, b2, c, rfl⟩ := hx
            exact hsymbY a b2 c p)
          (iteratedCovDerivAdjoint_fieldStrength_mem_adjoin_symbols l ν lam φ')
      · exact commute_symmetrizedDeriv_right
          (fun p' μ' φ' => hcS p' μ' φ' b hbS)
          (p.1 : Multiset (Fin 1 ⊕ Fin 3)) (bv.coord p.2)
    -- extraction: the invariant lies in the lower-order subalgebra
    have hzR₀ : z ∈ R₀ :=
      mem_of_translationInvariant R₀ Y hRY hYY Φ hfixR₀ hΦy hzsup
        (fun t => hzinv (Ut t))
    rw [hR₀] at hzR₀
    exact hzR₀
  -- bound the symbol order of the invariant, working relative to the full tower
  have hxS' : x ∈ Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3))
      (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra),
      b = A p μ φ} ∪
      ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra),
        b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ} ∪ S)) :=
    Algebra.adjoin_mono (Set.union_subset_union_right _ Set.subset_union_right) hx
  obtain ⟨n, hxn⟩ := exists_le_of_mem_adjoin_symbols_union _ hxS'
  -- convert bounded symbols to symmetrized symbols, absorbing the tower
  have hconv : ∀ (k : ℕ) (z : B),
      z ∈ Algebra.adjoin ℂ ({b : B | ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra), p.card ≤ k ∧
        b = A p μ φ} ∪
        ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
          (φ : Module.Dual ℝ GaugeAlgebra),
          b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ} ∪ S)) →
      z ∈ Algebra.adjoin ℂ ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3))
        (φ : Module.Dual ℝ GaugeAlgebra), r ≠ 0 ∧ r.card ≤ k + 1 ∧
        b = symmetrizedDeriv r A φ} ∪
        ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
          (φ : Module.Dual ℝ GaugeAlgebra),
          b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ} ∪ S)) := by
    intro k z hzk
    rw [symbolAdjoin_union_eq_symFieldAdjoin_union k
      ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra),
        b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ} ∪ S)] at hzk
    refine Algebra.adjoin_mono ?_ hzk
    rintro b ((⟨r, φ, h0, hcr, rfl⟩ | ⟨l, ν, lam, φ, _, rfl⟩) | hb)
    · exact Or.inl ⟨r, φ, h0, hcr, rfl⟩
    · exact Or.inr (Or.inl ⟨l, ν, lam, φ, rfl⟩)
    · exact Or.inr hb
  -- iterate the descent from the top order down to zero
  have hiter : ∀ (k : ℕ) (z : B),
      z ∈ Algebra.adjoin ℂ ({b : B | ∃ (r : Multiset (Fin 1 ⊕ Fin 3))
        (φ : Module.Dual ℝ GaugeAlgebra), r ≠ 0 ∧ r.card ≤ k ∧
        b = symmetrizedDeriv r A φ} ∪
        ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
          (φ : Module.Dual ℝ GaugeAlgebra),
          b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ} ∪ S)) →
      (∀ U : JetGaugeGroupI.truncationKer 0, repGauge U.1 z = z) →
      z ∈ Algebra.adjoin ℂ ({b : B | ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra),
        b = iteratedCovDerivAdjoint A l (fieldStrength A ν lam) 0 φ} ∪ S) := by
    intro k
    induction k with
    | zero =>
        intro z hz0 _
        refine Algebra.adjoin_mono ?_ hz0
        rintro b (⟨r, φ, hr0, hrc, rfl⟩ | hb)
        · exact absurd (Multiset.card_eq_zero.mp (Nat.le_zero.mp hrc)) hr0
        · exact hb
    | succ k ih =>
        intro z hzk hzinv
        exact ih z (hdescent k z hzk hzinv) hzinv
  exact hiter (n + 1) x (hconv n x hxn) fun U => hinv U.1

end IsGaugeField

end StandardModel
