/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.QuantumMechanics.QuadraticSystem.BoseEinsteinDistribution
public import Mathlib.LinearAlgebra.Matrix.Trace
public import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
public import Mathlib.Analysis.SpecialFunctions.Complex.Circle

/-!

# The KMS boundary condition for a truncated oscillator's Gibbs state

The last unbuilt piece the roadmap names explicitly: closing the loop from a derived thermal
state back to the KMS (Kubo–Martin–Schwinger) equilibrium condition. Full KMS theory needs
trace-class operators on the genuine (infinite-dimensional) Fock space and honest complex-analytic
continuation of `t ↦ ω(A α_t(B))` into the strip `0 < Im(t) < β` — real analysis this repo does not
have yet (`BE_FD_STATISTICS_ROADMAP.md`).

This file proves the *algebraic core* of KMS directly and honestly, in the one setting where it
reduces to finite-dimensional linear algebra with no complex-analytic machinery needed: the
`(N+1)`-level truncation of a single bosonic mode (occupation numbers `0,…,N` only — the harmonic
oscillator's own textbook approximation for numerics). There, `ρ = e^{-βH}` is an honest invertible
matrix, the dynamics `α_z(X) = U(z) X U(z)⁻¹` (`U(z) := e^{izH}`, an *explicit* diagonal formula,
entire in `z` by construction — no separate analyticity proof needed) is defined for every complex
`z` for free, and the KMS boundary identity `ω(A α_t(B))|_{t = iβ} = ω(BA)` is a direct consequence
of cyclicity of the matrix trace. This is the genuine mathematical content "why a Gibbs state is a
KMS state" reduces to; it is not yet connected to the operator-trace machinery of
`BoseEinsteinOperatorTrace.lean` (which lives on the untruncated, infinite-level Fock space) or to
the abstract quasifree/GNS side of this development.

## Main definitions

- `gibbs_kms_identity` : the fully general algebraic KMS identity, for any invertible `ρ` and any
  `A B` — `Tr(ρ·A·(ρ·B·ρ⁻¹)) = Tr(ρ·B·A)`.
- `truncatedGibbs` : the (unnormalized) Gibbs density matrix `diag(e^{-βε·0},…,e^{-βε·N})` of the
  `(N+1)`-level truncated oscillator.
- `truncatedDynamics` : `U(z) := diag(e^{izε·0},…,e^{izε·N})`, the (complex-parametrized) unitary
  evolution generated by the truncated number Hamiltonian `H = diag(0,ε,…,Nε)`.
- `truncatedGibbsState_kms` : **the KMS boundary condition**, specialized to the truncated
  oscillator's actual Gibbs state and dynamics: `ω(A · α_t(B))` at `t = iβ` equals `ω(B·A)`, for
  every pair of `(N+1)×(N+1)` matrices `A, B` — not just diagonal ones.

-/

@[expose] public section

namespace QuantumMechanics

noncomputable section

open Matrix

/-! ## A. The general algebraic KMS identity -/

/-- **The algebraic core of the KMS condition.** For any invertible `ρ` and any `A, B`, the
"boundary value" `Tr(ρ·A·(ρ·B·ρ⁻¹))` — the shape `ω(A α_{iβ}(B))·Tr(ρ)` takes when `α_{iβ}(B) =
ρBρ⁻¹`, as it does for a Gibbs dynamics `α_z(B) = e^{izH}Be^{-izH}` evaluated at `z = iβ` against
`ρ = e^{-βH}` — always equals `Tr(ρ·B·A)`, purely from cyclicity of the trace. No positivity, no
analyticity, no special structure of `ρ` beyond invertibility is used. -/
theorem gibbs_kms_identity {n : Type*} [Fintype n] [DecidableEq n] {R : Type*} [Field R]
    (ρ A B : Matrix n n R) (hρ : IsUnit ρ.det) :
    (ρ * A * (ρ * B * ρ⁻¹)).trace = (ρ * B * A).trace := by
  have hassoc : ρ * A * (ρ * B * ρ⁻¹) = ρ * A * ρ * B * ρ⁻¹ := by simp only [mul_assoc]
  have e2 : ρ⁻¹ * (ρ * A * ρ) * B = A * ρ * B := by
    have h1 : ρ⁻¹ * (ρ * A * ρ) = A * ρ := by
      rw [mul_assoc ρ A ρ, ← mul_assoc, Matrix.nonsing_inv_mul ρ hρ, one_mul]
    rw [h1]
  calc (ρ * A * (ρ * B * ρ⁻¹)).trace
      = (ρ * A * ρ * B * ρ⁻¹).trace := by rw [hassoc]
    _ = ((ρ * A * ρ) * B * ρ⁻¹).trace := rfl
    _ = (ρ⁻¹ * (ρ * A * ρ) * B).trace := Matrix.trace_mul_cycle (ρ * A * ρ) B ρ⁻¹
    _ = (A * ρ * B).trace := by rw [e2]
    _ = (ρ * B * A).trace := (Matrix.trace_mul_cycle ρ B A).symm

/-! ## B. The truncated oscillator -/

variable (N : ℕ) (β ε : ℝ)

/-- The `(N+1)`-level truncated number Hamiltonian's Gibbs density matrix (unnormalized):
`diag(e^{-βε·0}, e^{-βε·1}, …, e^{-βε·N})`. -/
def truncatedGibbs : Matrix (Fin (N + 1)) (Fin (N + 1)) ℂ :=
  Matrix.diagonal (fun k : Fin (N + 1) => ((Real.exp (-(β * ε) * (k : ℕ)) : ℝ) : ℂ))

/-- The truncated oscillator's unitary evolution, for a *complex* parameter `z`:
`U(z) := diag(e^{izε·0}, …, e^{izε·N})`. Defined for every `z : ℂ` by the same explicit diagonal
formula — the "analytic continuation" the KMS condition needs is, at this level of truncation,
free: there is no separate limiting or estimate to prove, `U` already makes sense at `z = iβ`. -/
def truncatedDynamicsU (z : ℂ) : Matrix (Fin (N + 1)) (Fin (N + 1)) ℂ :=
  Matrix.diagonal (fun k : Fin (N + 1) => Complex.exp (Complex.I * z * ε * (k : ℕ)))

theorem truncatedDynamicsU_mul (z w : ℂ) :
    truncatedDynamicsU N ε z * truncatedDynamicsU N ε w = truncatedDynamicsU N ε (z + w) := by
  unfold truncatedDynamicsU
  rw [Matrix.diagonal_mul_diagonal]
  congr 1
  funext k
  rw [← Complex.exp_add]
  ring_nf

@[simp]
theorem truncatedDynamicsU_zero : truncatedDynamicsU N ε 0 = 1 := by
  unfold truncatedDynamicsU
  simp

theorem isUnit_det_truncatedGibbs : IsUnit (truncatedGibbs N β ε).det := by
  rw [truncatedGibbs, Matrix.det_diagonal]
  apply IsUnit.mk0
  apply Finset.prod_ne_zero_iff.mpr
  intro k _
  exact Complex.ofReal_ne_zero.mpr (Real.exp_pos _).ne'

/-- **The dynamics, continued to `z = iβ`, is the Gibbs density matrix itself**:
`U(iβ) = e^{i(iβ)εk} = e^{-βεk} = ρ`. This is the concrete fact — a one-line consequence of
`I·I = -1` — that lets the KMS boundary value `α_{iβ}(B) = U(iβ) B U(iβ)⁻¹` be rewritten as
conjugation `ρ B ρ⁻¹` by the Gibbs matrix itself, matching `gibbs_kms_identity`'s hypothesis
exactly. -/
theorem truncatedDynamicsU_I_mul_beta_eq_gibbs :
    truncatedDynamicsU N ε (Complex.I * β) = truncatedGibbs N β ε := by
  unfold truncatedDynamicsU truncatedGibbs
  congr 1
  funext k
  rw [show Complex.I * (Complex.I * (β : ℂ)) * ε * (k : ℕ) =
      ((-(β * ε) * (k : ℕ) : ℝ) : ℂ) by
    push_cast
    linear_combination (β * ε * (k : ℕ) : ℂ) * Complex.I_mul_I]
  exact (Complex.ofReal_exp _).symm

/-- **The KMS boundary condition for the truncated oscillator's Gibbs state**, at any pair of
(not-necessarily-diagonal) matrices `A, B`: `Tr(ρ · A · (U(iβ) B U(iβ)⁻¹)) = Tr(ρ · B · A)` —
exactly `ω(A α_{iβ}(B)) · Tr(ρ) = ω(BA) · Tr(ρ)`, the KMS boundary value identity, for the actual
Gibbs density matrix and the actual (complex-extended) unitary dynamics of the truncated
oscillator, not an abstract placeholder `ρ`. -/
theorem truncatedGibbsState_kms (A B : Matrix (Fin (N + 1)) (Fin (N + 1)) ℂ) :
    (truncatedGibbs N β ε * A *
        (truncatedDynamicsU N ε (Complex.I * β) * B * (truncatedDynamicsU N ε (Complex.I * β))⁻¹)
      ).trace =
      (truncatedGibbs N β ε * B * A).trace := by
  rw [truncatedDynamicsU_I_mul_beta_eq_gibbs]
  exact gibbs_kms_identity (truncatedGibbs N β ε) A B (isUnit_det_truncatedGibbs N β ε)

end

end QuantumMechanics
