/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.ProbabilisticTheory.JordanOrderUnit.JB.GeneratedByOne.Inherited
public import Mathlib.Analysis.Normed.Algebra.Spectrum

/-!

# The norm of `C(a)` is uniform

## i. Overview

The JB axiom `‖x²‖ = ‖x‖²` holds in `C(a)`, so `‖x^(2ⁿ)‖ = ‖x‖^(2ⁿ)` and the spectral radius is at
most the norm.

## ii. Key results

- `JBAlgebra.ClosedGeneratedByOne.norm_mul_self` : `‖x²‖ = ‖x‖²`.
- `JBAlgebra.ClosedGeneratedByOne.norm_pow_two_pow` : `‖x^(2ⁿ)‖ = ‖x‖^(2ⁿ)`.

## iii. Table of contents

- A. Uniform square norm

-/

@[expose] public section

namespace ProbabilisticTheory

namespace JBAlgebra

variable {E : Type*} [NormedJordanAlgebra E] [JBAlgebra E]

open NormedJordanAlgebra
open scoped ENNReal NNReal

namespace ClosedGeneratedByOne

variable (a : E)

/-! ## A. Uniform square norm -/

/-- The JB square axiom restricts to the closed algebra generated by one element. -/
lemma norm_mul_self (x : ClosedGeneratedByOne a) : ‖x * x‖ = ‖x‖ ^ 2 := by
  exact JBAlgebra.norm_mul_self x

/-- The spectral radius is at most the norm. -/
lemma spectralRadius_le_norm (x : ClosedGeneratedByOne a) :
    spectralRadius ℝ x ≤ (‖x‖₊ : ℝ≥0∞) := by
  exact spectralRadius_le_nnnorm x

/-- Along powers of two, the closed one-generator algebra has a uniform norm. -/
lemma norm_pow_two_pow (x : ClosedGeneratedByOne a) (n : ℕ) :
    ‖x ^ (2 ^ n)‖ = ‖x‖ ^ (2 ^ n) := by
  induction n with
  | zero => simp
  | succ n ih =>
      calc
        ‖x ^ (2 ^ (n + 1))‖ = ‖(x ^ (2 ^ n)) * (x ^ (2 ^ n))‖ := by
          rw [pow_succ, pow_mul, pow_two]
        _ = ‖x ^ (2 ^ n)‖ ^ 2 := norm_mul_self a _
        _ = (‖x‖ ^ (2 ^ n)) ^ 2 := by rw [ih]
        _ = ‖x‖ ^ (2 ^ (n + 1)) := by
          rw [← pow_mul, pow_succ]

end ClosedGeneratedByOne

end JBAlgebra

end ProbabilisticTheory
