/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.IsCovStandardModel.Basic
public import Mathlib.Algebra.Algebra.NonUnitalSubalgebra
/-!
# The covariant generators of the field algebra

The covariant fields, indexed abstractly: `Generators` names one covariant tower
applied to a member of the dual basis of its value space, and `generatorVal` evaluates
it in the algebra. Only basis indices are stored, so the generators of a given mass
weight form a finite type. The field algebra is generated by these values
(`fieldAlgebra_eq_adjoin_range`), and they supercommute — the weight of a generator is
odd exactly when it is fermionic.

The grading of the algebra by mass weight is in `IsCovStandardModel.MassWeight`.

-/

@[expose] public section

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz


namespace IsCovStandardModel

variable {B : Type} [Ring B] [Algebra ℂ B]
  {repGauge : Representation ℂ GaugeGroupI B}
  {hrepGauge_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B),
    repGauge g (b₁ * b₂) = repGauge g b₁ * repGauge g b₂}
  {repLorentz : Representation ℂ SL(2,ℂ) B}
  {hrepLorentz_mul : ∀ (Λ : SL(2,ℂ)) (b₁ b₂ : B),
    repLorentz Λ (b₁ * b₂) = repLorentz Λ b₁ * repLorentz Λ b₂}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  {H : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ HiggsVec →ₗ[ℂ] B}
  {barH : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule HiggsVec) →ₗ[ℂ] B}
  {F : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) →
    Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
  {d : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ DownSinglet →ₗ[ℂ] B}
  {bard : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule DownSinglet) →ₗ[ℂ] B}
  {u : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ UpSinglet →ₗ[ℂ] B}
  {baru : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule UpSinglet) →ₗ[ℂ] B}
  {Q : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ QuarkDoublet →ₗ[ℂ] B}
  {barQ : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule QuarkDoublet) →ₗ[ℂ] B}
  {L : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ LeptonDoublet →ₗ[ℂ] B}
  {barL : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule LeptonDoublet) →ₗ[ℂ] B}
  {e : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ LeptonSinglet →ₗ[ℂ] B}
  {bare : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule LeptonSinglet) →ₗ[ℂ] B}
  (h : IsCovStandardModel B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
    massWeightPoly H barH F d bard u baru Q barQ L barL e bare)

/-!

## A. Derivative collections

-/


/-- The abstract index of a single covariant generator of the field algebra: one of
  the covariant-derivative towers of the field strength, of the Higgs and its
  conjugate, or of the three families of each fermion species and their conjugates,
  applied to a member of the dual basis of its value space. Only basis indices are
  stored, so for a fixed tower length the generators of a given mass weight form a
  finite type. The evaluation in `B` is `generatorVal`. -/
inductive Generators where
  /-- The Higgs tower `∇_l H` applied to a dual basis vector. -/
  | H : (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 → Generators
  /-- The conjugate-Higgs tower `∇_l H̄` applied to a dual basis vector. -/
  | barH : (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 → Generators
  /-- The field-strength tower `∇_l F_μν` applied to a dual basis vector. -/
  | F : (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) →
      (Fin 8 ⊕ Fin 3 ⊕ Fin 1) → Generators
  /-- The fermion tower `∇_l d` of the `i`-th family applied to a dual basis vector. -/
  | d : Fin 3 → (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 × Fin 3 → Generators
  /-- The fermion tower `∇_l bard` of the `i`-th family applied to a dual basis vector. -/
  | bard : Fin 3 → (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 × Fin 3 → Generators
  /-- The fermion tower `∇_l u` of the `i`-th family applied to a dual basis vector. -/
  | u : Fin 3 → (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 × Fin 3 → Generators
  /-- The fermion tower `∇_l baru` of the `i`-th family applied to a dual basis vector. -/
  | baru : Fin 3 → (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 × Fin 3 → Generators
  /-- The fermion tower `∇_l Q` of the `i`-th family applied to a dual basis vector. -/
  | Q : Fin 3 → (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 × Fin 3 × Fin 2 → Generators
  /-- The fermion tower `∇_l barQ` of the `i`-th family applied to a dual basis vector. -/
  | barQ : Fin 3 → (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 × Fin 3 × Fin 2 → Generators
  /-- The fermion tower `∇_l L` of the `i`-th family applied to a dual basis vector. -/
  | L : Fin 3 → (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 × Fin 2 → Generators
  /-- The fermion tower `∇_l barL` of the `i`-th family applied to a dual basis vector. -/
  | barL : Fin 3 → (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 × Fin 2 → Generators
  /-- The fermion tower `∇_l e` of the `i`-th family applied to a dual basis vector. -/
  | e : Fin 3 → (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 → Generators
  /-- The fermion tower `∇_l bare` of the `i`-th family applied to a dual basis vector. -/
  | bare : Fin 3 → (n : ℕ) → (Fin n → Fin 1 ⊕ Fin 3) → Fin 2 → Generators
deriving DecidableEq

namespace Generators

def IsFermionic : Generators → Prop
  | .H _ _ _ => False
  | .barH _ _ _ => False
  | .F _ _ _ _ _ => False
  | .d _ _ _ _ => True
  | .bard _ _ _ _ => True
  | .u _ _ _ _ => True
  | .baru _ _ _ _ => True
  | .Q _ _ _ _ => True
  | .barQ _ _ _ _ => True
  | .L _ _ _ _ => True
  | .barL _ _ _ _ => True
  | .e _ _ _ _ => True
  | .bare _ _ _ _ => True

/-- The Higgs generators: the covariant towers of the Higgs field and of its
  conjugate. -/
def IsHiggs : Generators → Prop
  | .H _ _ _ => True
  | .barH _ _ _ => True
  | _ => False

def IsGaugeField : Generators → Prop
  | .F _ _ _ _ _ => True
  | _ => False

/-- The number of derivatives for a given generator. -/
def toNumDerivatives : Generators → ℕ
  | .H n _ _ => n
  | .barH n _ _ => n
  | .F n _ _ _ _ => n
  | .d _ n _ _ => n
  | .bard _ n _ _ => n
  | .u _ n _ _ => n
  | .baru _ n _ _ => n
  | .Q _ n _ _ => n
  | .barQ _ n _ _ => n
  | .L _ n _ _ => n
  | .barL _ n _ _ => n
  | .e _ n _ _ => n
  | .bare _ n _ _ => n

end Generators
/-!

## B. Covariant generators

-/

/-- The three classes of covariant generator. -/
inductive GeneratorClass where
  /-- The gauge class: the field-strength towers. -/
  | gauge : GeneratorClass
  /-- The Higgs class: the Higgs towers and their conjugates. -/
  | higgs : GeneratorClass
  /-- The fermion class: the fermion towers and their conjugates. -/
  | fermion : GeneratorClass
deriving DecidableEq

/-- The three classes exhaust `GeneratorClass`. The instance is written out rather than
  derived: the `Fintype` deriving handler builds the enumerating `Finset` with a membership
  that resolves through `SetLike`, which is not type-correct here. -/
instance instFintypeGeneratorClass : Fintype GeneratorClass where
  elems := {GeneratorClass.gauge, GeneratorClass.higgs, GeneratorClass.fermion}
  complete := fun x => by cases x <;> decide

/-- The class of a covariant generator. -/
def Generators.kind : Generators → GeneratorClass
  | .F _ _ _ _ _ => .gauge
  | .H _ _ _ => .higgs
  | .barH _ _ _ => .higgs
  | _ => .fermion

@[simp]
lemma Generators.isGaugeField_iff_kind (g : Generators) :
    g.IsGaugeField ↔ g.kind = .gauge := by
  cases g <;> simp [Generators.IsGaugeField, Generators.kind]

@[simp]
lemma Generators.isHiggs_iff_kind (g : Generators) : g.IsHiggs ↔ g.kind = .higgs := by
  cases g <;> simp [Generators.IsHiggs, Generators.kind]

@[simp]
lemma Generators.isFermionic_iff_kind (g : Generators) :
    g.IsFermionic ↔ g.kind = .fermion := by
  cases g <;> simp [Generators.IsFermionic, Generators.kind]

/-- The mass weight (twice the mass dimension) of a covariant generator. -/
def Generators.weight : Generators → ℕ
  | .H n _ _ => 2 * (1 + n)
  | .barH n _ _ => 2 * (1 + n)
  | .F n _ _ _ _ => 2 * (2 + n)
  | .d _ n _ _ => 3 + 2 * n
  | .bard _ n _ _ => 3 + 2 * n
  | .u _ n _ _ => 3 + 2 * n
  | .baru _ n _ _ => 3 + 2 * n
  | .Q _ n _ _ => 3 + 2 * n
  | .barQ _ n _ _ => 3 + 2 * n
  | .L _ n _ _ => 3 + 2 * n
  | .barL _ n _ _ => 3 + 2 * n
  | .e _ n _ _ => 3 + 2 * n
  | .bare _ n _ _ => 3 + 2 * n

/-!

## Per-kind minimum weights

Each of the three classes of covariant generator carries a minimum mass weight: the
field-strength towers `F` are the heaviest, at weight `2 * (2 + n) ≥ 4`; the Higgs and
conjugate-Higgs towers `H`, `barH` are the lightest, at weight `2 * (1 + n) ≥ 2`; and
the ten families of fermion towers sit in between, at weight `3 + 2 * n ≥ 3`.

-/

/-- A gauge-class generator — a field-strength tower symbol — carries mass weight at
  least four. -/
lemma Generators.four_le_weight_of_gauge {g : Generators} (hg : g.kind = GeneratorClass.gauge) :
    4 ≤ g.weight := by
  cases g <;> simp_all [Generators.weight, Generators.kind]
  omega

/-- A Higgs-class generator — a Higgs or conjugate-Higgs tower symbol — carries mass
  weight at least two. -/
lemma Generators.two_le_weight_of_higgs {g : Generators} (hg : g.kind = GeneratorClass.higgs) :
    2 ≤ g.weight := by
  cases g <;> simp_all [Generators.weight, Generators.kind]

/-- A fermion-class generator — any of the ten families of fermion tower symbols —
  carries mass weight at least three. -/
lemma Generators.three_le_weight_of_fermion {g : Generators}
    (hg : g.kind = GeneratorClass.fermion) : 3 ≤ g.weight := by
  cases g <;> simp_all [Generators.weight, Generators.kind]

/-!

## B.1. The classes realised by a word

-/

/-- The classes realised by a word in the covariant generators. -/
def wordClasses (gl : List Generators) : Finset GeneratorClass :=
  (gl.map Generators.kind).toFinset

@[simp]
lemma wordClasses_nil : wordClasses [] = ∅ := by simp [wordClasses]

/-- Concatenating words unions the classes they realise. -/
lemma wordClasses_append (gl gl' : List Generators) :
    wordClasses (gl ++ gl') = wordClasses gl ∪ wordClasses gl' := by
  rw [wordClasses, wordClasses, wordClasses, List.map_append, List.toFinset_append]

/-- Prepending a generator inserts its class. -/
lemma wordClasses_cons (a : Generators) (gl : List Generators) :
    wordClasses (a :: gl) = insert a.kind (wordClasses gl) := by
  rw [wordClasses, wordClasses, List.map_cons, List.toFinset_cons]

/-- The total mass weight carried by the generators of a given class in a word. -/
def classWeight (c : GeneratorClass) (gl : List Generators) : ℕ :=
  ((gl.filter fun g => decide (g.kind = c)).map Generators.weight).sum

@[simp] lemma classWeight_nil (c : GeneratorClass) : classWeight c [] = 0 := rfl

lemma classWeight_cons_of_eq {c : GeneratorClass} {g : Generators} (hg : g.kind = c)
    (t : List Generators) :
    classWeight c (g :: t) = g.weight + classWeight c t := by
  simp [classWeight, hg]

lemma classWeight_cons_of_ne {c : GeneratorClass} {g : Generators} (hg : g.kind ≠ c)
    (t : List Generators) : classWeight c (g :: t) = classWeight c t := by
  simp [classWeight, hg]

/-- Every generator carries a non-zero mass weight. -/
lemma Generators.weight_pos (g : Generators) : 0 < g.weight := by
  cases g <;> simp [Generators.weight]

/-- A class realised by a word carries a non-zero part of its weight. -/
lemma classWeight_ne_zero {c : GeneratorClass} {gl : List Generators}
    (hc : c ∈ wordClasses gl) : classWeight c gl ≠ 0 := by
  induction gl with
  | nil => simp [wordClasses] at hc
  | cons g t ih =>
    rw [wordClasses_cons, Finset.mem_insert] at hc
    by_cases hg : g.kind = c
    · rw [classWeight_cons_of_eq hg]
      have := g.weight_pos
      omega
    · rw [classWeight_cons_of_ne hg]
      exact ih (hc.resolve_left fun hh => hg hh.symm)

/-- Over a word realising only two classes, the two class weights add up to the total
  weight. -/
lemma classWeight_add {c₁ c₂ : GeneratorClass} (hne : c₁ ≠ c₂) {gl : List Generators}
    (hgl : ∀ g ∈ gl, g.kind = c₁ ∨ g.kind = c₂) :
    classWeight c₁ gl + classWeight c₂ gl = (gl.map Generators.weight).sum := by
  induction gl with
  | nil => simp
  | cons g t ih =>
    have ht : ∀ g' ∈ t, g'.kind = c₁ ∨ g'.kind = c₂ := fun g' hg' => hgl g' (by simp [hg'])
    rcases hgl g (by simp) with hg | hg
    · rw [classWeight_cons_of_eq hg, classWeight_cons_of_ne (by rw [hg]; exact hne),
        List.map_cons, List.sum_cons, ← ih ht]
      omega
    · rw [classWeight_cons_of_eq hg, classWeight_cons_of_ne (by rw [hg]; exact hne.symm),
        List.map_cons, List.sum_cons, ← ih ht]
      omega

/-- A class realised by a word carries at least the minimum weight of that class: the
  generator witnessing the realisation already contributes that much, and the
  remaining generators of the class only add more. -/
lemma le_classWeight_of_mem {c : GeneratorClass} {gl : List Generators} {m : ℕ}
    (hc : c ∈ wordClasses gl) (hm : ∀ g : Generators, g.kind = c → m ≤ g.weight) :
    m ≤ classWeight c gl := by
  induction gl with
  | nil => simp [wordClasses] at hc
  | cons g t ih =>
    rw [wordClasses_cons, Finset.mem_insert] at hc
    by_cases hg : g.kind = c
    · rw [classWeight_cons_of_eq hg]
      have := hm g hg
      omega
    · rw [classWeight_cons_of_ne hg]
      exact ih (hc.resolve_left fun hh => hg hh.symm)

/-- The three class weights exhaust the total weight of a word: every generator has
  exactly one of the three kinds. -/
lemma classWeight_add_three (gl : List Generators) :
    classWeight GeneratorClass.gauge gl + classWeight GeneratorClass.higgs gl
      + classWeight GeneratorClass.fermion gl = (gl.map Generators.weight).sum := by
  induction gl with
  | nil => simp
  | cons g t ih =>
    cases hg : g.kind with
    | gauge =>
      rw [classWeight_cons_of_eq hg,
        classWeight_cons_of_ne (c := GeneratorClass.higgs) (by simp [hg]),
        classWeight_cons_of_ne (c := GeneratorClass.fermion) (by simp [hg]),
        List.map_cons, List.sum_cons]
      omega
    | higgs =>
      rw [classWeight_cons_of_ne (c := GeneratorClass.gauge) (by simp [hg]),
        classWeight_cons_of_eq hg,
        classWeight_cons_of_ne (c := GeneratorClass.fermion) (by simp [hg]),
        List.map_cons, List.sum_cons]
      omega
    | fermion =>
      rw [classWeight_cons_of_ne (c := GeneratorClass.gauge) (by simp [hg]),
        classWeight_cons_of_ne (c := GeneratorClass.higgs) (by simp [hg]),
        classWeight_cons_of_eq hg,
        List.map_cons, List.sum_cons]
      omega

set_option linter.unusedVariables false in
/-- The value in `B` of a covariant generator: the corresponding covariant tower
  applied to the indicated dual basis vector of its value space. -/
noncomputable def generatorVal
    (h : IsCovStandardModel B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
    massWeightPoly H barH F d bard u baru Q barQ L barL e bare) : Generators → B
  | .H _ l j => H l (HiggsVec.orthonormBasis.toBasis.coord j)
  | .barH _ l j => barH l (HiggsVec.orthonormBasis.toBasis.conj.coord j)
  | .F _ l μ ν j => F l μ ν (GaugeAlgebra.stdBasis.coord j)
  | .d i _ l j => d i l (DownSinglet.basis.coord j)
  | .bard i _ l j => bard i l (DownSinglet.basis.conj.coord j)
  | .u i _ l j => u i l (UpSinglet.basis.coord j)
  | .baru i _ l j => baru i l (UpSinglet.basis.conj.coord j)
  | .Q i _ l j => Q i l (QuarkDoublet.basis.coord j)
  | .barQ i _ l j => barQ i l (QuarkDoublet.basis.conj.coord j)
  | .L i _ l j => L i l (LeptonDoublet.basis.coord j)
  | .barL i _ l j => barL i l (LeptonDoublet.basis.conj.coord j)
  | .e i _ l j => e i l (LeptonSinglet.basis.coord j)
  | .bare i _ l j => bare i l (LeptonSinglet.basis.conj.coord j)

/-- Every covariant generator is a `massWeightPoly`-eigenvector of its weight. -/
lemma massWeightPoly_generatorVal (g : Generators) :
    massWeightPoly (h.generatorVal g) = Polynomial.monomial g.weight (h.generatorVal g) := by
  cases g with
  | H n l j => exact h.isHiggsSector.H_massWeight _ n l
  | barH n l j => exact h.isHiggsSector.barH_massWeight _ n l
  | F n l μ ν j => exact h.isGaugeSector.massWeight_F l μ ν _
  | d i n l j => exact h.isFermionSector.massWeight_d i l _
  | bard i n l j => exact h.isFermionSector.massWeight_bard i l _
  | u i n l j => exact h.isFermionSector.massWeight_u i l _
  | baru i n l j => exact h.isFermionSector.massWeight_baru i l _
  | Q i n l j => exact h.isFermionSector.massWeight_Q i l _
  | barQ i n l j => exact h.isFermionSector.massWeight_barQ i l _
  | L i n l j => exact h.isFermionSector.massWeight_L i l _
  | barL i n l j => exact h.isFermionSector.massWeight_barL i l _
  | e i n l j => exact h.isFermionSector.massWeight_e i l _
  | bare i n l j => exact h.isFermionSector.massWeight_bare i l _

lemma generatorVal_mem_fieldAlgebra (g : Generators) :
    h.generatorVal g ∈ h.fieldAlgebra := by
  rw [fieldAlgebra]
  refine Algebra.subset_adjoin ?_
  cases g with
    | F n l μ ν j =>
      exact Set.mem_union_left _ (Set.mem_union_left _
        (Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l, Set.mem_iUnion.mpr ⟨μ,
          Set.mem_iUnion.mpr ⟨ν, ⟨_, rfl⟩⟩⟩⟩⟩))
    | H n l j =>
      exact Set.mem_union_left _ (Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l, Set.mem_union_left _ ⟨_, rfl⟩⟩⟩))
    | barH n l j =>
      exact Set.mem_union_left _ (Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l, Set.mem_union_right _ ⟨_, rfl⟩⟩⟩))
    | d i n l j =>
      exact Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l,
          Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (⟨_, rfl⟩)))))))))⟩⟩⟩)
    | bard i n l j =>
      exact Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l,
          Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_right _ ⟨_, rfl⟩))))))))⟩⟩⟩)
    | u i n l j =>
      exact Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l,
          Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_right _ ⟨_, rfl⟩)))))))⟩⟩⟩)
    | baru i n l j =>
      exact Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l,
          Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_right _ ⟨_, rfl⟩))))))⟩⟩⟩)
    | Q i n l j =>
      exact Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l,
          Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_right _ ⟨_, rfl⟩)))))⟩⟩⟩)
    | barQ i n l j =>
      exact Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l,
          Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_right _ ⟨_, rfl⟩))))⟩⟩⟩)
    | L i n l j =>
      exact Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l,
          Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_right _ ⟨_, rfl⟩)))⟩⟩⟩)
    | barL i n l j =>
      exact Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l,
          Set.mem_union_left _ (Set.mem_union_left _ (Set.mem_union_right _ ⟨_, rfl⟩))⟩⟩⟩)
    | e i n l j =>
      exact Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l,
          Set.mem_union_left _ (Set.mem_union_right _ ⟨_, rfl⟩)⟩⟩⟩)
    | bare i n l j =>
      exact Set.mem_union_right _
        (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l,
          Set.mem_union_right _ ⟨_, rfl⟩⟩⟩⟩)

/-- Expanding every dual vector in the dual basis of its value space: the field
  algebra is already generated by the countable family of basis generators. -/
lemma fieldAlgebra_le_adjoin_range :
    h.fieldAlgebra ≤ Algebra.adjoin ℂ (Set.range h.generatorVal) := by
  rw [fieldAlgebra]
  refine Algebra.adjoin_le fun x hx => ?_
  simp only [Set.mem_union, Set.mem_iUnion, Set.mem_range] at hx
  obtain ((⟨n, l, μ, ν, φ, rfl⟩ | ⟨n, l, ⟨φ, rfl⟩ | ⟨φ, rfl⟩⟩) | ⟨i, n, l, hx⟩) := hx
  · rw [← GaugeAlgebra.stdBasis.sum_dual_apply_smul_coord φ]
    simp only [map_sum, map_smul]
    refine Subalgebra.sum_mem _ fun j _ => ?_
    rw [← algebraMap_smul ℂ (φ (GaugeAlgebra.stdBasis j))]
    exact Subalgebra.smul_mem _ (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.F n l μ ν j))) _
  · rw [← HiggsVec.orthonormBasis.toBasis.sum_dual_apply_smul_coord φ]
    simp only [map_sum, map_smul]
    exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
      (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.H n l j))) _
  · rw [← HiggsVec.orthonormBasis.toBasis.conj.sum_dual_apply_smul_coord φ]
    simp only [map_sum, map_smul]
    exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
      (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.barH n l j))) _
  · obtain (((((((((⟨φ, rfl⟩ | ⟨φ, rfl⟩) | ⟨φ, rfl⟩) | ⟨φ, rfl⟩) | ⟨φ, rfl⟩) | ⟨φ, rfl⟩) |
      ⟨φ, rfl⟩) | ⟨φ, rfl⟩) | ⟨φ, rfl⟩) | ⟨φ, rfl⟩) := hx
    · rw [← DownSinglet.basis.sum_dual_apply_smul_coord φ]
      simp only [map_sum, map_smul]
      exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
        (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.d i n l j))) _
    · rw [← DownSinglet.basis.conj.sum_dual_apply_smul_coord φ]
      simp only [map_sum, map_smul]
      exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
        (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.bard i n l j))) _
    · rw [← UpSinglet.basis.sum_dual_apply_smul_coord φ]
      simp only [map_sum, map_smul]
      exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
        (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.u i n l j))) _
    · rw [← UpSinglet.basis.conj.sum_dual_apply_smul_coord φ]
      simp only [map_sum, map_smul]
      exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
        (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.baru i n l j))) _
    · rw [← QuarkDoublet.basis.sum_dual_apply_smul_coord φ]
      simp only [map_sum, map_smul]
      exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
        (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.Q i n l j))) _
    · rw [← QuarkDoublet.basis.conj.sum_dual_apply_smul_coord φ]
      simp only [map_sum, map_smul]
      exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
        (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.barQ i n l j))) _
    · rw [← LeptonDoublet.basis.sum_dual_apply_smul_coord φ]
      simp only [map_sum, map_smul]
      exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
        (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.L i n l j))) _
    · rw [← LeptonDoublet.basis.conj.sum_dual_apply_smul_coord φ]
      simp only [map_sum, map_smul]
      exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
        (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.barL i n l j))) _
    · rw [← LeptonSinglet.basis.sum_dual_apply_smul_coord φ]
      simp only [map_sum, map_smul]
      exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
        (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.e i n l j))) _
    · rw [← LeptonSinglet.basis.conj.sum_dual_apply_smul_coord φ]
      simp only [map_sum, map_smul]
      exact Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _
        (Algebra.subset_adjoin
          (Set.mem_range_self (f := h.generatorVal) (Generators.bare i n l j))) _

/-- The field algebra is generated by the covariant basis generators. -/
lemma fieldAlgebra_eq_adjoin_range :
    h.fieldAlgebra = Algebra.adjoin ℂ (Set.range h.generatorVal) := by
  refine le_antisymm h.fieldAlgebra_le_adjoin_range (Algebra.adjoin_le ?_)
  rintro x ⟨g, rfl⟩
  exact h.generatorVal_mem_fieldAlgebra g

/-- A list of generator values is the list of values of a list of generators. -/
lemma exists_list_map_eq (l₀ : List B) :
    (∀ y ∈ l₀, y ∈ Set.range h.generatorVal) →
    ∃ gl : List Generators, gl.map h.generatorVal = l₀ := by
  induction l₀ with
  | nil => exact fun _ => ⟨[], rfl⟩
  | cons a t ih =>
    intro hl₀
    obtain ⟨g, hg⟩ := hl₀ a (by simp)
    obtain ⟨gl, hgl⟩ := ih (fun y hy => hl₀ y (by simp [hy]))
    exact ⟨g :: gl, by rw [List.map_cons, hg, hgl]⟩

/-- A word in the covariant generators is a `massWeightPoly`-eigenvector whose
  weight is the sum of the weights of its factors. -/
lemma massWeightPoly_generatorVal_list_prod (gl : List Generators) :
    massWeightPoly ((gl.map h.generatorVal).prod) =
      Polynomial.monomial ((gl.map Generators.weight).sum) ((gl.map h.generatorVal).prod) := by
  induction gl with
  | nil => simp
  | cons g t ih =>
    simp only [List.map_cons, List.prod_cons, List.sum_cons, map_mul,
      h.massWeightPoly_generatorVal, ih, Polynomial.monomial_mul_monomial]
/-!

## C. Supercommutativity of the generators

The mass weight doubles as the super-grading: the weight of a covariant generator
is odd exactly when the generator is fermionic. Two generators therefore exchange
up to the sign `(-1) ^ (weight * weight)`, and words of generators up to the sign
of the product of their total weights.

-/

/-- The field-strength symbols commute with the value of every covariant
  generator. -/
lemma commute_F_generatorVal {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3) (μ ν : Fin 1 ⊕ Fin 3)
    (ψ : Module.Dual ℝ GaugeAlgebra) (g : Generators) :
    Commute (F l μ ν ψ) (h.generatorVal g) := by
  cases g with
  | H n' l' j => exact h.F_comm_H l μ ν ψ l' _
  | barH n' l' j => exact h.F_comm_barH l μ ν ψ l' _
  | F n' l' μ' ν' j => exact h.isGaugeSector.F_comm_F l μ ν ψ l' μ' ν' _
  | d i n' l' j => exact h.F_comm_d l μ ν ψ i l' _
  | bard i n' l' j => exact h.F_comm_bard l μ ν ψ i l' _
  | u i n' l' j => exact h.F_comm_u l μ ν ψ i l' _
  | baru i n' l' j => exact h.F_comm_baru l μ ν ψ i l' _
  | Q i n' l' j => exact h.F_comm_Q l μ ν ψ i l' _
  | barQ i n' l' j => exact h.F_comm_barQ l μ ν ψ i l' _
  | L i n' l' j => exact h.F_comm_L l μ ν ψ i l' _
  | barL i n' l' j => exact h.F_comm_barL l μ ν ψ i l' _
  | e i n' l' j => exact h.F_comm_e l μ ν ψ i l' _
  | bare i n' l' j => exact h.F_comm_bare l μ ν ψ i l' _

/-- The Higgs symbols commute with the value of every covariant generator. -/
lemma commute_H_generatorVal {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ HiggsVec) (g : Generators) :
    Commute (H l φ) (h.generatorVal g) := by
  cases g with
  | H n' l' j => exact h.isHiggsSector.H_comm_H φ _ _ _ l l'
  | barH n' l' j => exact h.isHiggsSector.H_comm_barH φ _ _ _ l l'
  | F n' l' μ' ν' j => exact (h.F_comm_H l' μ' ν' _ l φ).symm
  | d i n' l' j => exact h.H_comm_d l φ i l' _
  | bard i n' l' j => exact h.H_comm_bard l φ i l' _
  | u i n' l' j => exact h.H_comm_u l φ i l' _
  | baru i n' l' j => exact h.H_comm_baru l φ i l' _
  | Q i n' l' j => exact h.H_comm_Q l φ i l' _
  | barQ i n' l' j => exact h.H_comm_barQ l φ i l' _
  | L i n' l' j => exact h.H_comm_L l φ i l' _
  | barL i n' l' j => exact h.H_comm_barL l φ i l' _
  | e i n' l' j => exact h.H_comm_e l φ i l' _
  | bare i n' l' j => exact h.H_comm_bare l φ i l' _

/-- The conjugate-Higgs symbols commute with the value of every covariant
  generator. -/
lemma commute_barH_generatorVal {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ (ConjModule HiggsVec)) (g : Generators) :
    Commute (barH l φ) (h.generatorVal g) := by
  cases g with
  | H n' l' j => exact (h.isHiggsSector.H_comm_barH _ φ _ _ l' l).symm
  | barH n' l' j => exact h.isHiggsSector.barH_comm_barH φ _ _ _ l l'
  | F n' l' μ' ν' j => exact (h.F_comm_barH l' μ' ν' _ l φ).symm
  | d i n' l' j => exact h.barH_comm_d l φ i l' _
  | bard i n' l' j => exact h.barH_comm_bard l φ i l' _
  | u i n' l' j => exact h.barH_comm_u l φ i l' _
  | baru i n' l' j => exact h.barH_comm_baru l φ i l' _
  | Q i n' l' j => exact h.barH_comm_Q l φ i l' _
  | barQ i n' l' j => exact h.barH_comm_barQ l φ i l' _
  | L i n' l' j => exact h.barH_comm_L l φ i l' _
  | barL i n' l' j => exact h.barH_comm_barL l φ i l' _
  | e i n' l' j => exact h.barH_comm_e l φ i l' _
  | bare i n' l' j => exact h.barH_comm_bare l φ i l' _

/-- A covariant generator of even mass weight is bosonic: its value commutes with
  the value of every covariant generator. -/
lemma commute_generatorVal_of_even {g : Generators} (hg : g.weight % 2 = 0)
    (g' : Generators) : Commute (h.generatorVal g) (h.generatorVal g') := by
  cases g with
  | H n l j => exact h.commute_H_generatorVal l _ g'
  | barH n l j => exact h.commute_barH_generatorVal l _ g'
  | F n l μ ν j => exact h.commute_F_generatorVal l μ ν _ g'
  | d i n l j => exact absurd hg (by simp only [Generators.weight]; omega)
  | bard i n l j => exact absurd hg (by simp only [Generators.weight]; omega)
  | u i n l j => exact absurd hg (by simp only [Generators.weight]; omega)
  | baru i n l j => exact absurd hg (by simp only [Generators.weight]; omega)
  | Q i n l j => exact absurd hg (by simp only [Generators.weight]; omega)
  | barQ i n l j => exact absurd hg (by simp only [Generators.weight]; omega)
  | L i n l j => exact absurd hg (by simp only [Generators.weight]; omega)
  | barL i n l j => exact absurd hg (by simp only [Generators.weight]; omega)
  | e i n l j => exact absurd hg (by simp only [Generators.weight]; omega)
  | bare i n l j => exact absurd hg (by simp only [Generators.weight]; omega)

/-- Fermionic generator values anticommute: the values of two covariant generators
  of odd mass weight exchange with a sign. -/
lemma generatorVal_anticomm_of_odd_of_odd {g g' : Generators}
    (hg : g.weight % 2 = 1) (hg' : g'.weight % 2 = 1) :
    h.generatorVal g * h.generatorVal g'
      = -(h.generatorVal g' * h.generatorVal g) := by
  cases g with
  | H n l j => exact absurd hg (by simp only [Generators.weight]; omega)
  | barH n l j => exact absurd hg (by simp only [Generators.weight]; omega)
  | F n l μ ν j => exact absurd hg (by simp only [Generators.weight]; omega)
  | d i n l j =>
    cases g' with
    | H n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | barH n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | F n' l' μ' ν' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | d i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.d_anticomm_d i i' l l' _ _
    | bard i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.d_anticomm_bard i i' l l' _ _
    | u i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.d_anticomm_u i i' l l' _ _
    | baru i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.d_anticomm_baru i i' l l' _ _
    | Q i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.d_anticomm_Q i i' l l' _ _
    | barQ i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.d_anticomm_barQ i i' l l' _ _
    | L i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.d_anticomm_L i i' l l' _ _
    | barL i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.d_anticomm_barL i i' l l' _ _
    | e i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.d_anticomm_e i i' l l' _ _
    | bare i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.d_anticomm_bare i i' l l' _ _
  | bard i n l j =>
    cases g' with
    | H n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | barH n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | F n' l' μ' ν' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | d i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.d_anticomm_bard i' i l' l, neg_neg]
    | bard i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.bard_anticomm_bard i i' l l' _ _
    | u i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.bard_anticomm_u i i' l l' _ _
    | baru i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.bard_anticomm_baru i i' l l' _ _
    | Q i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.bard_anticomm_Q i i' l l' _ _
    | barQ i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.bard_anticomm_barQ i i' l l' _ _
    | L i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.bard_anticomm_L i i' l l' _ _
    | barL i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.bard_anticomm_barL i i' l l' _ _
    | e i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.bard_anticomm_e i i' l l' _ _
    | bare i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.bard_anticomm_bare i i' l l' _ _
  | u i n l j =>
    cases g' with
    | H n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | barH n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | F n' l' μ' ν' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | d i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.d_anticomm_u i' i l' l, neg_neg]
    | bard i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.bard_anticomm_u i' i l' l, neg_neg]
    | u i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.u_anticomm_u i i' l l' _ _
    | baru i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.u_anticomm_baru i i' l l' _ _
    | Q i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.u_anticomm_Q i i' l l' _ _
    | barQ i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.u_anticomm_barQ i i' l l' _ _
    | L i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.u_anticomm_L i i' l l' _ _
    | barL i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.u_anticomm_barL i i' l l' _ _
    | e i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.u_anticomm_e i i' l l' _ _
    | bare i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.u_anticomm_bare i i' l l' _ _
  | baru i n l j =>
    cases g' with
    | H n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | barH n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | F n' l' μ' ν' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | d i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.d_anticomm_baru i' i l' l, neg_neg]
    | bard i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.bard_anticomm_baru i' i l' l, neg_neg]
    | u i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.u_anticomm_baru i' i l' l, neg_neg]
    | baru i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.baru_anticomm_baru i i' l l' _ _
    | Q i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.baru_anticomm_Q i i' l l' _ _
    | barQ i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.baru_anticomm_barQ i i' l l' _ _
    | L i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.baru_anticomm_L i i' l l' _ _
    | barL i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.baru_anticomm_barL i i' l l' _ _
    | e i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.baru_anticomm_e i i' l l' _ _
    | bare i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.baru_anticomm_bare i i' l l' _ _
  | Q i n l j =>
    cases g' with
    | H n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | barH n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | F n' l' μ' ν' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | d i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.d_anticomm_Q i' i l' l, neg_neg]
    | bard i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.bard_anticomm_Q i' i l' l, neg_neg]
    | u i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.u_anticomm_Q i' i l' l, neg_neg]
    | baru i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.baru_anticomm_Q i' i l' l, neg_neg]
    | Q i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.Q_anticomm_Q i i' l l' _ _
    | barQ i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.Q_anticomm_barQ i i' l l' _ _
    | L i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.Q_anticomm_L i i' l l' _ _
    | barL i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.Q_anticomm_barL i i' l l' _ _
    | e i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.Q_anticomm_e i i' l l' _ _
    | bare i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.Q_anticomm_bare i i' l l' _ _
  | barQ i n l j =>
    cases g' with
    | H n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | barH n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | F n' l' μ' ν' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | d i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.d_anticomm_barQ i' i l' l, neg_neg]
    | bard i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.bard_anticomm_barQ i' i l' l, neg_neg]
    | u i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.u_anticomm_barQ i' i l' l, neg_neg]
    | baru i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.baru_anticomm_barQ i' i l' l, neg_neg]
    | Q i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.Q_anticomm_barQ i' i l' l, neg_neg]
    | barQ i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.barQ_anticomm_barQ i i' l l' _ _
    | L i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.barQ_anticomm_L i i' l l' _ _
    | barL i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.barQ_anticomm_barL i i' l l' _ _
    | e i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.barQ_anticomm_e i i' l l' _ _
    | bare i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.barQ_anticomm_bare i i' l l' _ _
  | L i n l j =>
    cases g' with
    | H n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | barH n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | F n' l' μ' ν' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | d i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.d_anticomm_L i' i l' l, neg_neg]
    | bard i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.bard_anticomm_L i' i l' l, neg_neg]
    | u i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.u_anticomm_L i' i l' l, neg_neg]
    | baru i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.baru_anticomm_L i' i l' l, neg_neg]
    | Q i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.Q_anticomm_L i' i l' l, neg_neg]
    | barQ i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.barQ_anticomm_L i' i l' l, neg_neg]
    | L i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.L_anticomm_L i i' l l' _ _
    | barL i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.L_anticomm_barL i i' l l' _ _
    | e i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.L_anticomm_e i i' l l' _ _
    | bare i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.L_anticomm_bare i i' l l' _ _
  | barL i n l j =>
    cases g' with
    | H n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | barH n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | F n' l' μ' ν' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | d i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.d_anticomm_barL i' i l' l, neg_neg]
    | bard i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.bard_anticomm_barL i' i l' l, neg_neg]
    | u i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.u_anticomm_barL i' i l' l, neg_neg]
    | baru i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.baru_anticomm_barL i' i l' l, neg_neg]
    | Q i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.Q_anticomm_barL i' i l' l, neg_neg]
    | barQ i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.barQ_anticomm_barL i' i l' l, neg_neg]
    | L i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.L_anticomm_barL i' i l' l, neg_neg]
    | barL i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.barL_anticomm_barL i i' l l' _ _
    | e i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.barL_anticomm_e i i' l l' _ _
    | bare i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.barL_anticomm_bare i i' l l' _ _
  | e i n l j =>
    cases g' with
    | H n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | barH n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | F n' l' μ' ν' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | d i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.d_anticomm_e i' i l' l, neg_neg]
    | bard i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.bard_anticomm_e i' i l' l, neg_neg]
    | u i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.u_anticomm_e i' i l' l, neg_neg]
    | baru i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.baru_anticomm_e i' i l' l, neg_neg]
    | Q i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.Q_anticomm_e i' i l' l, neg_neg]
    | barQ i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.barQ_anticomm_e i' i l' l, neg_neg]
    | L i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.L_anticomm_e i' i l' l, neg_neg]
    | barL i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.barL_anticomm_e i' i l' l, neg_neg]
    | e i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.e_anticomm_e i i' l l' _ _
    | bare i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.e_anticomm_bare i i' l l' _ _
  | bare i n l j =>
    cases g' with
    | H n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | barH n' l' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | F n' l' μ' ν' j' => exact absurd hg' (by simp only [Generators.weight]; omega)
    | d i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.d_anticomm_bare i' i l' l, neg_neg]
    | bard i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.bard_anticomm_bare i' i l' l, neg_neg]
    | u i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.u_anticomm_bare i' i l' l, neg_neg]
    | baru i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.baru_anticomm_bare i' i l' l, neg_neg]
    | Q i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.Q_anticomm_bare i' i l' l, neg_neg]
    | barQ i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.barQ_anticomm_bare i' i l' l, neg_neg]
    | L i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.L_anticomm_bare i' i l' l, neg_neg]
    | barL i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.barL_anticomm_bare i' i l' l, neg_neg]
    | e i' n' l' j' =>
      simp only [generatorVal]
      rw [h.isFermionSector.e_anticomm_bare i' i l' l, neg_neg]
    | bare i' n' l' j' =>
      simp only [generatorVal]
      exact h.isFermionSector.bare_anticomm_bare i i' l l' _ _

/-- Two covariant generators exchange up to the sign determined by their mass
  weights: the weight is odd exactly on the fermionic generators, so the sign is
  `-1` precisely when both generators are fermionic. -/
lemma generatorVal_mul_generatorVal (g g' : Generators) :
    h.generatorVal g * h.generatorVal g' =
      ((-1 : ℂ) ^ (g.weight * g'.weight)) • (h.generatorVal g' * h.generatorVal g) := by
  rcases Nat.even_or_odd g.weight with hg | hg
  · rw [Even.neg_one_pow (hg.mul_right _), one_smul]
    exact h.commute_generatorVal_of_even (Nat.even_iff.mp hg) g'
  · rcases Nat.even_or_odd g'.weight with hg' | hg'
    · rw [Even.neg_one_pow (hg'.mul_left _), one_smul]
      exact (h.commute_generatorVal_of_even (Nat.even_iff.mp hg') g).symm
    · rw [Odd.neg_one_pow (hg.mul hg'), neg_one_smul]
      exact h.generatorVal_anticomm_of_odd_of_odd (Nat.odd_iff.mp hg) (Nat.odd_iff.mp hg')

/-- A generator value moves past a word of generators up to the sign of the
  product of the weights. -/
lemma generatorVal_mul_list_prod (g : Generators) (gl : List Generators) :
    h.generatorVal g * (gl.map h.generatorVal).prod =
      ((-1 : ℂ) ^ (g.weight * (gl.map Generators.weight).sum)) •
        ((gl.map h.generatorVal).prod * h.generatorVal g) := by
  induction gl with
  | nil => simp
  | cons g' t ih =>
    simp only [List.map_cons, List.prod_cons, List.sum_cons]
    calc h.generatorVal g * (h.generatorVal g' * (t.map h.generatorVal).prod)
        = (h.generatorVal g * h.generatorVal g') * (t.map h.generatorVal).prod := by
          rw [mul_assoc]
      _ = ((-1 : ℂ) ^ (g.weight * g'.weight)) •
            (h.generatorVal g' * (h.generatorVal g * (t.map h.generatorVal).prod)) := by
          rw [h.generatorVal_mul_generatorVal g g', smul_mul_assoc, mul_assoc]
      _ = ((-1 : ℂ) ^ (g.weight * g'.weight)) • (h.generatorVal g' *
            (((-1 : ℂ) ^ (g.weight * (t.map Generators.weight).sum)) •
              ((t.map h.generatorVal).prod * h.generatorVal g))) := by rw [ih]
      _ = ((-1 : ℂ) ^ (g.weight * (g'.weight + (t.map Generators.weight).sum))) •
            ((h.generatorVal g' * (t.map h.generatorVal).prod) * h.generatorVal g) := by
          rw [mul_smul_comm, smul_smul, ← pow_add, ← mul_add, ← mul_assoc]

/-- Two words of covariant generators exchange up to the sign of the product of
  their total weights. -/
lemma list_prod_mul_list_prod (gl gl' : List Generators) :
    (gl.map h.generatorVal).prod * (gl'.map h.generatorVal).prod =
      ((-1 : ℂ) ^ ((gl.map Generators.weight).sum * (gl'.map Generators.weight).sum)) •
        ((gl'.map h.generatorVal).prod * (gl.map h.generatorVal).prod) := by
  induction gl with
  | nil => simp
  | cons g t ih =>
    simp only [List.map_cons, List.prod_cons, List.sum_cons]
    calc (h.generatorVal g * (t.map h.generatorVal).prod) * (gl'.map h.generatorVal).prod
        = h.generatorVal g * ((t.map h.generatorVal).prod * (gl'.map h.generatorVal).prod) := by
          rw [mul_assoc]
      _ = ((-1 : ℂ) ^ ((t.map Generators.weight).sum * (gl'.map Generators.weight).sum)) •
            ((h.generatorVal g * (gl'.map h.generatorVal).prod) * (t.map h.generatorVal).prod) := by
          rw [ih, mul_smul_comm, ← mul_assoc]
      _ = ((-1 : ℂ) ^ ((t.map Generators.weight).sum * (gl'.map Generators.weight).sum)) •
            ((((-1 : ℂ) ^ (g.weight * (gl'.map Generators.weight).sum)) •
              ((gl'.map h.generatorVal).prod * h.generatorVal g)) * (t.map h.generatorVal).prod) := by
          rw [h.generatorVal_mul_list_prod g gl']
      _ = ((-1 : ℂ) ^ ((g.weight + (t.map Generators.weight).sum) *
              (gl'.map Generators.weight).sum)) •
            ((gl'.map h.generatorVal).prod * (h.generatorVal g * (t.map h.generatorVal).prod)) := by
          rw [smul_mul_assoc, smul_smul, ← pow_add, mul_assoc,
            show (t.map Generators.weight).sum * (gl'.map Generators.weight).sum
                + g.weight * (gl'.map Generators.weight).sum
              = (g.weight + (t.map Generators.weight).sum) *
                (gl'.map Generators.weight).sum from by ring]

end IsCovStandardModel

end StandardModel
