/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.IsCovStandardModel.Generators
/-!
# The mass-weight grading of the field algebra

The elements of the field algebra of a given mass weight form a submodule, which is
exactly the span of the words in the covariant generators of that total weight
(`massWeightSubmodule_eq_span`). Weight-homogeneous elements supercommute,
the gauge and Lorentz actions preserve the weight, and consequently an invariant
element decomposing into components of pairwise distinct weights has invariant
components.

-/

@[expose] public section

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz


namespace IsCovStandardModel

variable {B : Type} [Ring B] [Algebra ℂ B]
  {repGauge : Representation ℂ GaugeGroupI B}
  {hrepGauge_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B),
    repGauge g (b₁ * b₂) = repGauge g b₁ * repGauge g b₂}
  {repLorentz : Representation ℂ SL(2,ℂ) B}
  {hrepLorentz_mul : ∀ (Λ : SL(2,ℂ)) (b₁ b₂ : B),
    repLorentz Λ (b₁ * b₂) = repLorentz Λ b₁ * repLorentz Λ b₂}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  {H : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ HiggsVec →ₗ[ℂ] B}
  {barH : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule HiggsVec) →ₗ[ℂ] B}
  {F : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) →
    Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
  {d : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ DownSinglet →ₗ[ℂ] B}
  {bard : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule DownSinglet) →ₗ[ℂ] B}
  {u : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ UpSinglet →ₗ[ℂ] B}
  {baru : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule UpSinglet) →ₗ[ℂ] B}
  {Q : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ QuarkDoublet →ₗ[ℂ] B}
  {barQ : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule QuarkDoublet) →ₗ[ℂ] B}
  {L : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ LeptonDoublet →ₗ[ℂ] B}
  {barL : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule LeptonDoublet) →ₗ[ℂ] B}
  {e : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ LeptonSinglet →ₗ[ℂ] B}
  {bare : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule LeptonSinglet) →ₗ[ℂ] B}
  (h : IsCovStandardModel B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
    massWeightPoly H barH F d bard u baru Q barQ L barL e bare)

/-!

## A. The mass-weight submodules

-/



/-- All elements of the field algebra of mass weight exactly `n`: the intersection of
  the algebra generated by the covariant fields with the part on which
  `massWeightPoly` is the monomial `X ^ n`. -/
noncomputable def massWeightSubmodule
    (h : IsCovStandardModel B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
    massWeightPoly H barH F d bard u baru Q barQ L barL e bare) (n : ℕ) : Submodule ℂ B :=
  (h.fieldAlgebra).toSubmodule
    ⊓ LinearMap.ker (massWeightPoly.toLinearMap
      - (Polynomial.monomial n : B →ₗ[B] Polynomial B).restrictScalars ℂ)

lemma massWeightPoly_of_mem_massWeightSubmodule {n : ℕ} {x : B}
    (hx : x ∈ h.massWeightSubmodule n) :
    massWeightPoly x = Polynomial.monomial n x := by
  rw [massWeightSubmodule, Submodule.mem_inf] at hx
  rcases hx with ⟨-, hx'⟩
  rw [LinearMap.mem_ker] at hx'
  simp only [LinearMap.sub_apply, AlgHom.toLinearMap_apply, LinearMap.coe_restrictScalars,
    sub_eq_zero] at hx'
  exact hx'

lemma mem_fieldAlgebra_of_mem_massWeightSubmodule {n : ℕ} {x : B}
    (hx : x ∈ h.massWeightSubmodule n) : x ∈ h.fieldAlgebra := by
  rw [massWeightSubmodule, Submodule.mem_inf] at hx
  exact hx.1

/-- Membership in a mass-weight submodule: an element of the field algebra which
  `massWeightPoly` sends to the monomial of that weight. -/
lemma mem_massWeightSubmodule_of {n : ℕ} {x : B} (hmem : x ∈ h.fieldAlgebra)
    (hpoly : massWeightPoly x = Polynomial.monomial n x) :
    x ∈ h.massWeightSubmodule n := by
  rw [massWeightSubmodule]
  refine Submodule.mem_inf.mpr ⟨hmem, ?_⟩
  rw [LinearMap.mem_ker]
  simp only [LinearMap.sub_apply, AlgHom.toLinearMap_apply, LinearMap.coe_restrictScalars,
    sub_eq_zero]
  exact hpoly
/-!

## B. The weight grading of the field algebra

-/

/-- A word in the covariant generators lies in the mass-weight submodule of its total
  weight. -/
lemma list_prod_mem_massWeightSubmodule {w : ℕ} {gl : List Generators}
    (hw : (gl.map Generators.weight).sum = w) :
    (gl.map h.generatorVal).prod ∈ h.massWeightSubmodule w :=
  h.mem_massWeightSubmodule_of
    (Subalgebra.list_prod_mem _ fun y hy => by
      obtain ⟨g, -, rfl⟩ := List.mem_map.mp hy
      exact h.generatorVal_mem_fieldAlgebra g)
    (by rw [h.massWeightPoly_generatorVal_list_prod, hw])

/-- Reading off the `X ^ w` coefficient of `massWeightPoly` sends the field algebra
  into the span of the words of total weight `w` — the projection onto the weight-`w`
  component, with no independence argument needed. -/
lemma coeff_massWeightPoly_mem_span (w : ℕ) {x : B}
    (hx : x ∈ h.fieldAlgebra) :
    (massWeightPoly x).coeff w ∈ Submodule.span ℂ
      {y | ∃ gl : List Generators,
        (gl.map Generators.weight).sum = w ∧ (gl.map h.generatorVal).prod = y} := by
  rw [h.fieldAlgebra_eq_adjoin_range, ← Subalgebra.mem_toSubmodule,
    Algebra.adjoin_eq_span] at hx
  induction hx using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨l₀, hl₀, rfl⟩ := Submonoid.exists_list_of_mem_closure hy
    obtain ⟨gl, rfl⟩ := h.exists_list_map_eq l₀ hl₀
    rw [h.massWeightPoly_generatorVal_list_prod, Polynomial.coeff_monomial]
    by_cases hw : (gl.map Generators.weight).sum = w
    · rw [if_pos hw]
      exact Submodule.subset_span ⟨gl, hw, rfl⟩
    · rw [if_neg hw]
      exact Submodule.zero_mem _
  | zero =>
    rw [map_zero, Polynomial.coeff_zero]
    exact Submodule.zero_mem _
  | add a b ha hb iha ihb =>
    rw [map_add, Polynomial.coeff_add]
    exact Submodule.add_mem _ iha ihb
  | smul c a ha iha =>
    rw [map_smul, Polynomial.coeff_smul]
    exact Submodule.smul_mem _ _ iha

/-- **The weight grading of the field algebra.** The submodule of elements of the
  field algebra of mass weight `w` is exactly the span of the words in the covariant
  basis generators of total weight `w`. -/
lemma massWeightSubmodule_eq_span (w : ℕ) :
    h.massWeightSubmodule w = Submodule.span ℂ
      {x | ∃ gl : List Generators,
        (gl.map Generators.weight).sum = w ∧ (gl.map h.generatorVal).prod = x} := by
  refine le_antisymm (fun x hx => ?_) (Submodule.span_le.mpr ?_)
  · have h1 := h.massWeightPoly_of_mem_massWeightSubmodule hx
    have h2 := h.coeff_massWeightPoly_mem_span w
      (h.mem_fieldAlgebra_of_mem_massWeightSubmodule hx)
    rwa [h1, Polynomial.coeff_monomial, if_pos rfl] at h2
  · rintro x ⟨gl, hw, rfl⟩
    exact h.list_prod_mem_massWeightSubmodule hw
/-!

## C. Supercommutativity of weight-homogeneous elements

-/

/-- Weight-homogeneous elements of the field algebra supercommute: elements of the
  mass-weight submodules of weights `w` and `w'` exchange up to the sign
  `(-1) ^ (w * w')` — fermion parity is the parity of the mass weight. -/
lemma mul_eq_smul_mul_of_mem_massWeightSubmodule {w w' : ℕ} {x y : B}
    (hx : x ∈ h.massWeightSubmodule w) (hy : y ∈ h.massWeightSubmodule w') :
    x * y = ((-1 : ℂ) ^ (w * w')) • (y * x) := by
  rw [h.massWeightSubmodule_eq_span] at hx hy
  induction hx using Submodule.span_induction with
  | mem x hxw =>
    obtain ⟨gl, hglw, rfl⟩ := hxw
    induction hy using Submodule.span_induction with
    | mem y hyw =>
      obtain ⟨gl', hgl'w, rfl⟩ := hyw
      rw [← hglw, ← hgl'w]
      exact h.list_prod_mul_list_prod gl gl'
    | zero => simp
    | add a b ha hb iha ihb => rw [mul_add, iha, ihb, add_mul, smul_add]
    | smul c a ha iha => rw [mul_smul_comm, iha, smul_comm, smul_mul_assoc]
  | zero => simp
  | add a b ha hb iha ihb => rw [add_mul, iha, ihb, mul_add, smul_add]
  | smul c a ha iha => rw [smul_mul_assoc, iha, smul_comm, mul_smul_comm]

/-- Weight-homogeneous elements of the field algebra commute up to a scalar. -/
lemma exists_smul_mul_comm_of_mem_massWeightSubmodule {w w' : ℕ} {x y : B}
    (hx : x ∈ h.massWeightSubmodule w) (hy : y ∈ h.massWeightSubmodule w') :
    ∃ c : ℂ, x * y = c • (y * x) :=
  ⟨_, h.mul_eq_smul_mul_of_mem_massWeightSubmodule hx hy⟩

/-- Reordering a product of two weight-homogeneous elements does not change its
  span. -/
lemma span_mul_comm_of_mem_massWeightSubmodule {w w' : ℕ} {x y : B}
    (hx : x ∈ h.massWeightSubmodule w) (hy : y ∈ h.massWeightSubmodule w') :
    ℂ ∙ (x * y) = ℂ ∙ (y * x) := by
  rw [h.mul_eq_smul_mul_of_mem_massWeightSubmodule hx hy]
  exact Submodule.span_singleton_smul_eq ((isUnit_one.neg).pow _) _

/-!

## D. Invariance of the weight components

The gauge and Lorentz actions preserve the mass weight: they carry each covariant
tower into combinations of towers of the same derivative order. The weight
components of the field algebra are independent, so an invariant element that is
a sum of components of pairwise distinct weights has invariant components.

-/

/-- The mass-weight submodules are multiplicative: weights add under multiplication. -/
lemma mul_mem_massWeightSubmodule {w w2 : ℕ} {x y : B}
    (hx : x ∈ h.massWeightSubmodule w) (hy : y ∈ h.massWeightSubmodule w2) :
    x * y ∈ h.massWeightSubmodule (w + w2) :=
  h.mem_massWeightSubmodule_of
    (mul_mem (h.mem_fieldAlgebra_of_mem_massWeightSubmodule hx)
      (h.mem_fieldAlgebra_of_mem_massWeightSubmodule hy))
    (by rw [map_mul, h.massWeightPoly_of_mem_massWeightSubmodule hx,
      h.massWeightPoly_of_mem_massWeightSubmodule hy, Polynomial.monomial_mul_monomial])

/-- Any Higgs tower symbol lies in the mass-weight submodule of its weight. -/
lemma H_mem_massWeightSubmodule {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ HiggsVec) : H l φ ∈ h.massWeightSubmodule (2 * (1 + n)) := by
  rw [← HiggsVec.orthonormBasis.toBasis.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.H n l j]) (by simp [Generators.weight])

/-- Any conjugate-Higgs tower symbol lies in the mass-weight submodule of its weight. -/
lemma barH_mem_massWeightSubmodule {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ (ConjModule HiggsVec)) :
    barH l φ ∈ h.massWeightSubmodule (2 * (1 + n)) := by
  rw [← HiggsVec.orthonormBasis.toBasis.conj.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.barH n l j]) (by simp [Generators.weight])

/-- Any field-strength tower symbol lies in the mass-weight submodule of its weight. -/
lemma F_mem_massWeightSubmodule {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ GaugeAlgebra) :
    F l μ ν φ ∈ h.massWeightSubmodule (2 * (2 + n)) := by
  rw [← GaugeAlgebra.stdBasis.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => ?_
  rw [← algebraMap_smul ℂ (φ (GaugeAlgebra.stdBasis j))]
  refine Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.F n l μ ν j]) (by simp [Generators.weight])

/-- Any `d` tower symbol lies in the mass-weight submodule of its weight. -/
lemma d_mem_massWeightSubmodule (i : Fin 3) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ DownSinglet) : d i l φ ∈ h.massWeightSubmodule (3 + 2 * n) := by
  rw [← DownSinglet.basis.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.d i n l j]) (by simp [Generators.weight])

/-- A `d` tower symbol supercommutes with any weight-homogeneous element: its own
  weight `3 + 2 * n` is odd, so moving it past an element of weight `w` costs
  `(-1) ^ w`. -/
lemma d_supercommute_mem_massWeightSubmodule (i : Fin 3) {n : ℕ} {l : Fin n → Fin 1 ⊕ Fin 3}
    (φ : Module.Dual ℂ DownSinglet) {w : ℕ} (x : B) (hx : x ∈ h.massWeightSubmodule w) :
    d i l φ * x = ((-1 : ℂ) ^ w) • (x * d i l φ) := by
  rw [h.mul_eq_smul_mul_of_mem_massWeightSubmodule (h.d_mem_massWeightSubmodule i l φ) hx]
  congr 1
  rw [pow_mul]
  congr 1
  rw [pow_add, pow_mul]
  norm_num

/-- Any `bard` tower symbol lies in the mass-weight submodule of its weight. -/
lemma bard_mem_massWeightSubmodule (i : Fin 3) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ (ConjModule DownSinglet)) : bard i l φ ∈ h.massWeightSubmodule (3 + 2 * n) := by
  rw [← DownSinglet.basis.conj.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.bard i n l j]) (by simp [Generators.weight])

/-- Any `u` tower symbol lies in the mass-weight submodule of its weight. -/
lemma u_mem_massWeightSubmodule (i : Fin 3) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ UpSinglet) : u i l φ ∈ h.massWeightSubmodule (3 + 2 * n) := by
  rw [← UpSinglet.basis.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.u i n l j]) (by simp [Generators.weight])

/-- Any `baru` tower symbol lies in the mass-weight submodule of its weight. -/
lemma baru_mem_massWeightSubmodule (i : Fin 3) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ (ConjModule UpSinglet)) : baru i l φ ∈ h.massWeightSubmodule (3 + 2 * n) := by
  rw [← UpSinglet.basis.conj.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.baru i n l j]) (by simp [Generators.weight])

/-- Any `Q` tower symbol lies in the mass-weight submodule of its weight. -/
lemma Q_mem_massWeightSubmodule (i : Fin 3) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ QuarkDoublet) : Q i l φ ∈ h.massWeightSubmodule (3 + 2 * n) := by
  rw [← QuarkDoublet.basis.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.Q i n l j]) (by simp [Generators.weight])

/-- Any `barQ` tower symbol lies in the mass-weight submodule of its weight. -/
lemma barQ_mem_massWeightSubmodule (i : Fin 3) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ (ConjModule QuarkDoublet)) : barQ i l φ ∈ h.massWeightSubmodule (3 + 2 * n) := by
  rw [← QuarkDoublet.basis.conj.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.barQ i n l j]) (by simp [Generators.weight])

/-- Any `L` tower symbol lies in the mass-weight submodule of its weight. -/
lemma L_mem_massWeightSubmodule (i : Fin 3) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ LeptonDoublet) : L i l φ ∈ h.massWeightSubmodule (3 + 2 * n) := by
  rw [← LeptonDoublet.basis.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.L i n l j]) (by simp [Generators.weight])

/-- Any `barL` tower symbol lies in the mass-weight submodule of its weight. -/
lemma barL_mem_massWeightSubmodule (i : Fin 3) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ (ConjModule LeptonDoublet)) : barL i l φ ∈ h.massWeightSubmodule (3 + 2 * n) := by
  rw [← LeptonDoublet.basis.conj.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.barL i n l j]) (by simp [Generators.weight])

/-- Any `e` tower symbol lies in the mass-weight submodule of its weight. -/
lemma e_mem_massWeightSubmodule (i : Fin 3) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ LeptonSinglet) : e i l φ ∈ h.massWeightSubmodule (3 + 2 * n) := by
  rw [← LeptonSinglet.basis.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.e i n l j]) (by simp [Generators.weight])

/-- Any `bare` tower symbol lies in the mass-weight submodule of its weight. -/
lemma bare_mem_massWeightSubmodule (i : Fin 3) {n : ℕ} (l : Fin n → Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ (ConjModule LeptonSinglet)) : bare i l φ ∈ h.massWeightSubmodule (3 + 2 * n) := by
  rw [← LeptonSinglet.basis.conj.sum_dual_apply_smul_coord φ]
  simp only [map_sum, map_smul]
  refine Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ ?_
  simpa [generatorVal] using h.list_prod_mem_massWeightSubmodule
    (gl := [Generators.bare i n l j]) (by simp [Generators.weight])

/-- The gauge action carries a covariant generator into the mass-weight submodule
  of its weight. -/
lemma repGauge_generatorVal_mem (g : GaugeGroupI) (a : Generators) :
    repGauge g (h.generatorVal a) ∈ h.massWeightSubmodule a.weight := by
  cases a with
  | H n l j =>
    simp only [generatorVal]
    rw [h.isHiggsSector.H_equivariant g _ n l]
    exact h.H_mem_massWeightSubmodule l _
  | barH n l j =>
    simp only [generatorVal]
    rw [h.isHiggsSector.barH_equivariant g _ n l]
    exact h.barH_mem_massWeightSubmodule l _
  | F n l μ ν j =>
    simp only [generatorVal]
    rw [h.isGaugeSector.repGauge_F g l μ ν _]
    exact h.F_mem_massWeightSubmodule l μ ν _
  | d i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repGauge_d g i l _]
    exact h.d_mem_massWeightSubmodule i l _
  | bard i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repGauge_bard g i l _]
    exact h.bard_mem_massWeightSubmodule i l _
  | u i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repGauge_u g i l _]
    exact h.u_mem_massWeightSubmodule i l _
  | baru i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repGauge_baru g i l _]
    exact h.baru_mem_massWeightSubmodule i l _
  | Q i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repGauge_Q g i l _]
    exact h.Q_mem_massWeightSubmodule i l _
  | barQ i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repGauge_barQ g i l _]
    exact h.barQ_mem_massWeightSubmodule i l _
  | L i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repGauge_L g i l _]
    exact h.L_mem_massWeightSubmodule i l _
  | barL i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repGauge_barL g i l _]
    exact h.barL_mem_massWeightSubmodule i l _
  | e i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repGauge_e g i l _]
    exact h.e_mem_massWeightSubmodule i l _
  | bare i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repGauge_bare g i l _]
    exact h.bare_mem_massWeightSubmodule i l _

/-- The Lorentz action carries a covariant generator into the mass-weight submodule
  of its weight. -/
lemma repLorentz_generatorVal_mem (Λ : SL(2,ℂ)) (a : Generators) :
    repLorentz Λ (h.generatorVal a) ∈ h.massWeightSubmodule a.weight := by
  cases a with
  | H n l j =>
    simp only [generatorVal]
    rw [h.isHiggsSector.repLorentz_H Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.H_mem_massWeightSubmodule p _)
  | barH n l j =>
    simp only [generatorVal]
    rw [h.isHiggsSector.repLorentz_barH Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.barH_mem_massWeightSubmodule p _)
  | F n l μ ν j =>
    simp only [generatorVal]
    rw [h.isGaugeSector.repLorentz_F Λ n l μ ν _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (Submodule.sum_mem _ fun a _ => Submodule.smul_mem _ _
        (Submodule.sum_mem _ fun b _ => Submodule.smul_mem _ _
          (h.F_mem_massWeightSubmodule p a b _)))
  | d i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repLorentz_d i Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.d_mem_massWeightSubmodule i p _)
  | bard i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repLorentz_bard i Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.bard_mem_massWeightSubmodule i p _)
  | u i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repLorentz_u i Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.u_mem_massWeightSubmodule i p _)
  | baru i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repLorentz_baru i Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.baru_mem_massWeightSubmodule i p _)
  | Q i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repLorentz_Q i Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.Q_mem_massWeightSubmodule i p _)
  | barQ i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repLorentz_barQ i Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.barQ_mem_massWeightSubmodule i p _)
  | L i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repLorentz_L i Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.L_mem_massWeightSubmodule i p _)
  | barL i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repLorentz_barL i Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.barL_mem_massWeightSubmodule i p _)
  | e i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repLorentz_e i Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.e_mem_massWeightSubmodule i p _)
  | bare i n l j =>
    simp only [generatorVal]
    rw [h.isFermionSector.repLorentz_bare i Λ n l _]
    exact Submodule.sum_mem _ fun p _ => Submodule.smul_mem _ _
      (h.bare_mem_massWeightSubmodule i p _)

/-- The action `repGauge` preserves the mass-weight submodules. -/
lemma repGauge_mem_massWeightSubmodule {w : ℕ} {x : B} (g : GaugeGroupI)
    (hx : x ∈ h.massWeightSubmodule w) : repGauge g x ∈ h.massWeightSubmodule w := by
  rw [h.massWeightSubmodule_eq_span] at hx
  induction hx using Submodule.span_induction with
  | mem y hyw =>
    obtain ⟨gl, hglw, rfl⟩ := hyw
    subst hglw
    induction gl with
    | nil =>
      simp only [List.map_nil, List.prod_nil, List.sum_nil]
      rw [h.repGauge_one g]
      simpa using h.list_prod_mem_massWeightSubmodule (gl := ([] : List Generators)) rfl
    | cons a t ih =>
      simp only [List.map_cons, List.prod_cons, List.sum_cons]
      rw [h.repGauge_mul g]
      exact h.mul_mem_massWeightSubmodule (h.repGauge_generatorVal_mem g a) ih
  | zero => rw [map_zero]; exact Submodule.zero_mem _
  | add a b ha hb iha ihb => rw [map_add]; exact Submodule.add_mem _ iha ihb
  | smul c a ha iha => rw [map_smul]; exact Submodule.smul_mem _ _ iha

/-- The action `repLorentz` preserves the mass-weight submodules. -/
lemma repLorentz_mem_massWeightSubmodule {w : ℕ} {x : B} (Λ : SL(2,ℂ))
    (hx : x ∈ h.massWeightSubmodule w) : repLorentz Λ x ∈ h.massWeightSubmodule w := by
  rw [h.massWeightSubmodule_eq_span] at hx
  induction hx using Submodule.span_induction with
  | mem y hyw =>
    obtain ⟨gl, hglw, rfl⟩ := hyw
    subst hglw
    induction gl with
    | nil =>
      simp only [List.map_nil, List.prod_nil, List.sum_nil]
      rw [h.repLorentz_one Λ]
      simpa using h.list_prod_mem_massWeightSubmodule (gl := ([] : List Generators)) rfl
    | cons a t ih =>
      simp only [List.map_cons, List.prod_cons, List.sum_cons]
      rw [h.repLorentz_mul Λ]
      exact h.mul_mem_massWeightSubmodule (h.repLorentz_generatorVal_mem Λ a) ih
  | zero => rw [map_zero]; exact Submodule.zero_mem _
  | add a b ha hb iha ihb => rw [map_add]; exact Submodule.add_mem _ iha ihb
  | smul c a ha iha => rw [map_smul]; exact Submodule.smul_mem _ _ iha

/-- Components of pairwise distinct mass weights are independent: a vanishing sum
  of weight-homogeneous elements has vanishing terms. -/
lemma eq_zero_of_sum_massWeightSubmodule {n : ℕ} {w : Fin n → ℕ}
    (hw : Function.Injective w) {f : Fin n → B}
    (hf : ∀ i, f i ∈ h.massWeightSubmodule (w i)) (hsum : ∑ i, f i = 0) :
    ∀ i, f i = 0 := by
  intro i₀
  have hpoly := congrArg (fun z => Polynomial.coeff (massWeightPoly z) (w i₀)) hsum
  simp only [map_sum, Polynomial.finsetSum_coeff, map_zero, Polynomial.coeff_zero]
    at hpoly
  rw [Finset.sum_congr rfl (fun i _ => by
      rw [h.massWeightPoly_of_mem_massWeightSubmodule (hf i),
        Polynomial.coeff_monomial]),
    Finset.sum_eq_single i₀
      (fun i _ hne => if_neg fun hcontra => hne (hw hcontra))
      (by simp), if_pos rfl] at hpoly
  exact hpoly

/-- An invariant element decomposes into invariant weight components: if a gauge-
  and Lorentz-invariant `x` is the sum of components of pairwise distinct mass
  weights, every component is itself gauge and Lorentz invariant. -/
lemma invariant_of_eq_sum_massWeightSubmodule {n : ℕ} {x : B} {w : Fin n → ℕ}
    (hw : Function.Injective w) (f : Fin n → B) (hf : x = ∑ i, f i)
    (hx : ∀ i, f i ∈ h.massWeightSubmodule (w i))
    (hgauge : ∀ g, repGauge g x = x) (hlorentz : ∀ Λ, repLorentz Λ x = x) :
    ∀ i, (∀ g, repGauge g (f i) = f i) ∧ ∀ Λ, repLorentz Λ (f i) = f i := by
  have key : ∀ T : B →ₗ[ℂ] B, T x = x →
      (∀ i, T (f i) ∈ h.massWeightSubmodule (w i)) → ∀ i, T (f i) = f i := by
    intro T hTx hTf i₀
    have hzero : ∑ i, (T (f i) - f i) = 0 := by
      rw [Finset.sum_sub_distrib, ← map_sum, ← hf, hTx, sub_self]
    have hcomp := h.eq_zero_of_sum_massWeightSubmodule hw
      (f := fun i => T (f i) - f i)
      (fun i => Submodule.sub_mem _ (hTf i) (hx i)) hzero i₀
    exact sub_eq_zero.mp hcomp
  intro i
  constructor
  · intro g
    exact key (repGauge g) (hgauge g)
      (fun i => h.repGauge_mem_massWeightSubmodule g (hx i)) i
  · intro Λ
    exact key (repLorentz Λ) (hlorentz Λ)
      (fun i => h.repLorentz_mem_massWeightSubmodule Λ (hx i)) i

/-- The reduction of questions on invariants to invariants within
  mass weight submodules. -/
lemma invaraint_of_eq_sum_massWeightSubmodule {n : ℕ} {x : B}
    (f : Fin n → B) (hf : x = ∑ i, f i) (hx : ∀ i, f i ∈ h.massWeightSubmodule i.val)
    (hgauge : ∀ g, repGauge g x = x) (hlorentz : ∀ Λ, repLorentz Λ x = x) :
    ∀ i, (∀ g, repGauge g (f i) = f i) ∧ ∀ Λ, repLorentz Λ (f i) = f i :=
  h.invariant_of_eq_sum_massWeightSubmodule Fin.val_injective f hf hx hgauge hlorentz

end IsCovStandardModel

end StandardModel
