/-
Copyright (c) 2026 Nathaneal Sajan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathaneal Sajan
-/
module

public import Physlib.Mathematics.SymmetricAlgebra
public import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
public import Mathlib.LinearAlgebra.Complex.Module
/-!
# The local field algebra and its mapping-out universal property

## i. Overview

The local field algebra of a field theory is the algebra in which its local expressions,
such as Lagrangian terms, currents and field strengths, live. It is built from three
generator spaces, a complex space `Ef` of fermionic derivative symbols, a complex space
`Eb` of bosonic matter derivative symbols, and a real space `EA` of connection derivative
symbols. Writing `Λ` for the exterior algebra and `Sym` for the symmetric algebra, it is

`LocalFieldAlgebra Ef Eb EA = (Λ_ℂ Ef ⊗[ℂ] Sym_ℂ Eb) ⊗[ℂ] (ℂ ⊗[ℝ] Sym_ℝ EA)`,

the shape of `StandardModel.JetAlgebra` with the Standard Model's species replaced by
arbitrary generator spaces. All fermionic generators enter a single exterior algebra, so
that symbols of different species anticommute with each other and not merely with
themselves. The connection generators are real and are complexified once, a connection
being a real object whose algebra of polynomials is then extended to complex coefficients.
Nothing here is finite-dimensional, the generator spaces being spaces of ordinary
derivative symbols of arbitrary order.

This file proves the algebra's mapping-out universal property. An `Assignment` of the
three generator families in an associative unital complex algebra `B`, not assumed
commutative, subject to exactly the relations the generators themselves satisfy, extends
to a unique complex algebra homomorphism `LocalFieldAlgebra Ef Eb EA →ₐ[ℂ] B`. That is
what makes the carrier canonical rather than merely a convenient tensor product, and it is
what a realization of a field theory in an abstract algebra is built from.

The construction has one subtlety. Mathlib's `SymmetricAlgebra.lift` requires a
commutative target, while `B` need not be commutative. The bosonic and connection
generators are therefore lifted into `Assignment.evenSubalgebra`, the subalgebra of `B`
generated by their images, which the hypotheses make commutative, and the result is
composed with its inclusion. The connection factor is then extended from `ℝ` to `ℂ` by
`AlgHom.liftEquiv`, which, unlike the symmetric lift, does accept a noncommutative target.
Uniqueness likewise cannot use `SymmetricAlgebra.algHom_ext`, whose target is commutative;
it uses generation instead, through `adjoin_generators_eq_top`.

## ii. Key results

- `LocalFieldAlgebra` : the algebra, with the generator maps `ιFermion`, `ιBoson`,
  `ιConnection` and the relations they satisfy.
- `LocalFieldAlgebra.adjoin_generators_eq_top` : the algebra is generated by the three
  families.
- `LocalFieldAlgebra.Assignment` : a compatible assignment of the three generator families
  in an arbitrary complex algebra.
- `LinearMap.mul_swap_of_mul_self`, `LocalFieldAlgebra.ιFermion_mul_swap`,
  `LocalFieldAlgebra.Assignment.fermion_mul_swap` : polarization, by which the square-zero
  relation on the whole fermionic generator space already carries anticommutation across
  species.
- `LocalFieldAlgebra.Assignment.lift` : the induced algebra homomorphism, with the
  computation lemmas `lift_ιFermion`, `lift_ιBoson` and `lift_ιConnection`.
- `LocalFieldAlgebra.algHom_ext` : two algebra maps agreeing on the generators are equal.
- `LocalFieldAlgebra.Assignment.existsUnique_algHom` : the mapping-out universal
  property.
- `LocalFieldAlgebra.liftEquiv` : compatible assignments in `B` are the same thing as
  algebra maps into `B`.
- `LocalFieldAlgebra.Assignment.range_lift` : the range is the subalgebra generated by the
  three images.

## iii. Table of contents

- A. Generation, commutation and tensor products
  - A.1. Consequences of a generating set
  - A.2. Generating a tensor product
  - A.3. Polarization
- B. The local field algebra
  - B.1. The factor inclusions and the generators
  - B.2. The relations satisfied by the generators
  - B.3. Generation by the three families
- C. Compatible generator assignments
  - C.1. Polarization of the fermionic assignment
  - C.2. The commutative subalgebra of even images
  - C.3. The three factor maps
  - C.4. Commutation of the factor images
- D. The mapping-out universal property
  - D.1. The induced algebra homomorphism
  - D.2. Uniqueness
  - D.3. Assignments are the same thing as algebra maps
  - D.4. The range of the induced map

-/

@[expose] public section

open TensorProduct

/-!

## A. Generation, commutation and tensor products

Facts about algebras generated by a set, stated for a general base ring because they carry
no physics. They are the minimal API needed to lift into, and to prove uniqueness into, a
target that is not assumed commutative.

-/

namespace Algebra

section Generation

variable {R A B : Type*} [CommSemiring R] [Semiring A] [Algebra R A] [Semiring B]
  [Algebra R B]

/-!

### A.1. Consequences of a generating set

-/

/-- If `s` generates `A` and a subalgebra `S` of `B` contains the image of `s`, then it
  contains the whole range of an algebra map `A →ₐ[R] B`. -/
lemma range_le_of_adjoin_eq_top {s : Set A} (hs : Algebra.adjoin R s = ⊤) (φ : A →ₐ[R] B)
    {S : Subalgebra R B} (h : ∀ x ∈ s, φ x ∈ S) : φ.range ≤ S := by
  rw [← Algebra.map_top, ← hs, AlgHom.map_adjoin]
  exact Algebra.adjoin_le (Set.image_subset_iff.mpr h)

/-- If `s` generates `A` and `y` commutes with the image of `s` under an algebra map, then
  `y` commutes with the whole image. This is what extends a commutation relation from
  generators to a factor of a tensor product. -/
lemma commute_of_adjoin_eq_top {s : Set A} (hs : Algebra.adjoin R s = ⊤) (φ : A →ₐ[R] B)
    {y : B} (h : ∀ x ∈ s, Commute (φ x) y) (a : A) : Commute (φ a) y := by
  have ha : a ∈ Algebra.adjoin R s := hs ▸ Algebra.mem_top
  induction ha using Algebra.adjoin_induction with
  | mem x hx => exact h x hx
  | algebraMap r => rw [AlgHom.commutes]; exact Algebra.commute_algebraMap_left r y
  | add u v _ _ hu hv => rw [map_add]; exact hu.add_left hv
  | mul u v _ _ hu hv => rw [map_mul]; exact hu.mul_left hv

end Generation

namespace TensorProduct

/-!

### A.2. Generating a tensor product

-/

section Factors

variable {R A B : Type*} [CommSemiring R] [Semiring A] [Algebra R A] [Semiring B]
  [Algebra R B]

/-- A subalgebra of `A ⊗[R] B` containing every `a ⊗ₜ 1` and every `1 ⊗ₜ b` contains
  everything, since a pure tensor is the product of the two. -/
lemma mem_of_tmul_one_of_one_tmul {S : Subalgebra R (A ⊗[R] B)}
    (hA : ∀ a : A, a ⊗ₜ[R] (1 : B) ∈ S) (hB : ∀ b : B, (1 : A) ⊗ₜ[R] b ∈ S)
    (x : A ⊗[R] B) : x ∈ S := by
  induction x using _root_.TensorProduct.induction_on with
  | zero => exact zero_mem _
  | add u v hu hv => exact add_mem hu hv
  | tmul a b =>
    have h : a ⊗ₜ[R] b = (a ⊗ₜ[R] (1 : B)) * ((1 : A) ⊗ₜ[R] b) := by
      rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul]
    exact h ▸ mul_mem (hA a) (hB b)

/-- A subalgebra of `A ⊗[R] B` containing every `a ⊗ₜ 1` and every `1 ⊗ₜ b` is the whole
  algebra. -/
lemma eq_top_of_tmul_one_of_one_tmul {S : Subalgebra R (A ⊗[R] B)}
    (hA : ∀ a : A, a ⊗ₜ[R] (1 : B) ∈ S) (hB : ∀ b : B, (1 : A) ⊗ₜ[R] b ∈ S) : S = ⊤ :=
  _root_.Algebra.eq_top_iff.mpr fun x => mem_of_tmul_one_of_one_tmul hA hB x

end Factors

section BaseChange

variable {R A : Type*} [CommSemiring R] [Semiring A] [Algebra R A]
variable (S : Type*) [CommSemiring S] [Algebra R S] (s : Set A)

/-- Extension of scalars on the elements `1 ⊗ₜ a`. If `s` generates `A` over `R` then
  every `1 ⊗ₜ a` lies in the `S`-subalgebra of `S ⊗[R] A` generated by `1 ⊗ₜ s`. -/
lemma mem_adjoin_one_tmul (hs : Algebra.adjoin R s = ⊤) (a : A) :
    (1 : S) ⊗ₜ[R] a ∈ Algebra.adjoin S ((fun a : A => (1 : S) ⊗ₜ[R] a) '' s) := by
  have ha : a ∈ Algebra.adjoin R s := hs ▸ Algebra.mem_top
  induction ha using Algebra.adjoin_induction with
  | mem x hx => exact Algebra.subset_adjoin ⟨x, hx, rfl⟩
  | algebraMap r =>
    have h : (1 : S) ⊗ₜ[R] (algebraMap R A r)
        = algebraMap S (S ⊗[R] A) (algebraMap R S r) := by
      simp [Algebra.algebraMap_eq_smul_one, _root_.TensorProduct.tmul_smul,
        _root_.TensorProduct.smul_tmul', Algebra.TensorProduct.one_def]
    rw [h]
    exact Subalgebra.algebraMap_mem _ _
  | add x y _ _ hx hy => rw [_root_.TensorProduct.tmul_add]; exact add_mem hx hy
  | mul x y _ _ hx hy =>
    have h : (1 : S) ⊗ₜ[R] (x * y) = ((1 : S) ⊗ₜ[R] x) * ((1 : S) ⊗ₜ[R] y) := by
      rw [Algebra.TensorProduct.tmul_mul_tmul, one_mul]
    rw [h]
    exact mul_mem hx hy

/-- Every element of a base change lies in the subalgebra generated by the `1 ⊗ₜ s`. -/
lemma mem_adjoin_one_tmul_of_generates (hs : Algebra.adjoin R s = ⊤) (x : S ⊗[R] A) :
    x ∈ Algebra.adjoin S ((fun a : A => (1 : S) ⊗ₜ[R] a) '' s) := by
  induction x using _root_.TensorProduct.induction_on with
  | zero => exact zero_mem _
  | add u v hu hv => exact add_mem hu hv
  | tmul z a =>
    have h : z ⊗ₜ[R] a = z • ((1 : S) ⊗ₜ[R] a) := by
      rw [_root_.TensorProduct.smul_tmul', smul_eq_mul, mul_one]
    exact h ▸ Subalgebra.smul_mem _ (mem_adjoin_one_tmul S s hs a) z

/-- Extension of scalars preserves generation. If `s` generates `A` over `R` then the
  elements `1 ⊗ₜ a`, for `a ∈ s`, generate `S ⊗[R] A` over `S`. -/
lemma adjoin_one_tmul_eq_top (hs : Algebra.adjoin R s = ⊤) :
    Algebra.adjoin S ((fun a : A => (1 : S) ⊗ₜ[R] a) '' s)
      = (⊤ : Subalgebra S (S ⊗[R] A)) :=
  _root_.Algebra.eq_top_iff.mpr fun x => mem_adjoin_one_tmul_of_generates S s hs x

end BaseChange

end TensorProduct

end Algebra

/-!

### A.3. Polarization

-/

/-- Polarization. If every value of a linear map into a ring squares to zero, then any two
  values anticommute. Applied to a space of fermionic generators, this is what makes the
  single relation "every vector squares to zero" carry the anticommutation of distinct
  generators, including generators of different species, which sit in the same space. -/
lemma LinearMap.mul_swap_of_mul_self {R M B : Type*} [CommSemiring R] [AddCommMonoid M]
    [Module R M] [Ring B] [Algebra R B] (f : M →ₗ[R] B) (h : ∀ v, f v * f v = 0) (v w : M) :
    f v * f w = -(f w * f v) := by
  have hvw := h (v + w)
  rw [map_add, add_mul, mul_add, mul_add, h v, h w, zero_add, add_zero] at hvw
  exact eq_neg_of_add_eq_zero_left hvw

/-!

## B. The local field algebra

-/

variable (Ef Eb EA : Type*) [AddCommGroup Ef] [Module ℂ Ef] [AddCommGroup Eb]
  [Module ℂ Eb] [AddCommGroup EA] [Module ℝ EA]

/-- The local field algebra on a complex space `Ef` of fermionic generators, a complex
  space `Eb` of bosonic generators and a real space `EA` of connection generators. It is
  the exterior algebra of the fermions tensored with the symmetric algebra of the bosons,
  tensored with the complexified symmetric algebra of the connection. A local expression
  of a field theory, such as a Lagrangian term or a current, is an element of it.

  All fermionic generators share one exterior algebra, so that symbols of different species
  anticommute; separate exterior algebras joined by an ordinary tensor product would make
  them commute instead. The factor order matches `StandardModel.JetAlgebra`. -/
abbrev LocalFieldAlgebra : Type _ :=
  (ExteriorAlgebra ℂ Ef ⊗[ℂ] SymmetricAlgebra ℂ Eb) ⊗[ℂ] (ℂ ⊗[ℝ] SymmetricAlgebra ℝ EA)

namespace LocalFieldAlgebra

/-!

### B.1. The factor inclusions and the generators

-/

/-- The inclusion of the fermionic factor. -/
noncomputable def includeFermion : ExteriorAlgebra ℂ Ef →ₐ[ℂ] LocalFieldAlgebra Ef Eb EA :=
  (Algebra.TensorProduct.includeLeft
    (R := ℂ) (S := ℂ) (B := ℂ ⊗[ℝ] SymmetricAlgebra ℝ EA)).comp
    Algebra.TensorProduct.includeLeft

/-- The inclusion of the bosonic factor. -/
noncomputable def includeBoson : SymmetricAlgebra ℂ Eb →ₐ[ℂ] LocalFieldAlgebra Ef Eb EA :=
  (Algebra.TensorProduct.includeLeft
    (R := ℂ) (S := ℂ) (B := ℂ ⊗[ℝ] SymmetricAlgebra ℝ EA)).comp
    Algebra.TensorProduct.includeRight

/-- The inclusion of the complexified connection factor. -/
noncomputable def includeConnection :
    (ℂ ⊗[ℝ] SymmetricAlgebra ℝ EA) →ₐ[ℂ] LocalFieldAlgebra Ef Eb EA :=
  Algebra.TensorProduct.includeRight

/-- The fermionic generators of the local field algebra. -/
noncomputable def ιFermion : Ef →ₗ[ℂ] LocalFieldAlgebra Ef Eb EA :=
  (includeFermion Ef Eb EA).toLinearMap ∘ₗ ExteriorAlgebra.ι ℂ

/-- The bosonic generators of the local field algebra. -/
noncomputable def ιBoson : Eb →ₗ[ℂ] LocalFieldAlgebra Ef Eb EA :=
  (includeBoson Ef Eb EA).toLinearMap ∘ₗ SymmetricAlgebra.ι ℂ Eb

/-- The connection generators of the local field algebra. They are only real-linear, the
  connection generator space being a real vector space, complexified inside the algebra. -/
noncomputable def ιConnection : EA →ₗ[ℝ] LocalFieldAlgebra Ef Eb EA :=
  ((includeConnection Ef Eb EA).restrictScalars ℝ).toLinearMap ∘ₗ
    (Algebra.TensorProduct.includeRight
      (R := ℝ) (A := ℂ) (B := SymmetricAlgebra ℝ EA)).toLinearMap ∘ₗ
    SymmetricAlgebra.ι ℝ EA

variable {Ef Eb EA}

lemma ιFermion_apply (v : Ef) :
    ιFermion Ef Eb EA v
      = (ExteriorAlgebra.ι ℂ v ⊗ₜ[ℂ] (1 : SymmetricAlgebra ℂ Eb))
          ⊗ₜ[ℂ] (1 : ℂ ⊗[ℝ] SymmetricAlgebra ℝ EA) := rfl

lemma ιBoson_apply (v : Eb) :
    ιBoson Ef Eb EA v
      = ((1 : ExteriorAlgebra ℂ Ef) ⊗ₜ[ℂ] SymmetricAlgebra.ι ℂ Eb v)
          ⊗ₜ[ℂ] (1 : ℂ ⊗[ℝ] SymmetricAlgebra ℝ EA) := rfl

lemma ιConnection_apply (v : EA) :
    ιConnection Ef Eb EA v
      = (1 : ExteriorAlgebra ℂ Ef ⊗[ℂ] SymmetricAlgebra ℂ Eb)
          ⊗ₜ[ℂ] ((1 : ℂ) ⊗ₜ[ℝ] SymmetricAlgebra.ι ℝ EA v) := rfl

/-!

### B.2. The relations satisfied by the generators

These are the relations a compatible assignment is asked to reproduce, namely Fermi
statistics on the fermionic generators and commutativity everywhere else.

-/

/-- A fermionic generator squares to zero. This is Fermi statistics, in the form that
  implies anticommutation across the whole fermionic generator space by polarization. -/
@[simp]
lemma ιFermion_mul_self (v : Ef) :
    ιFermion Ef Eb EA v * ιFermion Ef Eb EA v = 0 := by
  simp [ιFermion_apply, Algebra.TensorProduct.tmul_mul_tmul]

/-- Two fermionic generators anticommute, including generators of two different species,
  which share the one exterior algebra. This is not an extra relation, being
  `ιFermion_mul_self` polarized. -/
lemma ιFermion_mul_swap (v w : Ef) :
    ιFermion Ef Eb EA v * ιFermion Ef Eb EA w
      = -(ιFermion Ef Eb EA w * ιFermion Ef Eb EA v) := by
  have h : ExteriorAlgebra.ι ℂ v * ExteriorAlgebra.ι ℂ w
      = -(ExteriorAlgebra.ι ℂ w * ExteriorAlgebra.ι (R := ℂ) v) :=
    eq_neg_of_add_eq_zero_left (ExteriorAlgebra.ι_add_mul_swap (R := ℂ) v w)
  simp [ιFermion_apply, Algebra.TensorProduct.tmul_mul_tmul, h, TensorProduct.neg_tmul]

/-- Two bosonic generators commute. -/
lemma ιBoson_commute (v w : Eb) :
    Commute (ιBoson Ef Eb EA v) (ιBoson Ef Eb EA w) := by
  simp [Commute, SemiconjBy, ιBoson_apply, Algebra.TensorProduct.tmul_mul_tmul, mul_comm]

/-- Two connection generators commute. -/
lemma ιConnection_commute (v w : EA) :
    Commute (ιConnection Ef Eb EA v) (ιConnection Ef Eb EA w) := by
  simp [Commute, SemiconjBy, ιConnection_apply, Algebra.TensorProduct.tmul_mul_tmul,
    mul_comm]

/-- A bosonic generator commutes with a connection generator. -/
lemma ιBoson_commute_ιConnection (v : Eb) (w : EA) :
    Commute (ιBoson Ef Eb EA v) (ιConnection Ef Eb EA w) := by
  simp [Commute, SemiconjBy, ιBoson_apply, ιConnection_apply,
    Algebra.TensorProduct.tmul_mul_tmul, mul_comm]

/-- A bosonic generator commutes with a fermionic generator, bosons being even. -/
lemma ιBoson_commute_ιFermion (v : Eb) (w : Ef) :
    Commute (ιBoson Ef Eb EA v) (ιFermion Ef Eb EA w) := by
  simp [Commute, SemiconjBy, ιBoson_apply, ιFermion_apply,
    Algebra.TensorProduct.tmul_mul_tmul, mul_comm]

/-- A connection generator commutes with a fermionic generator, the connection being even. -/
lemma ιConnection_commute_ιFermion (v : EA) (w : Ef) :
    Commute (ιConnection Ef Eb EA v) (ιFermion Ef Eb EA w) := by
  simp [Commute, SemiconjBy, ιConnection_apply, ιFermion_apply,
    Algebra.TensorProduct.tmul_mul_tmul, mul_comm]

variable (Ef Eb EA)

/-!

### B.3. Generation by the three families

-/

/-- The generators of the local field algebra, the images of the three generator spaces. -/
noncomputable def generators : Set (LocalFieldAlgebra Ef Eb EA) :=
  Set.range (ιFermion Ef Eb EA) ∪ Set.range (ιBoson Ef Eb EA)
    ∪ Set.range (ιConnection Ef Eb EA)

/-- The matter factor `Λ_ℂ Ef ⊗[ℂ] Sym_ℂ Eb` is generated by the images of the fermionic
  and bosonic generators. -/
lemma adjoin_matter_generators_eq_top :
    Algebra.adjoin ℂ
        (Set.range (fun v : Ef =>
            ExteriorAlgebra.ι ℂ v ⊗ₜ[ℂ] (1 : SymmetricAlgebra ℂ Eb))
          ∪ Set.range (fun v : Eb =>
            (1 : ExteriorAlgebra ℂ Ef) ⊗ₜ[ℂ] SymmetricAlgebra.ι ℂ Eb v)) = ⊤ := by
  refine Algebra.TensorProduct.eq_top_of_tmul_one_of_one_tmul (fun a => ?_) (fun b => ?_)
  · exact Algebra.range_le_of_adjoin_eq_top CliffordAlgebra.adjoin_range_ι
      (Algebra.TensorProduct.includeLeft (R := ℂ) (S := ℂ) (B := SymmetricAlgebra ℂ Eb))
      (by rintro _ ⟨v, rfl⟩; exact Algebra.subset_adjoin (Or.inl ⟨v, rfl⟩)) ⟨a, rfl⟩
  · exact Algebra.range_le_of_adjoin_eq_top SymmetricAlgebra.adjoin_range_ι
      (Algebra.TensorProduct.includeRight (R := ℂ) (A := ExteriorAlgebra ℂ Ef))
      (by rintro _ ⟨v, rfl⟩; exact Algebra.subset_adjoin (Or.inr ⟨v, rfl⟩)) ⟨b, rfl⟩

/-- The local field algebra is generated by its three families of generators. Every
  element is a polynomial in the fermionic, bosonic and connection symbols; this is the
  algebraic form of "every local expression is a polynomial in the fields and their
  derivatives", and it is what forces uniqueness in the universal property. -/
lemma adjoin_generators_eq_top :
    Algebra.adjoin ℂ (generators Ef Eb EA) = ⊤ := by
  refine Algebra.TensorProduct.eq_top_of_tmul_one_of_one_tmul (fun m => ?_) (fun y => ?_)
  · refine Algebra.range_le_of_adjoin_eq_top (adjoin_matter_generators_eq_top Ef Eb)
      (Algebra.TensorProduct.includeLeft (R := ℂ) (S := ℂ)
        (B := ℂ ⊗[ℝ] SymmetricAlgebra ℝ EA)) ?_ ⟨m, rfl⟩
    rintro _ (⟨v, rfl⟩ | ⟨v, rfl⟩)
    · exact Algebra.subset_adjoin (Or.inl (Or.inl ⟨v, rfl⟩))
    · exact Algebra.subset_adjoin (Or.inl (Or.inr ⟨v, rfl⟩))
  · refine Algebra.range_le_of_adjoin_eq_top
      (Algebra.TensorProduct.adjoin_one_tmul_eq_top ℂ (Set.range (SymmetricAlgebra.ι ℝ EA))
        SymmetricAlgebra.adjoin_range_ι)
      (Algebra.TensorProduct.includeRight (R := ℂ)
        (A := ExteriorAlgebra ℂ Ef ⊗[ℂ] SymmetricAlgebra ℂ Eb)) ?_ ⟨y, rfl⟩
    rintro _ ⟨_, ⟨v, rfl⟩, rfl⟩
    exact Algebra.subset_adjoin (Or.inr ⟨v, rfl⟩)

/-- Two algebra maps out of the local field algebra agreeing on the generators are
  equal. The target is not assumed commutative, so this cannot be deduced from
  `SymmetricAlgebra.algHom_ext`; it comes from generation. -/
lemma algHom_ext {B : Type*} [Ring B] [Algebra ℂ B]
    {Φ Ψ : LocalFieldAlgebra Ef Eb EA →ₐ[ℂ] B}
    (hf : ∀ v, Φ (ιFermion Ef Eb EA v) = Ψ (ιFermion Ef Eb EA v))
    (hb : ∀ v, Φ (ιBoson Ef Eb EA v) = Ψ (ιBoson Ef Eb EA v))
    (ha : ∀ v, Φ (ιConnection Ef Eb EA v) = Ψ (ιConnection Ef Eb EA v)) : Φ = Ψ :=
  AlgHom.ext_of_adjoin_eq_top (adjoin_generators_eq_top Ef Eb EA) (by
    rintro _ ((⟨v, rfl⟩ | ⟨v, rfl⟩) | ⟨v, rfl⟩)
    exacts [hf v, hb v, ha v])

/-!

## C. Compatible generator assignments

-/

/-- A compatible assignment of the generators of the local field algebra in a complex
  algebra `B`, given by three linear maps subject to exactly the relations of section B.2.
  The algebra `B` is not assumed commutative, and the commutation conditions are imposed
  only between the assigned images, not between an image and an arbitrary element of `B`.

  The condition `fermion_mul_self` is imposed on every vector of `Ef`, including sums
  across species; over `ℂ` it implies, by polarization, that distinct fermionic images
  anticommute. -/
@[ext]
structure Assignment (B : Type*) [Ring B] [Algebra ℂ B] where
  /-- The images of the fermionic generators. -/
  fermion : Ef →ₗ[ℂ] B
  /-- The images of the bosonic generators. -/
  boson : Eb →ₗ[ℂ] B
  /-- The images of the connection generators; only real-linear, as the connection
    generator space is real. -/
  connection : EA →ₗ[ℝ] B
  /-- Fermi statistics, every fermionic image squaring to zero. -/
  fermion_mul_self : ∀ v, fermion v * fermion v = 0
  /-- Bosonic images commute pairwise. -/
  boson_commute : ∀ v w, Commute (boson v) (boson w)
  /-- Connection images commute pairwise. -/
  connection_commute : ∀ v w, Commute (connection v) (connection w)
  /-- Bosonic and connection images commute with each other. -/
  boson_commute_connection : ∀ v w, Commute (boson v) (connection w)
  /-- Bosonic images commute with fermionic images. -/
  boson_commute_fermion : ∀ v w, Commute (boson v) (fermion w)
  /-- Connection images commute with fermionic images. -/
  connection_commute_fermion : ∀ v w, Commute (connection v) (fermion w)

section Assignments

namespace Assignment

variable {Ef Eb EA}
variable {B : Type*} [Ring B] [Algebra ℂ B] (d : Assignment Ef Eb EA B)

/-!

### C.1. Polarization of the fermionic assignment

-/

/-- The images of two fermionic generators anticommute. Only `fermion_mul_self` is
  assumed, and only vector by vector; because it is assumed on the whole of `Ef`, including
  sums across species, polarization already yields the cross-species anticommutation. So
  demanding anticommutation as a separate field of `Assignment` would be redundant. -/
lemma fermion_mul_swap (v w : Ef) :
    d.fermion v * d.fermion w = -(d.fermion w * d.fermion v) :=
  d.fermion.mul_swap_of_mul_self d.fermion_mul_self v w

/-!

### C.2. The commutative subalgebra of even images

-/

/-- The even generator images, the bosonic and connection images together. -/
def evenGenerators : Set B := Set.range d.boson ∪ Set.range d.connection

/-- The commutative subalgebra of `B` generated by the even images. The bosonic and
  connection assignments are lifted into it, because `SymmetricAlgebra.lift` requires a
  commutative target while `B` itself need not be commutative. -/
def evenSubalgebra : Subalgebra ℂ B := Algebra.adjoin ℂ d.evenGenerators

instance : IsMulCommutative d.evenSubalgebra := by
  refine Algebra.isMulCommutative_adjoin ℂ ?_
  rintro x (⟨v, rfl⟩ | ⟨v, rfl⟩) y (⟨w, rfl⟩ | ⟨w, rfl⟩)
  · exact d.boson_commute v w
  · exact d.boson_commute_connection v w
  · exact (d.boson_commute_connection w v).symm
  · exact d.connection_commute v w

open scoped IsMulCommutative

/-- The bosonic assignment, corestricted to the commutative subalgebra of even images. -/
def bosonGenerator : Eb →ₗ[ℂ] d.evenSubalgebra where
  toFun v := ⟨d.boson v, Algebra.subset_adjoin (Or.inl ⟨v, rfl⟩)⟩
  map_add' v w := Subtype.ext (by simp)
  map_smul' c v := Subtype.ext (by simp)

/-- The connection assignment, corestricted to the commutative subalgebra of even
  images. -/
def connectionGenerator : EA →ₗ[ℝ] d.evenSubalgebra where
  toFun v := ⟨d.connection v, Algebra.subset_adjoin (Or.inr ⟨v, rfl⟩)⟩
  map_add' v w := Subtype.ext (by simp)
  map_smul' c v := Subtype.ext (by simp)

/-!

### C.3. The three factor maps

-/

/-- The algebra map out of the fermionic factor, the exterior lift of the fermionic
  assignment, which already accepts an associative, possibly noncommutative, target. -/
noncomputable def fermionHom : ExteriorAlgebra ℂ Ef →ₐ[ℂ] B :=
  ExteriorAlgebra.lift ℂ ⟨d.fermion, d.fermion_mul_self⟩

/-- The algebra map out of the bosonic factor, the symmetric lift into the commutative
  subalgebra of even images, followed by its inclusion. -/
noncomputable def bosonHom : SymmetricAlgebra ℂ Eb →ₐ[ℂ] B :=
  d.evenSubalgebra.val.comp (SymmetricAlgebra.lift d.bosonGenerator)

/-- The real algebra map out of the real connection factor. -/
noncomputable def connectionHomReal : SymmetricAlgebra ℝ EA →ₐ[ℝ] B :=
  (d.evenSubalgebra.val.restrictScalars ℝ).comp
    (SymmetricAlgebra.lift d.connectionGenerator)

/-- The algebra map out of the complexified connection factor, obtained from
  `connectionHomReal` by the universal property of extension of scalars, which, unlike the
  symmetric lift, accepts a noncommutative target. -/
noncomputable def connectionHom : (ℂ ⊗[ℝ] SymmetricAlgebra ℝ EA) →ₐ[ℂ] B :=
  AlgHom.liftEquiv ℝ ℂ _ B d.connectionHomReal

@[simp]
lemma fermionHom_ι (v : Ef) : d.fermionHom (ExteriorAlgebra.ι ℂ v) = d.fermion v :=
  ExteriorAlgebra.lift_ι_apply (R := ℂ) d.fermion d.fermion_mul_self v

@[simp]
lemma bosonHom_ι (v : Eb) : d.bosonHom (SymmetricAlgebra.ι ℂ Eb v) = d.boson v := by
  simp [bosonHom, bosonGenerator]

@[simp]
lemma connectionHomReal_ι (v : EA) :
    d.connectionHomReal (SymmetricAlgebra.ι ℝ EA v) = d.connection v := by
  simp [connectionHomReal, connectionGenerator]

@[simp]
lemma connectionHom_tmul (z : ℂ) (p : SymmetricAlgebra ℝ EA) :
    d.connectionHom (z ⊗ₜ[ℝ] p) = z • d.connectionHomReal p := rfl

/-!

### C.4. Commutation of the factor images

The tensor-product lifts need commutation between whole factor images, which the
hypotheses supply only on generators. `Algebra.commute_of_adjoin_eq_top` propagates it.

-/

lemma fermionHom_commute_bosonHom (x : ExteriorAlgebra ℂ Ef) (y : SymmetricAlgebra ℂ Eb) :
    Commute (d.fermionHom x) (d.bosonHom y) := by
  refine Algebra.commute_of_adjoin_eq_top CliffordAlgebra.adjoin_range_ι d.fermionHom ?_ x
  rintro _ ⟨v, rfl⟩
  refine (Algebra.commute_of_adjoin_eq_top SymmetricAlgebra.adjoin_range_ι
    d.bosonHom ?_ y).symm
  rintro _ ⟨w, rfl⟩
  simpa using d.boson_commute_fermion w v

lemma fermionHom_commute_connectionHom (x : ExteriorAlgebra ℂ Ef)
    (y : ℂ ⊗[ℝ] SymmetricAlgebra ℝ EA) :
    Commute (d.fermionHom x) (d.connectionHom y) := by
  refine Algebra.commute_of_adjoin_eq_top CliffordAlgebra.adjoin_range_ι d.fermionHom ?_ x
  rintro _ ⟨v, rfl⟩
  induction y using TensorProduct.induction_on with
  | zero => simp
  | add u w hu hw => rw [map_add]; exact hu.add_right hw
  | tmul z p =>
    rw [connectionHom_tmul]
    refine Commute.smul_right ?_ z
    refine (Algebra.commute_of_adjoin_eq_top SymmetricAlgebra.adjoin_range_ι
      d.connectionHomReal ?_ p).symm
    rintro _ ⟨w, rfl⟩
    simpa using d.connection_commute_fermion w v

lemma bosonHom_commute_connectionHom (x : SymmetricAlgebra ℂ Eb)
    (y : ℂ ⊗[ℝ] SymmetricAlgebra ℝ EA) :
    Commute (d.bosonHom x) (d.connectionHom y) := by
  refine Algebra.commute_of_adjoin_eq_top SymmetricAlgebra.adjoin_range_ι d.bosonHom ?_ x
  rintro _ ⟨v, rfl⟩
  induction y using TensorProduct.induction_on with
  | zero => simp
  | add u w hu hw => rw [map_add]; exact hu.add_right hw
  | tmul z p =>
    rw [connectionHom_tmul]
    refine Commute.smul_right ?_ z
    refine (Algebra.commute_of_adjoin_eq_top SymmetricAlgebra.adjoin_range_ι
      d.connectionHomReal ?_ p).symm
    rintro _ ⟨w, rfl⟩
    simpa using (d.boson_commute_connection v w).symm

/-!

## D. The mapping-out universal property

-/

/-!

### D.1. The induced algebra homomorphism

-/

/-- The algebra map out of the matter factor `Λ_ℂ Ef ⊗[ℂ] Sym_ℂ Eb`. -/
noncomputable def matterHom :
    (ExteriorAlgebra ℂ Ef ⊗[ℂ] SymmetricAlgebra ℂ Eb) →ₐ[ℂ] B :=
  Algebra.TensorProduct.lift d.fermionHom d.bosonHom d.fermionHom_commute_bosonHom

lemma matterHom_commute_connectionHom
    (x : ExteriorAlgebra ℂ Ef ⊗[ℂ] SymmetricAlgebra ℂ Eb)
    (y : ℂ ⊗[ℝ] SymmetricAlgebra ℝ EA) :
    Commute (d.matterHom x) (d.connectionHom y) := by
  induction x using TensorProduct.induction_on with
  | zero => simp
  | add u w hu hw => rw [map_add]; exact hu.add_left hw
  | tmul a b =>
    rw [matterHom, Algebra.TensorProduct.lift_tmul]
    exact (d.fermionHom_commute_connectionHom a y).mul_left
      (d.bosonHom_commute_connectionHom b y)

/-- The algebra homomorphism induced by a compatible assignment. -/
noncomputable def lift : LocalFieldAlgebra Ef Eb EA →ₐ[ℂ] B :=
  Algebra.TensorProduct.lift d.matterHom d.connectionHom d.matterHom_commute_connectionHom

@[simp]
lemma lift_ιFermion (v : Ef) : d.lift (ιFermion Ef Eb EA v) = d.fermion v := by
  simp [lift, ιFermion_apply, matterHom]

@[simp]
lemma lift_ιBoson (v : Eb) : d.lift (ιBoson Ef Eb EA v) = d.boson v := by
  simp [lift, ιBoson_apply, matterHom]

@[simp]
lemma lift_ιConnection (v : EA) : d.lift (ιConnection Ef Eb EA v) = d.connection v := by
  simp [lift, ιConnection_apply, matterHom]

/-!

### D.2. Uniqueness

-/

/-- The mapping-out universal property of the local field algebra. A compatible assignment
  of the three generator families in an arbitrary, in particular noncommutative, complex
  algebra `B` extends to one and only one complex algebra homomorphism out of the local
  field algebra. -/
lemma existsUnique_algHom :
    ∃! Φ : LocalFieldAlgebra Ef Eb EA →ₐ[ℂ] B,
      (∀ v, Φ (ιFermion Ef Eb EA v) = d.fermion v) ∧
        (∀ v, Φ (ιBoson Ef Eb EA v) = d.boson v) ∧
          (∀ v, Φ (ιConnection Ef Eb EA v) = d.connection v) :=
  ⟨d.lift, ⟨d.lift_ιFermion, d.lift_ιBoson, d.lift_ιConnection⟩, fun _ hΦ =>
    algHom_ext Ef Eb EA (fun v => (hΦ.1 v).trans (d.lift_ιFermion v).symm)
      (fun v => (hΦ.2.1 v).trans (d.lift_ιBoson v).symm)
      (fun v => (hΦ.2.2 v).trans (d.lift_ιConnection v).symm)⟩

/-!

### D.3. Assignments are the same thing as algebra maps

-/

/-- The compatible assignment obtained by pushing one forward along an algebra map, every
  relation being preserved by an algebra homomorphism. -/
def comp {C : Type*} [Ring C] [Algebra ℂ C] (φ : B →ₐ[ℂ] C) : Assignment Ef Eb EA C where
  fermion := φ.toLinearMap ∘ₗ d.fermion
  boson := φ.toLinearMap ∘ₗ d.boson
  connection := (φ.restrictScalars ℝ).toLinearMap ∘ₗ d.connection
  fermion_mul_self v := by simpa using congrArg φ (d.fermion_mul_self v)
  boson_commute v w := (d.boson_commute v w).map φ
  connection_commute v w := (d.connection_commute v w).map φ
  boson_commute_connection v w := (d.boson_commute_connection v w).map φ
  boson_commute_fermion v w := (d.boson_commute_fermion v w).map φ
  connection_commute_fermion v w := (d.connection_commute_fermion v w).map φ

end Assignment

end Assignments

/-- The tautological assignment, with the generators of the local field algebra assigned
  to themselves. Its relations are those of section B.2. -/
noncomputable def canonicalAssignment :
    Assignment Ef Eb EA (LocalFieldAlgebra Ef Eb EA) where
  fermion := ιFermion Ef Eb EA
  boson := ιBoson Ef Eb EA
  connection := ιConnection Ef Eb EA
  fermion_mul_self := ιFermion_mul_self
  boson_commute := ιBoson_commute
  connection_commute := ιConnection_commute
  boson_commute_connection := ιBoson_commute_ιConnection
  boson_commute_fermion := ιBoson_commute_ιFermion
  connection_commute_fermion := ιConnection_commute_ιFermion

/-- Compatible assignments in `B` are the same thing as algebra maps into `B`. This is the
  universal property as an equivalence of types rather than a linear equivalence, neither
  side being a module in a way the other respects. -/
noncomputable def liftEquiv (B : Type*) [Ring B] [Algebra ℂ B] :
    Assignment Ef Eb EA B ≃ (LocalFieldAlgebra Ef Eb EA →ₐ[ℂ] B) where
  toFun d := d.lift
  invFun Φ := (canonicalAssignment Ef Eb EA).comp Φ
  left_inv d := by
    ext v
    exacts [d.lift_ιFermion v, d.lift_ιBoson v, d.lift_ιConnection v]
  right_inv Φ :=
    algHom_ext Ef Eb EA
      (((canonicalAssignment Ef Eb EA).comp Φ).lift_ιFermion)
      (((canonicalAssignment Ef Eb EA).comp Φ).lift_ιBoson)
      (((canonicalAssignment Ef Eb EA).comp Φ).lift_ιConnection)

/-!

### D.4. The range of the induced map

-/

section Range

namespace Assignment

variable {Ef Eb EA}
variable {B : Type*} [Ring B] [Algebra ℂ B] (d : Assignment Ef Eb EA B)

/-- The range of the induced map is the complex subalgebra generated by the three
  assignment images. No injectivity is claimed or required, since a realization of a field
  theory may identify local expressions. -/
lemma range_lift :
    d.lift.range
      = Algebra.adjoin ℂ
        (Set.range d.fermion ∪ Set.range d.boson ∪ Set.range d.connection) := by
  refine le_antisymm ?_ (Algebra.adjoin_le ?_)
  · refine Algebra.range_le_of_adjoin_eq_top (adjoin_generators_eq_top Ef Eb EA) d.lift ?_
    rintro _ ((⟨v, rfl⟩ | ⟨v, rfl⟩) | ⟨v, rfl⟩)
    · exact d.lift_ιFermion v ▸ Algebra.subset_adjoin (Or.inl (Or.inl ⟨v, rfl⟩))
    · exact d.lift_ιBoson v ▸ Algebra.subset_adjoin (Or.inl (Or.inr ⟨v, rfl⟩))
    · exact d.lift_ιConnection v ▸ Algebra.subset_adjoin (Or.inr ⟨v, rfl⟩)
  · rintro _ ((⟨v, rfl⟩ | ⟨v, rfl⟩) | ⟨v, rfl⟩)
    · exact ⟨ιFermion Ef Eb EA v, d.lift_ιFermion v⟩
    · exact ⟨ιBoson Ef Eb EA v, d.lift_ιBoson v⟩
    · exact ⟨ιConnection Ef Eb EA v, d.lift_ιConnection v⟩

end Assignment

end Range

end LocalFieldAlgebra
