/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.ClassicalFieldTheory.JetAlgebra.JetComponentSpace.Basic
/-!
# The field algebra of a matter field

## i. Overview

For a matter field valued in a complex vector space `V`, its *field algebra* is the algebra
generated by the component functions `∂_s ψ_α` and their conjugates `∂_s ψ̄_α` — the jet
component space `JetComponentSpace V` — subject to the statistics of the field: the
symmetric algebra for a bosonic field (`BosonicAlgebra V`), the exterior algebra for a
fermionic one (`FermionicAlgebra V`).

Everything that only uses the universal property of the algebra — the gauge and Lorentz
actions, the total derivative and its iterates, the mass-weight scaling — is the same for
both. This file isolates that universal property as the class `IsFieldAlgebra V A`: an
algebra `A` with an inclusion `ι` of the component functions, functorial in endomorphisms
of the component space, generated by `ι`, and with the induction principle that follows.
The two concrete algebras are instances, and the sibling files `GaugeAction`,
`LorentzAction`, `JetDeriv` and `MassDim` are stated once for any `[IsFieldAlgebra V A]`.

Only the statistics themselves — the commutation relations of the generators, and the
construction (not the properties) of the total derivative — live in the files of the two
concrete algebras.

## ii. Key results

- `IsFieldAlgebra` : the universal property of a field algebra.
- `FieldAlgebra.ι`, `FieldAlgebra.map` : the generators and functoriality, with `map_ι`,
  `map_id`, `map_comp_map` and the induction principle `FieldAlgebra.induction`.
- `FieldAlgebra.adjoin_ι_eq_top` : the algebra is generated by the component functions.
- `FieldAlgebra.ofField`, `FieldAlgebra.ofConjField` : the field and its conjugate.

## iii. Table of contents

- A. The universal property of a field algebra
- B. The field and its conjugate

-/

@[expose] public section

open TensorProduct

variable {V : Type} [AddCommGroup V] [Module ℂ V]

/-!

## A. The universal property of a field algebra

-/

/-- **A field algebra** of a `V`-valued matter field: a `ℂ`-algebra `A` generated by the
  component functions `JetComponentSpace V`, functorially in endomorphisms of the component
  space. The symmetric algebra (bosons) and the exterior algebra (fermions) are the two
  instances; the class records exactly what is used to build the gauge and Lorentz
  actions, the total derivative and the mass-weight scaling on `A`. -/
class IsFieldAlgebra (V : outParam Type) [AddCommGroup V] [Module ℂ V]
    (A : Type) [Ring A] [Algebra ℂ A] where
  /-- The inclusion of the component functions as generators. -/
  ι : JetComponentSpace V →ₗ[ℂ] A
  /-- Functoriality: an endomorphism of the component space induces an algebra
    endomorphism. -/
  map : (JetComponentSpace V →ₗ[ℂ] JetComponentSpace V) → (A →ₐ[ℂ] A)
  map_ι : ∀ (f : JetComponentSpace V →ₗ[ℂ] JetComponentSpace V) (x : JetComponentSpace V),
    map f (ι x) = ι (f x)
  map_id : map LinearMap.id = AlgHom.id ℂ A
  map_comp_map : ∀ (f g : JetComponentSpace V →ₗ[ℂ] JetComponentSpace V),
    (map g).comp (map f) = map (g ∘ₗ f)
  /-- The induction principle: a property of the scalars and the generators, closed under
    products and sums, holds everywhere. -/
  induction : ∀ {motive : A → Prop},
    (∀ r, motive (algebraMap ℂ A r)) → (∀ x, motive (ι x)) →
    (∀ a b, motive a → motive b → motive (a * b)) →
    (∀ a b, motive a → motive b → motive (a + b)) → ∀ a, motive a
  adjoin_ι_eq_top : Algebra.adjoin ℂ (Set.range ι) = ⊤

namespace FieldAlgebra

variable (A : Type) [Ring A] [Algebra ℂ A] [IsFieldAlgebra V A]

/-- The inclusion of the component functions as the generators of the field algebra. -/
abbrev ι : JetComponentSpace V →ₗ[ℂ] A := IsFieldAlgebra.ι

/-- **Functoriality of the field algebra** in the component space: an endomorphism of the
  component space induces an algebra endomorphism of the field algebra. -/
abbrev map (f : JetComponentSpace V →ₗ[ℂ] JetComponentSpace V) : A →ₐ[ℂ] A :=
  IsFieldAlgebra.map f

@[simp]
lemma map_ι (f : JetComponentSpace V →ₗ[ℂ] JetComponentSpace V) (x : JetComponentSpace V) :
    map A f (ι A x) = ι A (f x) :=
  IsFieldAlgebra.map_ι f x

@[simp]
lemma map_id : map A (LinearMap.id : JetComponentSpace V →ₗ[ℂ] JetComponentSpace V)
    = AlgHom.id ℂ A :=
  IsFieldAlgebra.map_id

lemma map_comp_map (f g : JetComponentSpace V →ₗ[ℂ] JetComponentSpace V) :
    (map A g).comp (map A f) = map A (g ∘ₗ f) :=
  IsFieldAlgebra.map_comp_map f g

/-- **The field algebra is generated by the component functions.** Every element is a
  polynomial in the degree-one elements — the symbols `∂_s ψ_α` and `∂_s ψ̄_α` themselves.
  This is the algebraic form of "every Lagrangian term is a polynomial in the component
  functions". -/
@[simp]
lemma adjoin_ι_eq_top : Algebra.adjoin ℂ (Set.range (ι (V := V) A)) = ⊤ :=
  IsFieldAlgebra.adjoin_ι_eq_top

variable {A}

/-- **The induction principle of the field algebra**: a property holding on the scalars and
  the generators, and closed under products and sums, holds everywhere. -/
@[elab_as_elim]
theorem induction {motive : A → Prop}
    (algebraMap : ∀ r, motive (algebraMap ℂ A r))
    (ι : ∀ x, motive (FieldAlgebra.ι A x))
    (mul : ∀ a b, motive a → motive b → motive (a * b))
    (add : ∀ a b, motive a → motive b → motive (a + b))
    (a : A) : motive a :=
  IsFieldAlgebra.induction algebraMap ι mul add a

/-!

## B. The field and its conjugate

The undifferentiated component functions sit inside the field algebra as the two
inclusions below. A component function is a *covector* on the target space: `ofField φ` is
the component of the field `ψ` along `φ`, the element written `ψ_α` when `φ` is the `α`-th
coordinate. The conjugate field is a covector on `ConjModule V`, whose scalar action is
twisted by complex conjugation — that twist is exactly the statement that `ψ̄` transforms
by the conjugate of the representation carried by `ψ`.

Every other generator of the algebra is an iterated derivative of one of these, which is
the content of `FieldAlgebra.adjoin_iteratedJetDeriv_eq_top`.

-/

variable (A)

/-- **The component function `ψ_φ` of the matter field** along the covector `φ` on `V`: the
  undifferentiated generator, sitting at the empty derivative label in the unconjugated half
  of the component space. -/
noncomputable def ofField : Module.Dual ℂ V →ₗ[ℂ] A :=
  (ι A).comp
    ((LinearMap.inl ℂ (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ V)
        (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ (ConjModule V))).comp
      (TensorProduct.mk ℂ DerivAlgebraComplex (Module.Dual ℂ V) 1))

/-- **The component function `ψ̄_φ` of the conjugate matter field** along the covector `φ`
  on `ConjModule V`: the undifferentiated generator in the conjugate half of the component
  space. -/
noncomputable def ofConjField : Module.Dual ℂ (ConjModule V) →ₗ[ℂ] A :=
  (ι A).comp
    ((LinearMap.inr ℂ (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ V)
        (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ (ConjModule V))).comp
      (TensorProduct.mk ℂ DerivAlgebraComplex (Module.Dual ℂ (ConjModule V)) 1))

lemma ofField_apply (φ : Module.Dual ℂ V) :
    ofField A φ = ι A
      (((1 : DerivAlgebraComplex) ⊗ₜ[ℂ] φ, 0) : JetComponentSpace V) := rfl

lemma ofConjField_apply (φ : Module.Dual ℂ (ConjModule V)) :
    ofConjField A φ = ι A
      ((0, (1 : DerivAlgebraComplex) ⊗ₜ[ℂ] φ) : JetComponentSpace V) := rfl

end FieldAlgebra
