/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.ClassicalFieldTheory.JetAlgebra.FieldAlgebra.Basic
public import Physlib.Mathematics.SymmetricAlgebra
public import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
/-!
# The bosonic and fermionic algebras

## i. Overview

The two field algebras of a `V`-valued matter field, distinguished by the statistics of the
field:

* the **bosonic algebra** `BosonicAlgebra V`, the symmetric algebra on the jet component
  space — the component functions commute;
* the **fermionic algebra** `FermionicAlgebra V`, the exterior algebra on the jet component
  space — the component functions anticommute.

Both are instances of `IsFieldAlgebra`, so the gauge and Lorentz actions, the total
derivative and the mass-weight scaling of `Physlib.ClassicalFieldTheory.JetAlgebra.FieldAlgebra`
apply to both. This file contains only what is specific to each: the definition, the
`IsFieldAlgebra` instance, the commutation relations of the generators, and the inclusion
of a species `comap` (contravariant in the target space, hence not part of the
single-space interface).

## ii. Key results

- `BosonicAlgebra`, `FermionicAlgebra` : the two algebras.
- `BosonicAlgebra.instIsFieldAlgebra`, `FermionicAlgebra.instIsFieldAlgebra`.
- `BosonicAlgebra.ι_mul_ι_comm`, `FermionicAlgebra.ι_sq_zero`,
  `FermionicAlgebra.ι_mul_ι_swap` : the statistics.
- `BosonicAlgebra.comap`, `FermionicAlgebra.comap` : the inclusion of a species.

-/

@[expose] public section

section Bosonic

open TensorProduct

variable {V : Type} [AddCommGroup V] [Module ℂ V]

/-!

## A. The bosonic algebra

-/

/-- The bosonic algebra of a `V`-valued matter field: the symmetric algebra on the space
  of component functions `∂_s φ_α` and `∂_s φ̄_α`. The symmetric product is the product of
  bosonic fields, its commutativity the Bose statistics. -/
abbrev BosonicAlgebra (V : Type) [AddCommGroup V] [Module ℂ V] : Type :=
  SymmetricAlgebra ℂ (JetComponentSpace V)

namespace BosonicAlgebra

/-!

### A.1. The generators of the bosonic algebra

-/

/-- **The bosonic algebra is generated by the component functions.** Every element is a
  polynomial in the degree-one elements — the symbols `∂_s φ_α` and `∂_s φ̄_α` themselves.
  This is the algebraic form of "every Lagrangian term is a polynomial in the component
  functions". -/
@[simp]
lemma adjoin_ι_eq_top :
    Algebra.adjoin ℂ (Set.range (SymmetricAlgebra.ι ℂ (JetComponentSpace V))) = ⊤ :=
  SymmetricAlgebra.adjoin_range_ι

/-- Two component functions commute: Bose statistics. -/
lemma ι_mul_ι_comm (x y : JetComponentSpace V) :
    (SymmetricAlgebra.ι ℂ _ x * SymmetricAlgebra.ι ℂ _ y : BosonicAlgebra V)
      = SymmetricAlgebra.ι ℂ _ y * SymmetricAlgebra.ι ℂ _ x :=
  mul_comm _ _

/-- The bosonic algebra is a field algebra: the symmetric algebra has the universal
  property. -/
noncomputable instance instIsFieldAlgebra : IsFieldAlgebra V (BosonicAlgebra V) where
  ι := SymmetricAlgebra.ι ℂ _
  map := SymmetricAlgebra.map
  map_ι f x := SymmetricAlgebra.map_apply_ι f x
  map_id := SymmetricAlgebra.map_id
  map_comp_map f g := SymmetricAlgebra.map_comp_map g f
  induction h1 h2 h3 h4 a := by
    induction a using SymmetricAlgebra.induction with
    | algebraMap r => exact h1 r
    | ι x => exact h2 x
    | mul a b ha hb => exact h3 a b ha hb
    | add a b ha hb => exact h4 a b ha hb
  adjoin_ι_eq_top := SymmetricAlgebra.adjoin_range_ι

lemma ι_eq : FieldAlgebra.ι (BosonicAlgebra V) = SymmetricAlgebra.ι ℂ (JetComponentSpace V) := rfl

/-!

### A.2. Inclusion of a species

A field valued in `V` that is one *species* among several — i.e. `V` is a summand of a
larger target space `W` — has its bosonic algebra sitting inside the bosonic algebra of
`W`. The inclusion is induced by the *projection* `W →ₗ[ℂ] V`, because component functions
are covectors on the target and therefore transpose. `comap` is that induced map, and it is
functorial and compatible with everything the algebra carries.

-/

variable {W : Type} [AddCommGroup W] [Module ℂ W]

/-- **The bosonic algebra is contravariant in the target space.** A linear map
  `f : V →ₗ[ℂ] W` induces an algebra homomorphism `BosonicAlgebra W →ₐ[ℂ] BosonicAlgebra V`
  by pulling back component functions. Applied to a *projection* out of a multi-species
  target space, this is the inclusion of one species' algebra into the whole. -/
noncomputable def comap (f : V →ₗ[ℂ] W) : BosonicAlgebra W →ₐ[ℂ] BosonicAlgebra V :=
  SymmetricAlgebra.map (JetComponentSpace.comap f)

@[simp]
lemma comap_ι (f : V →ₗ[ℂ] W) (x : JetComponentSpace W) :
    comap f (FieldAlgebra.ι (BosonicAlgebra W) x)
      = FieldAlgebra.ι (BosonicAlgebra V) (JetComponentSpace.comap f x) :=
  SymmetricAlgebra.map_apply_ι _ x

@[simp]
lemma comap_id : comap (LinearMap.id : V →ₗ[ℂ] V) = AlgHom.id ℂ (BosonicAlgebra V) := by
  rw [comap, JetComponentSpace.comap_id, SymmetricAlgebra.map_id]

/-- Functoriality: the order reverses, as it must for a contravariant construction. -/
lemma comap_comp {U : Type} [AddCommGroup U] [Module ℂ U] (f : V →ₗ[ℂ] W) (g : W →ₗ[ℂ] U) :
    comap (g.comp f) = (comap f).comp (comap g) := by
  rw [comap, comap, comap, JetComponentSpace.comap_comp, ← SymmetricAlgebra.map_comp_map]

/-- The inclusion sends a component function of the species to the corresponding component
  function of the whole. -/
@[simp]
lemma comap_ofField (f : V →ₗ[ℂ] W) (φ : Module.Dual ℂ W) :
    comap f (FieldAlgebra.ofField (BosonicAlgebra W) φ)
      = FieldAlgebra.ofField (BosonicAlgebra V) (φ ∘ₗ f) := by
  rw [FieldAlgebra.ofField_apply, comap_ι, FieldAlgebra.ofField_apply]
  congr 1

/-- The inclusion sends a conjugate component function of the species to the corresponding
  conjugate component function of the whole. -/
@[simp]
lemma comap_ofConjField (f : V →ₗ[ℂ] W) (φ : Module.Dual ℂ (ConjModule W)) :
    comap f (FieldAlgebra.ofConjField (BosonicAlgebra W) φ)
      = FieldAlgebra.ofConjField (BosonicAlgebra V) (φ ∘ₗ ConjModule.map f) := by
  rw [FieldAlgebra.ofConjField_apply, comap_ι, FieldAlgebra.ofConjField_apply]
  congr 1

end BosonicAlgebra

end Bosonic

section Fermionic

open TensorProduct

variable {V : Type} [AddCommGroup V] [Module ℂ V]

/-!

## A. The fermionic algebra

-/

/-- The fermionic algebra of a `V`-valued matter field: the exterior algebra on the space
  of component functions `∂_s ψ_α` and `∂_s ψ̄_α`. The exterior product is the product of
  fermionic fields, its anticommutativity the Fermi statistics. -/
abbrev FermionicAlgebra (V : Type) [AddCommGroup V] [Module ℂ V] : Type :=
  ExteriorAlgebra ℂ (JetComponentSpace V)

namespace FermionicAlgebra

/-!

### A.1. The generators of the fermionic algebra

-/

/-- **The fermionic algebra is generated by the component functions.** Every element is a
  polynomial in the degree-one elements — the symbols `∂_s ψ_α` and `∂_s ψ̄_α` themselves.
  This is the algebraic form of "every Lagrangian term is a polynomial in the component
  functions". -/
@[simp]
lemma adjoin_ι_eq_top :
    Algebra.adjoin ℂ (Set.range (ExteriorAlgebra.ι ℂ (M := JetComponentSpace V))) = ⊤ :=
  CliffordAlgebra.adjoin_range_ι

/-- A component function squares to zero: no fermionic field appears twice. -/
lemma ι_sq_zero (x : JetComponentSpace V) :
    ExteriorAlgebra.ι ℂ x * ExteriorAlgebra.ι ℂ x = (0 : FermionicAlgebra V) :=
  ExteriorAlgebra.ι_sq_zero x

/-- Two component functions anticommute. -/
lemma ι_mul_ι_swap (x y : JetComponentSpace V) :
    (ExteriorAlgebra.ι ℂ x * ExteriorAlgebra.ι ℂ y : FermionicAlgebra V)
      = - (ExteriorAlgebra.ι ℂ y * ExteriorAlgebra.ι ℂ x) :=
  eq_neg_of_add_eq_zero_left (ExteriorAlgebra.ι_add_mul_swap (R := ℂ) x y)

/-- The fermionic algebra is a field algebra: the exterior algebra has the universal
  property. -/
noncomputable instance instIsFieldAlgebra : IsFieldAlgebra V (FermionicAlgebra V) where
  ι := ExteriorAlgebra.ι ℂ
  map := ExteriorAlgebra.map
  map_ι f x := ExteriorAlgebra.map_apply_ι f x
  map_id := ExteriorAlgebra.map_id
  map_comp_map f g := ExteriorAlgebra.map_comp_map f g
  induction h1 h2 h3 h4 a := by
    induction a using ExteriorAlgebra.induction with
    | algebraMap r => exact h1 r
    | ι x => exact h2 x
    | mul a b ha hb => exact h3 a b ha hb
    | add a b ha hb => exact h4 a b ha hb
  adjoin_ι_eq_top := CliffordAlgebra.adjoin_range_ι

lemma ι_eq : FieldAlgebra.ι (FermionicAlgebra V) = ExteriorAlgebra.ι ℂ := rfl

/-!

### A.2. Inclusion of a species

A field valued in `V` that is one *species* among several — i.e. `V` is a summand of a
larger target space `U` — has its fermionic algebra sitting inside the fermionic algebra of
`U`. The inclusion is induced by the *projection* `U →ₗ[ℂ] V`, because component functions
are covectors on the target and therefore transpose. `comap` is that induced map, and it is
functorial and compatible with everything the algebra carries.

-/

variable {W : Type} [AddCommGroup W] [Module ℂ W]

/-- **The fermionic algebra is contravariant in the target space.** A linear map
  `f : V →ₗ[ℂ] W` induces an algebra homomorphism `FermionicAlgebra W →ₐ[ℂ] FermionicAlgebra V`
  by pulling back component functions. Applied to a *projection* out of a multi-species target
  space, this is the inclusion of one species' algebra into the whole. -/
noncomputable def comap (f : V →ₗ[ℂ] W) : FermionicAlgebra W →ₐ[ℂ] FermionicAlgebra V :=
  ExteriorAlgebra.map (JetComponentSpace.comap f)

@[simp]
lemma comap_ι (f : V →ₗ[ℂ] W) (x : JetComponentSpace W) :
    comap f (FieldAlgebra.ι (FermionicAlgebra W) x)
      = FieldAlgebra.ι (FermionicAlgebra V) (JetComponentSpace.comap f x) :=
  ExteriorAlgebra.map_apply_ι _ x

@[simp]
lemma comap_id : comap (LinearMap.id : V →ₗ[ℂ] V) = AlgHom.id ℂ (FermionicAlgebra V) := by
  rw [comap, JetComponentSpace.comap_id, ExteriorAlgebra.map_id]

/-- Functoriality: the order reverses, as it must for a contravariant construction. -/
lemma comap_comp {U : Type} [AddCommGroup U] [Module ℂ U] (f : V →ₗ[ℂ] W) (g : W →ₗ[ℂ] U) :
    comap (g.comp f) = (comap f).comp (comap g) := by
  rw [comap, comap, comap, JetComponentSpace.comap_comp, ← ExteriorAlgebra.map_comp_map]

/-- The inclusion sends a component function of the species to the corresponding component
  function of the whole. -/
@[simp]
lemma comap_ofField (f : V →ₗ[ℂ] W) (φ : Module.Dual ℂ W) :
    comap f (FieldAlgebra.ofField (FermionicAlgebra W) φ)
      = FieldAlgebra.ofField (FermionicAlgebra V) (φ ∘ₗ f) := by
  rw [FieldAlgebra.ofField_apply, comap_ι, FieldAlgebra.ofField_apply]
  congr 1

/-- The inclusion sends a conjugate component function of the species to the corresponding
  conjugate component function of the whole. -/
@[simp]
lemma comap_ofConjField (f : V →ₗ[ℂ] W) (φ : Module.Dual ℂ (ConjModule W)) :
    comap f (FieldAlgebra.ofConjField (FermionicAlgebra W) φ)
      = FieldAlgebra.ofConjField (FermionicAlgebra V) (φ ∘ₗ ConjModule.map f) := by
  rw [FieldAlgebra.ofConjField_apply, comap_ι, FieldAlgebra.ofConjField_apply]
  congr 1

end FermionicAlgebra

end Fermionic
