/-
Copyright (c) 2026 Nathaneal Sajan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathaneal Sajan
-/
module

public import Physlib.ClassicalFieldTheory.GaugeTheory.LocalFieldAlgebra.CovariantDeriv
public import Physlib.Mathematics.AlgebraRepresentation
/-!
# The covariant field algebra of a gauge theory

## i. Overview

`T.LocalCovFieldAlgebra` is the complex unital subalgebra of the local field algebra `J(T)`
of a field datum generated by the covariant expressions of the theory: the covariant
towers `∇_{l 0} ⋯ ∇_{l (n-1)} ψ` of every matter species and of their conjugate components,
along all ordered tuples of directions, with the undifferentiated fields as the case
`n = 0`, and the field strength with its ordered covariant derivatives `∇_l F_μν` included
from the gauge-only algebra. Being a subalgebra of `J(T)` it inherits the relations of
`J(T)`; no second free algebra is built, and `algHom_ext` gives uniqueness of maps out of
it but not their existence.

Its elements are gauge covariant, not gauge invariant. The jet gauge group preserves it
unconditionally, and under `GaugeFieldData.PureJetsActTrivially` its action factors
through evaluation to the ordinary gauge group; the Lorentz group preserves it under
`GaugeFieldData.GaugeLorentzCompatible`. The restricted actions are built with
`Representation.restrictSubalgebra`, so they agree with the ambient actions under the
inclusion `Subalgebra.val` by construction.

## ii. Key results

- `GaugeFieldData.LocalCovFieldAlgebra` : the covariant field algebra, with
  `LocalCovFieldAlgebra.induction`, `LocalCovFieldAlgebra.mapsTo`,
  `LocalCovFieldAlgebra.algHom_ext` and `LocalCovFieldAlgebra.algHom_ext_towers`.
- `LocalCovFieldAlgebra.covFermion`, `LocalCovFieldAlgebra.covFieldStrength` and
  companions : the generators as elements of the covariant field algebra.
- `LocalCovFieldAlgebra.repJet`, `LocalCovFieldAlgebra.repValue`,
  `LocalCovFieldAlgebra.repLorentzGroup` : the restricted actions.
- `LocalCovFieldAlgebra.repJet_eq_ofConstant_eval_of_mem`,
  `LocalCovFieldAlgebra.repJet_eq_repValue_eval` : the factorization through evaluation.

## iii. Table of contents

- A. The covariant field algebra
  - A.1. Generation
  - A.2. The generators as elements of the covariant field algebra
- B. Stability under the actions
- C. The restricted actions
  - C.1. The action of the ordinary gauge group
  - C.2. The actions on the generators

-/

@[expose] public section

open TensorProduct Matrix MatrixGroups Lorentz
open GaugeAlgebraRealization (repDualCoeff)

namespace GaugeFieldData

variable {G₀ : Type} [Group G₀] {𝔤 : Type} [LieRing 𝔤] [LieAlgebra ℝ 𝔤] [Module.Finite ℝ 𝔤]
  {GJ : Type} [Group GJ] {𝔤J : Type} [LieRing 𝔤J] [LieAlgebra ℝ 𝔤J]
  {jets : LocalGaugeData G₀ 𝔤 GJ 𝔤J} (T : GaugeFieldData jets)

/-!

## A. The covariant field algebra

-/

/-- The covariant generators of the local field algebra: the included field-strength tower
  and the covariant matter towers of every species, unconjugated and conjugate, along all
  ordered tuples of directions. -/
def covGenerators : Set T.LocalFieldAlgebra :=
  (⋃ l : List (Fin 1 ⊕ Fin 3), ⋃ μ, ⋃ ν, Set.range (T.covDerivFieldStrength l μ ν))
    ∪ ((⋃ i, ⋃ n : ℕ, ⋃ l : Fin n → (Fin 1 ⊕ Fin 3),
        Set.range (T.covDerivFermion i l) ∪ Set.range (T.covDerivConjFermion i l))
      ∪ (⋃ j, ⋃ n : ℕ, ⋃ l : Fin n → (Fin 1 ⊕ Fin 3),
        Set.range (T.covDerivBoson j l) ∪ Set.range (T.covDerivConjBoson j l)))

/-- The covariant field algebra of a field datum: the complex unital subalgebra of its local
  field algebra generated by the covariant matter towers of every species, their conjugates,
  and the included field-strength tower. -/
noncomputable def LocalCovFieldAlgebra : Subalgebra ℂ T.LocalFieldAlgebra :=
  Algebra.adjoin ℂ T.covGenerators

namespace LocalCovFieldAlgebra

variable {T}

/-!

### A.1. Generation

-/

lemma covDerivFieldStrength_mem (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ 𝔤) : T.covDerivFieldStrength l μ ν φ ∈ T.LocalCovFieldAlgebra :=
  Algebra.subset_adjoin (Or.inl (Set.mem_iUnion.mpr ⟨l, Set.mem_iUnion.mpr ⟨μ,
    Set.mem_iUnion.mpr ⟨ν, φ, rfl⟩⟩⟩))

lemma covDerivFermion_mem (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (T.FermionValue i)) : T.covDerivFermion i l φ ∈ T.LocalCovFieldAlgebra :=
  Algebra.subset_adjoin (Or.inr (Or.inl (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n,
    Set.mem_iUnion.mpr ⟨l, Or.inl ⟨φ, rfl⟩⟩⟩⟩)))

lemma covDerivConjFermion_mem (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))) :
    T.covDerivConjFermion i l φ ∈ T.LocalCovFieldAlgebra :=
  Algebra.subset_adjoin (Or.inr (Or.inl (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n,
    Set.mem_iUnion.mpr ⟨l, Or.inr ⟨φ, rfl⟩⟩⟩⟩)))

lemma covDerivBoson_mem (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (T.BosonValue j)) : T.covDerivBoson j l φ ∈ T.LocalCovFieldAlgebra :=
  Algebra.subset_adjoin (Or.inr (Or.inr (Set.mem_iUnion.mpr ⟨j, Set.mem_iUnion.mpr ⟨n,
    Set.mem_iUnion.mpr ⟨l, Or.inl ⟨φ, rfl⟩⟩⟩⟩)))

lemma covDerivConjBoson_mem (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))) :
    T.covDerivConjBoson j l φ ∈ T.LocalCovFieldAlgebra :=
  Algebra.subset_adjoin (Or.inr (Or.inr (Set.mem_iUnion.mpr ⟨j, Set.mem_iUnion.mpr ⟨n,
    Set.mem_iUnion.mpr ⟨l, Or.inr ⟨φ, rfl⟩⟩⟩⟩)))

/-- The undifferentiated matter symbols lie in the covariant field algebra, as the case of
  zero covariant derivatives. -/
lemma fermionSymbol_zero_mem (i : T.FermionSpecies) (φ : Module.Dual ℂ (T.FermionValue i)) :
    T.fermionSymbol i 0 φ ∈ T.LocalCovFieldAlgebra :=
  covDerivFermion_mem i (fun k : Fin 0 => k.elim0) φ

lemma conjFermionSymbol_zero_mem (i : T.FermionSpecies)
    (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))) :
    T.conjFermionSymbol i 0 φ ∈ T.LocalCovFieldAlgebra :=
  covDerivConjFermion_mem i (fun k : Fin 0 => k.elim0) φ

lemma bosonSymbol_zero_mem (j : T.BosonSpecies) (φ : Module.Dual ℂ (T.BosonValue j)) :
    T.bosonSymbol j 0 φ ∈ T.LocalCovFieldAlgebra :=
  covDerivBoson_mem j (fun k : Fin 0 => k.elim0) φ

lemma conjBosonSymbol_zero_mem (j : T.BosonSpecies)
    (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))) :
    T.conjBosonSymbol j 0 φ ∈ T.LocalCovFieldAlgebra :=
  covDerivConjBoson_mem j (fun k : Fin 0 => k.elim0) φ

/-- Case analysis on the covariant generators. -/
lemma covGenerators_cases {P : T.LocalFieldAlgebra → Prop} {b : T.LocalFieldAlgebra}
    (hb : b ∈ T.covGenerators)
    (hF : ∀ (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤),
      P (T.covDerivFieldStrength l μ ν φ))
    (hψ : ∀ (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (T.FermionValue i)), P (T.covDerivFermion i l φ))
    (hψc : ∀ (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))), P (T.covDerivConjFermion i l φ))
    (hφ : ∀ (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (T.BosonValue j)), P (T.covDerivBoson j l φ))
    (hφc : ∀ (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))), P (T.covDerivConjBoson j l φ)) :
    P b := by
  simp only [covGenerators, Set.mem_union, Set.mem_iUnion, Set.mem_range] at hb
  obtain ⟨l, μ, ν, φ, rfl⟩ | ⟨i, n, l, ⟨φ, rfl⟩ | ⟨φ, rfl⟩⟩ | ⟨j, n, l, ⟨φ, rfl⟩ | ⟨φ, rfl⟩⟩ := hb
  · exact hF l μ ν φ
  · exact hψ i l φ
  · exact hψc i l φ
  · exact hφ j l φ
  · exact hφc j l φ

/-- The generation principle: a property holding on the covariant generators and on the
  scalars, and closed under sums and products, holds on the whole covariant field
  algebra. -/
lemma induction {P : T.LocalFieldAlgebra → Prop} {x : T.LocalFieldAlgebra}
    (hx : x ∈ T.LocalCovFieldAlgebra)
    (hF : ∀ (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤),
      P (T.covDerivFieldStrength l μ ν φ))
    (hψ : ∀ (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (T.FermionValue i)), P (T.covDerivFermion i l φ))
    (hψc : ∀ (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))), P (T.covDerivConjFermion i l φ))
    (hφ : ∀ (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (T.BosonValue j)), P (T.covDerivBoson j l φ))
    (hφc : ∀ (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))), P (T.covDerivConjBoson j l φ))
    (halg : ∀ z : ℂ, P (z • (1 : T.LocalFieldAlgebra)))
    (hadd : ∀ x y, P x → P y → P (x + y))
    (hmul : ∀ x y, P x → P y → P (x * y)) : P x := by
  induction hx using Algebra.adjoin_induction with
  | mem b hb => exact covGenerators_cases hb hF hψ hψc hφ hφc
  | algebraMap z =>
    rw [Algebra.algebraMap_eq_smul_one]
    exact halg z
  | add a b _ _ ha hb => exact hadd a b ha hb
  | mul a b _ _ ha hb => exact hmul a b ha hb

/-- An algebra endomorphism carrying the covariant generators into the covariant field
  algebra carries the whole covariant field algebra into itself. -/
lemma mapsTo (f : T.LocalFieldAlgebra →ₐ[ℂ] T.LocalFieldAlgebra)
    (hgen : ∀ b ∈ T.covGenerators, f b ∈ T.LocalCovFieldAlgebra)
    {x : T.LocalFieldAlgebra} (hx : x ∈ T.LocalCovFieldAlgebra) :
    f x ∈ T.LocalCovFieldAlgebra :=
  Algebra.apply_mem_of_mem_adjoin f hgen hx

/-- Two algebra maps out of the covariant field algebra agreeing on the covariant
  generators are equal. This is uniqueness only: the covariant field algebra is not free on
  its generators, so an assignment of their images does not by itself define a map. -/
lemma algHom_ext {B : Type} [Semiring B] [Algebra ℂ B]
    {f g : ↥T.LocalCovFieldAlgebra →ₐ[ℂ] B}
    (h : ∀ b (hb : b ∈ T.covGenerators), f ⟨b, Algebra.subset_adjoin hb⟩
      = g ⟨b, Algebra.subset_adjoin hb⟩) : f = g :=
  AlgHom.ext_of_eq_adjoin rfl fun b hb => h b hb

/-!

### A.2. The generators as elements of the covariant field algebra

-/

variable (T)

/-- The included field-strength tower `∇_l F_μν^φ`, as elements of the covariant field
  algebra. -/
noncomputable def covFieldStrength (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ 𝔤) : T.LocalCovFieldAlgebra :=
  ⟨T.covDerivFieldStrength l μ ν φ, covDerivFieldStrength_mem l μ ν φ⟩

/-- The covariant tower `∇_l ψ^φ` of a fermionic species, as elements of the covariant field
  algebra. -/
noncomputable def covFermion (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (T.FermionValue i) →ₗ[ℂ] T.LocalCovFieldAlgebra where
  toFun φ := ⟨T.covDerivFermion i l φ, covDerivFermion_mem i l φ⟩
  map_add' _ _ := Subtype.ext (map_add (T.covDerivFermion i l) _ _)
  map_smul' _ _ := Subtype.ext (map_smul (T.covDerivFermion i l) _ _)

/-- The conjugate covariant tower of a fermionic species, as elements of the covariant field
  algebra. -/
noncomputable def covConjFermion (i : T.FermionSpecies) {n : ℕ}
    (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (ConjModule (T.FermionValue i)) →ₗ[ℂ] T.LocalCovFieldAlgebra where
  toFun φ := ⟨T.covDerivConjFermion i l φ, covDerivConjFermion_mem i l φ⟩
  map_add' _ _ := Subtype.ext (map_add (T.covDerivConjFermion i l) _ _)
  map_smul' _ _ := Subtype.ext (map_smul (T.covDerivConjFermion i l) _ _)

/-- The covariant tower of a bosonic species, as elements of the covariant field algebra. -/
noncomputable def covBoson (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (T.BosonValue j) →ₗ[ℂ] T.LocalCovFieldAlgebra where
  toFun φ := ⟨T.covDerivBoson j l φ, covDerivBoson_mem j l φ⟩
  map_add' _ _ := Subtype.ext (map_add (T.covDerivBoson j l) _ _)
  map_smul' _ _ := Subtype.ext (map_smul (T.covDerivBoson j l) _ _)

/-- The conjugate covariant tower of a bosonic species, as elements of the covariant field
  algebra. -/
noncomputable def covConjBoson (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (ConjModule (T.BosonValue j)) →ₗ[ℂ] T.LocalCovFieldAlgebra where
  toFun φ := ⟨T.covDerivConjBoson j l φ, covDerivConjBoson_mem j l φ⟩
  map_add' _ _ := Subtype.ext (map_add (T.covDerivConjBoson j l) _ _)
  map_smul' _ _ := Subtype.ext (map_smul (T.covDerivConjBoson j l) _ _)

variable {T}

@[simp]
lemma coe_covFieldStrength (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ 𝔤) :
    (covFieldStrength T l μ ν φ : T.LocalFieldAlgebra) = T.covDerivFieldStrength l μ ν φ := rfl

@[simp]
lemma coe_covFermion (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (T.FermionValue i)) :
    (covFermion T i l φ : T.LocalFieldAlgebra) = T.covDerivFermion i l φ := rfl

@[simp]
lemma coe_covConjFermion (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))) :
    (covConjFermion T i l φ : T.LocalFieldAlgebra) = T.covDerivConjFermion i l φ := rfl

@[simp]
lemma coe_covBoson (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (T.BosonValue j)) :
    (covBoson T j l φ : T.LocalFieldAlgebra) = T.covDerivBoson j l φ := rfl

@[simp]
lemma coe_covConjBoson (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))) :
    (covConjBoson T j l φ : T.LocalFieldAlgebra) = T.covDerivConjBoson j l φ := rfl

/-- Two algebra maps out of the covariant field algebra agreeing on the five towers are
  equal. Like `GaugeFieldData.LocalCovFieldAlgebra.algHom_ext` this is uniqueness only. -/
lemma algHom_ext_towers {B : Type} [Semiring B] [Algebra ℂ B]
    {f g : ↥T.LocalCovFieldAlgebra →ₐ[ℂ] B}
    (hF : ∀ (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤),
      f (covFieldStrength T l μ ν φ) = g (covFieldStrength T l μ ν φ))
    (hψ : ∀ (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (T.FermionValue i)),
      f (covFermion T i l φ) = g (covFermion T i l φ))
    (hψc : ∀ (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))),
      f (covConjFermion T i l φ) = g (covConjFermion T i l φ))
    (hφ : ∀ (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (T.BosonValue j)),
      f (covBoson T j l φ) = g (covBoson T j l φ))
    (hφc : ∀ (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))),
      f (covConjBoson T j l φ) = g (covConjBoson T j l φ)) : f = g := by
  refine algHom_ext fun b hb => ?_
  refine covGenerators_cases (P := fun b => ∀ hb' : b ∈ T.LocalCovFieldAlgebra,
    f ⟨b, hb'⟩ = g ⟨b, hb'⟩) hb ?_ ?_ ?_ ?_ ?_ (Algebra.subset_adjoin hb)
  · intro l μ ν φ _
    exact hF l μ ν φ
  · intro i n l φ _
    exact hψ i l φ
  · intro i n l φ _
    exact hψc i l φ
  · intro j n l φ _
    exact hφ j l φ
  · intro j n l φ _
    exact hφc j l φ

/-!

## B. Stability under the actions

-/

/-- The jet gauge group preserves the covariant field algebra: a jet carries each generator
  to a generator of the same tower. -/
lemma repJet_mem (U : GJ) {x : T.LocalFieldAlgebra} (hx : x ∈ T.LocalCovFieldAlgebra) :
    T.repJet U x ∈ T.LocalCovFieldAlgebra := by
  refine mapsTo (T.repJetAlgHom U) (fun b hb => ?_) hx
  refine covGenerators_cases (P := fun b => T.repJetAlgHom U b ∈ T.LocalCovFieldAlgebra) hb
    (fun l μ ν φ => ?_) (fun i n l φ => ?_) (fun i n l φ => ?_)
    (fun j n l φ => ?_) (fun j n l φ => ?_)
  · rw [← repJet_apply, repJet_covDerivFieldStrength]
    exact covDerivFieldStrength_mem l μ ν _
  · rw [← repJet_apply, repJet_covDerivFermion]
    exact covDerivFermion_mem i l _
  · rw [← repJet_apply, repJet_covDerivConjFermion]
    exact covDerivConjFermion_mem i l _
  · rw [← repJet_apply, repJet_covDerivBoson]
    exact covDerivBoson_mem j l _
  · rw [← repJet_apply, repJet_covDerivConjBoson]
    exact covDerivConjBoson_mem j l _

/-- The Lorentz group preserves the covariant field algebra under
  `GaugeFieldData.GaugeLorentzCompatible`: the generators mix among themselves. -/
lemma repLorentzGroup_mem (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ))
    {x : T.LocalFieldAlgebra} (hx : x ∈ T.LocalCovFieldAlgebra) :
    T.repLorentzGroup Λ x ∈ T.LocalCovFieldAlgebra := by
  refine mapsTo (T.repLorentzAlgHom Λ) (fun b hb => ?_) hx
  refine covGenerators_cases (P := fun b => T.repLorentzAlgHom Λ b ∈ T.LocalCovFieldAlgebra) hb
    (fun l μ ν φ => ?_) (fun i n l φ => ?_) (fun i n l φ => ?_)
    (fun j n l φ => ?_) (fun j n l φ => ?_)
  · exact repLorentzGroup_covDerivFieldStrength_mem Λ l μ ν φ
      fun l' a b => covDerivFieldStrength_mem l' a b φ
  · exact repLorentzGroup_covDerivFermion_mem Λ i (hGL.1 i) l φ
      fun p ψ => covDerivFermion_mem i p ψ
  · exact repLorentzGroup_covDerivConjFermion_mem Λ i (hGL.1 i) l φ
      fun p ψ => covDerivConjFermion_mem i p ψ
  · exact repLorentzGroup_covDerivBoson_mem Λ j (hGL.2 j) l φ
      fun p ψ => covDerivBoson_mem j p ψ
  · exact repLorentzGroup_covDerivConjBoson_mem Λ j (hGL.2 j) l φ
      fun p ψ => covDerivConjBoson_mem j p ψ

/-!

## C. The restricted actions

-/

variable (T)

/-- The action of the jet gauge group on the covariant field algebra, restricted from the
  local field algebra. -/
noncomputable def repJet : Representation ℂ GJ T.LocalCovFieldAlgebra :=
  T.repJet.restrictSubalgebra T.LocalCovFieldAlgebra fun U _ hx => repJet_mem U hx

variable {T}

@[simp]
lemma coe_repJet (U : GJ) (x : T.LocalCovFieldAlgebra) :
    (repJet T U x : T.LocalFieldAlgebra) = T.repJet U x := rfl

lemma repJet_apply_mul (U : GJ) (x y : T.LocalCovFieldAlgebra) :
    repJet T U (x * y) = repJet T U x * repJet T U y :=
  Subtype.ext (GaugeFieldData.repJet_apply_mul U (x : T.LocalFieldAlgebra) y)

variable (T)

/-- The action of the Lorentz group on the covariant field algebra, restricted from the
  local field algebra under `GaugeFieldData.GaugeLorentzCompatible`. -/
noncomputable def repLorentzGroup (hGL : T.GaugeLorentzCompatible) :
    Representation ℂ SL(2,ℂ) T.LocalCovFieldAlgebra :=
  T.repLorentzGroup.restrictSubalgebra T.LocalCovFieldAlgebra
    fun Λ _ hx => repLorentzGroup_mem hGL Λ hx

variable {T}

@[simp]
lemma coe_repLorentzGroup (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ))
    (x : T.LocalCovFieldAlgebra) :
    (repLorentzGroup T hGL Λ x : T.LocalFieldAlgebra) = T.repLorentzGroup Λ x := rfl

lemma repLorentzGroup_apply_mul (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ))
    (x y : T.LocalCovFieldAlgebra) :
    repLorentzGroup T hGL Λ (x * y) = repLorentzGroup T hGL Λ x * repLorentzGroup T hGL Λ y :=
  Subtype.ext (GaugeFieldData.repLorentzGroup_apply_mul Λ (x : T.LocalFieldAlgebra) y)

/-!

### C.1. The action of the ordinary gauge group

-/

variable (T)

/-- The action of the ordinary gauge group on the covariant field algebra: the jet action at
  the constant jets. -/
noncomputable def repValue : Representation ℂ G₀ T.LocalCovFieldAlgebra :=
  (repJet T).comp jets.ofConstant

variable {T}

@[simp]
lemma coe_repValue (g : G₀) (x : T.LocalCovFieldAlgebra) :
    (repValue T g x : T.LocalFieldAlgebra) = T.repJet (jets.ofConstant g) x := rfl

lemma repValue_apply_mul (g : G₀) (x y : T.LocalCovFieldAlgebra) :
    repValue T g (x * y) = repValue T g x * repValue T g y :=
  repJet_apply_mul (jets.ofConstant g) x y

/-- Under `GaugeFieldData.PureJetsActTrivially`, a jet acts on every element of the
  covariant field algebra as the constant jet of its value, stated in the local field
  algebra. -/
lemma repJet_eq_ofConstant_eval_of_mem (hP : T.PureJetsActTrivially) (U : GJ)
    {x : T.LocalFieldAlgebra} (hx : x ∈ T.LocalCovFieldAlgebra) :
    T.repJet U x = T.repJet (jets.ofConstant (jets.eval U)) x := by
  refine induction (P := fun y => T.repJet U y = T.repJet (jets.ofConstant (jets.eval U)) y)
    hx ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_
  · intro l μ ν φ
    exact repJet_covDerivFieldStrength_ofConstant_eval U l μ ν φ
  · intro i n l φ
    exact repJet_covDerivFermion_ofConstant_eval U i (hP.1 i) l φ
  · intro i n l φ
    exact repJet_covDerivConjFermion_ofConstant_eval U i (hP.1 i) l φ
  · intro j n l φ
    exact repJet_covDerivBoson_ofConstant_eval U j (hP.2 j) l φ
  · intro j n l φ
    exact repJet_covDerivConjBoson_ofConstant_eval U j (hP.2 j) l φ
  · intro z
    exact (map_smul (T.repJet U) z 1).trans
      (((congrArg (z • ·) (repJet_apply_one U)).trans
        (congrArg (z • ·) (repJet_apply_one _)).symm).trans
      (map_smul (T.repJet (jets.ofConstant (jets.eval U))) z 1).symm)
  · intro x y hx hy
    exact (map_add (T.repJet U) x y).trans
      ((congrArg₂ (· + ·) hx hy).trans
        (map_add (T.repJet (jets.ofConstant (jets.eval U))) x y).symm)
  · intro x y hx hy
    exact (GaugeFieldData.repJet_apply_mul U x y).trans
      ((congrArg₂ (· * ·) hx hy).trans (GaugeFieldData.repJet_apply_mul _ x y).symm)

/-- Under `GaugeFieldData.PureJetsActTrivially`, the action of the jet gauge group on the
  covariant field algebra factors through evaluation: a jet acts as the constant jet of its
  value, so the derivatives of a gauge transformation act trivially on covariant
  expressions. -/
theorem repJet_eq_repValue_eval (hP : T.PureJetsActTrivially) (U : GJ)
    (x : T.LocalCovFieldAlgebra) : repJet T U x = repValue T (jets.eval U) x :=
  Subtype.ext (repJet_eq_ofConstant_eval_of_mem hP U x.2)

/-!

### C.2. The actions on the generators

-/

/-- The ordinary gauge group rotates the adjoint index of the field-strength tower through
  the dual adjoint action of the inverse. -/
lemma repValue_covFieldStrength (g : G₀) (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ 𝔤) :
    repValue T g (covFieldStrength T l μ ν φ)
      = covFieldStrength T l μ ν ((jets.adjointValue g⁻¹).dualMap φ) := by
  refine Subtype.ext ?_
  rw [coe_repValue, coe_covFieldStrength, coe_covFieldStrength, repJet_covDerivFieldStrength,
    map_inv jets.eval, jets.eval_ofConstant]

/-- A jet acts on the field-strength tower through the value of its inverse alone. -/
lemma repJet_covFieldStrength (U : GJ) (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ 𝔤) :
    repJet T U (covFieldStrength T l μ ν φ)
      = covFieldStrength T l μ ν ((jets.adjointValue (jets.eval U⁻¹)).dualMap φ) :=
  Subtype.ext (repJet_covDerivFieldStrength U l μ ν φ)

/-- A jet acts on the covariant tower of a fermionic species through the zeroth dual Taylor
  coefficient of its inverse on the value index. -/
lemma repJet_covFermion (U : GJ) (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (T.FermionValue i)) :
    repJet T U (covFermion T i l φ)
      = covFermion T i l (repDualCoeff (T.fermion i).repJet U⁻¹ 0 φ) :=
  Subtype.ext (repJet_covDerivFermion U i l φ)

lemma repJet_covConjFermion (U : GJ) (i : T.FermionSpecies) {n : ℕ}
    (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))) :
    repJet T U (covConjFermion T i l φ)
      = covConjFermion T i l
          (repDualCoeff (JetComponentSpace.repConj (T.fermion i).repJet) U⁻¹ 0 φ) :=
  Subtype.ext (repJet_covDerivConjFermion U i l φ)

lemma repJet_covBoson (U : GJ) (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (T.BosonValue j)) :
    repJet T U (covBoson T j l φ) = covBoson T j l (repDualCoeff (T.boson j).repJet U⁻¹ 0 φ) :=
  Subtype.ext (repJet_covDerivBoson U j l φ)

lemma repJet_covConjBoson (U : GJ) (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))) :
    repJet T U (covConjBoson T j l φ)
      = covConjBoson T j l
          (repDualCoeff (JetComponentSpace.repConj (T.boson j).repJet) U⁻¹ 0 φ) :=
  Subtype.ext (repJet_covDerivConjBoson U j l φ)

-- The entry `Λ_{b a}` of the Lorentz matrix of `Λ : SL(2,ℂ)`, as a complex scalar.
set_option quotPrecheck false in
local notation:max "L[" Λ "]" b:max a:max => (((SL2C.toLorentzGroup Λ).1 b a : ℝ) : ℂ)

/-- The Lorentz law of the field-strength tower in the covariant field algebra: every
  covariant slot and both covector indices mix by the columns of the Lorentz matrix. -/
lemma repLorentzGroup_covFieldStrength (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ))
    {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤) :
    repLorentzGroup T hGL Λ (covFieldStrength T (List.ofFn l) μ ν φ)
      = ∑ p : Fin n → (Fin 1 ⊕ Fin 3), (∏ k, L[Λ] (p k) (l k)) •
          ∑ a, L[Λ] a μ • ∑ b, L[Λ] b ν • covFieldStrength T (List.ofFn p) a b φ := by
  refine Subtype.ext ((repLorentzGroup_covDerivFieldStrength Λ l μ ν φ).trans ?_)
  simp only [AddSubmonoidClass.coe_finsetSum, Subalgebra.coe_smul, coe_covFieldStrength]

/-- The Lorentz law of the covariant tower of a fermionic species in the covariant field
  algebra: every covariant slot mixes by the columns of the Lorentz matrix and the value
  index transforms contragrediently. -/
lemma repLorentzGroup_covFermion (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ))
    (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (T.FermionValue i)) :
    repLorentzGroup T hGL Λ (covFermion T i l φ)
      = ∑ p : Fin n → (Fin 1 ⊕ Fin 3), (∏ k, L[Λ] (p k) (l k)) •
          covFermion T i p ((T.fermion i).repLorentz.dual Λ φ) := by
  refine Subtype.ext ((repLorentzGroup_covDerivFermion Λ i (hGL.1 i) l φ).trans ?_)
  simp only [AddSubmonoidClass.coe_finsetSum, Subalgebra.coe_smul, coe_covFermion]

lemma repLorentzGroup_covConjFermion (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ))
    (i : T.FermionSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))) :
    repLorentzGroup T hGL Λ (covConjFermion T i l φ)
      = ∑ p : Fin n → (Fin 1 ⊕ Fin 3), (∏ k, L[Λ] (p k) (l k)) •
          covConjFermion T i p ((T.fermion i).repLorentz.conj.dual Λ φ) := by
  refine Subtype.ext ((repLorentzGroup_covDerivConjFermion Λ i (hGL.1 i) l φ).trans ?_)
  simp only [AddSubmonoidClass.coe_finsetSum, Subalgebra.coe_smul, coe_covConjFermion]

lemma repLorentzGroup_covBoson (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ))
    (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (T.BosonValue j)) :
    repLorentzGroup T hGL Λ (covBoson T j l φ)
      = ∑ p : Fin n → (Fin 1 ⊕ Fin 3), (∏ k, L[Λ] (p k) (l k)) •
          covBoson T j p ((T.boson j).repLorentz.dual Λ φ) := by
  refine Subtype.ext ((repLorentzGroup_covDerivBoson Λ j (hGL.2 j) l φ).trans ?_)
  simp only [AddSubmonoidClass.coe_finsetSum, Subalgebra.coe_smul, coe_covBoson]

lemma repLorentzGroup_covConjBoson (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ))
    (j : T.BosonSpecies) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))) :
    repLorentzGroup T hGL Λ (covConjBoson T j l φ)
      = ∑ p : Fin n → (Fin 1 ⊕ Fin 3), (∏ k, L[Λ] (p k) (l k)) •
          covConjBoson T j p ((T.boson j).repLorentz.conj.dual Λ φ) := by
  refine Subtype.ext ((repLorentzGroup_covDerivConjBoson Λ j (hGL.2 j) l φ).trans ?_)
  simp only [AddSubmonoidClass.coe_finsetSum, Subalgebra.coe_smul, coe_covConjBoson]

end LocalCovFieldAlgebra

end GaugeFieldData
