/-
Copyright (c) 2026 Nathaneal Sajan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathaneal Sajan
-/
module

public import Physlib.ClassicalFieldTheory.GaugeTheory.LocalCovFieldAlgebra.Basic
public import Physlib.ClassicalFieldTheory.GaugeTheory.LocalFieldAlgebra.Sector
/-!
# The covariant sector algebras of the local field algebra

## i. Overview

A sector `S`, a finite set of `GaugeFieldData.FieldCategory`, selects covariant generator
families of the local field algebra `J(T)` of a field datum: the covariant towers
`∇_{l 0} ⋯ ∇_{l (n-1)} ψ` of every fermionic species and their conjugates, along all
ordered tuples of directions, for `fermion`; those of every bosonic species and their
conjugates for `scalar`; and the included field-strength tower `∇_l F_μν` for `gauge`.
Towers of length zero are the undifferentiated fields, and the ordered derivative labels
are kept. The covariant sector algebra `T.CovSectorAlgebra S` is the complex unital
subalgebra of `J(T)` generated by the selected towers; the full sector recovers
`T.LocalCovFieldAlgebra`, so every covariant sector algebra lies in it.

As for the ordinary sectors, `scalar` names the bosonic species without any Lorentz-scalar
hypothesis. A covariant sector algebra is not claimed to lie in the ordinary sector algebra
of the same sector: a covariant matter derivative contains connection terms whether or not
`gauge` is selected.

The actions and their restrictions follow the covariant field algebra, with the same
hypotheses: none for the jet and ordinary gauge groups,
`GaugeFieldData.GaugeLorentzCompatible` for the Lorentz group, and
`GaugeFieldData.PureJetsActTrivially` for the factorization of the jet action through
evaluation.

## ii. Key results

- `GaugeFieldData.CovSectorAlgebra` : the covariant sector algebra of a sector, with
  `CovSectorAlgebra.induction` and `CovSectorAlgebra.algHom_ext`.
- `CovSectorAlgebra.mono`, `CovSectorAlgebra.empty`, `CovSectorAlgebra.univ`,
  `CovSectorAlgebra.union`, `CovSectorAlgebra.le_localCovFieldAlgebra` : the lattice laws
  of the selection and the containment in the covariant field algebra.
- `CovSectorAlgebra.repJet`, `CovSectorAlgebra.repValue`,
  `CovSectorAlgebra.repLorentzGroup` : the restricted actions.
- `CovSectorAlgebra.repJet_eq_repValue_eval` : the factorization through evaluation.

## iii. Table of contents

- A. The covariant generators of a sector
- B. The covariant sector algebra
  - B.1. Membership of the selected towers
  - B.2. Generation
  - B.3. The lattice laws of the selection
- C. Stability under the actions
- D. The restricted actions
  - D.1. The action of the ordinary gauge group
  - D.2. The inclusions

-/

@[expose] public section

open TensorProduct Matrix MatrixGroups Lorentz

namespace GaugeFieldData

variable {G₀ : Type} [Group G₀] {𝔤 : Type} [LieRing 𝔤] [LieAlgebra ℝ 𝔤] [Module.Finite ℝ 𝔤]
  {GJ : Type} [Group GJ] {𝔤J : Type} [LieRing 𝔤J] [LieAlgebra ℝ 𝔤J]
  {jets : LocalGaugeData G₀ 𝔤 GJ 𝔤J} (T : GaugeFieldData jets)

/-!

## A. The covariant generators of a sector

-/

/-- The covariant generators of one field category. -/
def covCategoryGenerators : FieldCategory → Set T.LocalFieldAlgebra
  | .fermion => ⋃ i, ⋃ n : ℕ, ⋃ l : Fin n → (Fin 1 ⊕ Fin 3),
      Set.range (T.covDerivFermion i l) ∪ Set.range (T.covDerivConjFermion i l)
  | .gauge => ⋃ l : List (Fin 1 ⊕ Fin 3), ⋃ μ, ⋃ ν, Set.range (T.covDerivFieldStrength l μ ν)
  | .scalar => ⋃ j, ⋃ n : ℕ, ⋃ l : Fin n → (Fin 1 ⊕ Fin 3),
      Set.range (T.covDerivBoson j l) ∪ Set.range (T.covDerivConjBoson j l)

/-- The covariant generators selected by a sector. -/
def covSectorGenerators (S : Finset FieldCategory) : Set T.LocalFieldAlgebra :=
  ⋃ c ∈ S, T.covCategoryGenerators c

lemma covSectorGenerators_mono {S S' : Finset FieldCategory} (h : S ⊆ S') :
    T.covSectorGenerators S ⊆ T.covSectorGenerators S' :=
  Set.iUnion₂_subset fun _ hc => Finset.subset_set_biUnion_of_mem (h hc)

@[simp]
lemma covSectorGenerators_empty : T.covSectorGenerators ∅ = ∅ := by
  simp [covSectorGenerators]

lemma covSectorGenerators_union (S S' : Finset FieldCategory) :
    T.covSectorGenerators (S ∪ S') = T.covSectorGenerators S ∪ T.covSectorGenerators S' :=
  Finset.set_biUnion_union S S' _

/-- The full sector selects the covariant generators of the covariant field algebra. -/
lemma covSectorGenerators_univ : T.covSectorGenerators Finset.univ = T.covGenerators := by
  ext x
  simp only [covSectorGenerators, Finset.mem_univ, Set.iUnion_true, Set.mem_iUnion]
  constructor
  · rintro ⟨c, hc⟩
    cases c
    · exact Or.inr (Or.inl hc)
    · exact Or.inl hc
    · exact Or.inr (Or.inr hc)
  · rintro (h | h | h)
    exacts [⟨.gauge, h⟩, ⟨.fermion, h⟩, ⟨.scalar, h⟩]

/-!

## B. The covariant sector algebra

-/

/-- The covariant sector algebra of a sector `S`: the subalgebra of the local field
  algebra generated by the covariant towers of the selected categories. -/
noncomputable def CovSectorAlgebra (S : Finset FieldCategory) :
    Subalgebra ℂ T.LocalFieldAlgebra :=
  Algebra.adjoin ℂ (T.covSectorGenerators S)

namespace CovSectorAlgebra

variable {T} {S : Finset FieldCategory}

/-!

### B.1. Membership of the selected towers

-/

lemma covDerivFieldStrength_mem (hS : FieldCategory.gauge ∈ S) (l : List (Fin 1 ⊕ Fin 3))
    (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤) :
    T.covDerivFieldStrength l μ ν φ ∈ T.CovSectorAlgebra S :=
  Algebra.subset_adjoin (Finset.subset_set_biUnion_of_mem (f := T.covCategoryGenerators) hS
    (Set.mem_iUnion.mpr ⟨l, Set.mem_iUnion.mpr ⟨μ, Set.mem_iUnion.mpr ⟨ν, φ, rfl⟩⟩⟩))

lemma covDerivFermion_mem (hS : FieldCategory.fermion ∈ S) (i : T.FermionSpecies) {n : ℕ}
    (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (T.FermionValue i)) :
    T.covDerivFermion i l φ ∈ T.CovSectorAlgebra S :=
  Algebra.subset_adjoin (Finset.subset_set_biUnion_of_mem (f := T.covCategoryGenerators) hS
    (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l, Or.inl ⟨φ, rfl⟩⟩⟩⟩))

lemma covDerivConjFermion_mem (hS : FieldCategory.fermion ∈ S) (i : T.FermionSpecies) {n : ℕ}
    (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))) :
    T.covDerivConjFermion i l φ ∈ T.CovSectorAlgebra S :=
  Algebra.subset_adjoin (Finset.subset_set_biUnion_of_mem (f := T.covCategoryGenerators) hS
    (Set.mem_iUnion.mpr ⟨i, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l, Or.inr ⟨φ, rfl⟩⟩⟩⟩))

lemma covDerivBoson_mem (hS : FieldCategory.scalar ∈ S) (j : T.BosonSpecies) {n : ℕ}
    (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (T.BosonValue j)) :
    T.covDerivBoson j l φ ∈ T.CovSectorAlgebra S :=
  Algebra.subset_adjoin (Finset.subset_set_biUnion_of_mem (f := T.covCategoryGenerators) hS
    (Set.mem_iUnion.mpr ⟨j, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l, Or.inl ⟨φ, rfl⟩⟩⟩⟩))

lemma covDerivConjBoson_mem (hS : FieldCategory.scalar ∈ S) (j : T.BosonSpecies) {n : ℕ}
    (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))) :
    T.covDerivConjBoson j l φ ∈ T.CovSectorAlgebra S :=
  Algebra.subset_adjoin (Finset.subset_set_biUnion_of_mem (f := T.covCategoryGenerators) hS
    (Set.mem_iUnion.mpr ⟨j, Set.mem_iUnion.mpr ⟨n, Set.mem_iUnion.mpr ⟨l, Or.inr ⟨φ, rfl⟩⟩⟩⟩))

/-- The included field strength, as the tower of empty length. -/
lemma fieldStrength_mem (hS : FieldCategory.gauge ∈ S) (μ ν : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ 𝔤) :
    T.includeConnection ((1 : ℂ) ⊗ₜ[ℝ] LocalGaugeFieldAlgebra.fieldStrength 𝔤 μ ν φ)
      ∈ T.CovSectorAlgebra S :=
  covDerivFieldStrength_mem hS [] μ ν φ

/-- The undifferentiated matter symbols, as the towers of length zero. -/
lemma fermionSymbol_zero_mem (hS : FieldCategory.fermion ∈ S) (i : T.FermionSpecies)
    (φ : Module.Dual ℂ (T.FermionValue i)) : T.fermionSymbol i 0 φ ∈ T.CovSectorAlgebra S :=
  covDerivFermion_mem hS i (fun k : Fin 0 => k.elim0) φ

lemma conjFermionSymbol_zero_mem (hS : FieldCategory.fermion ∈ S) (i : T.FermionSpecies)
    (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))) :
    T.conjFermionSymbol i 0 φ ∈ T.CovSectorAlgebra S :=
  covDerivConjFermion_mem hS i (fun k : Fin 0 => k.elim0) φ

lemma bosonSymbol_zero_mem (hS : FieldCategory.scalar ∈ S) (j : T.BosonSpecies)
    (φ : Module.Dual ℂ (T.BosonValue j)) : T.bosonSymbol j 0 φ ∈ T.CovSectorAlgebra S :=
  covDerivBoson_mem hS j (fun k : Fin 0 => k.elim0) φ

lemma conjBosonSymbol_zero_mem (hS : FieldCategory.scalar ∈ S) (j : T.BosonSpecies)
    (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))) :
    T.conjBosonSymbol j 0 φ ∈ T.CovSectorAlgebra S :=
  covDerivConjBoson_mem hS j (fun k : Fin 0 => k.elim0) φ

/-!

### B.2. Generation

-/

/-- Case analysis on the covariant generators of a sector. -/
lemma covSectorGenerators_cases {P : T.LocalFieldAlgebra → Prop} {b : T.LocalFieldAlgebra}
    (hb : b ∈ T.covSectorGenerators S)
    (hF : FieldCategory.gauge ∈ S → ∀ (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ 𝔤), P (T.covDerivFieldStrength l μ ν φ))
    (hψ : FieldCategory.fermion ∈ S → ∀ (i : T.FermionSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (T.FermionValue i)),
      P (T.covDerivFermion i l φ))
    (hψc : FieldCategory.fermion ∈ S → ∀ (i : T.FermionSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))),
      P (T.covDerivConjFermion i l φ))
    (hφ : FieldCategory.scalar ∈ S → ∀ (j : T.BosonSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (T.BosonValue j)),
      P (T.covDerivBoson j l φ))
    (hφc : FieldCategory.scalar ∈ S → ∀ (j : T.BosonSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))),
      P (T.covDerivConjBoson j l φ)) : P b := by
  simp only [covSectorGenerators, Set.mem_iUnion, exists_prop] at hb
  obtain ⟨c, hc, hbc⟩ := hb
  cases c with
  | fermion =>
    simp only [covCategoryGenerators, Set.mem_iUnion, Set.mem_union, Set.mem_range] at hbc
    obtain ⟨i, n, l, ⟨φ, rfl⟩ | ⟨φ, rfl⟩⟩ := hbc
    · exact hψ hc i l φ
    · exact hψc hc i l φ
  | gauge =>
    simp only [covCategoryGenerators, Set.mem_iUnion, Set.mem_range] at hbc
    obtain ⟨l, μ, ν, φ, rfl⟩ := hbc
    exact hF hc l μ ν φ
  | scalar =>
    simp only [covCategoryGenerators, Set.mem_iUnion, Set.mem_union, Set.mem_range] at hbc
    obtain ⟨j, n, l, ⟨φ, rfl⟩ | ⟨φ, rfl⟩⟩ := hbc
    · exact hφ hc j l φ
    · exact hφc hc j l φ

/-- A property holding on the selected towers and the scalars and closed under sums and
  products holds on the covariant sector algebra. -/
lemma induction {P : T.LocalFieldAlgebra → Prop} {x : T.LocalFieldAlgebra}
    (hx : x ∈ T.CovSectorAlgebra S)
    (hF : FieldCategory.gauge ∈ S → ∀ (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ 𝔤), P (T.covDerivFieldStrength l μ ν φ))
    (hψ : FieldCategory.fermion ∈ S → ∀ (i : T.FermionSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (T.FermionValue i)),
      P (T.covDerivFermion i l φ))
    (hψc : FieldCategory.fermion ∈ S → ∀ (i : T.FermionSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))),
      P (T.covDerivConjFermion i l φ))
    (hφ : FieldCategory.scalar ∈ S → ∀ (j : T.BosonSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (T.BosonValue j)),
      P (T.covDerivBoson j l φ))
    (hφc : FieldCategory.scalar ∈ S → ∀ (j : T.BosonSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))),
      P (T.covDerivConjBoson j l φ))
    (halg : ∀ z : ℂ, P (z • (1 : T.LocalFieldAlgebra)))
    (hadd : ∀ x y, P x → P y → P (x + y))
    (hmul : ∀ x y, P x → P y → P (x * y)) : P x := by
  induction hx using Algebra.adjoin_induction with
  | mem b hb => exact covSectorGenerators_cases hb hF hψ hψc hφ hφc
  | algebraMap z =>
    rw [Algebra.algebraMap_eq_smul_one]
    exact halg z
  | add a b _ _ ha hb => exact hadd a b ha hb
  | mul a b _ _ ha hb => exact hmul a b ha hb

/-- Two algebra maps out of a covariant sector algebra agreeing on the selected towers
  are equal. This is uniqueness only: the algebra is not free on its towers, so an
  assignment on them need not extend to a map. -/
lemma algHom_ext {B : Type} [Semiring B] [Algebra ℂ B]
    {f g : ↥(T.CovSectorAlgebra S) →ₐ[ℂ] B}
    (hF : ∀ (hS : FieldCategory.gauge ∈ S) (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ 𝔤),
      f ⟨T.covDerivFieldStrength l μ ν φ, covDerivFieldStrength_mem hS l μ ν φ⟩
        = g ⟨T.covDerivFieldStrength l μ ν φ, covDerivFieldStrength_mem hS l μ ν φ⟩)
    (hψ : ∀ (hS : FieldCategory.fermion ∈ S) (i : T.FermionSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (T.FermionValue i)),
      f ⟨T.covDerivFermion i l φ, covDerivFermion_mem hS i l φ⟩
        = g ⟨T.covDerivFermion i l φ, covDerivFermion_mem hS i l φ⟩)
    (hψc : ∀ (hS : FieldCategory.fermion ∈ S) (i : T.FermionSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))),
      f ⟨T.covDerivConjFermion i l φ, covDerivConjFermion_mem hS i l φ⟩
        = g ⟨T.covDerivConjFermion i l φ, covDerivConjFermion_mem hS i l φ⟩)
    (hφ : ∀ (hS : FieldCategory.scalar ∈ S) (j : T.BosonSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (T.BosonValue j)),
      f ⟨T.covDerivBoson j l φ, covDerivBoson_mem hS j l φ⟩
        = g ⟨T.covDerivBoson j l φ, covDerivBoson_mem hS j l φ⟩)
    (hφc : ∀ (hS : FieldCategory.scalar ∈ S) (j : T.BosonSpecies) {n : ℕ}
      (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))),
      f ⟨T.covDerivConjBoson j l φ, covDerivConjBoson_mem hS j l φ⟩
        = g ⟨T.covDerivConjBoson j l φ, covDerivConjBoson_mem hS j l φ⟩) : f = g := by
  refine AlgHom.ext_of_eq_adjoin rfl fun b hb => ?_
  refine covSectorGenerators_cases (P := fun b => ∀ hb' : b ∈ T.CovSectorAlgebra S,
    f ⟨b, hb'⟩ = g ⟨b, hb'⟩) hb ?_ ?_ ?_ ?_ ?_ (Algebra.subset_adjoin hb)
  · intro hS l μ ν φ _
    exact hF hS l μ ν φ
  · intro hS i n l φ _
    exact hψ hS i l φ
  · intro hS i n l φ _
    exact hψc hS i l φ
  · intro hS j n l φ _
    exact hφ hS j l φ
  · intro hS j n l φ _
    exact hφc hS j l φ

/-!

### B.3. The lattice laws of the selection

-/

variable (T)

lemma mono {S S' : Finset FieldCategory} (h : S ⊆ S') :
    T.CovSectorAlgebra S ≤ T.CovSectorAlgebra S' :=
  Algebra.adjoin_mono (covSectorGenerators_mono T h)

/-- The empty covariant sector algebra is the image of the scalars. -/
@[simp]
lemma empty : T.CovSectorAlgebra ∅ = ⊥ := by
  unfold CovSectorAlgebra
  rw [covSectorGenerators_empty, Algebra.adjoin_empty]

@[simp]
lemma univ : T.CovSectorAlgebra Finset.univ = T.LocalCovFieldAlgebra := by
  unfold CovSectorAlgebra
  rw [covSectorGenerators_univ]
  rfl

lemma union (S S' : Finset FieldCategory) :
    T.CovSectorAlgebra (S ∪ S') = T.CovSectorAlgebra S ⊔ T.CovSectorAlgebra S' := by
  unfold CovSectorAlgebra
  rw [covSectorGenerators_union, Algebra.adjoin_union]

variable (S) in
lemma le_localCovFieldAlgebra : T.CovSectorAlgebra S ≤ T.LocalCovFieldAlgebra :=
  (univ T).symm ▸ mono T (Finset.subset_univ S)

variable {T}

/-!

## C. Stability under the actions

A jet carries a tower element to an element of the same tower, and a Lorentz
transformation to a combination of elements of the same tower, so both actions preserve
every covariant sector algebra.

-/

lemma repJet_mem (U : GJ) {x : T.LocalFieldAlgebra} (hx : x ∈ T.CovSectorAlgebra S) :
    T.repJet U x ∈ T.CovSectorAlgebra S := by
  refine Algebra.apply_mem_of_mem_adjoin (T.repJetAlgHom U) (fun b hb => ?_) hx
  refine covSectorGenerators_cases (P := fun b => T.repJetAlgHom U b ∈ T.CovSectorAlgebra S) hb
    (fun hS l μ ν φ => ?_) (fun hS i n l φ => ?_) (fun hS i n l φ => ?_)
    (fun hS j n l φ => ?_) (fun hS j n l φ => ?_)
  · rw [← repJet_apply, repJet_covDerivFieldStrength]
    exact covDerivFieldStrength_mem hS l μ ν _
  · rw [← repJet_apply, repJet_covDerivFermion]
    exact covDerivFermion_mem hS i l _
  · rw [← repJet_apply, repJet_covDerivConjFermion]
    exact covDerivConjFermion_mem hS i l _
  · rw [← repJet_apply, repJet_covDerivBoson]
    exact covDerivBoson_mem hS j l _
  · rw [← repJet_apply, repJet_covDerivConjBoson]
    exact covDerivConjBoson_mem hS j l _

lemma repLorentzGroup_mem (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ))
    {x : T.LocalFieldAlgebra} (hx : x ∈ T.CovSectorAlgebra S) :
    T.repLorentzGroup Λ x ∈ T.CovSectorAlgebra S := by
  refine Algebra.apply_mem_of_mem_adjoin (T.repLorentzAlgHom Λ) (fun b hb => ?_) hx
  refine covSectorGenerators_cases
    (P := fun b => T.repLorentzAlgHom Λ b ∈ T.CovSectorAlgebra S) hb
    (fun hS l μ ν φ => ?_) (fun hS i n l φ => ?_) (fun hS i n l φ => ?_)
    (fun hS j n l φ => ?_) (fun hS j n l φ => ?_)
  · exact repLorentzGroup_covDerivFieldStrength_mem Λ l μ ν φ
      fun l' a b => covDerivFieldStrength_mem hS l' a b φ
  · exact repLorentzGroup_covDerivFermion_mem Λ i (hGL.1 i) l φ
      fun p ψ => covDerivFermion_mem hS i p ψ
  · exact repLorentzGroup_covDerivConjFermion_mem Λ i (hGL.1 i) l φ
      fun p ψ => covDerivConjFermion_mem hS i p ψ
  · exact repLorentzGroup_covDerivBoson_mem Λ j (hGL.2 j) l φ
      fun p ψ => covDerivBoson_mem hS j p ψ
  · exact repLorentzGroup_covDerivConjBoson_mem Λ j (hGL.2 j) l φ
      fun p ψ => covDerivConjBoson_mem hS j p ψ

/-!

## D. The restricted actions

-/

variable (T S)

/-- The jet gauge group acting on a covariant sector algebra, by restriction. -/
noncomputable def repJet : Representation ℂ GJ (T.CovSectorAlgebra S) :=
  T.repJet.restrictSubalgebra (T.CovSectorAlgebra S) fun U _ hx => repJet_mem U hx

/-- The Lorentz group acting on a covariant sector algebra, by restriction. -/
noncomputable def repLorentzGroup (hGL : T.GaugeLorentzCompatible) :
    Representation ℂ SL(2,ℂ) (T.CovSectorAlgebra S) :=
  T.repLorentzGroup.restrictSubalgebra (T.CovSectorAlgebra S)
    fun Λ _ hx => repLorentzGroup_mem hGL Λ hx

variable {T S}

@[simp]
lemma coe_repJet (U : GJ) (x : T.CovSectorAlgebra S) :
    (repJet T S U x : T.LocalFieldAlgebra) = T.repJet U x := rfl

lemma repJet_apply_mul (U : GJ) (x y : T.CovSectorAlgebra S) :
    repJet T S U (x * y) = repJet T S U x * repJet T S U y :=
  Subtype.ext (GaugeFieldData.repJet_apply_mul U (x : T.LocalFieldAlgebra) y)

@[simp]
lemma coe_repLorentzGroup (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ))
    (x : T.CovSectorAlgebra S) :
    (repLorentzGroup T S hGL Λ x : T.LocalFieldAlgebra) = T.repLorentzGroup Λ x := rfl

lemma repLorentzGroup_apply_mul (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ))
    (x y : T.CovSectorAlgebra S) :
    repLorentzGroup T S hGL Λ (x * y)
      = repLorentzGroup T S hGL Λ x * repLorentzGroup T S hGL Λ y :=
  Subtype.ext (GaugeFieldData.repLorentzGroup_apply_mul Λ (x : T.LocalFieldAlgebra) y)

/-!

### D.1. The action of the ordinary gauge group

-/

variable (T S)

/-- The ordinary gauge group acting on a covariant sector algebra, through the constant
  jets. -/
noncomputable def repValue : Representation ℂ G₀ (T.CovSectorAlgebra S) :=
  (repJet T S).comp jets.ofConstant

variable {T S}

@[simp]
lemma coe_repValue (g : G₀) (x : T.CovSectorAlgebra S) :
    (repValue T S g x : T.LocalFieldAlgebra) = T.repJet (jets.ofConstant g) x := rfl

lemma repValue_apply_mul (g : G₀) (x y : T.CovSectorAlgebra S) :
    repValue T S g (x * y) = repValue T S g x * repValue T S g y :=
  repJet_apply_mul (jets.ofConstant g) x y

/-- Under `GaugeFieldData.PureJetsActTrivially`, the jet action factors through
  evaluation: `LocalCovFieldAlgebra.repJet_eq_ofConstant_eval_of_mem` read on the
  sector. -/
lemma repJet_eq_repValue_eval (hP : T.PureJetsActTrivially) (U : GJ)
    (x : T.CovSectorAlgebra S) : repJet T S U x = repValue T S (jets.eval U) x :=
  Subtype.ext (LocalCovFieldAlgebra.repJet_eq_ofConstant_eval_of_mem hP U
    (le_localCovFieldAlgebra T S x.2))

/-!

### D.2. The inclusions

The restricted actions agree along `Subalgebra.inclusion` with those of a larger sector and
of the covariant field algebra.

-/

lemma inclusion_repJet {S' : Finset FieldCategory} (h : S ⊆ S') (U : GJ)
    (x : T.CovSectorAlgebra S) :
    Subalgebra.inclusion (mono T h) (repJet T S U x)
      = repJet T S' U (Subalgebra.inclusion (mono T h) x) := by
  -- `rfl` unfolds the ambient action through its universal property and times out.
  unfold repJet
  exact Representation.inclusion_restrictSubalgebra T.repJet (mono T h) _ _ U x

lemma inclusion_repLorentzGroup {S' : Finset FieldCategory} (h : S ⊆ S')
    (hGL : T.GaugeLorentzCompatible) (Λ : SL(2,ℂ)) (x : T.CovSectorAlgebra S) :
    Subalgebra.inclusion (mono T h) (repLorentzGroup T S hGL Λ x)
      = repLorentzGroup T S' hGL Λ (Subalgebra.inclusion (mono T h) x) := by
  unfold repLorentzGroup
  exact Representation.inclusion_restrictSubalgebra T.repLorentzGroup (mono T h) _ _ Λ x

lemma inclusion_repValue {S' : Finset FieldCategory} (h : S ⊆ S') (g : G₀)
    (x : T.CovSectorAlgebra S) :
    Subalgebra.inclusion (mono T h) (repValue T S g x)
      = repValue T S' g (Subalgebra.inclusion (mono T h) x) :=
  inclusion_repJet h (jets.ofConstant g) x

lemma inclusion_localCovFieldAlgebra_repJet (U : GJ) (x : T.CovSectorAlgebra S) :
    Subalgebra.inclusion (le_localCovFieldAlgebra T S) (repJet T S U x)
      = LocalCovFieldAlgebra.repJet T U (Subalgebra.inclusion (le_localCovFieldAlgebra T S) x) := by
  unfold repJet LocalCovFieldAlgebra.repJet
  exact Representation.inclusion_restrictSubalgebra T.repJet (le_localCovFieldAlgebra T S)
    _ _ U x

lemma inclusion_localCovFieldAlgebra_repLorentzGroup (hGL : T.GaugeLorentzCompatible)
    (Λ : SL(2,ℂ)) (x : T.CovSectorAlgebra S) :
    Subalgebra.inclusion (le_localCovFieldAlgebra T S) (repLorentzGroup T S hGL Λ x)
      = LocalCovFieldAlgebra.repLorentzGroup T hGL Λ
          (Subalgebra.inclusion (le_localCovFieldAlgebra T S) x) := by
  unfold repLorentzGroup LocalCovFieldAlgebra.repLorentzGroup
  exact Representation.inclusion_restrictSubalgebra T.repLorentzGroup
    (le_localCovFieldAlgebra T S) _ _ Λ x

lemma inclusion_localCovFieldAlgebra_repValue (g : G₀) (x : T.CovSectorAlgebra S) :
    Subalgebra.inclusion (le_localCovFieldAlgebra T S) (repValue T S g x)
      = LocalCovFieldAlgebra.repValue T g (Subalgebra.inclusion (le_localCovFieldAlgebra T S) x) :=
  inclusion_localCovFieldAlgebra_repJet (jets.ofConstant g) x

end CovSectorAlgebra

end GaugeFieldData
