/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.ClassicalFieldTheory.GaugeTheory.GaugeBoson.Basic

/-!
# The formal total derivative on the gauge-boson jet algebra

## i. Overview

The formal total spacetime derivative extends from the component functions of the gauge
bosons to their whole jet algebra as a derivation: it is
`SymmetricAlgebra.derivationOfLinear` applied to the shift `∂_s A_μ^φ ↦ ∂_{s + {ν}} A_μ^φ`
on the jet component space, which is right multiplication by the derivative symbol `∂_ν`
on the `DerivAlgebraReal` factor.

The four directional derivatives commute and iterate along a multiset of directions. The
jet algebra is generated by the gauge fields and their iterated derivatives, and the
derivative extends to the complexification `ℂ ⊗[ℝ] GaugeJetAlgebra` by base change, where
the ambient Lagrangian theory uses it.

## ii. Key results

- `GaugeBoson.JetComponentSpace.jetDeriv` : the derivative shift on the component space.
- `GaugeJetAlgebra.jetDeriv` : the formal total derivative, a derivation.
- `GaugeJetAlgebra.iteratedJetDeriv` : the iterated derivative along a multiset.
- `GaugeJetAlgebra.iteratedJetDeriv_ofA` : `∂_s A_μ^φ` as a generator.
- `GaugeJetAlgebra.adjoin_iteratedJetDeriv_eq_top` : the algebra is generated by the
  gauge fields and their derivatives.
- `GaugeJetAlgebra.complexJetDeriv` : the derivative on the complexification.

## iii. Table of contents

- A. The derivative on the jet component space
- B. The total derivative on the jet algebra
- C. The iterated total derivative
- D. Generation by the gauge fields and their derivatives
- E. The derivative on the complexification

-/

@[expose] public section

set_option linter.unusedSectionVars false

variable {𝔤 : Type} [LieRing 𝔤] [LieAlgebra ℝ 𝔤] [Module.Finite ℝ 𝔤]


open TensorProduct

/-!

## A. The derivative on the jet component space

-/

namespace GaugeBoson

variable (𝔤) in
/-- The derivative of components in the jet component space, in the direction `ν`: the
  shift `∂_s A_μ^φ ↦ ∂_{s + {ν}} A_μ^φ` of the derivative label, i.e. right multiplication
  by the degree-one symbol `∂_ν` on the `DerivAlgebraReal` factor. -/
noncomputable def JetComponentSpace.jetDeriv (ν : Fin 1 ⊕ Fin 3) :
    (JetComponentSpace 𝔤) →ₗ[ℝ] (JetComponentSpace 𝔤) :=
  TensorProduct.map
    (LinearMap.mulRight ℝ
      (DerivAlgebraReal.basisMultiset ({ν} : Multiset (Fin 1 ⊕ Fin 3))))
    LinearMap.id

@[simp]
lemma JetComponentSpace.jetDeriv_tmul (ν : Fin 1 ⊕ Fin 3) (a : DerivAlgebraReal)
    (φ : Module.Dual ℝ (GaugeBoson 𝔤)) :
    (JetComponentSpace.jetDeriv 𝔤) ν (a ⊗ₜ[ℝ] φ)
      = (a * DerivAlgebraReal.basisMultiset
          ({ν} : Multiset (Fin 1 ⊕ Fin 3))) ⊗ₜ[ℝ] φ := rfl

/-- Total derivatives commute on the component space: the derivative labels live in a
  symmetric algebra. -/
lemma JetComponentSpace.jetDeriv_comm (μ ν : Fin 1 ⊕ Fin 3) :
    ((JetComponentSpace.jetDeriv 𝔤) μ).comp ((JetComponentSpace.jetDeriv 𝔤) ν)
      = ((JetComponentSpace.jetDeriv 𝔤) ν).comp ((JetComponentSpace.jetDeriv 𝔤) μ) := by
  have hmul : ∀ b c : DerivAlgebraReal,
      (LinearMap.mulRight ℝ b).comp (LinearMap.mulRight ℝ c)
        = LinearMap.mulRight ℝ (c * b) :=
    fun b c => LinearMap.ext fun x => by
      simp only [LinearMap.coe_comp, Function.comp_apply, LinearMap.mulRight_apply,
        mul_assoc]
  rw [JetComponentSpace.jetDeriv, JetComponentSpace.jetDeriv, ← TensorProduct.map_comp,
    ← TensorProduct.map_comp, hmul, hmul, mul_comm]

end GaugeBoson

namespace GaugeJetAlgebra

/-!

## B. The total derivative on the jet algebra

-/

variable (𝔤) in
/-- The formal total spacetime derivative on the gauge-boson jet algebra in the direction
  `ν`: the derivation extending the shift `∂_s A_μ^φ ↦ ∂_{s + {ν}} A_μ^φ` of the component
  functions. -/
noncomputable def jetDeriv (ν : Fin 1 ⊕ Fin 3) : (GaugeJetAlgebra 𝔤) →ₗ[ℝ] (GaugeJetAlgebra 𝔤) :=
  SymmetricAlgebra.derivationOfLinear ((GaugeBoson.JetComponentSpace.jetDeriv 𝔤) ν)

@[simp]
lemma jetDeriv_ι (ν : Fin 1 ⊕ Fin 3) (x : (GaugeBoson.JetComponentSpace 𝔤)) :
    (jetDeriv 𝔤) ν (SymmetricAlgebra.ι ℝ _ x)
      = SymmetricAlgebra.ι ℝ _ ((GaugeBoson.JetComponentSpace.jetDeriv 𝔤) ν x) :=
  SymmetricAlgebra.derivationOfLinear_ι _ x

@[simp]
lemma jetDeriv_one (ν : Fin 1 ⊕ Fin 3) : (jetDeriv 𝔤) ν (1 : (GaugeJetAlgebra 𝔤)) = 0 :=
  SymmetricAlgebra.derivationOfLinear_one _

@[simp]
lemma jetDeriv_algebraMap (ν : Fin 1 ⊕ Fin 3) (r : ℝ) :
    (jetDeriv 𝔤) ν (algebraMap ℝ (GaugeJetAlgebra 𝔤) r) = 0 :=
  SymmetricAlgebra.derivationOfLinear_algebraMap _ r

/-- The total derivative is a derivation: the Leibniz rule. -/
lemma jetDeriv_mul (ν : Fin 1 ⊕ Fin 3) (x y : (GaugeJetAlgebra 𝔤)) :
    (jetDeriv 𝔤) ν (x * y) = (jetDeriv 𝔤) ν x * y + x * (jetDeriv 𝔤) ν y :=
  SymmetricAlgebra.derivationOfLinear_mul _ x y

/-- Mixed partials agree on the jet algebra. -/
lemma jetDeriv_comm_apply (μ ν : Fin 1 ⊕ Fin 3) (x : (GaugeJetAlgebra 𝔤)) :
    (jetDeriv 𝔤) μ ((jetDeriv 𝔤) ν x) = (jetDeriv 𝔤) ν ((jetDeriv 𝔤) μ x) :=
  SymmetricAlgebra.derivationOfLinear_comm_apply
    (GaugeBoson.JetComponentSpace.jetDeriv_comm μ ν) x

lemma jetDeriv_comm (μ ν : Fin 1 ⊕ Fin 3) :
    ((jetDeriv 𝔤) μ).comp ((jetDeriv 𝔤) ν) = ((jetDeriv 𝔤) ν).comp ((jetDeriv 𝔤) μ) :=
  LinearMap.ext fun x => jetDeriv_comm_apply μ ν x

/-!

## C. The iterated total derivative

-/

instance : RightCommutative
    (fun (D : (GaugeJetAlgebra 𝔤) →ₗ[ℝ] (GaugeJetAlgebra 𝔤)) (μ : Fin 1 ⊕ Fin 3) =>
      D.comp ((jetDeriv 𝔤) μ)) where
  right_comm D μ ν := by
    show (D.comp ((jetDeriv 𝔤) μ)).comp ((jetDeriv 𝔤) ν) = (D.comp ((jetDeriv 𝔤) ν)).comp
      ((jetDeriv 𝔤) μ)
    rw [LinearMap.comp_assoc, LinearMap.comp_assoc, jetDeriv_comm]

variable (𝔤) in
/-- The iterated total derivative `∂_s` along a multiset `s` of directions, well defined
  because the directional derivatives commute. -/
noncomputable def iteratedJetDeriv (s : Multiset (Fin 1 ⊕ Fin 3)) :
    (GaugeJetAlgebra 𝔤) →ₗ[ℝ] (GaugeJetAlgebra 𝔤) :=
  s.foldl (fun D μ => D.comp ((jetDeriv 𝔤) μ)) LinearMap.id

@[simp]
lemma iteratedJetDeriv_zero :
    (iteratedJetDeriv 𝔤) (0 : Multiset (Fin 1 ⊕ Fin 3)) = LinearMap.id := rfl

/-- Any initial map factors out of the fold defining the iterated derivative. -/
lemma foldl_comp_eq (s : Multiset (Fin 1 ⊕ Fin 3)) :
    ∀ D : (GaugeJetAlgebra 𝔤) →ₗ[ℝ] (GaugeJetAlgebra 𝔤),
      s.foldl (fun D μ => D.comp ((jetDeriv 𝔤) μ)) D = D ∘ₗ (iteratedJetDeriv 𝔤) s := by
  induction s using Multiset.induction_on with
  | empty =>
    intro D
    rw [iteratedJetDeriv_zero]
    rfl
  | cons ν t ih =>
    intro D
    rw [iteratedJetDeriv, Multiset.foldl_cons, Multiset.foldl_cons, ih, ih,
      LinearMap.id_comp, LinearMap.comp_assoc]

lemma iteratedJetDeriv_cons (μ : Fin 1 ⊕ Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    (iteratedJetDeriv 𝔤) (μ ::ₘ s) = (jetDeriv 𝔤) μ ∘ₗ (iteratedJetDeriv 𝔤) s := by
  rw [iteratedJetDeriv, Multiset.foldl_cons, foldl_comp_eq, LinearMap.id_comp]

@[simp]
lemma iteratedJetDeriv_singleton (μ : Fin 1 ⊕ Fin 3) :
    (iteratedJetDeriv 𝔤) ({μ} : Multiset (Fin 1 ⊕ Fin 3)) = (jetDeriv 𝔤) μ := by
  rw [show ({μ} : Multiset (Fin 1 ⊕ Fin 3)) = μ ::ₘ 0 from rfl, iteratedJetDeriv_cons,
    iteratedJetDeriv_zero, LinearMap.comp_id]

/-- Differentiating along `s + t` is differentiating along `t` and then along `s`. -/
lemma iteratedJetDeriv_add (s t : Multiset (Fin 1 ⊕ Fin 3)) :
    (iteratedJetDeriv 𝔤) (s + t) = (iteratedJetDeriv 𝔤) t ∘ₗ (iteratedJetDeriv 𝔤) s := by
  induction t using Multiset.induction_on with
  | empty => rw [add_zero, iteratedJetDeriv_zero, LinearMap.id_comp]
  | cons μ t ih =>
    rw [show s + μ ::ₘ t = μ ::ₘ (s + t) from by
        rw [← Multiset.singleton_add, ← Multiset.singleton_add, ← add_assoc,
          add_comm s ({μ} : Multiset (Fin 1 ⊕ Fin 3)), add_assoc],
      iteratedJetDeriv_cons, ih, iteratedJetDeriv_cons, LinearMap.comp_assoc]

/-- On a component function the iterated derivative writes the derivative symbol `∂_s`
  into the derivative label. -/
lemma iteratedJetDeriv_ι (s : Multiset (Fin 1 ⊕ Fin 3)) (a : DerivAlgebraReal)
    (φ : Module.Dual ℝ (GaugeBoson 𝔤)) :
    (iteratedJetDeriv 𝔤) s (SymmetricAlgebra.ι ℝ _ (a ⊗ₜ[ℝ] φ))
      = SymmetricAlgebra.ι ℝ _
          ((a * DerivAlgebraReal.basisMultiset s) ⊗ₜ[ℝ] φ) := by
  induction s using Multiset.induction_on generalizing a with
  | empty =>
    rw [iteratedJetDeriv_zero, LinearMap.id_apply,
      DerivAlgebraReal.basisMultiset_nil, mul_one]
  | cons μ s ih =>
    rw [iteratedJetDeriv_cons, LinearMap.comp_apply, ih, jetDeriv_ι,
      GaugeBoson.JetComponentSpace.jetDeriv_tmul, mul_assoc,
      DerivAlgebraReal.basisMultiset_mul,
      show s + ({μ} : Multiset (Fin 1 ⊕ Fin 3)) = μ ::ₘ s from by
        rw [add_comm, Multiset.singleton_add]]

/-- **The derivative generator `∂_s A_μ^φ`**: the iterated derivative of the gauge-field
  component function. -/
lemma iteratedJetDeriv_ofA (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ 𝔤) :
    (iteratedJetDeriv 𝔤) s ((ofA 𝔤) μ φ)
      = SymmetricAlgebra.ι ℝ _
          (DerivAlgebraReal.basisMultiset s ⊗ₜ[ℝ]
            (GaugeBoson.componentDual 𝔤) (Lorentz.CoVector.basis.dualBasis μ) φ) := by
  rw [ofA_apply, ofComponent_apply, iteratedJetDeriv_ι, one_mul]

/-!

## D. Generation by the gauge fields and their derivatives

-/

/-- Every covector on the gauge-boson target space decomposes along the Lorentz coordinate
  directions into component covectors: the spacetime index is expanded in the coordinate
  basis, while the adjoint index stays abstract. -/
lemma _root_.GaugeBoson.dual_eq_sum_componentDual
    (ψ : Module.Dual ℝ (GaugeBoson 𝔤)) :
    ψ = ∑ μ, (GaugeBoson.componentDual 𝔤) (Lorentz.CoVector.basis.dualBasis μ)
      (ψ ∘ₗ (GaugeBoson.valLinEquiv 𝔤).symm.toLinearMap ∘ₗ
        TensorProduct.mk ℝ Lorentz.CoVector 𝔤 (Lorentz.CoVector.basis μ)) := by
  refine LinearMap.ext fun v => ?_
  obtain ⟨m⟩ := v
  induction m using TensorProduct.induction_on with
  | zero =>
    rw [show (⟨0⟩ : (GaugeBoson 𝔤)) = 0 from rfl]
    simp
  | tmul x a =>
    rw [LinearMap.sum_apply]
    have hx : (⟨x ⊗ₜ[ℝ] a⟩ : (GaugeBoson 𝔤))
        = ∑ μ, Lorentz.CoVector.basis.dualBasis μ x •
            (⟨Lorentz.CoVector.basis μ ⊗ₜ[ℝ] a⟩ : (GaugeBoson 𝔤)) := by
      apply (GaugeBoson.valLinEquiv 𝔤).injective
      rw [map_sum]
      conv_lhs =>
        rw [GaugeBoson.valLinEquiv_apply,
          show (⟨x ⊗ₜ[ℝ] a⟩ : (GaugeBoson 𝔤)).val = x ⊗ₜ[ℝ] a from rfl,
          ← Lorentz.CoVector.basis.sum_repr x, TensorProduct.sum_tmul]
      refine Finset.sum_congr rfl fun μ _ => ?_
      rw [map_smul, GaugeBoson.valLinEquiv_apply,
        show (⟨Lorentz.CoVector.basis μ ⊗ₜ[ℝ] a⟩ : (GaugeBoson 𝔤)).val
          = Lorentz.CoVector.basis μ ⊗ₜ[ℝ] a from rfl, ← TensorProduct.smul_tmul',
        Module.Basis.dualBasis_apply]
    conv_lhs => rw [hx, map_sum]
    refine Finset.sum_congr rfl fun μ _ => ?_
    rw [map_smul, GaugeBoson.componentDual_apply_val_tmul, smul_eq_mul]
    rfl
  | add m₁ m₂ h₁ h₂ =>
    simp only [show (⟨m₁ + m₂⟩ : (GaugeBoson 𝔤)) = (⟨m₁⟩ : (GaugeBoson 𝔤)) + ⟨m₂⟩ from rfl,
      map_add, LinearMap.sum_apply] at h₁ h₂ ⊢
    rw [h₁, h₂, ← Finset.sum_add_distrib]

set_option maxHeartbeats 1000000 in
/-- **The jet algebra is generated by the gauge fields and their derivatives.** Every
  element is a polynomial in the derivative generators `∂_s A_μ^φ` — nothing else is
  available to write down for the gauge sector of a Lagrangian. -/
theorem adjoin_iteratedJetDeriv_eq_top :
    Algebra.adjoin ℝ
      (⋃ s : Multiset (Fin 1 ⊕ Fin 3), ⋃ μ : Fin 1 ⊕ Fin 3,
        Set.range (fun φ : Module.Dual ℝ 𝔤 => (iteratedJetDeriv 𝔤) s ((ofA 𝔤) μ φ)))
      = (⊤ : Subalgebra ℝ (GaugeJetAlgebra 𝔤)) := by
  set S : Set (GaugeJetAlgebra 𝔤) :=
    ⋃ s : Multiset (Fin 1 ⊕ Fin 3), ⋃ μ : Fin 1 ⊕ Fin 3,
      Set.range (fun φ : Module.Dual ℝ 𝔤 => (iteratedJetDeriv 𝔤) s ((ofA 𝔤) μ φ))
    with hS
  /- The derivative generators lie in the adjoined set. -/
  have hgen : ∀ (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ 𝔤),
      SymmetricAlgebra.ι ℝ _ (DerivAlgebraReal.basisMultiset s ⊗ₜ[ℝ]
        (GaugeBoson.componentDual 𝔤) (Lorentz.CoVector.basis.dualBasis μ) φ)
        ∈ Algebra.adjoin ℝ S := by
    intro s μ φ
    rw [← iteratedJetDeriv_ofA, hS]
    exact Algebra.subset_adjoin
      (Set.mem_iUnion.mpr ⟨s, Set.mem_iUnion.mpr ⟨μ, ⟨φ, rfl⟩⟩⟩)
  /- Any covector slot: expand the spacetime index in the coordinate basis. -/
  have hcomp : ∀ (s : Multiset (Fin 1 ⊕ Fin 3)) (ψ : Module.Dual ℝ (GaugeBoson 𝔤)),
      SymmetricAlgebra.ι ℝ _ (DerivAlgebraReal.basisMultiset s ⊗ₜ[ℝ] ψ)
        ∈ Algebra.adjoin ℝ S := by
    intro s ψ
    rw [show DerivAlgebraReal.basisMultiset s ⊗ₜ[ℝ] ψ
        = ∑ μ, DerivAlgebraReal.basisMultiset s ⊗ₜ[ℝ]
            (GaugeBoson.componentDual 𝔤) (Lorentz.CoVector.basis.dualBasis μ)
              (ψ ∘ₗ (GaugeBoson.valLinEquiv 𝔤).symm.toLinearMap ∘ₗ
                TensorProduct.mk ℝ Lorentz.CoVector 𝔤
                  (Lorentz.CoVector.basis μ)) from by
      conv_lhs => rw [GaugeBoson.dual_eq_sum_componentDual ψ]
      rw [TensorProduct.tmul_sum], map_sum]
    exact Subalgebra.sum_mem _ fun μ _ => hgen s μ _
  /- The derivative monomials span the `DerivAlgebraReal` factor. -/
  refine top_le_iff.mp ?_
  rw [← adjoin_ι_eq_top]
  refine Algebra.adjoin_le ?_
  rintro _ ⟨x, rfl⟩
  induction x using TensorProduct.induction_on with
  | zero => rw [map_zero]; exact zero_mem _
  | add y z hy hz => rw [map_add]; exact add_mem hy hz
  | tmul a ψ =>
    have ha : a ∈ Submodule.span ℝ (Set.range DerivAlgebraReal.basisMultiset) := by
      rw [DerivAlgebraReal.basisMultiset.span_eq]; trivial
    induction ha using Submodule.span_induction with
    | mem b hb => obtain ⟨s, rfl⟩ := hb; exact hcomp s ψ
    | zero => rw [TensorProduct.zero_tmul, map_zero]; exact zero_mem _
    | add b c _ _ hb hc => rw [TensorProduct.add_tmul, map_add]; exact add_mem hb hc
    | smul c b _ hb =>
      rw [← TensorProduct.smul_tmul', map_smul]
      exact Subalgebra.smul_mem _ hb c

/-!

## E. The derivative on the complexification

-/

variable (𝔤) in
/-- The formal total derivative on the complexified gauge-boson jet algebra, by base
  change. This is the derivative the ambient Lagrangian theory uses. -/
noncomputable def complexJetDeriv (ν : Fin 1 ⊕ Fin 3) :
    ℂ ⊗[ℝ] (GaugeJetAlgebra 𝔤) →ₗ[ℂ] ℂ ⊗[ℝ] (GaugeJetAlgebra 𝔤) :=
  LinearMap.baseChange ℂ ((jetDeriv 𝔤) ν)

@[simp]
lemma complexJetDeriv_tmul (ν : Fin 1 ⊕ Fin 3) (z : ℂ) (x : (GaugeJetAlgebra 𝔤)) :
    (complexJetDeriv 𝔤) ν (z ⊗ₜ[ℝ] x) = z ⊗ₜ[ℝ] (jetDeriv 𝔤) ν x := rfl

set_option maxHeartbeats 1000000 in
/-- The Leibniz rule on the complexification. -/
lemma complexJetDeriv_mul (ν : Fin 1 ⊕ Fin 3) (x y : ℂ ⊗[ℝ] (GaugeJetAlgebra 𝔤)) :
    (complexJetDeriv 𝔤) ν (x * y)
      = (complexJetDeriv 𝔤) ν x * y + x * (complexJetDeriv 𝔤) ν y := by
  induction x using TensorProduct.induction_on with
  | zero => simp
  | add x₁ x₂ h₁ h₂ =>
    rw [add_mul, map_add, map_add, h₁, h₂, add_mul, add_mul]
    abel
  | tmul z₁ a₁ =>
    induction y using TensorProduct.induction_on with
    | zero => simp
    | add y₁ y₂ h₁ h₂ =>
      rw [mul_add, map_add, map_add, h₁, h₂, mul_add, mul_add]
      abel
    | tmul z₂ a₂ =>
      rw [Algebra.TensorProduct.tmul_mul_tmul, complexJetDeriv_tmul, complexJetDeriv_tmul,
        complexJetDeriv_tmul, jetDeriv_mul, TensorProduct.tmul_add,
        Algebra.TensorProduct.tmul_mul_tmul, Algebra.TensorProduct.tmul_mul_tmul]

/-- The complexified total derivatives commute. -/
lemma complexJetDeriv_comm (μ ν : Fin 1 ⊕ Fin 3) :
    ((complexJetDeriv 𝔤) μ).comp ((complexJetDeriv 𝔤) ν)
      = ((complexJetDeriv 𝔤) ν).comp ((complexJetDeriv 𝔤) μ) := by
  rw [complexJetDeriv, complexJetDeriv, ← LinearMap.baseChange_comp,
    ← LinearMap.baseChange_comp, jetDeriv_comm]

end GaugeJetAlgebra

