/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.GaugeBosons.GaugeJetAlgebra.LorentzAction
public import Physlib.Particles.StandardModel.GaugeBosons.GaugeJetAlgebra.GaugeAction
public import Physlib.Particles.StandardModel.GaugeBosons.AlgebraValued.Symmeterized
/-!
# Gauge invariants of the gauge-boson jet algebra

## i. Overview

The gauge-boson jet algebra, complexified, together with its Lorentz action, jet gauge
action and gauge-field derivative symbols, is a *gauge field* in the sense of
the abstract covariance machinery of
`Physlib.Particles.StandardModel.GaugeBosons.AlgebraValued`: the structure `IsGaugeField`
holds. This file establishes that instance and instantiates the abstract classification
of invariants:

**a gauge-invariant element of the subalgebra generated by the gauge-field symbols
`∂_s A_μ^φ` — together with any set `S` of elements fixed by the pure jets — is a
polynomial in the covariant derivatives of the field strength and the elements of `S`.**

This is the covariance reduction for the gauge sector: after it, only the field
strengths, their covariant derivatives, and the matter content `S` remain.

## ii. Key results

- `GaugeJetAlgebra.gaugeField` : the gauge-field derivative symbols, as a family over the
  derivative multiset and the dual of the gauge algebra.
- `GaugeJetAlgebra.isGaugeField` : the complexified gauge-boson jet algebra is a gauge
  field.
- `GaugeJetAlgebra.invariant_mem_adjoin_fieldStrength` : the classification of gauge
  invariants.

## iii. Table of contents

- A. The gauge-field structure
  - A.1. The gauge-field derivative symbols
  - A.2. The `IsGaugeField` instance
- B. The classification of gauge invariants

-/

@[expose] public section

set_option maxHeartbeats 1000000

namespace StandardModel

namespace GaugeJetAlgebra

open TensorProduct Matrix MatrixGroups

/-!

## A. The gauge-field structure

-/

/-!

### A.1. The gauge-field derivative symbols

-/

/-- The gauge-field derivative symbols of the complexified gauge-boson jet algebra, as a
  family over the derivative multiset, the spacetime index and the dual of the gauge
  algebra — the form consumed by the abstract covariance machinery. -/
noncomputable def gaugeField (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) :
    Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] ℂ ⊗[ℝ] GaugeJetAlgebra :=
  (Lorentz.iteratedD complexJetDeriv complexJetDeriv_comm s).restrictScalars ℝ ∘ₗ
    (TensorProduct.mk ℝ ℂ GaugeJetAlgebra 1).comp (ofA μ)

@[simp]
lemma gaugeField_apply (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    gaugeField s μ φ = Lorentz.iteratedD complexJetDeriv complexJetDeriv_comm s
      ((1 : ℂ) ⊗ₜ[ℝ] ofA μ φ) := rfl

/-!

### A.2. The `IsGaugeField` instance

-/

/-- **The complexified gauge-boson jet algebra is a gauge field**: its derivative symbols
  are those of a Lorentz covector, transform under the jet gauge group by the all-orders
  Leibniz convolution of the adjoint Taylor coefficients plus the Maurer–Cartan shift, and
  the gauge action is multiplicative. -/
theorem isGaugeField :
    IsGaugeField complexRepLorentzGroup complexRepJetGaugeGroupI gaugeField where
  lorentz_apply Λ n l μ φ := by
    calc complexRepLorentzGroup Λ (gaugeField (List.ofFn l) μ φ)
        = ∑ p : Fin n → (Fin 1 ⊕ Fin 3),
            (∏ i, (((Lorentz.SL2C.toLorentzGroup Λ).1 (p i) (l i) : ℝ) : ℂ)) •
            Lorentz.iteratedD complexJetDeriv complexJetDeriv_comm (List.ofFn p)
              (complexRepLorentzGroup Λ ((1 : ℂ) ⊗ₜ[ℝ] ofA μ φ)) :=
          Lorentz.IsLorentzDeriv.rep_iteratedD_ofFn complexJetDeriv_comm Λ l
            ((1 : ℂ) ⊗ₜ[ℝ] ofA μ φ)
      _ = _ := by
          refine Finset.sum_congr rfl fun p _ => ?_
          rw [complexRepLorentzGroup_one_tmul_ofA, map_sum]
          refine congrArg (HSMul.hSMul _) (Finset.sum_congr rfl fun a _ => ?_)
          rw [map_smul]
          rfl
  gauge_apply_deriv U s μ φ := complexRepJetGaugeGroupI_iteratedD_one_tmul_ofA U s μ φ
  gauge_mul U b₁ b₂ := complexRepJetGaugeGroupI_apply_mul U b₁ b₂

/-!

## B. The classification of gauge invariants

-/

/-- **The classification of gauge invariants of the gauge-boson jet algebra**: a
  gauge-invariant element of the subalgebra generated by the gauge-field symbols
  `∂_s A_μ^φ` and a set `S` of elements fixed by the pure jets — for instance, the
  covariant towers of matter fields — is a polynomial in the covariant derivatives of the
  field strength and the elements of `S`.

  This is the covariance reduction of the gauge sector: invariance eliminates the bare
  gauge-field symbols in favour of the field strength and its covariant derivatives. -/
theorem invariant_mem_adjoin_fieldStrength
    (S : Set (ℂ ⊗[ℝ] GaugeJetAlgebra))
    (hS : ∀ y ∈ S, ∀ U : JetGaugeGroupI.truncationKer 0,
      complexRepJetGaugeGroupI U.1 y = y)
    {x : ℂ ⊗[ℝ] GaugeJetAlgebra}
    (hx : x ∈ Algebra.adjoin ℂ ({b : ℂ ⊗[ℝ] GaugeJetAlgebra |
      ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra),
      b = gaugeField p μ φ} ∪ S))
    (hinv : ∀ U : JetGaugeGroupI, complexRepJetGaugeGroupI U x = x) :
    x ∈ Algebra.adjoin ℂ ({b : ℂ ⊗[ℝ] GaugeJetAlgebra |
      ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra),
      b = IsGaugeField.iteratedCovDerivAdjoint gaugeField l
        (IsGaugeField.fieldStrength gaugeField ν lam) 0 φ} ∪ S) :=
  IsGaugeField.invariant_mem_adjoin_fieldStrength isGaugeField
    (fun _ _ _ _ _ _ => Commute.all _ _)
    S (fun _ _ _ _ _ => Commute.all _ _) hS hx hinv

end GaugeJetAlgebra

end StandardModel
