/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.GaugeBosons.GaugeJetAlgebra.Basic
public import Physlib.Particles.LagrangianTheory.Basic
/-!
# The formal total derivative on the gauge-boson jet algebra

## i. Overview

The formal total spacetime derivative extends from the component functions of the gauge
bosons to their whole jet algebra as a derivation: it is
`SymmetricAlgebra.derivationOfLinear` applied to the shift `∂_s A_μ^φ ↦ ∂_{s + {ν}} A_μ^φ`
on the jet component space, which is right multiplication by the derivative symbol `∂_ν`
on the `DerivAlgebraReal` factor.

The four directional derivatives commute and iterate along a multiset of directions. The
jet algebra is generated by the gauge fields and their iterated derivatives, and the
derivative extends to the complexification `ℂ ⊗[ℝ] GaugeJetAlgebra` by base change, where
the ambient Lagrangian theory uses it.

## ii. Key results

- `GaugeBoson.JetComponentSpace.jetDeriv` : the derivative shift on the component space.
- `GaugeJetAlgebra.jetDeriv` : the formal total derivative, a derivation.
- `GaugeJetAlgebra.iteratedJetDeriv` : the iterated derivative along a multiset.
- `GaugeJetAlgebra.iteratedJetDeriv_ofA` : `∂_s A_μ^φ` as a generator.
- `GaugeJetAlgebra.adjoin_iteratedJetDeriv_eq_top` : the algebra is generated by the
  gauge fields and their derivatives.
- `GaugeJetAlgebra.complexJetDeriv` : the derivative on the complexification.

## iii. Table of contents

- A. The derivative on the jet component space
- B. The total derivative on the jet algebra
- C. The iterated total derivative
- D. Generation by the gauge fields and their derivatives
- E. The derivative on the complexification

-/

@[expose] public section

namespace StandardModel

open TensorProduct

/-!

## A. The derivative on the jet component space

-/

namespace GaugeBoson

/-- The derivative of components in the jet component space, in the direction `ν`: the
  shift `∂_s A_μ^φ ↦ ∂_{s + {ν}} A_μ^φ` of the derivative label, i.e. right multiplication
  by the degree-one symbol `∂_ν` on the `DerivAlgebraReal` factor. -/
noncomputable def JetComponentSpace.jetDeriv (ν : Fin 1 ⊕ Fin 3) :
    JetComponentSpace →ₗ[ℝ] JetComponentSpace :=
  TensorProduct.map
    (LinearMap.mulRight ℝ
      (LagrangianTheory.dualRealJetAlgebraBasis ({ν} : Multiset (Fin 1 ⊕ Fin 3))))
    LinearMap.id

@[simp]
lemma JetComponentSpace.jetDeriv_tmul (ν : Fin 1 ⊕ Fin 3) (a : DerivAlgebraReal)
    (φ : Module.Dual ℝ GaugeBoson) :
    JetComponentSpace.jetDeriv ν (a ⊗ₜ[ℝ] φ)
      = (a * LagrangianTheory.dualRealJetAlgebraBasis
          ({ν} : Multiset (Fin 1 ⊕ Fin 3))) ⊗ₜ[ℝ] φ := rfl

/-- Total derivatives commute on the component space: the derivative labels live in a
  symmetric algebra. -/
lemma JetComponentSpace.jetDeriv_comm (μ ν : Fin 1 ⊕ Fin 3) :
    (JetComponentSpace.jetDeriv μ).comp (JetComponentSpace.jetDeriv ν)
      = (JetComponentSpace.jetDeriv ν).comp (JetComponentSpace.jetDeriv μ) := by
  have hmul : ∀ b c : DerivAlgebraReal,
      (LinearMap.mulRight ℝ b).comp (LinearMap.mulRight ℝ c)
        = LinearMap.mulRight ℝ (c * b) :=
    fun b c => LinearMap.ext fun x => by
      simp only [LinearMap.coe_comp, Function.comp_apply, LinearMap.mulRight_apply,
        mul_assoc]
  rw [JetComponentSpace.jetDeriv, JetComponentSpace.jetDeriv, ← TensorProduct.map_comp,
    ← TensorProduct.map_comp, hmul, hmul, mul_comm]

end GaugeBoson

namespace GaugeJetAlgebra

/-!

## B. The total derivative on the jet algebra

-/

/-- The formal total spacetime derivative on the gauge-boson jet algebra in the direction
  `ν`: the derivation extending the shift `∂_s A_μ^φ ↦ ∂_{s + {ν}} A_μ^φ` of the component
  functions. -/
noncomputable def jetDeriv (ν : Fin 1 ⊕ Fin 3) : GaugeJetAlgebra →ₗ[ℝ] GaugeJetAlgebra :=
  SymmetricAlgebra.derivationOfLinear (GaugeBoson.JetComponentSpace.jetDeriv ν)

@[simp]
lemma jetDeriv_ι (ν : Fin 1 ⊕ Fin 3) (x : GaugeBoson.JetComponentSpace) :
    jetDeriv ν (SymmetricAlgebra.ι ℝ _ x)
      = SymmetricAlgebra.ι ℝ _ (GaugeBoson.JetComponentSpace.jetDeriv ν x) :=
  SymmetricAlgebra.derivationOfLinear_ι _ x

@[simp]
lemma jetDeriv_one (ν : Fin 1 ⊕ Fin 3) : jetDeriv ν (1 : GaugeJetAlgebra) = 0 :=
  SymmetricAlgebra.derivationOfLinear_one _

@[simp]
lemma jetDeriv_algebraMap (ν : Fin 1 ⊕ Fin 3) (r : ℝ) :
    jetDeriv ν (algebraMap ℝ GaugeJetAlgebra r) = 0 :=
  SymmetricAlgebra.derivationOfLinear_algebraMap _ r

/-- The total derivative is a derivation: the Leibniz rule. -/
lemma jetDeriv_mul (ν : Fin 1 ⊕ Fin 3) (x y : GaugeJetAlgebra) :
    jetDeriv ν (x * y) = jetDeriv ν x * y + x * jetDeriv ν y :=
  SymmetricAlgebra.derivationOfLinear_mul _ x y

/-- Mixed partials agree on the jet algebra. -/
lemma jetDeriv_comm_apply (μ ν : Fin 1 ⊕ Fin 3) (x : GaugeJetAlgebra) :
    jetDeriv μ (jetDeriv ν x) = jetDeriv ν (jetDeriv μ x) :=
  SymmetricAlgebra.derivationOfLinear_comm_apply
    (GaugeBoson.JetComponentSpace.jetDeriv_comm μ ν) x

lemma jetDeriv_comm (μ ν : Fin 1 ⊕ Fin 3) :
    (jetDeriv μ).comp (jetDeriv ν) = (jetDeriv ν).comp (jetDeriv μ) :=
  LinearMap.ext fun x => jetDeriv_comm_apply μ ν x

/-!

## C. The iterated total derivative

-/

instance : RightCommutative
    (fun (D : GaugeJetAlgebra →ₗ[ℝ] GaugeJetAlgebra) (μ : Fin 1 ⊕ Fin 3) =>
      D.comp (jetDeriv μ)) where
  right_comm D μ ν := by
    show (D.comp (jetDeriv μ)).comp (jetDeriv ν) = (D.comp (jetDeriv ν)).comp (jetDeriv μ)
    rw [LinearMap.comp_assoc, LinearMap.comp_assoc, jetDeriv_comm]

/-- The iterated total derivative `∂_s` along a multiset `s` of directions, well defined
  because the directional derivatives commute. -/
noncomputable def iteratedJetDeriv (s : Multiset (Fin 1 ⊕ Fin 3)) :
    GaugeJetAlgebra →ₗ[ℝ] GaugeJetAlgebra :=
  s.foldl (fun D μ => D.comp (jetDeriv μ)) LinearMap.id

@[simp]
lemma iteratedJetDeriv_zero :
    iteratedJetDeriv (0 : Multiset (Fin 1 ⊕ Fin 3)) = LinearMap.id := rfl

/-- Any initial map factors out of the fold defining the iterated derivative. -/
lemma foldl_comp_eq (s : Multiset (Fin 1 ⊕ Fin 3)) :
    ∀ D : GaugeJetAlgebra →ₗ[ℝ] GaugeJetAlgebra,
      s.foldl (fun D μ => D.comp (jetDeriv μ)) D = D ∘ₗ iteratedJetDeriv s := by
  induction s using Multiset.induction_on with
  | empty =>
    intro D
    rw [iteratedJetDeriv_zero]
    rfl
  | cons ν t ih =>
    intro D
    rw [iteratedJetDeriv, Multiset.foldl_cons, Multiset.foldl_cons, ih, ih,
      LinearMap.id_comp, LinearMap.comp_assoc]

lemma iteratedJetDeriv_cons (μ : Fin 1 ⊕ Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    iteratedJetDeriv (μ ::ₘ s) = jetDeriv μ ∘ₗ iteratedJetDeriv s := by
  rw [iteratedJetDeriv, Multiset.foldl_cons, foldl_comp_eq, LinearMap.id_comp]

@[simp]
lemma iteratedJetDeriv_singleton (μ : Fin 1 ⊕ Fin 3) :
    iteratedJetDeriv ({μ} : Multiset (Fin 1 ⊕ Fin 3)) = jetDeriv μ := by
  rw [show ({μ} : Multiset (Fin 1 ⊕ Fin 3)) = μ ::ₘ 0 from rfl, iteratedJetDeriv_cons,
    iteratedJetDeriv_zero, LinearMap.comp_id]

/-- Differentiating along `s + t` is differentiating along `t` and then along `s`. -/
lemma iteratedJetDeriv_add (s t : Multiset (Fin 1 ⊕ Fin 3)) :
    iteratedJetDeriv (s + t) = iteratedJetDeriv t ∘ₗ iteratedJetDeriv s := by
  induction t using Multiset.induction_on with
  | empty => rw [add_zero, iteratedJetDeriv_zero, LinearMap.id_comp]
  | cons μ t ih =>
    rw [show s + μ ::ₘ t = μ ::ₘ (s + t) from by
        rw [← Multiset.singleton_add, ← Multiset.singleton_add, ← add_assoc,
          add_comm s ({μ} : Multiset (Fin 1 ⊕ Fin 3)), add_assoc],
      iteratedJetDeriv_cons, ih, iteratedJetDeriv_cons, LinearMap.comp_assoc]

/-- On a component function the iterated derivative writes the derivative symbol `∂_s`
  into the derivative label. -/
lemma iteratedJetDeriv_ι (s : Multiset (Fin 1 ⊕ Fin 3)) (a : DerivAlgebraReal)
    (φ : Module.Dual ℝ GaugeBoson) :
    iteratedJetDeriv s (SymmetricAlgebra.ι ℝ _ (a ⊗ₜ[ℝ] φ))
      = SymmetricAlgebra.ι ℝ _
          ((a * LagrangianTheory.dualRealJetAlgebraBasis s) ⊗ₜ[ℝ] φ) := by
  induction s using Multiset.induction_on generalizing a with
  | empty =>
    rw [iteratedJetDeriv_zero, LinearMap.id_apply,
      LagrangianTheory.dualRealJetAlgebraBasis_nil, mul_one]
  | cons μ s ih =>
    rw [iteratedJetDeriv_cons, LinearMap.comp_apply, ih, jetDeriv_ι,
      GaugeBoson.JetComponentSpace.jetDeriv_tmul, mul_assoc,
      LagrangianTheory.dualRealJetAlgebraBasis_mul,
      show s + ({μ} : Multiset (Fin 1 ⊕ Fin 3)) = μ ::ₘ s from by
        rw [add_comm, Multiset.singleton_add]]

/-- **The derivative generator `∂_s A_μ^φ`**: the iterated derivative of the gauge-field
  component function. -/
lemma iteratedJetDeriv_ofA (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    iteratedJetDeriv s (ofA μ φ)
      = SymmetricAlgebra.ι ℝ _
          (LagrangianTheory.dualRealJetAlgebraBasis s ⊗ₜ[ℝ]
            GaugeBoson.componentDual (Lorentz.CoVector.basis.dualBasis μ) φ) := by
  rw [ofA_apply, ofComponent_apply, iteratedJetDeriv_ι, one_mul]

/-!

## D. Generation by the gauge fields and their derivatives

-/

/-- Every covector on the gauge-boson target space decomposes along the Lorentz coordinate
  directions into component covectors: the spacetime index is expanded in the coordinate
  basis, while the adjoint index stays abstract. -/
lemma _root_.StandardModel.GaugeBoson.dual_eq_sum_componentDual
    (ψ : Module.Dual ℝ GaugeBoson) :
    ψ = ∑ μ, GaugeBoson.componentDual (Lorentz.CoVector.basis.dualBasis μ)
      (ψ ∘ₗ GaugeBoson.valLinEquiv.symm.toLinearMap ∘ₗ
        TensorProduct.mk ℝ Lorentz.CoVector GaugeAlgebra (Lorentz.CoVector.basis μ)) := by
  refine LinearMap.ext fun v => ?_
  obtain ⟨m⟩ := v
  induction m using TensorProduct.induction_on with
  | zero =>
    rw [show (⟨0⟩ : GaugeBoson) = 0 from rfl]
    simp
  | tmul x a =>
    rw [LinearMap.sum_apply]
    have hx : (⟨x ⊗ₜ[ℝ] a⟩ : GaugeBoson)
        = ∑ μ, Lorentz.CoVector.basis.dualBasis μ x •
            (⟨Lorentz.CoVector.basis μ ⊗ₜ[ℝ] a⟩ : GaugeBoson) := by
      apply GaugeBoson.valLinEquiv.injective
      rw [map_sum]
      conv_lhs =>
        rw [GaugeBoson.valLinEquiv_apply,
          show (⟨x ⊗ₜ[ℝ] a⟩ : GaugeBoson).val = x ⊗ₜ[ℝ] a from rfl,
          ← Lorentz.CoVector.basis.sum_repr x, TensorProduct.sum_tmul]
      refine Finset.sum_congr rfl fun μ _ => ?_
      rw [map_smul, GaugeBoson.valLinEquiv_apply,
        show (⟨Lorentz.CoVector.basis μ ⊗ₜ[ℝ] a⟩ : GaugeBoson).val
          = Lorentz.CoVector.basis μ ⊗ₜ[ℝ] a from rfl, ← TensorProduct.smul_tmul',
        Module.Basis.dualBasis_apply]
    conv_lhs => rw [hx, map_sum]
    refine Finset.sum_congr rfl fun μ _ => ?_
    rw [map_smul, GaugeBoson.componentDual_apply_val_tmul, smul_eq_mul]
    rfl
  | add m₁ m₂ h₁ h₂ =>
    simp only [show (⟨m₁ + m₂⟩ : GaugeBoson) = (⟨m₁⟩ : GaugeBoson) + ⟨m₂⟩ from rfl,
      map_add, LinearMap.sum_apply] at h₁ h₂ ⊢
    rw [h₁, h₂, ← Finset.sum_add_distrib]

set_option maxHeartbeats 1000000 in
/-- **The jet algebra is generated by the gauge fields and their derivatives.** Every
  element is a polynomial in the derivative generators `∂_s A_μ^φ` — nothing else is
  available to write down for the gauge sector of a Lagrangian. -/
theorem adjoin_iteratedJetDeriv_eq_top :
    Algebra.adjoin ℝ
      (⋃ s : Multiset (Fin 1 ⊕ Fin 3), ⋃ μ : Fin 1 ⊕ Fin 3,
        Set.range (fun φ : Module.Dual ℝ GaugeAlgebra => iteratedJetDeriv s (ofA μ φ)))
      = (⊤ : Subalgebra ℝ GaugeJetAlgebra) := by
  set S : Set GaugeJetAlgebra :=
    ⋃ s : Multiset (Fin 1 ⊕ Fin 3), ⋃ μ : Fin 1 ⊕ Fin 3,
      Set.range (fun φ : Module.Dual ℝ GaugeAlgebra => iteratedJetDeriv s (ofA μ φ))
    with hS
  /- The derivative generators lie in the adjoined set. -/
  have hgen : ∀ (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
      (φ : Module.Dual ℝ GaugeAlgebra),
      SymmetricAlgebra.ι ℝ _ (LagrangianTheory.dualRealJetAlgebraBasis s ⊗ₜ[ℝ]
        GaugeBoson.componentDual (Lorentz.CoVector.basis.dualBasis μ) φ)
        ∈ Algebra.adjoin ℝ S := by
    intro s μ φ
    rw [← iteratedJetDeriv_ofA, hS]
    exact Algebra.subset_adjoin
      (Set.mem_iUnion.mpr ⟨s, Set.mem_iUnion.mpr ⟨μ, ⟨φ, rfl⟩⟩⟩)
  /- Any covector slot: expand the spacetime index in the coordinate basis. -/
  have hcomp : ∀ (s : Multiset (Fin 1 ⊕ Fin 3)) (ψ : Module.Dual ℝ GaugeBoson),
      SymmetricAlgebra.ι ℝ _ (LagrangianTheory.dualRealJetAlgebraBasis s ⊗ₜ[ℝ] ψ)
        ∈ Algebra.adjoin ℝ S := by
    intro s ψ
    rw [show LagrangianTheory.dualRealJetAlgebraBasis s ⊗ₜ[ℝ] ψ
        = ∑ μ, LagrangianTheory.dualRealJetAlgebraBasis s ⊗ₜ[ℝ]
            GaugeBoson.componentDual (Lorentz.CoVector.basis.dualBasis μ)
              (ψ ∘ₗ GaugeBoson.valLinEquiv.symm.toLinearMap ∘ₗ
                TensorProduct.mk ℝ Lorentz.CoVector GaugeAlgebra
                  (Lorentz.CoVector.basis μ)) from by
      conv_lhs => rw [GaugeBoson.dual_eq_sum_componentDual ψ]
      rw [TensorProduct.tmul_sum], map_sum]
    exact Subalgebra.sum_mem _ fun μ _ => hgen s μ _
  /- The derivative monomials span the `DerivAlgebraReal` factor. -/
  refine top_le_iff.mp ?_
  rw [← adjoin_ι_eq_top]
  refine Algebra.adjoin_le ?_
  rintro _ ⟨x, rfl⟩
  induction x using TensorProduct.induction_on with
  | zero => rw [map_zero]; exact zero_mem _
  | add y z hy hz => rw [map_add]; exact add_mem hy hz
  | tmul a ψ =>
    have ha : a ∈ Submodule.span ℝ (Set.range LagrangianTheory.dualRealJetAlgebraBasis) := by
      rw [LagrangianTheory.dualRealJetAlgebraBasis.span_eq]; trivial
    induction ha using Submodule.span_induction with
    | mem b hb => obtain ⟨s, rfl⟩ := hb; exact hcomp s ψ
    | zero => rw [TensorProduct.zero_tmul, map_zero]; exact zero_mem _
    | add b c _ _ hb hc => rw [TensorProduct.add_tmul, map_add]; exact add_mem hb hc
    | smul c b _ hb =>
      rw [← TensorProduct.smul_tmul', map_smul]
      exact Subalgebra.smul_mem _ hb c

/-!

## E. The derivative on the complexification

-/

/-- The formal total derivative on the complexified gauge-boson jet algebra, by base
  change. This is the derivative the ambient Lagrangian theory uses. -/
noncomputable def complexJetDeriv (ν : Fin 1 ⊕ Fin 3) :
    ℂ ⊗[ℝ] GaugeJetAlgebra →ₗ[ℂ] ℂ ⊗[ℝ] GaugeJetAlgebra :=
  LinearMap.baseChange ℂ (jetDeriv ν)

@[simp]
lemma complexJetDeriv_tmul (ν : Fin 1 ⊕ Fin 3) (z : ℂ) (x : GaugeJetAlgebra) :
    complexJetDeriv ν (z ⊗ₜ[ℝ] x) = z ⊗ₜ[ℝ] jetDeriv ν x := rfl

set_option maxHeartbeats 1000000 in
/-- The Leibniz rule on the complexification. -/
lemma complexJetDeriv_mul (ν : Fin 1 ⊕ Fin 3) (x y : ℂ ⊗[ℝ] GaugeJetAlgebra) :
    complexJetDeriv ν (x * y)
      = complexJetDeriv ν x * y + x * complexJetDeriv ν y := by
  induction x using TensorProduct.induction_on with
  | zero => simp
  | add x₁ x₂ h₁ h₂ =>
    rw [add_mul, map_add, map_add, h₁, h₂, add_mul, add_mul]
    abel
  | tmul z₁ a₁ =>
    induction y using TensorProduct.induction_on with
    | zero => simp
    | add y₁ y₂ h₁ h₂ =>
      rw [mul_add, map_add, map_add, h₁, h₂, mul_add, mul_add]
      abel
    | tmul z₂ a₂ =>
      rw [Algebra.TensorProduct.tmul_mul_tmul, complexJetDeriv_tmul, complexJetDeriv_tmul,
        complexJetDeriv_tmul, jetDeriv_mul, TensorProduct.tmul_add,
        Algebra.TensorProduct.tmul_mul_tmul, Algebra.TensorProduct.tmul_mul_tmul]

/-- The complexified total derivatives commute. -/
lemma complexJetDeriv_comm (μ ν : Fin 1 ⊕ Fin 3) :
    (complexJetDeriv μ).comp (complexJetDeriv ν)
      = (complexJetDeriv ν).comp (complexJetDeriv μ) := by
  rw [complexJetDeriv, complexJetDeriv, ← LinearMap.baseChange_comp,
    ← LinearMap.baseChange_comp, jetDeriv_comm]

end GaugeJetAlgebra

end StandardModel
