/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.LinearAlgebra.AffineSpace.Independent
public import Mathlib.Analysis.Convex.Strict.Extreme
public import Mathlib.Analysis.Convex.Combination
public import Mathlib.LinearAlgebra.StdBasis
public import Mathlib.Algebra.BigOperators.Field
public import Mathlib.Topology.UnitInterval

/-!
# Simplices

Simplices as convex hulls of affinely independent points, and the standard simplex.

## i. Overview

A simplex is the convex hull of finitely many affinely independent points, its extreme points. Every
point of a simplex is a mixture of the extreme points with unique weights, its barycentric
coordinates. The model is the standard simplex of probability vectors in `ι → ℝ`, whose extreme
points are the standard basis vectors. Being a simplex is invariant under affine equivalences.

## ii. Key results

- `IsSimplex` states that a convex set is generated by finitely many affinely independent extreme
  points.
- `IsSimplex.eq_of_affineCombination_eq` proves that the weights are unique.
- `affineIndependent_of_convexCombination_eq` proves that unique weights give affine independence.
- `stdSimplexSet` is the standard simplex in `ι → ℝ`.
- `extremePoints_stdSimplexSet` proves that its extreme points are the standard basis vectors.
- `isSimplex_of_affineEquiv_stdSimplexSet` proves that a set affinely equivalent to a standard
  simplex is a simplex.

## iii. Table of contents

- A. Simplices
- B. The standard simplex
- C. Affine equivalences

## iv. References

* None.

-/

@[expose] public section

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

/-!

## A. Simplices

-/

/-- A set generated by finitely many affinely independent extreme points. -/
structure IsSimplex (K : Set E) : Prop where
  /-- There are finitely many extreme points. -/
  finite : (K.extremePoints ℝ).Finite
  /-- The set is the convex hull of its extreme points. -/
  generates : K = convexHull ℝ (K.extremePoints ℝ)
  /-- The extreme points are affinely independent. -/
  affineIndependent : AffineIndependent ℝ (Subtype.val : ↥(K.extremePoints ℝ) → E)

/-- Two convex combinations of the extreme points of a simplex giving the same point have the
same weights. -/
lemma IsSimplex.eq_of_affineCombination_eq {K : Set E} (hK : IsSimplex K)
    (s₁ s₂ : Finset ↥(K.extremePoints ℝ)) (w₁ w₂ : ↥(K.extremePoints ℝ) → ℝ)
    (hw₁ : ∑ i ∈ s₁, w₁ i = 1) (hw₂ : ∑ i ∈ s₂, w₂ i = 1)
    (heq : s₁.affineCombination ℝ Subtype.val w₁ = s₂.affineCombination ℝ Subtype.val w₂) :
    Set.indicator (↑s₁) w₁ = Set.indicator (↑s₂) w₂ :=
  hK.affineIndependent.indicator_eq_of_affineCombination_eq s₁ s₂ w₁ w₂ hw₁ hw₂ heq

/-- A set generated by two distinct extreme points is a simplex. -/
lemma isSimplex_of_extremePoints_eq_pair {K : Set E} {p q : E} (hpq : p ≠ q)
    (hK : K = convexHull ℝ {p, q}) (hext : K.extremePoints ℝ = {p, q}) : IsSimplex K where
  finite := hext ▸ (Set.finite_singleton q).insert p
  generates := hK.trans (by rw [hext])
  affineIndependent := by
    have hrange : Set.range ![p, q] = {p, q} := by simp [Set.pair_comm]
    rw [hext, ← hrange]
    exact (affineIndependent_of_ne ℝ hpq).range

/-- A simplex has at most `finrank + 1` extreme points. -/
lemma IsSimplex.card_le_finrank_add_one_of_mapsTo {K : Set E} [FiniteDimensional ℝ E]
    (hK : IsSimplex K) {ι : Type*} [Fintype ι] {p : ι → E} (hp : Function.Injective p)
    (hpK : ∀ i, p i ∈ K.extremePoints ℝ) :
    Fintype.card ι ≤ Module.finrank ℝ E + 1 := by
  rcases isEmpty_or_nonempty ι with _ | _
  · simp
  let q : ι ↪ ↥(K.extremePoints ℝ) :=
    ⟨fun i => ⟨p i, hpK i⟩, fun i j hij => hp (congrArg Subtype.val hij)⟩
  have hp' : AffineIndependent ℝ p := hK.affineIndependent.comp_embedding q
  have := hp'.finrank_vectorSpan_add_one
  have := Submodule.finrank_le (vectorSpan ℝ (Set.range p))
  omega

/-- Splitting weights summing to zero into positive and negative parts gives equal sums. -/
lemma sum_max_neg_zero_eq {ι : Type*} {s : Finset ι} {w : ι → ℝ} (hw : ∑ i ∈ s, w i = 0) :
    ∑ i ∈ s, max (-w i) 0 = ∑ i ∈ s, max (w i) 0 := by
  have : ∑ i ∈ s, (max (w i) 0 - max (-w i) 0) = 0 := by
    simpa only [max_zero_sub_max_neg_zero_eq_self] using hw
  rw [Finset.sum_sub_distrib] at this
  linarith

lemma sum_max_smul_eq {ι : Type*} {s : Finset ι} {w : ι → ℝ} {p : ι → E}
    (hwp : ∑ i ∈ s, w i • p i = 0) :
    ∑ i ∈ s, max (w i) 0 • p i = ∑ i ∈ s, max (-w i) 0 • p i := by
  rw [← sub_eq_zero, ← Finset.sum_sub_distrib]
  simpa only [← sub_smul, max_zero_sub_max_neg_zero_eq_self] using hwp

/-- A family is affinely independent when its convex combinations have unique weights. -/
lemma affineIndependent_of_convexCombination_eq {ι : Type*} {p : ι → E}
    (h : ∀ (s : Finset ι) (w₁ w₂ : ι → ℝ), (∀ i ∈ s, 0 ≤ w₁ i) → (∀ i ∈ s, 0 ≤ w₂ i) →
      ∑ i ∈ s, w₁ i = 1 → ∑ i ∈ s, w₂ i = 1 → ∑ i ∈ s, w₁ i • p i = ∑ i ∈ s, w₂ i • p i →
      ∀ i ∈ s, w₁ i = w₂ i) : AffineIndependent ℝ p := by
  refine affineIndependent_iff.2 fun s w hw hwp i hi => ?_
  have hneg := sum_max_neg_zero_eq hw
  set m := ∑ j ∈ s, max (w j) 0
  suffices max (w i) 0 = max (-w i) 0 by linarith [max_zero_sub_max_neg_zero_eq_self (w i)]
  rcases (Finset.sum_nonneg fun j _ => le_max_right (w j) 0 : 0 ≤ m).eq_or_lt with hm | hm
  · rw [(Finset.sum_eq_zero_iff_of_nonneg fun j _ => le_max_right (w j) 0).1 hm.symm i hi,
      (Finset.sum_eq_zero_iff_of_nonneg fun j _ => le_max_right (-w j) 0).1
        (hneg.trans hm.symm) i hi]
  have := h s (fun j => max (w j) 0 / m) (fun j => max (-w j) 0 / m)
    (fun j _ => div_nonneg (le_max_right _ _) hm.le)
    (fun j _ => div_nonneg (le_max_right _ _) hm.le)
    (by rw [← Finset.sum_div, div_self hm.ne']) (by rw [← Finset.sum_div, hneg, div_self hm.ne'])
    (by simp only [div_eq_inv_mul, mul_smul, ← Finset.smul_sum, sum_max_smul_eq hwp]) i hi
  exact (div_left_inj' hm.ne').1 this

/-!

## B. The standard simplex

-/

variable (ι : Type*) [Fintype ι]

/-- The standard simplex in `ι → ℝ`: the vectors with nonnegative coordinates summing to `1`. -/
def stdSimplexSet : Set (ι → ℝ) := {f | (∀ i, 0 ≤ f i) ∧ ∑ i, f i = 1}

lemma convex_stdSimplexSet : Convex ℝ (stdSimplexSet ι) := by
  refine fun f hf g hg a b ha hb hab => ⟨fun i => ?_, ?_⟩
  · simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul]
    exact add_nonneg (mul_nonneg ha (hf.1 i)) (mul_nonneg hb (hg.1 i))
  · simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul, Finset.sum_add_distrib, ← Finset.mul_sum,
      hf.2, hg.2, mul_one, hab]

variable {ι}

lemma le_one_of_mem_stdSimplexSet {f : ι → ℝ} (hf : f ∈ stdSimplexSet ι) (i : ι) : f i ≤ 1 :=
  hf.2 ▸ Finset.single_le_sum (fun j _ => hf.1 j) (Finset.mem_univ i)

variable [DecidableEq ι]

lemma single_mem_stdSimplexSet (i : ι) : Pi.single i (1 : ℝ) ∈ stdSimplexSet ι :=
  ⟨fun j => by by_cases h : j = i <;> simp [h], by simp⟩

/-- A point of the standard simplex with coordinate `1` at `i` is the `i`-th basis vector. -/
lemma eq_single_of_mem_stdSimplexSet {f : ι → ℝ} (hf : f ∈ stdSimplexSet ι) {i : ι}
    (hi : f i = 1) : f = Pi.single i 1 := by
  have h := hf.2
  rw [← Finset.add_sum_erase _ _ (Finset.mem_univ i), hi, add_eq_left,
    Finset.sum_eq_zero_iff_of_nonneg fun j _ => hf.1 j] at h
  funext j
  rcases eq_or_ne j i with rfl | hj
  · simp [hi]
  · simp [hj, h j (Finset.mem_erase.mpr ⟨hj, Finset.mem_univ j⟩)]

lemma convexHull_range_single :
    convexHull ℝ (Set.range fun i : ι => Pi.single i (1 : ℝ)) = stdSimplexSet ι := by
  refine (convexHull_min (Set.range_subset_iff.2 single_mem_stdSimplexSet)
    (convex_stdSimplexSet ι)).antisymm fun w ⟨hw₀, hw₁⟩ => ?_
  have hw : w = ∑ i, w i • Pi.single i (1 : ℝ) := by
    ext j
    simp [Finset.sum_apply, Pi.single_apply]
  rw [hw, ← Finset.univ.centerMass_eq_of_sum_1 _ hw₁]
  exact Finset.univ.centerMass_mem_convexHull (fun i _ => hw₀ i) (hw₁.symm ▸ zero_lt_one)
    fun i _ => Set.mem_range_self i

/-- The extreme points of the standard simplex are the standard basis vectors. -/
lemma extremePoints_stdSimplexSet :
    (stdSimplexSet ι).extremePoints ℝ = Set.range fun i : ι => Pi.single i (1 : ℝ) := by
  refine subset_antisymm ?_ (Set.range_subset_iff.2 fun i =>
    mem_extremePoints.2 ⟨single_mem_stdSimplexSet i, ?_⟩)
  · conv_lhs => rw [← convexHull_range_single]
    exact extremePoints_convexHull_subset
  rintro y hy z hz ⟨a, b, ha, hb, hab, h⟩
  have hi : a * y i + b * z i = 1 := by simpa using congrFun h i
  have hy1 := le_one_of_mem_stdSimplexSet hy i
  have hz1 := le_one_of_mem_stdSimplexSet hz i
  exact ⟨eq_single_of_mem_stdSimplexSet hy (by nlinarith),
    eq_single_of_mem_stdSimplexSet hz (by nlinarith)⟩

omit [Fintype ι] in
lemma affineIndependent_pi_single : AffineIndependent ℝ fun i : ι => Pi.single i (1 : ℝ) :=
  (Pi.linearIndependent_single_one ι ℝ).affineIndependent

lemma isSimplex_stdSimplexSet : IsSimplex (stdSimplexSet ι) where
  finite := by rw [extremePoints_stdSimplexSet]; exact Set.finite_range _
  generates := by rw [extremePoints_stdSimplexSet, convexHull_range_single]
  affineIndependent := by
    rw [extremePoints_stdSimplexSet]
    exact affineIndependent_pi_single.range

/-!

## C. Affine equivalences

-/

variable {F : Type*} [AddCommGroup F] [Module ℝ F]

/-- An affine equivalence maps extreme points to extreme points. -/
lemma AffineEquiv.image_extremePoints (e : E ≃ᵃ[ℝ] F) (s : Set E) :
    e '' s.extremePoints ℝ = (e '' s).extremePoints ℝ := by
  ext b
  obtain ⟨a, rfl⟩ := e.surjective b
  have : ∀ x y, e '' openSegment ℝ x y = openSegment ℝ (e x) (e y) :=
    image_openSegment _ e.toAffineMap
  simp only [mem_extremePoints, e.surjective.forall, e.injective.mem_set_image,
    e.injective.eq_iff, ← this]

/-- The image of a simplex under an affine equivalence is a simplex. -/
lemma IsSimplex.map {K : Set E} (hK : IsSimplex K) (e : E ≃ᵃ[ℝ] F) : IsSimplex (e '' K) where
  finite := e.image_extremePoints K ▸ hK.finite.image _
  generates := by
    rw [← e.image_extremePoints K]
    conv_lhs => rw [hK.generates]
    exact AffineMap.image_convexHull (e : E →ᵃ[ℝ] F) _
  affineIndependent := by
    rw [← e.image_extremePoints K]
    exact e.affineIndependent_set_of_eq_iff.mpr hK.affineIndependent

omit [DecidableEq ι] in
/-- A set affinely equivalent to a standard simplex is a simplex. -/
lemma isSimplex_of_affineEquiv_stdSimplexSet {K : Set E} (e : E ≃ᵃ[ℝ] (ι → ℝ))
    (hK : e '' K = stdSimplexSet ι) : IsSimplex K := by
  classical
  simpa [Set.image_image, ← hK] using isSimplex_stdSimplexSet.map e.symm

/-- The unit interval is a simplex. -/
lemma isSimplex_unitInterval : IsSimplex (unitInterval : Set ℝ) :=
  isSimplex_of_extremePoints_eq_pair zero_ne_one
    (by rw [convexHull_pair, segment_eq_Icc zero_le_one]) (Set.extremePoints_Icc zero_le_one)
