/-
Copyright (c) 2026 Nathaneal Sajan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathaneal Sajan
-/
module

public import Physlib.ClassicalFieldTheory.GaugeTheory.GaugeBoson.LocalGaugeFieldAlgebra.FieldStrength
public import Physlib.Mathematics.AlgebraRepresentation
/-!
# The covariant field algebra of the gauge bosons

## i. Overview

`LocalGaugeCovFieldAlgebra 𝔤` is the real unital subalgebra of
`LocalGaugeFieldAlgebra 𝔤` generated by the field strength and its iterated covariant
derivatives `∇_{l₁} ⋯ ∇_{lₙ} F_μν^φ` — the set `GaugeAlgebraRealization.tower` of the
family `derivA 𝔤` — together with the scalars.

Its elements are gauge covariant, not gauge invariant: a jet acts on each generator
through the base-point adjoint action of its value alone, rotating the adjoint index, so
the subalgebra is preserved and the jet action on it factors through evaluation to the
ordinary gauge group. The Lorentz group preserves it too, the generators mixing among
themselves. The canonical inclusion into the ambient algebra is `Subalgebra.val`, and the
restricted actions are built with `Representation.restrictSubalgebra`.

## ii. Key results

- `LocalGaugeCovFieldAlgebra` : the covariant field algebra, with
  `LocalGaugeCovFieldAlgebra.induction`, `LocalGaugeCovFieldAlgebra.mapsTo` and
  `LocalGaugeCovFieldAlgebra.algHom_ext` as its generation API.
- `LocalGaugeCovFieldAlgebra.covF` : the generators `∇_l F_μν^φ` as elements of the
  covariant field algebra.
- `LocalGaugeCovFieldAlgebra.repJet`, `LocalGaugeCovFieldAlgebra.repValue`,
  `LocalGaugeCovFieldAlgebra.repLorentzGroup` : the restricted actions of the jet gauge
  group, of the ordinary gauge group and of the Lorentz group.
- `LocalGaugeCovFieldAlgebra.repJet_eq_repValue_eval` : the jet action factors through
  evaluation.
- `LocalGaugeCovFieldAlgebra.complexVal` : the complexified inclusion, injective by
  flatness, with the complexified actions `complexRepValue` and `complexRepLorentzGroup`.

## iii. Table of contents

- A. The covariant field algebra
  - A.1. Generation
  - A.2. The generators as elements of the covariant field algebra
- B. Stability under the actions
- C. The restricted actions
  - C.1. The action of the ordinary gauge group
  - C.2. The actions on the generators
- D. The complexification

-/

@[expose] public section

set_option linter.unusedSectionVars false

variable {G₀ : Type} [Group G₀] {𝔤 : Type} [LieRing 𝔤] [LieAlgebra ℝ 𝔤] [Module.Finite ℝ 𝔤]
variable {GJ : Type} [Group GJ] {𝔤J : Type} [LieRing 𝔤J] [LieAlgebra ℝ 𝔤J]
variable {jets : LocalGaugeData G₀ 𝔤 GJ 𝔤J}

open TensorProduct Matrix MatrixGroups Lorentz
open LocalGaugeFieldAlgebra (derivA fieldStrength covDerivFieldStrength repJetAlgHom
  repJet_covDerivFieldStrength_eval repLorentzGroup_covDerivFieldStrength repJet_algebraMap
  repJet_apply_mul)

/-!

## A. The covariant field algebra

-/

variable (𝔤) in
/-- The covariant field algebra of the gauge bosons: the real unital subalgebra of the
  local gauge field algebra generated by the field strength and its iterated covariant
  derivatives `∇_{l₁} ⋯ ∇_{lₙ} F_μν^φ`, along all ordered lists of directions. -/
noncomputable def LocalGaugeCovFieldAlgebra : Subalgebra ℝ (LocalGaugeFieldAlgebra 𝔤) :=
  Algebra.adjoin ℝ (GaugeAlgebraRealization.tower (derivA 𝔤))

namespace LocalGaugeCovFieldAlgebra

/-- The generating set, as the covariant derivatives of the field strength. -/
lemma mem_tower_iff (x : LocalGaugeFieldAlgebra 𝔤) :
    x ∈ GaugeAlgebraRealization.tower (derivA 𝔤) ↔
      ∃ (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤),
        x = covDerivFieldStrength 𝔤 l μ ν φ :=
  Iff.rfl

/-!

### A.1. Generation

-/

lemma covDerivFieldStrength_mem (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ 𝔤) : covDerivFieldStrength 𝔤 l μ ν φ ∈ LocalGaugeCovFieldAlgebra 𝔤 :=
  Algebra.subset_adjoin ⟨l, μ, ν, φ, rfl⟩

lemma fieldStrength_mem (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤) :
    fieldStrength 𝔤 μ ν φ ∈ LocalGaugeCovFieldAlgebra 𝔤 :=
  covDerivFieldStrength_mem [] μ ν φ

/-- Inside the covariant field algebra, the preimage of the generating tower under the
  inclusion generates the whole real subalgebra. -/
lemma adjoin_preimage_tower_eq_top :
    Algebra.adjoin ℝ ((Subtype.val : LocalGaugeCovFieldAlgebra 𝔤 → LocalGaugeFieldAlgebra 𝔤)
      ⁻¹' GaugeAlgebraRealization.tower (derivA 𝔤)) = ⊤ :=
  Algebra.adjoin_adjoin_coe_preimage

/-- The generation principle: a property holding on the covariant derivatives of the
  field strength and on the scalars, and closed under sums and products, holds on the
  whole covariant field algebra. -/
lemma induction {P : LocalGaugeFieldAlgebra 𝔤 → Prop} {x : LocalGaugeFieldAlgebra 𝔤}
    (hx : x ∈ LocalGaugeCovFieldAlgebra 𝔤)
    (hgen : ∀ (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤),
      P (covDerivFieldStrength 𝔤 l μ ν φ))
    (halg : ∀ r : ℝ, P (algebraMap ℝ (LocalGaugeFieldAlgebra 𝔤) r))
    (hadd : ∀ x y, P x → P y → P (x + y))
    (hmul : ∀ x y, P x → P y → P (x * y)) : P x := by
  induction hx using Algebra.adjoin_induction with
  | mem b hb =>
    obtain ⟨l, μ, ν, φ, rfl⟩ := hb
    exact hgen l μ ν φ
  | algebraMap r => exact halg r
  | add a b _ _ ha hb => exact hadd a b ha hb
  | mul a b _ _ ha hb => exact hmul a b ha hb

/-- An algebra endomorphism carrying the generators into the covariant field algebra
  carries the whole covariant field algebra into itself. -/
lemma mapsTo (f : LocalGaugeFieldAlgebra 𝔤 →ₐ[ℝ] LocalGaugeFieldAlgebra 𝔤)
    (hgen : ∀ (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤),
      f (covDerivFieldStrength 𝔤 l μ ν φ) ∈ LocalGaugeCovFieldAlgebra 𝔤)
    {x : LocalGaugeFieldAlgebra 𝔤} (hx : x ∈ LocalGaugeCovFieldAlgebra 𝔤) :
    f x ∈ LocalGaugeCovFieldAlgebra 𝔤 := by
  have hle : (LocalGaugeCovFieldAlgebra 𝔤).map f ≤ LocalGaugeCovFieldAlgebra 𝔤 := by
    rw [LocalGaugeCovFieldAlgebra, ← Algebra.adjoin_image]
    refine Algebra.adjoin_le ?_
    rintro _ ⟨_, ⟨l, μ, ν, φ, rfl⟩, rfl⟩
    exact hgen l μ ν φ
  exact hle ⟨x, hx, rfl⟩

/-!

### A.2. The generators as elements of the covariant field algebra

-/

variable (𝔤) in
/-- The generators `∇_l F_μν^φ` of the covariant field algebra, as elements of it. -/
noncomputable def covF (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) :
    Module.Dual ℝ 𝔤 →ₗ[ℝ] LocalGaugeCovFieldAlgebra 𝔤 where
  toFun φ := ⟨covDerivFieldStrength 𝔤 l μ ν φ, covDerivFieldStrength_mem l μ ν φ⟩
  map_add' _ _ := Subtype.ext (map_add _ _ _)
  map_smul' _ _ := Subtype.ext (map_smul _ _ _)

@[simp]
lemma coe_covF (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤) :
    (covF 𝔤 l μ ν φ : LocalGaugeFieldAlgebra 𝔤) = covDerivFieldStrength 𝔤 l μ ν φ := rfl

lemma coe_covF_nil (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤) :
    (covF 𝔤 [] μ ν φ : LocalGaugeFieldAlgebra 𝔤) = fieldStrength 𝔤 μ ν φ := rfl

lemma val_comp_covF (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) :
    (LocalGaugeCovFieldAlgebra 𝔤).val.toLinearMap ∘ₗ covF 𝔤 l μ ν
      = covDerivFieldStrength 𝔤 l μ ν := rfl

/-- Two algebra maps out of the covariant field algebra agreeing on the generators are
  equal. This is uniqueness only: the covariant field algebra is not free on the generators,
  so an assignment of their images does not by itself define a map. -/
lemma algHom_ext {B : Type} [Semiring B] [Algebra ℝ B]
    {f g : LocalGaugeCovFieldAlgebra 𝔤 →ₐ[ℝ] B}
    (h : ∀ (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤),
      f (covF 𝔤 l μ ν φ) = g (covF 𝔤 l μ ν φ)) : f = g :=
  AlgHom.ext_of_eq_adjoin rfl fun x hx => by
    obtain ⟨l, μ, ν, φ, rfl⟩ := hx
    exact h l μ ν φ

/-!

## B. Stability under the actions

-/

/-- The jet gauge group preserves the covariant field algebra: a jet rotates the adjoint
  index of each generator through the value of its inverse. -/
lemma repJet_mem (U : GJ) {x : LocalGaugeFieldAlgebra 𝔤}
    (hx : x ∈ LocalGaugeCovFieldAlgebra 𝔤) :
    LocalGaugeFieldAlgebra.repJet jets U x ∈ LocalGaugeCovFieldAlgebra 𝔤 :=
  mapsTo (repJetAlgHom jets U) (fun l μ ν φ => by
    show LocalGaugeFieldAlgebra.repJet jets U (covDerivFieldStrength 𝔤 l μ ν φ) ∈ _
    rw [repJet_covDerivFieldStrength_eval]
    exact covDerivFieldStrength_mem l μ ν _) hx

/-- The Lorentz group preserves the covariant field algebra: the generators mix among
  themselves by the columns of the Lorentz matrix. -/
lemma repLorentzGroup_mem (Λ : SL(2,ℂ)) {x : LocalGaugeFieldAlgebra 𝔤}
    (hx : x ∈ LocalGaugeCovFieldAlgebra 𝔤) :
    LocalGaugeFieldAlgebra.repLorentzGroup 𝔤 Λ x ∈ LocalGaugeCovFieldAlgebra 𝔤 :=
  mapsTo (SymmetricAlgebra.map (GaugeBoson.JetComponentSpace.repLorentzGroup 𝔤 Λ))
    (fun l μ ν φ => by
      show LocalGaugeFieldAlgebra.repLorentzGroup 𝔤 Λ (covDerivFieldStrength 𝔤 l μ ν φ) ∈ _
      obtain ⟨n, l', rfl⟩ : ∃ (n : ℕ) (l' : Fin n → (Fin 1 ⊕ Fin 3)), l = List.ofFn l' :=
        ⟨_, l.get, (List.ofFn_get l).symm⟩
      rw [repLorentzGroup_covDerivFieldStrength]
      exact Subalgebra.sum_mem _ fun p _ => Subalgebra.smul_mem _
        (Subalgebra.sum_mem _ fun a _ => Subalgebra.smul_mem _
          (Subalgebra.sum_mem _ fun b _ => Subalgebra.smul_mem _
            (covDerivFieldStrength_mem _ a b φ) _) _) _) hx

/-!

## C. The restricted actions

-/

variable (jets) in
/-- The action of the jet gauge group on the covariant field algebra, restricted from the
  local gauge field algebra. -/
noncomputable def repJet : Representation ℝ GJ (LocalGaugeCovFieldAlgebra 𝔤) :=
  (LocalGaugeFieldAlgebra.repJet jets).restrictSubalgebra _ fun U _ hx => repJet_mem U hx

@[simp]
lemma coe_repJet (U : GJ) (x : LocalGaugeCovFieldAlgebra 𝔤) :
    (repJet jets U x : LocalGaugeFieldAlgebra 𝔤) = LocalGaugeFieldAlgebra.repJet jets U x := rfl

lemma repJet_apply_mul (U : GJ) (x y : LocalGaugeCovFieldAlgebra 𝔤) :
    repJet jets U (x * y) = repJet jets U x * repJet jets U y :=
  Subtype.ext (LocalGaugeFieldAlgebra.repJet_apply_mul U (x : LocalGaugeFieldAlgebra 𝔤) y)

variable (𝔤) in
/-- The action of the Lorentz group on the covariant field algebra, restricted from the
  local gauge field algebra. -/
noncomputable def repLorentzGroup : Representation ℝ SL(2,ℂ) (LocalGaugeCovFieldAlgebra 𝔤) :=
  (LocalGaugeFieldAlgebra.repLorentzGroup 𝔤).restrictSubalgebra _
    fun Λ _ hx => repLorentzGroup_mem Λ hx

@[simp]
lemma coe_repLorentzGroup (Λ : SL(2,ℂ)) (x : LocalGaugeCovFieldAlgebra 𝔤) :
    (repLorentzGroup 𝔤 Λ x : LocalGaugeFieldAlgebra 𝔤)
      = LocalGaugeFieldAlgebra.repLorentzGroup 𝔤 Λ x := rfl

lemma repLorentzGroup_apply_mul (Λ : SL(2,ℂ)) (x y : LocalGaugeCovFieldAlgebra 𝔤) :
    repLorentzGroup 𝔤 Λ (x * y) = repLorentzGroup 𝔤 Λ x * repLorentzGroup 𝔤 Λ y :=
  Subtype.ext
    (LocalGaugeFieldAlgebra.repLorentzGroup_apply_mul Λ (x : LocalGaugeFieldAlgebra 𝔤) y)

/-!

### C.1. The action of the ordinary gauge group

-/

variable (jets) in
/-- The action of the ordinary gauge group on the covariant field algebra: the jet action
  at the constant jets. -/
noncomputable def repValue : Representation ℝ G₀ (LocalGaugeCovFieldAlgebra 𝔤) :=
  (repJet jets).comp jets.ofConstant

@[simp]
lemma coe_repValue (g : G₀) (x : LocalGaugeCovFieldAlgebra 𝔤) :
    (repValue jets g x : LocalGaugeFieldAlgebra 𝔤)
      = LocalGaugeFieldAlgebra.repJet jets (jets.ofConstant g) x := rfl

lemma repValue_apply_mul (g : G₀) (x y : LocalGaugeCovFieldAlgebra 𝔤) :
    repValue jets g (x * y) = repValue jets g x * repValue jets g y :=
  repJet_apply_mul (jets.ofConstant g) x y

/-- The action of the jet gauge group on the covariant field algebra factors through
  evaluation: a jet acts as the constant jet of its value. The derivatives of a gauge
  transformation act trivially on covariant expressions. -/
theorem repJet_eq_repValue_eval (U : GJ) (x : LocalGaugeCovFieldAlgebra 𝔤) :
    repJet jets U x = repValue jets (jets.eval U) x := by
  refine Subtype.ext ?_
  rw [coe_repJet, coe_repValue]
  refine LocalGaugeCovFieldAlgebra.induction (P := fun y => LocalGaugeFieldAlgebra.repJet jets U y
    = LocalGaugeFieldAlgebra.repJet jets (jets.ofConstant (jets.eval U)) y) x.2 ?_ ?_ ?_ ?_
  · intro l μ ν φ
    rw [repJet_covDerivFieldStrength_eval, repJet_covDerivFieldStrength_eval,
      map_inv jets.eval, map_inv jets.eval, jets.eval_ofConstant]
  · intro r
    rw [repJet_algebraMap, repJet_algebraMap]
  · intro x y hx hy
    rw [map_add, map_add, hx, hy]
  · intro x y hx hy
    rw [LocalGaugeFieldAlgebra.repJet_apply_mul, LocalGaugeFieldAlgebra.repJet_apply_mul, hx, hy]

/-!

### C.2. The actions on the generators

-/

/-- The ordinary gauge group rotates the adjoint index of a generator through the dual
  adjoint action of the inverse. -/
lemma repValue_covF (g : G₀) (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ 𝔤) :
    repValue jets g (covF 𝔤 l μ ν φ) = covF 𝔤 l μ ν ((jets.adjointValue g⁻¹).dualMap φ) := by
  refine Subtype.ext ?_
  rw [coe_repValue, coe_covF, coe_covF, repJet_covDerivFieldStrength_eval, map_inv jets.eval,
    jets.eval_ofConstant]

/-- A jet acts on a generator through the value of its inverse alone. -/
lemma repJet_covF (U : GJ) (l : List (Fin 1 ⊕ Fin 3)) (μ ν : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ 𝔤) :
    repJet jets U (covF 𝔤 l μ ν φ)
      = covF 𝔤 l μ ν ((jets.adjointValue (jets.eval U⁻¹)).dualMap φ) := by
  rw [repJet_eq_repValue_eval, repValue_covF, map_inv jets.eval]

/-- The Lorentz law of the generators: every covariant slot and both covector indices mix
  by the columns of the Lorentz matrix. -/
lemma repLorentzGroup_covF (Λ : SL(2,ℂ)) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (μ ν : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤) :
    repLorentzGroup 𝔤 Λ (covF 𝔤 (List.ofFn l) μ ν φ)
      = ∑ p : Fin n → (Fin 1 ⊕ Fin 3), (∏ i, ((SL2C.toLorentzGroup Λ).1 (p i) (l i) : ℝ)) •
          ∑ a, ((SL2C.toLorentzGroup Λ).1 a μ : ℝ) • ∑ b, ((SL2C.toLorentzGroup Λ).1 b ν : ℝ) •
            covF 𝔤 (List.ofFn p) a b φ := by
  refine Subtype.ext ?_
  rw [coe_repLorentzGroup, coe_covF, repLorentzGroup_covDerivFieldStrength]
  simp only [AddSubmonoidClass.coe_finsetSum, Subalgebra.coe_smul, coe_covF]

/-!

## D. The complexification

The real covariant field algebra base changed along `ℝ → ℂ`, for the comparison with the
covariant gauge sector of a field datum; the complexified inclusion is injective by
flatness of `ℂ` over `ℝ`.

-/

variable (𝔤) in
/-- The complexified covariant field algebra inside the complexified local gauge field
  algebra: the base change of `Subalgebra.val` along `ℝ → ℂ`. -/
noncomputable def complexVal :
    (ℂ ⊗[ℝ] LocalGaugeCovFieldAlgebra 𝔤) →ₐ[ℂ] ℂ ⊗[ℝ] LocalGaugeFieldAlgebra 𝔤 :=
  Algebra.TensorProduct.map (AlgHom.id ℂ ℂ) (LocalGaugeCovFieldAlgebra 𝔤).val

@[simp]
lemma complexVal_tmul (z : ℂ) (x : LocalGaugeCovFieldAlgebra 𝔤) :
    complexVal 𝔤 (z ⊗ₜ[ℝ] x) = z ⊗ₜ[ℝ] (x : LocalGaugeFieldAlgebra 𝔤) := rfl

lemma complexVal_injective : Function.Injective (complexVal 𝔤) :=
  Module.Flat.lTensor_preserves_injective_linearMap
    (LocalGaugeCovFieldAlgebra 𝔤).val.toLinearMap Subtype.val_injective

variable (jets) in
/-- The action of the ordinary gauge group on the complexified covariant field algebra, by
  base change. -/
noncomputable def complexRepValue :
    Representation ℂ G₀ (ℂ ⊗[ℝ] LocalGaugeCovFieldAlgebra 𝔤) :=
  Representation.baseChange ℂ (repValue jets)

@[simp]
lemma complexRepValue_tmul (g : G₀) (z : ℂ) (x : LocalGaugeCovFieldAlgebra 𝔤) :
    complexRepValue jets g (z ⊗ₜ[ℝ] x) = z ⊗ₜ[ℝ] repValue jets g x := rfl

variable (𝔤) in
/-- The Lorentz action on the complexified covariant field algebra, by base change. -/
noncomputable def complexRepLorentzGroup :
    Representation ℂ SL(2,ℂ) (ℂ ⊗[ℝ] LocalGaugeCovFieldAlgebra 𝔤) :=
  Representation.baseChange ℂ (repLorentzGroup 𝔤)

@[simp]
lemma complexRepLorentzGroup_tmul (Λ : SL(2,ℂ)) (z : ℂ) (x : LocalGaugeCovFieldAlgebra 𝔤) :
    complexRepLorentzGroup 𝔤 Λ (z ⊗ₜ[ℝ] x) = z ⊗ₜ[ℝ] repLorentzGroup 𝔤 Λ x := rfl

/-- Along the complexified inclusion the ordinary gauge group acts as the constant jets. -/
lemma complexVal_complexRepValue (g : G₀) (y : ℂ ⊗[ℝ] LocalGaugeCovFieldAlgebra 𝔤) :
    complexVal 𝔤 (complexRepValue jets g y)
      = LocalGaugeFieldAlgebra.complexRepJet jets (jets.ofConstant g) (complexVal 𝔤 y) :=
  Representation.baseChange_naturality (σ := (LocalGaugeFieldAlgebra.repJet jets).comp
    jets.ofConstant) ℂ (LocalGaugeCovFieldAlgebra 𝔤).val.toLinearMap coe_repValue g y

/-- Along the complexified inclusion the Lorentz action is the ambient one. -/
lemma complexVal_complexRepLorentzGroup (Λ : SL(2,ℂ))
    (y : ℂ ⊗[ℝ] LocalGaugeCovFieldAlgebra 𝔤) :
    complexVal 𝔤 (complexRepLorentzGroup 𝔤 Λ y)
      = LocalGaugeFieldAlgebra.complexRepLorentzGroup 𝔤 Λ (complexVal 𝔤 y) :=
  Representation.baseChange_naturality (σ := LocalGaugeFieldAlgebra.repLorentzGroup 𝔤) ℂ
    (LocalGaugeCovFieldAlgebra 𝔤).val.toLinearMap coe_repLorentzGroup Λ y

end LocalGaugeCovFieldAlgebra
