/-
Copyright (c) 2024 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Mathlib.Analysis.Complex.Basic
public import Mathlib.Data.Matrix.Reflection
public import Mathlib.LinearAlgebra.CliffordAlgebra.Basic
public import Physlib.Meta.TODO.Basic
public import Physlib.Relativity.Tensors.RealTensor.Vector.Basic
public import Physlib.Relativity.MinkowskiMatrix
/-!
# The Clifford Algebra

This file defines the Gamma matrices and their relationship to the Clifford algebra.

## Main Definitions

- `γ0, γ1, γ2, γ3`: The four gamma matrices in the Dirac representation (4×4 complex matrices)
- `γ`: The gamma matrices indexed by `Fin 1 ⊕ Fin 3`, matching the Minkowski index type
- `γSet`: The set of gamma matrices
- `diracForm`: The quadratic form with Minkowski signature (+,-,-,-)
  corresponding to the gamma matrices
- `diracAlgebra`: The algebra generated by the gamma matrices over ℝ
- `ofCliffordAlgebra`: The algebra homomorphism from the Clifford algebra to `diracAlgebra`
- `slash`: The Dirac slash operator on Lorentz vectors
- `slashProd`: The product of a list of Dirac slash operators on Lorentz vectors

## Main Results

- `gamma_anticomm`: The Clifford anticommutator for gamma matrices
- `ofCliffordAlgebra_surjective`: The homomorphism `ofCliffordAlgebra` is surjective

## TODO

- Complete the isomorphism by proving injectivity of `ofCliffordAlgebra` (requires dimension theory)
- Construct the `AlgEquiv` between `CliffordAlgebra diracForm` and `diracAlgebra`

-/

@[expose] public section
TODO "Prove injectivity of ofCliffordAlgebra and construct the full isomorphism."
namespace spaceTime
open Complex

noncomputable section diracRepresentation

/-- The γ⁰ gamma matrix in the Dirac representation. -/
def γ0 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![1, 0, 0, 0; 0, 1, 0, 0; 0, 0, -1, 0; 0, 0, 0, -1]

/-- The γ¹ gamma matrix in the Dirac representation. -/
def γ1 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![0, 0, 0, 1; 0, 0, 1, 0; 0, -1, 0, 0; -1, 0, 0, 0]

/-- The γ² gamma matrix in the Dirac representation. -/
def γ2 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![0, 0, 0, - I; 0, 0, I, 0; 0, I, 0, 0; -I, 0, 0, 0]

/-- The γ³ gamma matrix in the Dirac representation. -/
def γ3 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![0, 0, 1, 0; 0, 0, 0, -1; -1, 0, 0, 0; 0, 1, 0, 0]

theorem _root_.Matrix.one_fin_four {α} [Zero α] [One α] :
    (1 : Matrix (Fin 4) (Fin 4) α) = !![1, 0, 0, 0; 0, 1, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1] :=
  Matrix.etaExpand_eq _ |>.symm

@[simp] lemma γ0_mul_γ0 : γ0 * γ0 = 1 := by simp [γ0, Matrix.one_fin_four]
@[simp] lemma γ1_mul_γ1 : γ1 * γ1 = -1 := by simp [γ1, Matrix.one_fin_four]
@[simp] lemma γ2_mul_γ2 : γ2 * γ2 = -1 := by simp [γ2, Matrix.one_fin_four]
@[simp] lemma γ3_mul_γ3 : γ3 * γ3 = -1 := by simp [γ3, Matrix.one_fin_four]

@[simp] lemma γ1_mul_γ0 : γ1 * γ0 = -(γ0 * γ1) := by simp [γ0, γ1]
@[simp] lemma γ2_mul_γ0 : γ2 * γ0 = -(γ0 * γ2) := by simp [γ0, γ2]
@[simp] lemma γ3_mul_γ0 : γ3 * γ0 = -(γ0 * γ3) := by simp [γ0, γ3]
@[simp] lemma γ2_mul_γ1 : γ2 * γ1 = -(γ1 * γ2) := by simp [γ1, γ2]
@[simp] lemma γ3_mul_γ1 : γ3 * γ1 = -(γ1 * γ3) := by simp [γ1, γ3]
@[simp] lemma γ3_mul_γ2 : γ3 * γ2 = -(γ2 * γ3) := by simp [γ2, γ3]

/-- The γ⁵ gamma matrix in the Dirac representation. -/
def γ5 : Matrix (Fin 4) (Fin 4) ℂ := I • (γ0 * γ1 * γ2 * γ3)

/-- The γ gamma matrices in the Dirac representation. -/
@[simp]
def γ : Fin 1 ⊕ Fin 3 → Matrix (Fin 4) (Fin 4) ℂ
  | Sum.inl _ => γ0
  | Sum.inr 0 => γ1
  | Sum.inr 1 => γ2
  | Sum.inr 2 => γ3

namespace γ

open spaceTime

variable (μ ν : Fin 1 ⊕ Fin 3)

/-- The subset of `Matrix (Fin 4) (Fin 4) ℂ` formed by the gamma matrices in the Dirac
representation. -/
@[simp]
def γSet : Set (Matrix (Fin 4) (Fin 4) ℂ) := {γ i | i : Fin 1 ⊕ Fin 3}

lemma γ_in_γSet (μ : Fin 1 ⊕ Fin 3) : γ μ ∈ γSet := ⟨μ, rfl⟩

/-- The algebra generated by the gamma matrices in the Dirac representation. -/
def diracAlgebra : Subalgebra ℝ (Matrix (Fin 4) (Fin 4) ℂ) :=
  Algebra.adjoin ℝ γSet

lemma γSet_subset_diracAlgebra : γSet ⊆ diracAlgebra :=
  Algebra.subset_adjoin

lemma γ_in_diracAlgebra (μ : Fin 1 ⊕ Fin 3) : γ μ ∈ diracAlgebra :=
  γSet_subset_diracAlgebra (γ_in_γSet μ)

/-- The Clifford anticommutator identity for gamma matrices. -/
theorem gamma_anticomm (μ ν : Fin 1 ⊕ Fin 3) :
    γ μ * γ ν + γ ν * γ μ =
      (2 * ((minkowskiMatrix μ ν : ℝ) : ℂ)) • (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
  cases μ with
  | inl μ =>
    fin_cases μ
    cases ν with
    | inl ν =>
      fin_cases ν
      simp [γ0_mul_γ0, minkowskiMatrix.inl_0_inl_0, two_smul]
    | inr ν =>
      fin_cases ν <;>
        simp [γ1_mul_γ0, γ2_mul_γ0, γ3_mul_γ0, minkowskiMatrix.off_diag_zero]
  | inr μ =>
    cases ν with
    | inl ν =>
      fin_cases μ <;> fin_cases ν <;>
        simp [γ1_mul_γ0, γ2_mul_γ0, γ3_mul_γ0, minkowskiMatrix.off_diag_zero]
    | inr ν =>
      fin_cases μ <;> fin_cases ν <;>
        simp [γ1_mul_γ1, γ2_mul_γ2, γ3_mul_γ3,
              γ2_mul_γ1, γ3_mul_γ1, γ3_mul_γ2,
              minkowskiMatrix.inr_i_inr_i, minkowskiMatrix.off_diag_zero,
              two_smul, neg_smul, neg_add_rev]

/-- The quadratic form of the clifford algebra corresponding to the `γ` matrices. -/
@[simps!]
def diracForm : QuadraticForm ℝ (Fin 4 → ℝ) :=
  QuadraticMap.sq.comp (LinearMap.proj 0)
    - QuadraticMap.sq.comp (LinearMap.proj 1)
    - QuadraticMap.sq.comp (LinearMap.proj 2)
    - QuadraticMap.sq.comp (LinearMap.proj 3)

/-- The injection from the clifford algebra over `diracForm` into the algebra generated by the
`γ` matrices. -/
def ofCliffordAlgebra : CliffordAlgebra diracForm →ₐ[ℝ] diracAlgebra :=
  CliffordAlgebra.lift _
    ⟨∑ i : Fin 4, (LinearMap.proj i).smulRight ⟨γ (finSumFinEquiv.symm i), γ_in_diracAlgebra _⟩,
     fun v => by
      ext : 1
      have h0 : (finSumFinEquiv.symm (0 : Fin 4) : Fin 1 ⊕ Fin 3) = Sum.inl 0 := rfl
      have h1 : (finSumFinEquiv.symm (1 : Fin 4) : Fin 1 ⊕ Fin 3) = Sum.inr 0 := rfl
      have h2 : (finSumFinEquiv.symm (2 : Fin 4) : Fin 1 ⊕ Fin 3) = Sum.inr 1 := rfl
      have h3 : (finSumFinEquiv.symm (3 : Fin 4) : Fin 1 ⊕ Fin 3) = Sum.inr 2 := rfl
      simp only [Fin.sum_univ_four, Fin.isValue, h0, h1, h2, h3, γ,
        LinearMap.add_apply, LinearMap.coe_smulRight, LinearMap.coe_proj,
        Function.eval, SetLike.mk_smul_mk, AddMemClass.mk_add_mk, MulMemClass.mk_mul_mk, mul_add,
        Algebra.mul_smul_comm, add_mul, Algebra.smul_mul_assoc, γ0_mul_γ0, γ1_mul_γ0, smul_neg,
        γ2_mul_γ0, γ3_mul_γ0, smul_add, γ1_mul_γ1, γ2_mul_γ1, γ3_mul_γ1, γ2_mul_γ2, γ3_mul_γ2,
        γ3_mul_γ3, diracForm_apply, Algebra.algebraMap_eq_smul_one, SetLike.val_smul,
        OneMemClass.coe_one]
      module⟩

/-- The generator of the Clifford algebra corresponding to `γ i`. -/
@[simp]
lemma ofCliffordAlgebra_ι_single (i : Fin 1 ⊕ Fin 3) (r : ℝ) :
    ofCliffordAlgebra (CliffordAlgebra.ι _ (Pi.single (finSumFinEquiv i) r)) =
      r • ⟨γ i, γ_in_diracAlgebra _⟩ :=
  CliffordAlgebra.lift_ι_apply _ _ _ |>.trans <| Subtype.ext <| by
    simp only [LinearMap.coe_sum, LinearMap.coe_smulRight, LinearMap.coe_proj, Function.eval,
      SetLike.mk_smul_mk, Finset.sum_apply, AddSubmonoidClass.coe_finsetSum]
    rw [Finset.sum_eq_single (finSumFinEquiv i)]
    · simp [Equiv.symm_apply_apply]
    · intro b _ hb
      simp [Pi.single_eq_of_ne hb]
    · simp

/-! ### Surjectivity of ofCliffordAlgebra -/

/-- Each gamma matrix (as an element of diracAlgebra) is in the range of ofCliffordAlgebra. -/
lemma γ_subtype_in_range (i : Fin 1 ⊕ Fin 3) :
    ⟨γ i, γ_in_diracAlgebra i⟩ ∈ ofCliffordAlgebra.range := by
  use CliffordAlgebra.ι diracForm (Pi.single (finSumFinEquiv i) 1)
  simp [ofCliffordAlgebra_ι_single]

/-- Helper lemma: If a matrix is in Algebra.adjoin ℝ γSet, then its subtype is in the range. -/
private lemma mem_adjoin_imp_subtype_in_range (m : Matrix (Fin 4) (Fin 4) ℂ)
    (hm : m ∈ Algebra.adjoin ℝ γSet) : ⟨m, hm⟩ ∈ ofCliffordAlgebra.range := by
  induction hm using Algebra.adjoin_induction with
  | mem y hy =>
    -- y ∈ γSet, so y = γ i for some i : Fin 1 ⊕ Fin 3
    obtain ⟨i, rfl⟩ := hy
    exact γ_subtype_in_range i
  | algebraMap r =>
    -- r from ℝ
    use algebraMap ℝ _ r
    ext
    simp [Algebra.algebraMap_eq_smul_one]
  | add y z _ _ hy hz =>
    -- If y and z are in range, so is y + z
    obtain ⟨y', hy'⟩ := hy
    obtain ⟨z', hz'⟩ := hz
    use y' + z'
    ext : 1
    have hy'' : (ofCliffordAlgebra y' : Matrix (Fin 4) (Fin 4) ℂ) = y := congr_arg Subtype.val hy'
    have hz'' : (ofCliffordAlgebra z' : Matrix (Fin 4) (Fin 4) ℂ) = z := congr_arg Subtype.val hz'
    simp [hy'', hz'']
  | mul y z _ _ hy hz =>
    -- If y and z are in range, so is y * z
    obtain ⟨y', hy'⟩ := hy
    obtain ⟨z', hz'⟩ := hz
    use y' * z'
    ext : 1
    have hy'' : (ofCliffordAlgebra y' : Matrix (Fin 4) (Fin 4) ℂ) = y := congr_arg Subtype.val hy'
    have hz'' : (ofCliffordAlgebra z' : Matrix (Fin 4) (Fin 4) ℂ) = z := congr_arg Subtype.val hz'
    simp [hy'', hz'']

/-- The range of ofCliffordAlgebra equals the top subalgebra (i.e., all of diracAlgebra). -/
lemma ofCliffordAlgebra_range_eq_top : ofCliffordAlgebra.range = ⊤ := by
  rw [eq_top_iff]
  intro x _
  exact mem_adjoin_imp_subtype_in_range x.val x.property

/-- The homomorphism `ofCliffordAlgebra` is surjective. -/
theorem ofCliffordAlgebra_surjective : Function.Surjective ofCliffordAlgebra := by
  rw [← AlgHom.range_eq_top]
  exact ofCliffordAlgebra_range_eq_top

/-! ### Dirac Slash Operators -/

namespace Slash

/-- The Dirac slash of a Lorentz vector. -/
def slash (k : Lorentz.Vector) : Matrix (Fin 4) (Fin 4) ℂ :=
  ∑ μ : Fin 1 ⊕ Fin 3, (k μ : ℂ) • γ μ

/-- The componentwise complexification of a Lorentz vector in 1+3 dimensions. -/
private def complex_vector (k : Lorentz.Vector) : Fin 1 ⊕ Fin 3 → ℂ :=
  fun μ => (k μ : ℂ)

@[simp]
lemma slash_zero : slash (0 : Lorentz.Vector) = 0 := by
  change (∑ μ : Fin 1 ⊕ Fin 3, complex_vector (0 : Lorentz.Vector) μ • γ μ) = 0
  simp [complex_vector]

@[simp]
lemma slash_add (k l : Lorentz.Vector) : slash (k + l) = slash k + slash l := by
  change (∑ μ : Fin 1 ⊕ Fin 3, complex_vector (k + l) μ • γ μ) =
    (∑ μ : Fin 1 ⊕ Fin 3, complex_vector k μ • γ μ) +
      (∑ μ : Fin 1 ⊕ Fin 3, complex_vector l μ • γ μ)
  simp [complex_vector, add_smul, Finset.sum_add_distrib]

@[simp]
lemma slash_smul (c : ℝ) (k : Lorentz.Vector) : slash (c • k) = c • slash k := by
  change (∑ μ : Fin 1 ⊕ Fin 3, complex_vector (c • k) μ • γ μ) =
    c • (∑ μ : Fin 1 ⊕ Fin 3, complex_vector k μ • γ μ)
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [complex_vector, Fintype.sum_sum_type, Fin.sum_univ_three] <;>
    ring_nf

/-- Product of list of slash factors, in left-to-right order. -/
def slashProd (ks : List (Lorentz.Vector)) : Matrix (Fin 4) (Fin 4) ℂ :=
  (ks.map slash).prod

@[simp]
lemma slashProd_nil : slashProd [] = 1 := rfl

@[simp]
lemma slashProd_cons (k : Lorentz.Vector) (ks : List (Lorentz.Vector)) :
    slashProd (k :: ks) = slash k * slashProd ks := rfl

end Slash

end γ

end diracRepresentation
end spaceTime
