/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.ClassicalFieldTheory.GaugeTheory.MatterField.Basic
public import Physlib.ClassicalFieldTheory.JetAlgebra.FieldAlgebra.ConstantGaugeAction
public import Physlib.ClassicalFieldTheory.JetAlgebra.FieldAlgebra.LorentzAction
public import Physlib.ClassicalFieldTheory.JetAlgebra.FieldAlgebra.MassDim
public import Physlib.ClassicalFieldTheory.JetAlgebra.FieldAlgebra.Statistics
/-!
# The field algebras of a matter field

## i. Overview

A field algebra of a matter field `M` is any algebra generated by the component functions
`∂_s ψ_α` of `M` — the bosonic and fermionic jet algebras are the two canonical choices.
This file transports the data of `M` onto such an algebra: the jet gauge action, the
global gauge action along the canonical inclusion `jets.ofConstant` of the constant jets,
the Lorentz action and the mass-weight scaling.

It sits downstream of the component space that `M` indexes, which is why it is separate
from the file carrying the structure itself.

## ii. Key results

- `MatterField.BosonicJetAlgebra`, `MatterField.FermionicJetAlgebra` : the two canonical
  field algebras of a matter field.
- `MatterField.repJetAlgebra` : the jet gauge action on a field algebra of the field.
- `MatterField.repConstant` : the global gauge action, along `jets.ofConstant`.
- `MatterField.repLorentzGroup` : the Lorentz action on a field algebra of the field.
- `MatterField.massWeightScale` : the mass-weight scaling on a field algebra of the field.

## iii. Table of contents

- A. The bosonic and fermionic jet algebras
- B. The actions on a field algebra of the matter field

-/

@[expose] public section

open Matrix MatrixGroups TensorProduct

namespace MatterField

variable {G : Type} [Group G] {𝔤 : Type} [LieRing 𝔤] [LieAlgebra ℝ 𝔤]
  {G₀ : Type} [Group G₀] {𝔤J : Type} [LieRing 𝔤J] [LieAlgebra ℝ 𝔤J]
  {jets : LocalGaugeData G 𝔤 G₀ 𝔤J} (M : MatterField jets)

/-!

## A. The bosonic and fermionic jet algebras

-/

/-- The bosonic jet algebra of a matter field. -/
abbrev BosonicJetAlgebra : Type := BosonicAlgebra M.V

/-- The fermionic jet algebra of a matter field. -/
abbrev FermionicJetAlgebra : Type := FermionicAlgebra M.V

/-!

## B. The actions on a field algebra of the matter field

-/

variable (A : Type) [Ring A] [Algebra ℂ A] [IsFieldAlgebra M.V A]

/-- The jet gauge action on a field algebra of the matter field. -/
noncomputable def repJetAlgebra : Representation ℂ G A :=
  FieldAlgebra.repJet M.repJet M.repJet_smul

/-- The global gauge action on a field algebra of the matter field, along the canonical
  inclusion `jets.ofConstant : G₀ →* G` of the constant jets. -/
noncomputable def repConstant : Representation ℂ G₀ A :=
  FieldAlgebra.repConstant jets.ofConstant M.repJet M.repJet_smul

/-- The Lorentz action on a field algebra of the matter field. -/
noncomputable def repLorentzGroup : Representation ℂ SL(2,ℂ) A :=
  FieldAlgebra.repLorentzGroup M.repLorentz

/-- The mass-weight scaling on a field algebra of the matter field. -/
noncomputable def massWeightScale (c : ℂ) : A →ₐ[ℂ] A :=
  FieldAlgebra.massWeightScale M.massWeight c

lemma repJetAlgebra_ι (U : G) (x : JetComponentSpace M.V) :
    M.repJetAlgebra A U (FieldAlgebra.ι A x) =
      FieldAlgebra.ι A (JetComponentSpace.repJet M.repJet M.repJet_smul U x) :=
  FieldAlgebra.repJet_ι _ _ U x

lemma repConstant_apply (g : G₀) :
    M.repConstant A g = M.repJetAlgebra A (jets.ofConstant g) := rfl

lemma repLorentzGroup_ι (Λ : SL(2,ℂ)) (x : JetComponentSpace M.V) :
    M.repLorentzGroup A Λ (FieldAlgebra.ι A x) =
      FieldAlgebra.ι A (JetComponentSpace.repLorentzGroup M.repLorentz Λ x) :=
  FieldAlgebra.repLorentzGroup_ι _ Λ x

lemma massWeightScale_ι (c : ℂ) (x : JetComponentSpace M.V) :
    M.massWeightScale A c (FieldAlgebra.ι A x) =
      FieldAlgebra.ι A (JetComponentSpace.massWeightScale M.massWeight c x) :=
  FieldAlgebra.massWeightScale_ι _ c x

end MatterField
