/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.IsCovStandardModel.Sectors
public import Physlib.Particles.StandardModel.IsHiggsSector.MassWeight.Basic
/-!
# The Yukawa sector's mass-weight submodules

The mixed Higgs-fermion sector — the `{higgs, fermion}` two-class sector of
`Sectors.lean` — is the home of the Yukawa couplings. Since the Higgs sector is
bosonic, its algebra commutes with the fermion algebra
(`commute_of_mem_higgsAlgebra_of_mem_fermionAlgebra`), which feeds the abstract
two-class machinery `sectorMassWeight_pair_le` to bound each weight-`w` piece of the
sector by a join of products of the two sectors' own mass-weight submodules
(`sectorMassWeight_higgs_fermion_le`). Combined with the explicit low-weight tables
for the Higgs sector (vanishing at odd weight) and the fermion sector (vanishing at
weight `1`, `2` and `4`), this pins the sector down explicitly up to weight eight: it
vanishes below weight five and at weight six, and at weights five, seven and eight it
sits inside the expected Yukawa-type products, the last of these being the weight of
the Yukawa term `H ψ ψ` itself.

-/

@[expose] public section

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz


namespace IsCovStandardModel

variable {B : Type} [Ring B] [Algebra ℂ B]
  {repGauge : Representation ℂ GaugeGroupI B}
  {hrepGauge_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B),
    repGauge g (b₁ * b₂) = repGauge g b₁ * repGauge g b₂}
  {repLorentz : Representation ℂ SL(2,ℂ) B}
  {hrepLorentz_mul : ∀ (Λ : SL(2,ℂ)) (b₁ b₂ : B),
    repLorentz Λ (b₁ * b₂) = repLorentz Λ b₁ * repLorentz Λ b₂}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  {H : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ HiggsVec →ₗ[ℂ] B}
  {barH : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule HiggsVec) →ₗ[ℂ] B}
  {F : {n : ℕ} → (Fin n → Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) →
    Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}
  {d : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ DownSinglet →ₗ[ℂ] B}
  {bard : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule DownSinglet) →ₗ[ℂ] B}
  {u : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ UpSinglet →ₗ[ℂ] B}
  {baru : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule UpSinglet) →ₗ[ℂ] B}
  {Q : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ QuarkDoublet →ₗ[ℂ] B}
  {barQ : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule QuarkDoublet) →ₗ[ℂ] B}
  {L : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ LeptonDoublet →ₗ[ℂ] B}
  {barL : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule LeptonDoublet) →ₗ[ℂ] B}
  {e : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ LeptonSinglet →ₗ[ℂ] B}
  {bare : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule LeptonSinglet) →ₗ[ℂ] B}
  (h : IsCovStandardModel B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
    massWeightPoly H barH F d bard u baru Q barQ L barL e bare)

/-!

## Cross-algebra commutation

The Higgs sector is bosonic, so its algebra commutes with the fermion algebra
elementwise: this is the algebraic input to the whole Yukawa-sector decomposition.

-/

/-- **The Higgs sector is bosonic**: every element of the algebra generated by the
  Higgs towers commutes with every element of the algebra generated by the fermion
  towers. -/
lemma commute_of_mem_higgsAlgebra_of_mem_fermionAlgebra {x y : B}
    (hx : x ∈ h.isHiggsSector.higgsAlgebra) (hy : y ∈ h.isFermionSector.fermionAlgebra) :
    Commute x y := by
  have hgen : ∀ a ∈ (⋃ (k : ℕ) (dd : Fin k → (Fin 1 ⊕ Fin 3)),
      Set.range (H dd) ∪ Set.range (barH dd)),
      ∀ b ∈ (⋃ (i : Fin 3) (k : ℕ) (dd : Fin k → (Fin 1 ⊕ Fin 3)),
        Set.range (d i dd) ∪ Set.range (bard i dd) ∪ Set.range (u i dd) ∪
        Set.range (baru i dd) ∪ Set.range (Q i dd) ∪ Set.range (barQ i dd) ∪
        Set.range (L i dd) ∪ Set.range (barL i dd) ∪ Set.range (e i dd) ∪
        Set.range (bare i dd)), Commute a b := by
    intro a ha b hb
    simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range] at ha hb
    obtain ⟨k1, d1, ⟨φ1, rfl⟩ | ⟨φ1, rfl⟩⟩ := ha <;>
      obtain ⟨i, k2, dd, (((((((((⟨φ2, rfl⟩ | ⟨φ2, rfl⟩) | ⟨φ2, rfl⟩) | ⟨φ2, rfl⟩) | ⟨φ2, rfl⟩) |
        ⟨φ2, rfl⟩) | ⟨φ2, rfl⟩) | ⟨φ2, rfl⟩) | ⟨φ2, rfl⟩) | ⟨φ2, rfl⟩)⟩ := hb
    · exact h.H_comm_d _ _ _ _ _
    · exact h.H_comm_bard _ _ _ _ _
    · exact h.H_comm_u _ _ _ _ _
    · exact h.H_comm_baru _ _ _ _ _
    · exact h.H_comm_Q _ _ _ _ _
    · exact h.H_comm_barQ _ _ _ _ _
    · exact h.H_comm_L _ _ _ _ _
    · exact h.H_comm_barL _ _ _ _ _
    · exact h.H_comm_e _ _ _ _ _
    · exact h.H_comm_bare _ _ _ _ _
    · exact h.barH_comm_d _ _ _ _ _
    · exact h.barH_comm_bard _ _ _ _ _
    · exact h.barH_comm_u _ _ _ _ _
    · exact h.barH_comm_baru _ _ _ _ _
    · exact h.barH_comm_Q _ _ _ _ _
    · exact h.barH_comm_barQ _ _ _ _ _
    · exact h.barH_comm_L _ _ _ _ _
    · exact h.barH_comm_barL _ _ _ _ _
    · exact h.barH_comm_e _ _ _ _ _
    · exact h.barH_comm_bare _ _ _ _ _
  rw [IsHiggsSector.higgsAlgebra] at hx
  rw [IsFermionSector.fermionAlgebra] at hy
  refine Algebra.commute_of_mem_adjoin_of_forall_mem_commute hy fun b hb => ?_
  exact (Algebra.commute_of_mem_adjoin_of_forall_mem_commute hx
    fun a ha => (hgen a ha b hb).symm).symm

/-- The fermion-sector and Higgs-sector mass-weight submodules commute past each
  other, in the order needed by `sectorMassWeight_pair_le`. -/
lemma fermionMassWeight_mul_higgsMassWeight_le (a b : ℕ) :
    h.isFermionSector.massWeightSubmodule a * h.isHiggsSector.massWeightSubmodule b
      ≤ h.isHiggsSector.massWeightSubmodule b * h.isFermionSector.massWeightSubmodule a := by
  refine Submodule.mul_le.mpr fun x hx y hy => ?_
  rw [← (h.commute_of_mem_higgsAlgebra_of_mem_fermionAlgebra
    (h.isHiggsSector.mem_higgsAlgebra_of_mem_massWeightSubmodule hy)
    (h.isFermionSector.mem_fermionAlgebra_of_mem_massWeightSubmodule hx)).eq]
  exact Submodule.mul_mem_mul hy hx

/-!

## The Yukawa sector at a fixed mass weight

-/

/-- **The Yukawa-sector decomposition**: the weight-`w` piece of the `{higgs,
  fermion}` sector is contained in the join, over the splittings of `w` into two
  non-zero parts, of the products of the Higgs-sector and fermion-sector mass-weight
  submodules. -/
lemma sectorMassWeight_higgs_fermion_le (w : ℕ) :
    h.sectorMassWeight {GeneratorClass.higgs, GeneratorClass.fermion} w
      ≤ ⨆ (p : ℕ × ℕ) (_ : p.1 + p.2 = w) (_ : p.1 ≠ 0) (_ : p.2 ≠ 0),
        h.isHiggsSector.massWeightSubmodule p.1 * h.isFermionSector.massWeightSubmodule p.2 :=
  h.sectorMassWeight_pair_le (by decide) h.sectorMassWeight_higgs_le h.sectorMassWeight_fermion_le
    h.isHiggsSector.one_le_massWeightSubmodule_zero
    h.isFermionSector.one_le_massWeightSubmodule_zero
    h.isHiggsSector.massWeightSubmodule_mul_le h.isFermionSector.massWeightSubmodule_mul_le
    h.fermionMassWeight_mul_higgsMassWeight_le w

/-- **Below weight five, the Yukawa sector vanishes**: no splitting of a total weight
  under five into two non-zero parts survives — the Higgs part is either odd (hence
  zero) or equal to two, forcing the fermion part to be one or two (hence also
  zero). -/
lemma sectorMassWeight_higgs_fermion_eq_bot_of_lt_five {w : ℕ} (hw : w < 5) :
    h.sectorMassWeight {GeneratorClass.higgs, GeneratorClass.fermion} w = ⊥ := by
  refine le_antisymm (le_trans (h.sectorMassWeight_higgs_fermion_le w) ?_) bot_le
  refine iSup_le fun p => iSup_le fun hp => iSup_le fun h1 => iSup_le fun h2 => ?_
  obtain ⟨a, b⟩ := p
  simp only at hp h1 h2
  have ha0 : 0 < a := Nat.pos_of_ne_zero h1
  have ha3 : a ≤ 3 := by omega
  interval_cases a
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 1 (by decide), Submodule.bot_mul]
  · have hb0 : 0 < b := Nat.pos_of_ne_zero h2
    have hb2 : b ≤ 2 := by omega
    interval_cases b
    · rw [h.isFermionSector.massWeightSubmodule_one_eq, Submodule.mul_bot]
    · rw [h.isFermionSector.massWeightSubmodule_two_eq, Submodule.mul_bot]
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 3 (by decide), Submodule.bot_mul]

/-- **The Yukawa sector vanishes at weight six**: every splitting of six into two
  non-zero parts has either an odd Higgs part or a fermion part of weight two or
  four, all of which vanish. -/
lemma sectorMassWeight_higgs_fermion_six :
    h.sectorMassWeight {GeneratorClass.higgs, GeneratorClass.fermion} 6 = ⊥ := by
  refine le_antisymm (le_trans (h.sectorMassWeight_higgs_fermion_le 6) ?_) bot_le
  refine iSup_le fun p => iSup_le fun hp => iSup_le fun h1 => iSup_le fun h2 => ?_
  obtain ⟨a, b⟩ := p
  simp only at hp h1 h2
  have ha0 : 0 < a := Nat.pos_of_ne_zero h1
  have ha5 : a ≤ 5 := by omega
  interval_cases a
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 1 (by decide), Submodule.bot_mul]
  · have hb : b = 4 := by omega
    rw [hb, h.isFermionSector.massWeightSubmodule_four_eq, Submodule.mul_bot]
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 3 (by decide), Submodule.bot_mul]
  · have hb : b = 2 := by omega
    rw [hb, h.isFermionSector.massWeightSubmodule_two_eq, Submodule.mul_bot]
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 5 (by decide), Submodule.bot_mul]

/-- A product of a Higgs-weight piece and a fermion-weight piece lands in the Yukawa
  sector of the total weight. -/
lemma mul_le_sectorMassWeight_higgs_fermion {a b w : ℕ} {X Y : Submodule ℂ B}
    (ha : a ≠ 0) (hb : b ≠ 0) (hab : a + b = w)
    (hX : X ≤ h.isHiggsSector.massWeightSubmodule a)
    (hY : Y ≤ h.isFermionSector.massWeightSubmodule b) :
    X * Y ≤ h.sectorMassWeight {GeneratorClass.higgs, GeneratorClass.fermion} w := by
  have hset : ({GeneratorClass.higgs} ∪ {GeneratorClass.fermion} : Finset GeneratorClass)
      = {GeneratorClass.higgs, GeneratorClass.fermion} := by decide
  refine Submodule.mul_le.mpr fun x hx y hy => ?_
  have hx' : x ∈ h.sectorMassWeight {GeneratorClass.higgs} a := by
    rw [h.sectorMassWeight_higgs_eq ha]; exact hX hx
  have hy' : y ∈ h.sectorMassWeight {GeneratorClass.fermion} b := by
    rw [h.sectorMassWeight_fermion_eq hb]; exact hY hy
  have hmem := h.mul_mem_sectorMassWeight hx' hy'
  rwa [hset, hab] at hmem

/-- **The weight-five Yukawa sector**: the only surviving splitting is the Higgs
  field itself (weight two) against the underived fermion towers (weight three). -/
lemma sectorMassWeight_higgs_fermion_five :
    h.sectorMassWeight {GeneratorClass.higgs, GeneratorClass.fermion} 5
      = h.isHiggsSector.derivSubmodule 0 * h.isFermionSector.derivSubmodule 0 := by
  refine le_antisymm ?_ ?_
  case refine_2 =>
    exact h.mul_le_sectorMassWeight_higgs_fermion (a := 2) (b := 3) (by norm_num)
      (by norm_num) (by norm_num)
      (le_of_eq h.isHiggsSector.massWeightSubmodule_two_eq_deriv.symm)
      (le_of_eq h.isFermionSector.massWeightSubmodule_three_eq.symm)
  rw [← h.isHiggsSector.massWeightSubmodule_two_eq_deriv]
  refine le_trans (h.sectorMassWeight_higgs_fermion_le 5) ?_
  refine iSup_le fun p => iSup_le fun hp => iSup_le fun h1 => iSup_le fun h2 => ?_
  obtain ⟨a, b⟩ := p
  simp only at hp h1 h2
  have ha0 : 0 < a := Nat.pos_of_ne_zero h1
  have ha4 : a ≤ 4 := by omega
  interval_cases a
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 1 (by decide), Submodule.bot_mul]
    exact bot_le
  · have hb : b = 3 := by omega
    rw [hb, h.isFermionSector.massWeightSubmodule_three_eq]
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 3 (by decide), Submodule.bot_mul]
    exact bot_le
  · have hb : b = 1 := by omega
    rw [hb, h.isFermionSector.massWeightSubmodule_one_eq, Submodule.mul_bot]
    exact bot_le

set_option maxHeartbeats 1000000 in
/-- **The weight-seven Yukawa sector**: the surviving splittings pair the Higgs
  field (weight two) with the once-derived fermion towers (weight five), or the
  once-derived Higgs field (weight four) with the underived fermion towers (weight
  three). -/
lemma sectorMassWeight_higgs_fermion_seven :
    h.sectorMassWeight {GeneratorClass.higgs, GeneratorClass.fermion} 7
      = h.isHiggsSector.derivSubmodule 0 * h.isFermionSector.derivSubmodule 1
        ⊔ h.isHiggsSector.derivSubmodule 1 * h.isFermionSector.derivSubmodule 0
        ⊔ h.isHiggsSector.derivSubmodule 0 * h.isHiggsSector.derivSubmodule 0
          * h.isFermionSector.derivSubmodule 0 := by
  refine le_antisymm ?_ ?_
  case refine_2 =>
    refine sup_le (sup_le ?_ ?_) ?_
    · exact h.mul_le_sectorMassWeight_higgs_fermion (a := 2) (b := 5) (by norm_num)
        (by norm_num) (by norm_num)
        (le_of_eq h.isHiggsSector.massWeightSubmodule_two_eq_deriv.symm)
        (le_of_eq h.isFermionSector.massWeightSubmodule_five_eq.symm)
    · exact h.mul_le_sectorMassWeight_higgs_fermion (a := 4) (b := 3) (by norm_num)
        (by norm_num) (by norm_num)
        (by rw [h.isHiggsSector.massWeightSubmodule_four_eq_deriv]; exact le_sup_left)
        (le_of_eq h.isFermionSector.massWeightSubmodule_three_eq.symm)
    · exact h.mul_le_sectorMassWeight_higgs_fermion (a := 4) (b := 3) (by norm_num)
        (by norm_num) (by norm_num)
        (by rw [h.isHiggsSector.massWeightSubmodule_four_eq_deriv]; exact le_sup_right)
        (le_of_eq h.isFermionSector.massWeightSubmodule_three_eq.symm)
  refine le_trans (h.sectorMassWeight_higgs_fermion_le 7) ?_
  refine iSup_le fun p => iSup_le fun hp => iSup_le fun h1 => iSup_le fun h2 => ?_
  obtain ⟨a, b⟩ := p
  simp only at hp h1 h2
  have ha0 : 0 < a := Nat.pos_of_ne_zero h1
  have ha6 : a ≤ 6 := by omega
  interval_cases a
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 1 (by decide), Submodule.bot_mul]
    exact bot_le
  · have hb : b = 5 := by omega
    rw [hb, h.isFermionSector.massWeightSubmodule_five_eq,
      h.isHiggsSector.massWeightSubmodule_two_eq_deriv]
    exact le_sup_left.trans le_sup_left
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 3 (by decide), Submodule.bot_mul]
    exact bot_le
  · have hb : b = 3 := by omega
    rw [hb, h.isFermionSector.massWeightSubmodule_three_eq,
      h.isHiggsSector.massWeightSubmodule_four_eq_deriv, Submodule.sup_mul]
    exact sup_le (le_sup_right.trans le_sup_left) le_sup_right
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 5 (by decide), Submodule.bot_mul]
    exact bot_le
  · have hb : b = 1 := by omega
    rw [hb, h.isFermionSector.massWeightSubmodule_one_eq, Submodule.mul_bot]
    exact bot_le

/-- **The weight-eight Yukawa sector**: the only surviving splitting pairs the Higgs
  field (weight two) with the product of two underived fermion towers (weight six)
  — this is the sector of the Yukawa term `H ψ ψ` itself. -/
lemma sectorMassWeight_higgs_fermion_eight :
    h.sectorMassWeight {GeneratorClass.higgs, GeneratorClass.fermion} 8
      = h.isHiggsSector.derivSubmodule 0
        * (h.isFermionSector.derivSubmodule 0 * h.isFermionSector.derivSubmodule 0) := by
  refine le_antisymm ?_ ?_
  case refine_2 =>
    exact h.mul_le_sectorMassWeight_higgs_fermion (a := 2) (b := 6) (by norm_num)
      (by norm_num) (by norm_num)
      (le_of_eq h.isHiggsSector.massWeightSubmodule_two_eq_deriv.symm)
      (le_of_eq h.isFermionSector.massWeightSubmodule_six_eq.symm)
  rw [← h.isHiggsSector.massWeightSubmodule_two_eq_deriv]
  refine le_trans (h.sectorMassWeight_higgs_fermion_le 8) ?_
  refine iSup_le fun p => iSup_le fun hp => iSup_le fun h1 => iSup_le fun h2 => ?_
  obtain ⟨a, b⟩ := p
  simp only at hp h1 h2
  have ha0 : 0 < a := Nat.pos_of_ne_zero h1
  have ha7 : a ≤ 7 := by omega
  interval_cases a
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 1 (by decide), Submodule.bot_mul]
    exact bot_le
  · have hb : b = 6 := by omega
    rw [hb, h.isFermionSector.massWeightSubmodule_six_eq]
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 3 (by decide), Submodule.bot_mul]
    exact bot_le
  · have hb : b = 4 := by omega
    rw [hb, h.isFermionSector.massWeightSubmodule_four_eq, Submodule.mul_bot]
    exact bot_le
  · rw [h.isHiggsSector.massWeightSubmodule_odd_eq_bot 5 (by decide), Submodule.bot_mul]
    exact bot_le
  · have hb : b = 2 := by omega
    rw [hb, h.isFermionSector.massWeightSubmodule_two_eq, Submodule.mul_bot]
    exact bot_le
  · have hb : b = 1 := by omega
    rw [hb, h.isFermionSector.massWeightSubmodule_one_eq, Submodule.mul_bot]
    exact bot_le

end IsCovStandardModel

end StandardModel
