/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.JetAlgebra.Invariants
/-!
# The generators of the jet algebra of the Standard Model

## i. Overview

The jet algebra of the Standard Model is generated by thirteen families of derivative
symbols: the gauge field `∂_s A_μ^φ`, the Higgs field `∂_s H_φ` and its conjugate, and the
five fermion species — the lepton doublet, the charged-lepton singlet, the quark doublet
and the up- and down-type quark singlets — each in three generations and each with a
conjugate. They are the families the structure `AlgebraRealization` asks for.

Every one of them has the same shape: take the undifferentiated component function of the
sector, push it into the full jet algebra along that sector's inclusion, and differentiate
it `s` times,

`X s φ = ∂_s (include (of… φ))`.

The gauge family is `JetAlgebra.gaugeField`, already built in `JetAlgebra.Invariants`; the
other twelve are built here.

The point of the file is not the definitions but their reduction: because the iterated
total derivative restricts to each sector's own derivative, and each sector's own iterated
derivative of an undifferentiated symbol is a single degree-one element carrying the
derivative label `s`, every family collapses to a *single generator* — one `ι` of the
component space, included. That is what makes the statistics of the symbols visible: the
gauge symbols are central, the Higgs symbols commute with everything bosonic and with the
fermions (they sit in a different tensor factor), and any two fermion symbols anticommute
because they are degree-one elements of an exterior algebra.

## ii. Key results

- `JetAlgebra.higgsField`, `JetAlgebra.conjHiggsField` : the Higgs families.
- `JetAlgebra.fermionSymbol`, `JetAlgebra.conjFermionSymbol` : the fermion symbols on the
  total fermionic target space, of which the ten species families are restrictions.
- `JetAlgebra.downSingletField`, … : the ten fermion families.
- `JetAlgebra.gaugeField_commute` : the gauge symbols commute with everything.
- `JetAlgebra.MemHiggsSector.commute`, `MemHiggsSector.commute_of_memFermionSector` : the
  Higgs symbols commute with the Higgs and with the fermions.
- `JetAlgebra.IsFermionGenerator.anticomm` : two fermion symbols anticommute.

## iii. Table of contents

- A. The Higgs generators
- B. The fermion generators
  - B.1. The symbols on the total fermionic target space
  - B.2. The ten species families
  - B.3. The reduction of the species families
- C. The statistics of the generators
  - C.1. The gauge symbols are central
  - C.2. The Higgs sector
  - C.3. The fermionic sector

-/

@[expose] public section

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 1000000
set_option synthInstance.maxSize 2048
set_option maxRecDepth 8000

namespace StandardModel

namespace JetAlgebra

open TensorProduct Matrix MatrixGroups

/-!

## A. The Higgs generators

The Higgs sector enters the full jet algebra through `includeHiggs`; differentiating the
undifferentiated component functions `HiggsJetAlgebra.ofHiggs` and `ofConjHiggs` there
gives the two Higgs families. Since `iteratedD_includeHiggs` turns the full derivative into
the Higgs sector's own, and `BosonicAlgebra.iteratedJetDeriv_ofField` evaluates that on an
undifferentiated symbol, each family is a single included degree-one element.

-/

/-- The derivative symbols `∂_s H_φ` of the Higgs field inside the jet algebra of the
  Standard Model. -/
noncomputable def higgsField (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ HiggsVec →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeHiggs.toLinearMap.comp HiggsJetAlgebra.ofHiggs)

/-- The derivative symbols `∂_s H̄_φ` of the conjugate Higgs field inside the jet algebra
  of the Standard Model. -/
noncomputable def conjHiggsField (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (ConjModule HiggsVec) →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeHiggs.toLinearMap.comp HiggsJetAlgebra.ofConjHiggs)

/-- A Higgs symbol is a single generator of the Higgs sector, included: the derivative
  label `s` sits in the derivative factor of the unconjugated half of the component
  space. -/
lemma higgsField_apply (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ HiggsVec) :
    higgsField s φ = includeHiggs (SymmetricAlgebra.ι ℂ _
      ((DerivAlgebraComplex.basis s ⊗ₜ[ℂ] φ, 0) : JetComponentSpace HiggsVec)) := by
  rw [higgsField, LinearMap.comp_apply, LinearMap.comp_apply,
    show includeHiggs.toLinearMap (HiggsJetAlgebra.ofHiggs φ)
      = includeHiggs (BosonicAlgebra.ofField φ) from rfl,
    iteratedD_includeHiggs, BosonicAlgebra.iteratedJetDeriv_ofField]

/-- A conjugate Higgs symbol is a single generator of the Higgs sector, included: the
  derivative label `s` sits in the derivative factor of the conjugate half of the component
  space. -/
lemma conjHiggsField_apply (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule HiggsVec)) :
    conjHiggsField s φ = includeHiggs (SymmetricAlgebra.ι ℂ _
      ((0, DerivAlgebraComplex.basis s ⊗ₜ[ℂ] φ) : JetComponentSpace HiggsVec)) := by
  rw [conjHiggsField, LinearMap.comp_apply, LinearMap.comp_apply,
    show includeHiggs.toLinearMap (HiggsJetAlgebra.ofConjHiggs φ)
      = includeHiggs (BosonicAlgebra.ofConjField φ) from rfl,
    iteratedD_includeHiggs, BosonicAlgebra.iteratedJetDeriv_ofConjField]

/-!

## B. The fermion generators

-/

/-!

### B.1. The symbols on the total fermionic target space

The fermionic jet algebra is built on `FermionSpace`, the product of the five species; a
covector there gives a symbol of the full algebra. The ten species families of the next
section are these symbols restricted along the projections onto a species and generation,
so it is worth reducing them once here.

-/

/-- The derivative symbols `∂_s ψ_φ` of a covector `φ` on the total fermionic target
  space, inside the jet algebra of the Standard Model. -/
noncomputable def fermionSymbol (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ FermionSpace →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp FermionicAlgebra.ofField)

/-- The conjugate derivative symbols `∂_s ψ̄_φ` of a covector `φ` on the conjugate of the
  total fermionic target space. -/
noncomputable def conjFermionSymbol (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (ConjModule FermionSpace) →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp FermionicAlgebra.ofConjField)

/-- A fermionic symbol is a single generator of the fermionic sector, included: the
  derivative label `s` sits in the derivative factor of the unconjugated half of the
  component space. -/
lemma fermionSymbol_apply (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ FermionSpace) :
    fermionSymbol s φ = includeFermion (ExteriorAlgebra.ι ℂ
      ((DerivAlgebraComplex.basis s ⊗ₜ[ℂ] φ, 0) : JetComponentSpace FermionSpace)) := by
  rw [fermionSymbol, LinearMap.comp_apply, LinearMap.comp_apply,
    show includeFermion.toLinearMap (FermionicAlgebra.ofField φ)
      = includeFermion (FermionicAlgebra.ofField φ) from rfl,
    iteratedD_includeFermion, FermionicAlgebra.iteratedJetDeriv_ofField]

/-- A conjugate fermionic symbol is a single generator of the fermionic sector, included:
  the derivative label `s` sits in the derivative factor of the conjugate half of the
  component space. -/
lemma conjFermionSymbol_apply (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule FermionSpace)) :
    conjFermionSymbol s φ = includeFermion (ExteriorAlgebra.ι ℂ
      ((0, DerivAlgebraComplex.basis s ⊗ₜ[ℂ] φ) : JetComponentSpace FermionSpace)) := by
  rw [conjFermionSymbol, LinearMap.comp_apply, LinearMap.comp_apply,
    show includeFermion.toLinearMap (FermionicAlgebra.ofConjField φ)
      = includeFermion (FermionicAlgebra.ofConjField φ) from rfl,
    iteratedD_includeFermion, FermionicAlgebra.iteratedJetDeriv_ofConjField]

/-!

### B.2. The ten species families

-/

/-- The derivative symbols `∂_s ψ_φ` of the `i`-th generation lepton doublet inside the jet
  algebra of the Standard Model. -/
noncomputable def leptonDoubletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ LeptonDoublet →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp (FermionJetAlgebra.ofLeptonDoublet i))

/-- The conjugate derivative symbols `∂_s ψ̄_φ` of the `i`-th generation lepton doublet
  inside the jet algebra of the Standard Model. -/
noncomputable def conjLeptonDoubletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (ConjModule LeptonDoublet) →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp (FermionJetAlgebra.ofConjLeptonDoublet i))

/-- The derivative symbols `∂_s ψ_φ` of the `i`-th generation charged-lepton singlet inside the jet
  algebra of the Standard Model. -/
noncomputable def leptonSingletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ LeptonSinglet →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp (FermionJetAlgebra.ofLeptonSinglet i))

/-- The conjugate derivative symbols `∂_s ψ̄_φ` of the `i`-th generation charged-lepton singlet
  inside the jet algebra of the Standard Model. -/
noncomputable def conjLeptonSingletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (ConjModule LeptonSinglet) →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp (FermionJetAlgebra.ofConjLeptonSinglet i))

/-- The derivative symbols `∂_s ψ_φ` of the `i`-th generation quark doublet inside the jet
  algebra of the Standard Model. -/
noncomputable def quarkDoubletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ QuarkDoublet →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp (FermionJetAlgebra.ofQuarkDoublet i))

/-- The conjugate derivative symbols `∂_s ψ̄_φ` of the `i`-th generation quark doublet
  inside the jet algebra of the Standard Model. -/
noncomputable def conjQuarkDoubletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (ConjModule QuarkDoublet) →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp (FermionJetAlgebra.ofConjQuarkDoublet i))

/-- The derivative symbols `∂_s ψ_φ` of the `i`-th generation up-type quark singlet inside the jet
  algebra of the Standard Model. -/
noncomputable def upSingletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ UpSinglet →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp (FermionJetAlgebra.ofUpSinglet i))

/-- The conjugate derivative symbols `∂_s ψ̄_φ` of the `i`-th generation up-type quark singlet
  inside the jet algebra of the Standard Model. -/
noncomputable def conjUpSingletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (ConjModule UpSinglet) →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp (FermionJetAlgebra.ofConjUpSinglet i))

/-- The derivative symbols `∂_s ψ_φ` of the `i`-th generation down-type quark singlet inside the jet
  algebra of the Standard Model. -/
noncomputable def downSingletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ DownSinglet →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp (FermionJetAlgebra.ofDownSinglet i))

/-- The conjugate derivative symbols `∂_s ψ̄_φ` of the `i`-th generation down-type quark singlet
  inside the jet algebra of the Standard Model. -/
noncomputable def conjDownSingletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (ConjModule DownSinglet) →ₗ[ℂ] JetAlgebra :=
  (Lorentz.iteratedD (A := JetAlgebra) jetDeriv jetDeriv_comm s).comp
    (includeFermion.toLinearMap.comp (FermionJetAlgebra.ofConjDownSinglet i))

/-!

### B.3. The reduction of the species families

Each species family is the total fermionic symbol of the covector pulled back along the
projection onto that species and generation, and hence — by `fermionSymbol_apply` — a
single included generator. Both facts are recorded: the first is what identifies the
generating sets in the proof that the families generate the whole algebra, the second is
what fixes their statistics.

-/

/-- The symbols of the `i`-th generation lepton doublet are the total fermionic symbols
  of the covectors pulled back along the projection onto that species and generation. -/
lemma leptonDoubletField_eq_fermionSymbol (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ LeptonDoublet) :
    leptonDoubletField i s φ
      = fermionSymbol s (Module.Dual.transpose (FermionSpace.leptonDoubletProj i) φ) := rfl

/-- The conjugate symbols of the `i`-th generation lepton doublet are the total conjugate
  fermionic symbols of the covectors pulled back along the projection. -/
lemma conjLeptonDoubletField_eq_conjFermionSymbol (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule LeptonDoublet)) :
    conjLeptonDoubletField i s φ = conjFermionSymbol s
      (Module.Dual.transpose (ConjModule.map (FermionSpace.leptonDoubletProj i)) φ) := rfl

/-- A symbol of the `i`-th generation lepton doublet is a single generator of the
  fermionic sector, included. -/
lemma leptonDoubletField_apply (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ LeptonDoublet) :
    leptonDoubletField i s φ = includeFermion (ExteriorAlgebra.ι ℂ
      (DerivAlgebraComplex.basis s ⊗ₜ[ℂ]
        Module.Dual.transpose (FermionSpace.leptonDoubletProj i) φ, 0)) := by
  rw [leptonDoubletField_eq_fermionSymbol, fermionSymbol_apply]

/-- A conjugate symbol of the `i`-th generation lepton doublet is a single generator of
  the fermionic sector, included. -/
lemma conjLeptonDoubletField_apply (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule LeptonDoublet)) :
    conjLeptonDoubletField i s φ = includeFermion (ExteriorAlgebra.ι ℂ
      (0, DerivAlgebraComplex.basis s ⊗ₜ[ℂ]
        Module.Dual.transpose (ConjModule.map (FermionSpace.leptonDoubletProj i)) φ)) := by
  rw [conjLeptonDoubletField_eq_conjFermionSymbol, conjFermionSymbol_apply]

/-- The symbols of the `i`-th generation charged-lepton singlet are the total fermionic symbols
  of the covectors pulled back along the projection onto that species and generation. -/
lemma leptonSingletField_eq_fermionSymbol (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ LeptonSinglet) :
    leptonSingletField i s φ
      = fermionSymbol s (Module.Dual.transpose (FermionSpace.leptonSingletProj i) φ) := rfl

/-- The conjugate symbols of the `i`-th generation charged-lepton singlet are the total conjugate
  fermionic symbols of the covectors pulled back along the projection. -/
lemma conjLeptonSingletField_eq_conjFermionSymbol (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule LeptonSinglet)) :
    conjLeptonSingletField i s φ = conjFermionSymbol s
      (Module.Dual.transpose (ConjModule.map (FermionSpace.leptonSingletProj i)) φ) := rfl

/-- A symbol of the `i`-th generation charged-lepton singlet is a single generator of the
  fermionic sector, included. -/
lemma leptonSingletField_apply (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ LeptonSinglet) :
    leptonSingletField i s φ = includeFermion (ExteriorAlgebra.ι ℂ
      (DerivAlgebraComplex.basis s ⊗ₜ[ℂ]
        Module.Dual.transpose (FermionSpace.leptonSingletProj i) φ, 0)) := by
  rw [leptonSingletField_eq_fermionSymbol, fermionSymbol_apply]

/-- A conjugate symbol of the `i`-th generation charged-lepton singlet is a single generator of
  the fermionic sector, included. -/
lemma conjLeptonSingletField_apply (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule LeptonSinglet)) :
    conjLeptonSingletField i s φ = includeFermion (ExteriorAlgebra.ι ℂ
      (0, DerivAlgebraComplex.basis s ⊗ₜ[ℂ]
        Module.Dual.transpose (ConjModule.map (FermionSpace.leptonSingletProj i)) φ)) := by
  rw [conjLeptonSingletField_eq_conjFermionSymbol, conjFermionSymbol_apply]

/-- The symbols of the `i`-th generation quark doublet are the total fermionic symbols
  of the covectors pulled back along the projection onto that species and generation. -/
lemma quarkDoubletField_eq_fermionSymbol (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ QuarkDoublet) :
    quarkDoubletField i s φ
      = fermionSymbol s (Module.Dual.transpose (FermionSpace.quarkDoubletProj i) φ) := rfl

/-- The conjugate symbols of the `i`-th generation quark doublet are the total conjugate
  fermionic symbols of the covectors pulled back along the projection. -/
lemma conjQuarkDoubletField_eq_conjFermionSymbol (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule QuarkDoublet)) :
    conjQuarkDoubletField i s φ = conjFermionSymbol s
      (Module.Dual.transpose (ConjModule.map (FermionSpace.quarkDoubletProj i)) φ) := rfl

/-- A symbol of the `i`-th generation quark doublet is a single generator of the
  fermionic sector, included. -/
lemma quarkDoubletField_apply (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ QuarkDoublet) :
    quarkDoubletField i s φ = includeFermion (ExteriorAlgebra.ι ℂ
      (DerivAlgebraComplex.basis s ⊗ₜ[ℂ]
        Module.Dual.transpose (FermionSpace.quarkDoubletProj i) φ, 0)) := by
  rw [quarkDoubletField_eq_fermionSymbol, fermionSymbol_apply]

/-- A conjugate symbol of the `i`-th generation quark doublet is a single generator of
  the fermionic sector, included. -/
lemma conjQuarkDoubletField_apply (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule QuarkDoublet)) :
    conjQuarkDoubletField i s φ = includeFermion (ExteriorAlgebra.ι ℂ
      (0, DerivAlgebraComplex.basis s ⊗ₜ[ℂ]
        Module.Dual.transpose (ConjModule.map (FermionSpace.quarkDoubletProj i)) φ)) := by
  rw [conjQuarkDoubletField_eq_conjFermionSymbol, conjFermionSymbol_apply]

/-- The symbols of the `i`-th generation up-type quark singlet are the total fermionic symbols
  of the covectors pulled back along the projection onto that species and generation. -/
lemma upSingletField_eq_fermionSymbol (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ UpSinglet) :
    upSingletField i s φ
      = fermionSymbol s (Module.Dual.transpose (FermionSpace.upSingletProj i) φ) := rfl

/-- The conjugate symbols of the `i`-th generation up-type quark singlet are the total conjugate
  fermionic symbols of the covectors pulled back along the projection. -/
lemma conjUpSingletField_eq_conjFermionSymbol (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule UpSinglet)) :
    conjUpSingletField i s φ = conjFermionSymbol s
      (Module.Dual.transpose (ConjModule.map (FermionSpace.upSingletProj i)) φ) := rfl

/-- A symbol of the `i`-th generation up-type quark singlet is a single generator of the
  fermionic sector, included. -/
lemma upSingletField_apply (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ UpSinglet) :
    upSingletField i s φ = includeFermion (ExteriorAlgebra.ι ℂ
      (DerivAlgebraComplex.basis s ⊗ₜ[ℂ]
        Module.Dual.transpose (FermionSpace.upSingletProj i) φ, 0)) := by
  rw [upSingletField_eq_fermionSymbol, fermionSymbol_apply]

/-- A conjugate symbol of the `i`-th generation up-type quark singlet is a single generator of
  the fermionic sector, included. -/
lemma conjUpSingletField_apply (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule UpSinglet)) :
    conjUpSingletField i s φ = includeFermion (ExteriorAlgebra.ι ℂ
      (0, DerivAlgebraComplex.basis s ⊗ₜ[ℂ]
        Module.Dual.transpose (ConjModule.map (FermionSpace.upSingletProj i)) φ)) := by
  rw [conjUpSingletField_eq_conjFermionSymbol, conjFermionSymbol_apply]

/-- The symbols of the `i`-th generation down-type quark singlet are the total fermionic symbols
  of the covectors pulled back along the projection onto that species and generation. -/
lemma downSingletField_eq_fermionSymbol (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ DownSinglet) :
    downSingletField i s φ
      = fermionSymbol s (Module.Dual.transpose (FermionSpace.downSingletProj i) φ) := rfl

/-- The conjugate symbols of the `i`-th generation down-type quark singlet are the total conjugate
  fermionic symbols of the covectors pulled back along the projection. -/
lemma conjDownSingletField_eq_conjFermionSymbol (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule DownSinglet)) :
    conjDownSingletField i s φ = conjFermionSymbol s
      (Module.Dual.transpose (ConjModule.map (FermionSpace.downSingletProj i)) φ) := rfl

/-- A symbol of the `i`-th generation down-type quark singlet is a single generator of the
  fermionic sector, included. -/
lemma downSingletField_apply (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ DownSinglet) :
    downSingletField i s φ = includeFermion (ExteriorAlgebra.ι ℂ
      (DerivAlgebraComplex.basis s ⊗ₜ[ℂ]
        Module.Dual.transpose (FermionSpace.downSingletProj i) φ, 0)) := by
  rw [downSingletField_eq_fermionSymbol, fermionSymbol_apply]

/-- A conjugate symbol of the `i`-th generation down-type quark singlet is a single generator of
  the fermionic sector, included. -/
lemma conjDownSingletField_apply (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule DownSinglet)) :
    conjDownSingletField i s φ = includeFermion (ExteriorAlgebra.ι ℂ
      (0, DerivAlgebraComplex.basis s ⊗ₜ[ℂ]
        Module.Dual.transpose (ConjModule.map (FermionSpace.downSingletProj i)) φ)) := by
  rw [conjDownSingletField_eq_conjFermionSymbol, conjFermionSymbol_apply]

/-!

## C. The statistics of the generators

Every commutation obligation of `AlgebraRealization` is one of three facts, and none of them
mentions the derivative label: the gauge symbols are central, the Higgs symbols commute
with the Higgs sector and with the fermionic sector, and the fermionic symbols anticommute.
They are stated here once, about arbitrary elements with the relevant sector membership,
together with the membership of each family; the instance then instantiates them.

-/

/-!

### C.1. The gauge symbols are central

-/

/-- The gauge-field symbols commute with everything in the jet algebra: they lie in the
  gauge tensor factor, which is central. -/
lemma gaugeField_commute (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
    (ψ : Module.Dual ℝ GaugeAlgebra) (x : JetAlgebra) :
    Commute (gaugeField s μ ψ) x :=
  (includeGauge_commute (GaugeJetAlgebra.gaugeField s μ ψ) x).symm

/-!

### C.2. The Higgs sector

-/

/-- An element of the jet algebra lies in the Higgs sector when it is the image of the
  Higgs jet algebra under the Higgs inclusion. -/
def MemHiggsSector (x : JetAlgebra) : Prop :=
  ∃ h : HiggsJetAlgebra, x = includeHiggs h

/-- An element of the jet algebra lies in the fermionic sector when it is the image of the
  fermionic jet algebra under the fermionic inclusion. -/
def MemFermionSector (x : JetAlgebra) : Prop :=
  ∃ f : FermionJetAlgebra, x = includeFermion f

/-- The Higgs symbols lie in the Higgs sector. -/
lemma memHiggsSector_higgsField (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ HiggsVec) : MemHiggsSector (higgsField s φ) :=
  ⟨_, higgsField_apply s φ⟩

/-- The conjugate Higgs symbols lie in the Higgs sector. -/
lemma memHiggsSector_conjHiggsField (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule HiggsVec)) : MemHiggsSector (conjHiggsField s φ) :=
  ⟨_, conjHiggsField_apply s φ⟩

/-- Two elements of the Higgs sector commute: the Higgs jet algebra is a symmetric
  algebra, hence commutative, and the inclusion is an algebra map. -/
lemma MemHiggsSector.commute {x y : JetAlgebra} (hx : MemHiggsSector x)
    (hy : MemHiggsSector y) : Commute x y := by
  obtain ⟨h, rfl⟩ := hx
  obtain ⟨h', rfl⟩ := hy
  show includeHiggs h * includeHiggs h' = includeHiggs h' * includeHiggs h
  rw [← map_mul, ← map_mul, mul_comm]

/-- The right factor of a tensor product commutes with the left: the abstract statement,
  proved at abstract types so that it can be instantiated on the jet algebra without
  rewriting inside it. -/
private lemma tensor_left_comm_right {A B C : Type*} [Ring A] [Algebra ℂ A]
    [Ring B] [Algebra ℂ B] [Ring C] [Algebra ℂ C] (a : A) (b : B) :
    (((1 : A) ⊗ₜ[ℂ] b) ⊗ₜ[ℂ] (1 : C)) * ((a ⊗ₜ[ℂ] (1 : B)) ⊗ₜ[ℂ] (1 : C))
      = ((a ⊗ₜ[ℂ] (1 : B)) ⊗ₜ[ℂ] (1 : C)) * (((1 : A) ⊗ₜ[ℂ] b) ⊗ₜ[ℂ] (1 : C)) := by
  rw [Algebra.TensorProduct.tmul_mul_tmul, Algebra.TensorProduct.tmul_mul_tmul,
    Algebra.TensorProduct.tmul_mul_tmul, Algebra.TensorProduct.tmul_mul_tmul,
    one_mul, mul_one, mul_one, one_mul, mul_one]

/-- An element of the Higgs sector commutes with an element of the fermionic sector: they
  sit in different factors of the tensor product, so their product is the same pure tensor
  in either order. This is the statement that the Higgs is a boson — it carries no
  statistics against the fermions. -/
lemma MemHiggsSector.commute_of_memFermionSector {x y : JetAlgebra}
    (hx : MemHiggsSector x) (hy : MemFermionSector y) : Commute x y := by
  obtain ⟨h, rfl⟩ := hx
  obtain ⟨f, rfl⟩ := hy
  exact tensor_left_comm_right (C := ℂ ⊗[ℝ] GaugeJetAlgebra) f h

/-!

### C.3. The fermionic sector

-/

/-- An element of the jet algebra is a fermionic generator when it is the image, under the
  fermionic inclusion, of a degree-one element of the fermionic jet algebra. Every one of
  the ten fermion families consists of such elements, by the reductions of section B.3. -/
def IsFermionGenerator (x : JetAlgebra) : Prop :=
  ∃ v : JetComponentSpace FermionSpace, x = includeFermion (ExteriorAlgebra.ι ℂ v)

/-- A fermionic generator lies in the fermionic sector. -/
lemma IsFermionGenerator.memFermionSector {x : JetAlgebra} (hx : IsFermionGenerator x) :
    MemFermionSector x := by
  obtain ⟨v, rfl⟩ := hx
  exact ⟨_, rfl⟩

/-- Two fermionic generators anticommute: they are degree-one elements of an exterior
  algebra, pushed through an algebra map. This single fact is the Fermi statistics of every
  matter symbol of the Standard Model, across species and generations alike. -/
lemma IsFermionGenerator.anticomm {x y : JetAlgebra} (hx : IsFermionGenerator x)
    (hy : IsFermionGenerator y) : x * y = -(y * x) := by
  obtain ⟨v, rfl⟩ := hx
  obtain ⟨w, rfl⟩ := hy
  rw [← map_mul, FermionicAlgebra.ι_mul_ι_swap, map_neg, map_mul]

/-- The symbols of the `i`-th generation lepton doublet are fermionic generators. -/
lemma isFermionGenerator_leptonDoubletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ LeptonDoublet) : IsFermionGenerator (leptonDoubletField i s φ) :=
  ⟨_, leptonDoubletField_apply i s φ⟩

/-- The conjugate symbols of the `i`-th generation lepton doublet are fermionic
  generators. -/
lemma isFermionGenerator_conjLeptonDoubletField (i : Fin 3)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule LeptonDoublet)) :
    IsFermionGenerator (conjLeptonDoubletField i s φ) :=
  ⟨_, conjLeptonDoubletField_apply i s φ⟩

/-- The symbols of the `i`-th generation charged-lepton singlet are fermionic generators. -/
lemma isFermionGenerator_leptonSingletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ LeptonSinglet) : IsFermionGenerator (leptonSingletField i s φ) :=
  ⟨_, leptonSingletField_apply i s φ⟩

/-- The conjugate symbols of the `i`-th generation charged-lepton singlet are fermionic
  generators. -/
lemma isFermionGenerator_conjLeptonSingletField (i : Fin 3)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule LeptonSinglet)) :
    IsFermionGenerator (conjLeptonSingletField i s φ) :=
  ⟨_, conjLeptonSingletField_apply i s φ⟩

/-- The symbols of the `i`-th generation quark doublet are fermionic generators. -/
lemma isFermionGenerator_quarkDoubletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ QuarkDoublet) : IsFermionGenerator (quarkDoubletField i s φ) :=
  ⟨_, quarkDoubletField_apply i s φ⟩

/-- The conjugate symbols of the `i`-th generation quark doublet are fermionic
  generators. -/
lemma isFermionGenerator_conjQuarkDoubletField (i : Fin 3)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule QuarkDoublet)) :
    IsFermionGenerator (conjQuarkDoubletField i s φ) :=
  ⟨_, conjQuarkDoubletField_apply i s φ⟩

/-- The symbols of the `i`-th generation up-type quark singlet are fermionic generators. -/
lemma isFermionGenerator_upSingletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ UpSinglet) : IsFermionGenerator (upSingletField i s φ) :=
  ⟨_, upSingletField_apply i s φ⟩

/-- The conjugate symbols of the `i`-th generation up-type quark singlet are fermionic
  generators. -/
lemma isFermionGenerator_conjUpSingletField (i : Fin 3)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule UpSinglet)) :
    IsFermionGenerator (conjUpSingletField i s φ) :=
  ⟨_, conjUpSingletField_apply i s φ⟩

/-- The symbols of the `i`-th generation down-type quark singlet are fermionic generators. -/
lemma isFermionGenerator_downSingletField (i : Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ DownSinglet) : IsFermionGenerator (downSingletField i s φ) :=
  ⟨_, downSingletField_apply i s φ⟩

/-- The conjugate symbols of the `i`-th generation down-type quark singlet are fermionic
  generators. -/
lemma isFermionGenerator_conjDownSingletField (i : Fin 3)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule DownSinglet)) :
    IsFermionGenerator (conjDownSingletField i s φ) :=
  ⟨_, conjDownSingletField_apply i s φ⟩

end JetAlgebra

end StandardModel
