/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.JetAlgebra.LorentzAction
public import Physlib.Particles.StandardModel.JetAlgebra.GaugeAction
public import Physlib.ClassicalFieldTheory.GaugeTheory.GaugeBoson.Realization.Symmetrized
public import Physlib.Particles.StandardModel.GaugeGroup.MaurerCartan.Freeness
/-!
# Gauge invariants of the jet algebra of the Standard Model

## i. Overview

The jet algebra of the Standard Model, with its Lorentz action, jet gauge action, the
gauge-field generators included from the gauge sector, and the total derivative, is a
*gauge field* in the sense of the abstract covariance machinery of
`Physlib.ClassicalFieldTheory.GaugeTheory.GaugeBoson.Realization`. This file establishes that
instance and instantiates the abstract classification of invariants on the full algebra:

**a gauge-invariant element of the subalgebra generated by the gauge-field symbols
`∂_s A_μ^φ` — together with any set `S` of elements fixed by the pure jets, such as the
covariant towers of the fermion and Higgs fields — is a polynomial in the covariant
derivatives of the field strength and the elements of `S`.**

This is the covariance reduction of the Standard Model jet algebra: gauge invariance
eliminates the bare gauge-field symbols in favour of field strengths and covariant
derivatives.

## ii. Key results

- `JetAlgebra.gaugeField` : the gauge-field generators inside the full jet algebra.
- `JetAlgebra.gaugeField_eq_ιConnection` : they are the connection generators of the field
  datum.
- `JetAlgebra.gaugeRealization` : the jet algebra of the Standard Model realizes the
  gauge-boson jet algebra.
- `JetAlgebra.invariant_mem_adjoin_fieldStrength` : the classification of gauge
  invariants.

## iii. Table of contents

- A. The gauge field inside the jet algebra
  - A.1. The gauge-field generators
  - A.2. Centrality
- B. The gauge realization
- C. The classification of gauge invariants

-/

@[expose] public section

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 1000000
set_option synthInstance.maxSize 2048
set_option maxRecDepth 8000

namespace StandardModel

namespace JetAlgebra

open TensorProduct Matrix MatrixGroups

/-!

## A. The gauge field inside the jet algebra

-/

/-!

### A.1. The gauge-field generators

-/

/-- The gauge-field derivative symbols of the jet algebra of the Standard Model: the
  gauge sector's symbols, included into the full algebra. It is written as a composite of
  two existing linear maps rather than as an anonymous constructor, so that its real
  linearity is inherited rather than proved by rewriting inside the jet algebra. -/
noncomputable def gaugeField (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3) :
    Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] JetAlgebra :=
  (includeGauge.toLinearMap.restrictScalars ℝ).comp
    ((LocalGaugeFieldAlgebra.gaugeField GaugeAlgebra) s μ)

@[simp]
lemma gaugeField_apply (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    gaugeField s μ φ = includeGauge ((LocalGaugeFieldAlgebra.gaugeField GaugeAlgebra) s μ φ) := rfl

/-- The gauge-field symbols `∂_s A_μ^φ` are the connection generators of the field datum:
  the derivative label, the spacetime index and the adjoint covector are unchanged, and the
  real generator enters the complexification with the scalar one. -/
@[simp]
lemma gaugeField_eq_ιConnection (s : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℝ GaugeAlgebra) :
    gaugeField s μ φ
      = fieldData.ιConnection (DerivAlgebraReal.basisMultiset s ⊗ₜ[ℝ]
          GaugeBoson.componentDual GaugeAlgebra
            (Lorentz.CoVector.basis.dualBasis μ) φ) := by
  have hsector : (LocalGaugeFieldAlgebra.gaugeField GaugeAlgebra) s μ φ
      = (1 : ℂ) ⊗ₜ[ℝ] SymmetricAlgebra.ι ℝ (GaugeBoson.JetComponentSpace GaugeAlgebra)
          (DerivAlgebraReal.basisMultiset s ⊗ₜ[ℝ]
            GaugeBoson.componentDual GaugeAlgebra
              (Lorentz.CoVector.basis.dualBasis μ) φ) :=
    (LocalGaugeFieldAlgebra.gaugeField_apply s μ φ).trans
      ((LocalGaugeFieldAlgebra.iteratedD_complexJetDeriv_one_tmul s
            ((LocalGaugeFieldAlgebra.ofA GaugeAlgebra) μ φ)).trans
        (congrArg (fun g : LocalGaugeFieldAlgebra GaugeAlgebra => (1 : ℂ) ⊗ₜ[ℝ] g)
          (LocalGaugeFieldAlgebra.iteratedJetDeriv_ofA s μ φ)))
  exact ((gaugeField_apply s μ φ).trans
      (congrArg (fun y : ℂ ⊗[ℝ] LocalGaugeFieldAlgebra GaugeAlgebra => includeGauge y)
        hsector)).trans
    (includeGauge_one_tmul_ι _)

/-!

### A.2. Centrality

-/

/-- The gauge sector lands in the centre of the jet algebra. -/
lemma includeGauge_mem_center (y : ℂ ⊗[ℝ] (LocalGaugeFieldAlgebra GaugeAlgebra)) :
    includeGauge y ∈ Subring.center JetAlgebra :=
  Subring.mem_center_iff.mpr fun z => includeGauge_commute y z

/-!

## B. The gauge realization

-/

/-- The jet algebra of the Standard Model realizes the gauge-boson jet algebra through the
  central inclusion of the gauge sector, equivariantly for the jet gauge group and the
  Lorentz group. -/
noncomputable def gaugeRealization :
    GaugeAlgebraRealization localGaugeData JetAlgebra repJetGaugeGroupI repLorentzGroup where
  toAlgHom := includeGauge
  A := gaugeField
  A_eq _ _ _ := rfl
  map_repJet U y := (repJetGaugeGroupI_includeGauge U y).symm
  map_repLorentz Λ y := (repLorentzGroup_includeGauge Λ y).symm
  repJet_mul := repJetGaugeGroupI_apply_mul
  repLorentz_mul := repLorentzGroup_apply_mul

lemma gaugeRealization_A : gaugeRealization.A = gaugeField := rfl

/-!

## C. The classification of gauge invariants

-/

/-- **The classification of gauge invariants of the jet algebra of the Standard Model**:
  a gauge-invariant element of the subalgebra generated by the gauge-field symbols
  `∂_s A_μ^φ` and a set `S` of elements fixed by the pure jets — such as the covariant
  towers of the fermion and Higgs fields — is a polynomial in the covariant derivatives
  of the field strength and the elements of `S`.

  This is the covariance reduction of the Standard Model jet algebra: gauge invariance
  eliminates the bare gauge-field symbols in favour of the field strength, its covariant
  derivatives, and the matter content `S`. -/
theorem invariant_mem_adjoin_fieldStrength (S : Set JetAlgebra)
    (hS : ∀ y ∈ S, ∀ U : localGaugeData.truncationKer 0, repJetGaugeGroupI U.1 y = y)
    {x : JetAlgebra}
    (hx : x ∈ Algebra.adjoin ℂ ({b : JetAlgebra |
      ∃ (p : Multiset (Fin 1 ⊕ Fin 3)) (μ : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra),
      b = gaugeField p μ φ} ∪ S))
    (hinv : ∀ U : JetGaugeGroupI, repJetGaugeGroupI U x = x) :
    x ∈ Algebra.adjoin ℂ ({b : JetAlgebra |
      ∃ (l : List (Fin 1 ⊕ Fin 3)) (ν lam : Fin 1 ⊕ Fin 3)
        (φ : Module.Dual ℝ GaugeAlgebra),
      b = GaugeAlgebraRealization.iteratedCovDerivAdjoint gaugeField l
        (GaugeAlgebraRealization.fieldStrength gaugeField ν lam) 0 φ} ∪ S) :=
  GaugeAlgebraRealization.invariant_mem_adjoin_fieldStrength gaugeRealization S
    (fun p μ φ y _ =>
      Subring.mem_center_iff.mp
        (includeGauge_mem_center ((LocalGaugeFieldAlgebra.gaugeField GaugeAlgebra) p μ φ)) y)
    hS hx hinv

end JetAlgebra

end StandardModel
