/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.ClassicalFieldTheory.GaugeTheory.GaugeBoson.Basic
public import Physlib.ClassicalFieldTheory.GaugeTheory.LocalGaugeData.Basic
public import Physlib.Relativity.DerivAlgebra
public import Physlib.Mathematics.SymmetricAlgebra
public import Mathlib.LinearAlgebra.Dual.Lemmas

/-!
# The jet algebra of the gauge bosons of a gauge theory

## i. Overview

The gauge bosons of a gauge theory with Lie algebra `𝔤` are jointly one bosonic field
valued in `Lorentz.CoVector ⊗[ℝ] 𝔤`, the target space `GaugeBoson 𝔤` of
`Physlib.ClassicalFieldTheory.GaugeTheory.GaugeBoson.Basic`. Its *jet algebra* — the
algebra in which the gauge-boson part of a Lagrangian lives — is the free commutative
algebra on the component functions `∂_s A_μ^φ`, built here in the same way as the
`BBoson` jet algebra, but non-abelian and **without a basis of the gauge algebra**: the
adjoint index is carried by an abstract covector `φ : Module.Dual ℝ 𝔤` throughout,
following the dual-family formulation of
`Physlib.ClassicalFieldTheory.GaugeTheory.GaugeBoson.Realization`. For the Standard Model,
`𝔤` is `StandardModel.GaugeAlgebra`.

Following the split promised for this directory, the structure is:
1. this file — the jet algebra with its generators, over the target space and jet
   component space of `GaugeBoson.Basic`;
2. `LorentzAction` — the action of the Lorentz group;
3. `GaugeAction` — the action of the jet gauge group;
4. `JetDeriv` — the formal total derivative;
5. `MassDim` — the mass-dimension grading.

## ii. Key results

- `GaugeJetAlgebra` : the jet algebra of the gauge bosons.
- `GaugeJetAlgebra.ofComponent`, `GaugeJetAlgebra.ofA` : the generators.

## iii. Table of contents

- A. The jet algebra
  - A.1. The generators

-/

@[expose] public section

set_option linter.unusedSectionVars false

variable {𝔤 : Type} [LieRing 𝔤] [LieAlgebra ℝ 𝔤] [Module.Finite ℝ 𝔤]


open TensorProduct


/-!

## A. The jet algebra

-/

variable (𝔤) in
/-- **The jet algebra of the gauge bosons**: the free commutative algebra
  on the component functions `∂_s A_μ^φ` of the gauge-boson field, realized as the
  symmetric algebra on the jet component space. The commutativity of the product is the
  Bose statistics of the gauge fields. -/
abbrev GaugeJetAlgebra : Type := SymmetricAlgebra ℝ (GaugeBoson.JetComponentSpace 𝔤)

namespace GaugeJetAlgebra

/-!

### A.1. The generators

-/

variable (𝔤) in
/-- The undifferentiated component function `A^φ` of the gauge-boson field along a
  covector `φ` on the target space. -/
noncomputable def ofComponent : Module.Dual ℝ (GaugeBoson 𝔤) →ₗ[ℝ] (GaugeJetAlgebra 𝔤) :=
  (SymmetricAlgebra.ι ℝ _).comp
    (TensorProduct.mk ℝ DerivAlgebraReal (Module.Dual ℝ (GaugeBoson 𝔤)) 1)

lemma ofComponent_apply (φ : Module.Dual ℝ (GaugeBoson 𝔤)) :
    (ofComponent 𝔤) φ = SymmetricAlgebra.ι ℝ _ ((1 : DerivAlgebraReal) ⊗ₜ[ℝ] φ) := rfl

variable (𝔤) in
/-- **The component function `A_μ^φ` of the gauge-boson field**: the spacetime index `μ`
  paired against the Lorentz coordinate basis, the adjoint index against the abstract
  covector `φ` on the gauge algebra. These are the generators the ambient theory sees;
  no basis of the gauge algebra is involved. -/
noncomputable def ofA (μ : Fin 1 ⊕ Fin 3) :
    Module.Dual ℝ 𝔤 →ₗ[ℝ] (GaugeJetAlgebra 𝔤) :=
  (ofComponent 𝔤).comp ((GaugeBoson.componentDual 𝔤) (Lorentz.CoVector.basis.dualBasis μ))

lemma ofA_apply (μ : Fin 1 ⊕ Fin 3) (φ : Module.Dual ℝ 𝔤) :
    (ofA 𝔤) μ φ = (ofComponent 𝔤) ((GaugeBoson.componentDual 𝔤)
      (Lorentz.CoVector.basis.dualBasis μ) φ) := rfl

/-- The jet algebra is generated by the component functions. -/
@[simp]
lemma adjoin_ι_eq_top :
    Algebra.adjoin ℝ (Set.range (SymmetricAlgebra.ι ℝ (GaugeBoson.JetComponentSpace 𝔤))) = ⊤ :=
  SymmetricAlgebra.adjoin_range_ι

end GaugeJetAlgebra

