/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Mathematics.HomogeneousGenerators
public import Physlib.Particles.StandardModel.IsFermionSector.Basic
/-!
# The mass-weight grading of the fermion sector

## i. Overview

The elements of the fermion algebra of a given mass weight form a submodule. Mass weight is
twice the mass dimension, so that it is a natural number: a fermion tower `∇ⁿψ` with `n`
covariant derivatives has mass dimension `3/2 + n` and mass weight `3 + 2 * n`, and a term
of mass dimension four, as in the Lagrangian, has mass weight eight.

The fermion towers generate the fermion algebra, and `massWeightPoly` is a monomial on
each of them. The results of `Physlib.Mathematics.HomogeneousGenerators` then describe
every mass-weight submodule. The submodules of weight at most eight are found by removing
the leftmost tower of each product, and weight eight collapses, by the commutation of the
derivative submodules, to the kinetic sector `derivSubmodule 0 * derivSubmodule 1`.

## ii. Key results

- `massWeightSubmodule_eq_iSup_mul` : removing the leftmost fermion tower.
- `massWeightSubmodule_eq` : the binary weight recursion.
- `massWeightSubmodule_eq_bot` : the weights `1`, `2` and `4` are empty.
- `massWeightSubmodule_three_eq` to `massWeightSubmodule_eight_eq` : the mass weights up to eight.

## iii. Table of contents

- A. The mass-weight submodules
- B. The fermion towers generate and have weight `3 + 2 * n`
- C. The weight decompositions
- D. Mass weights up to eight

-/

@[expose] public section

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz

namespace IsFermionSector

variable {B : Type} [Ring B] [Algebra ℂ B]
  {repGauge : Representation ℂ GaugeGroupI B}
  {hrepGauge_mul : ∀ (g : GaugeGroupI) (b₁ b₂ : B),
    repGauge g (b₁ * b₂) = repGauge g b₁ * repGauge g b₂}
  {repLorentz : Representation ℂ SL(2,ℂ) B}
  {hrepLorentz_mul : ∀ (Λ : SL(2,ℂ)) (b₁ b₂ : B),
    repLorentz Λ (b₁ * b₂) = repLorentz Λ b₁ * repLorentz Λ b₂}
  {d : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ DownSinglet →ₗ[ℂ] B}
  {bard : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule DownSinglet) →ₗ[ℂ] B}
  {u : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ UpSinglet →ₗ[ℂ] B}
  {baru : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule UpSinglet) →ₗ[ℂ] B}
  {Q : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ QuarkDoublet →ₗ[ℂ] B}
  {barQ : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule QuarkDoublet) →ₗ[ℂ] B}
  {L : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ LeptonDoublet →ₗ[ℂ] B}
  {barL : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule LeptonDoublet) →ₗ[ℂ] B}
  {e : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ LeptonSinglet →ₗ[ℂ] B}
  {bare : {n : ℕ} → Fin 3 → (Fin n → Fin 1 ⊕ Fin 3) → Module.Dual ℂ (ConjModule LeptonSinglet) →ₗ[ℂ] B}
  {massWeightPoly : B →ₐ[ℂ] Polynomial B}
  (h : IsFermionSector B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
      d bard u baru Q barQ L barL e bare massWeightPoly)

/-!

## A. The mass-weight submodules

-/

/-- All elements of the fermion algebra of mass weight exactly `w`: the intersection
  of the algebra generated by the fermion towers with the part on which
  `massWeightPoly` is the monomial `X ^ w`. -/
noncomputable def massWeightSubmodule (h : IsFermionSector B repGauge hrepGauge_mul repLorentz hrepLorentz_mul
      d bard u baru Q barQ L barL e bare massWeightPoly) (w : ℕ) :
    Submodule ℂ B :=
  (h.fermionAlgebra).toSubmodule
    ⊓ LinearMap.ker (massWeightPoly.toLinearMap
      - (Polynomial.monomial w : B →ₗ[B] Polynomial B).restrictScalars ℂ)

lemma massWeightPoly_of_mem_massWeightSubmodule {w : ℕ} {x : B}
    (hx : x ∈ h.massWeightSubmodule w) :
    massWeightPoly x = Polynomial.monomial w x :=
  (Subalgebra.mem_homogeneousSubmodule_iff.mp hx).2

lemma mem_fermionAlgebra_of_mem_massWeightSubmodule {w : ℕ} {x : B}
    (hx : x ∈ h.massWeightSubmodule w) : x ∈ h.fermionAlgebra :=
  (Subalgebra.mem_homogeneousSubmodule_iff.mp hx).1

lemma one_le_massWeightSubmodule_zero : (1 : Submodule ℂ B) ≤ h.massWeightSubmodule 0 :=
  Subalgebra.one_le_homogeneousSubmodule_zero

lemma massWeightSubmodule_mul_le (m n : ℕ) :
    h.massWeightSubmodule m * h.massWeightSubmodule n ≤ h.massWeightSubmodule (m + n) :=
  Subalgebra.homogeneousSubmodule_mul_le m n

/-!

## B. The fermion towers generate and have weight `3 + 2 * n`

-/

/-- The fermion algebra is generated by the fermion towers of every derivative order. -/
lemma fermionAlgebra_eq_adjoin_derivSubmodule :
    h.fermionAlgebra = Algebra.adjoin ℂ (⋃ n, (h.derivSubmodule n : Set B)) := by
  simp only [h.derivSubmodule_eq_span, Algebra.adjoin_iUnion, Algebra.adjoin_span,
    fermionAlgebra]
  exact iSup_comm

/-- `massWeightPoly` is the monomial `X ^ (3 + 2 * n)` on the fermion towers with `n`
  covariant derivatives. -/
lemma massWeightPoly_of_mem_derivSubmodule (n : ℕ) :
    ∀ x ∈ h.derivSubmodule n, massWeightPoly x = Polynomial.monomial (3 + 2 * n) x := by
  intro x hx
  rw [h.derivSubmodule_eq_span] at hx
  induction hx using Submodule.span_induction with
  | mem y hy =>
    simp only [Set.mem_iUnion, Set.mem_union, Set.mem_range] at hy
    obtain ⟨i, l, (((((((((⟨φ, rfl⟩ | ⟨φ, rfl⟩) | ⟨φ, rfl⟩) | ⟨φ, rfl⟩) | ⟨φ, rfl⟩) | ⟨φ, rfl⟩) |
      ⟨φ, rfl⟩) | ⟨φ, rfl⟩) | ⟨φ, rfl⟩) | ⟨φ, rfl⟩)⟩ := hy <;>
    simp only [h.massWeight_d, h.massWeight_bard, h.massWeight_u, h.massWeight_baru,
      h.massWeight_Q, h.massWeight_barQ, h.massWeight_L, h.massWeight_barL, h.massWeight_e,
      h.massWeight_bare]
  | zero => simp
  | add x y _ _ hx hy => rw [map_add, hx, hy, map_add]
  | smul c x _ hx => rw [map_smul, hx, Polynomial.smul_monomial]

/-- A fermion tower with `n` covariant derivatives has mass weight `3 + 2 * n`. -/
lemma derivSubmodule_le_massWeightSubmodule (n : ℕ) :
    h.derivSubmodule n ≤ h.massWeightSubmodule (3 + 2 * n) :=
  Subalgebra.le_homogeneousSubmodule h.fermionAlgebra_eq_adjoin_derivSubmodule
    h.massWeightPoly_of_mem_derivSubmodule n

/-!

## C. The weight decompositions

Every result here is a spanning statement: a submodule is a join of products of fermion
towers, in the order written. It says nothing about the products being nonzero or
independent.

-/

/-- Weight zero is the scalars: every fermion tower has positive weight. -/
lemma massWeightSubmodule_zero_eq : h.massWeightSubmodule 0 = 1 :=
  Subalgebra.homogeneousSubmodule_zero_eq_one h.fermionAlgebra_eq_adjoin_derivSubmodule
    h.massWeightPoly_of_mem_derivSubmodule (fun n => by omega)

/-- The weight recursion: an element of positive mass weight `i` is a sum of single
  fermion towers of weight `i` and of products of two elements of lower positive weights
  summing to `i`. -/
lemma massWeightSubmodule_eq (i : ℕ) (hi : 0 < i) :
    h.massWeightSubmodule i
      = (⨆ k ∈ Finset.univ.filter (fun k : Fin i => 3 + 2 * (k : ℕ) = i),
          h.derivSubmodule (k : ℕ))
        ⊔ (⨆ p ∈ Finset.univ.filter (fun p : Fin i × Fin i => (p.1 : ℕ) + (p.2 : ℕ) = i),
            h.massWeightSubmodule (p.1 : ℕ) * h.massWeightSubmodule (p.2 : ℕ)) :=
  Subalgebra.homogeneousSubmodule_eq_sup_iSup_mul (deg := fun n => 3 + 2 * n)
    h.fermionAlgebra_eq_adjoin_derivSubmodule h.massWeightPoly_of_mem_derivSubmodule
    (fun n => by omega) i hi

/-- Removing the leftmost fermion tower: an element of positive weight `w` is a sum of
  products of a tower `∇ⁿψ` of weight `3 + 2 * n ≤ w` with an element of the remaining
  weight. -/
lemma massWeightSubmodule_eq_iSup_mul (w : ℕ) (hw : 0 < w) :
    h.massWeightSubmodule w
      = ⨆ n ∈ (Finset.range (w + 1)).filter (fun n => 3 + 2 * n ≤ w),
          h.derivSubmodule n * h.massWeightSubmodule (w - (3 + 2 * n)) :=
  Subalgebra.homogeneousSubmodule_eq_iSup_mul (deg := fun n => 3 + 2 * n)
    h.fermionAlgebra_eq_adjoin_derivSubmodule h.massWeightPoly_of_mem_derivSubmodule
    (fun n => by omega) hw

/-- The weights `1`, `2` and `4` are empty: the tower weights `3, 5, 7, …` and their sums
  only reach `0`, `3` and every weight from `5` on. -/
lemma massWeightSubmodule_eq_bot {w : ℕ} (hw : ¬ (w = 0 ∨ w = 3 ∨ 5 ≤ w)) :
    h.massWeightSubmodule w = ⊥ :=
  Subalgebra.homogeneousSubmodule_eq_bot h.fermionAlgebra_eq_adjoin_derivSubmodule
    h.massWeightPoly_of_mem_derivSubmodule (fun w => w = 0 ∨ w = 3 ∨ 5 ≤ w)
    (by omega) (fun n => by omega) (fun a b ha hb => by omega) hw

/-!

## D. Mass weights up to eight

Each case removes the leftmost tower. The towers `ψ`, `∇ψ` and `∇∇ψ` have weights `3`, `5`
and `7`; the remaining weight is then read off from a smaller weight.

-/

/-- There is nothing of weight one. -/
lemma massWeightSubmodule_one_eq : h.massWeightSubmodule 1 = ⊥ :=
  h.massWeightSubmodule_eq_bot (by omega)

/-- There is nothing of weight two. -/
lemma massWeightSubmodule_two_eq : h.massWeightSubmodule 2 = ⊥ :=
  h.massWeightSubmodule_eq_bot (by omega)

/-- Weight three is the underived fermion towers: `ψ` leaves weight zero. -/
lemma massWeightSubmodule_three_eq :
    h.massWeightSubmodule 3 = h.derivSubmodule 0 := by
  rw [h.massWeightSubmodule_eq_iSup_mul 3 (by norm_num),
    show (Finset.range 4).filter (fun n => 3 + 2 * n ≤ 3) = {0} from by decide,
    Finset.iSup_singleton]
  simp [h.massWeightSubmodule_zero_eq]

/-- There is nothing of weight four. -/
lemma massWeightSubmodule_four_eq : h.massWeightSubmodule 4 = ⊥ :=
  h.massWeightSubmodule_eq_bot (by omega)

/-- Weight five is the once-derived fermion towers: `ψ` would leave weight two, which is
  empty, and `∇ψ` leaves weight zero. -/
lemma massWeightSubmodule_five_eq :
    h.massWeightSubmodule 5 = h.derivSubmodule 1 := by
  rw [h.massWeightSubmodule_eq_iSup_mul 5 (by norm_num),
    show (Finset.range 6).filter (fun n => 3 + 2 * n ≤ 5) = {0, 1} from by decide,
    Finset.iSup_insert, Finset.iSup_singleton]
  simp [h.massWeightSubmodule_zero_eq, h.massWeightSubmodule_two_eq]

/-- Weight six is the products of two underived fermion towers: `ψ` leaves weight three,
  which is `ψ`, and `∇ψ` would leave weight one, which is empty. -/
lemma massWeightSubmodule_six_eq :
    h.massWeightSubmodule 6 = h.derivSubmodule 0 * h.derivSubmodule 0 := by
  rw [h.massWeightSubmodule_eq_iSup_mul 6 (by norm_num),
    show (Finset.range 7).filter (fun n => 3 + 2 * n ≤ 6) = {0, 1} from by decide,
    Finset.iSup_insert, Finset.iSup_singleton]
  simp [h.massWeightSubmodule_three_eq, h.massWeightSubmodule_one_eq]

/-- Weight seven is the twice-derived fermion towers: `ψ` and `∇ψ` would leave weights
  four and two, which are empty, and `∇∇ψ` leaves weight zero. -/
lemma massWeightSubmodule_seven_eq :
    h.massWeightSubmodule 7 = h.derivSubmodule 2 := by
  rw [h.massWeightSubmodule_eq_iSup_mul 7 (by norm_num),
    show (Finset.range 8).filter (fun n => 3 + 2 * n ≤ 7) = {0, 1, 2} from by decide,
    Finset.iSup_insert, Finset.iSup_insert, Finset.iSup_singleton]
  simp [h.massWeightSubmodule_four_eq, h.massWeightSubmodule_two_eq,
    h.massWeightSubmodule_zero_eq]

/-- Weight eight is the products of an underived and a once-derived fermion tower, the
  kinetic-term sector: `ψ` leaves `∇ψ`, `∇ψ` leaves `ψ`, and `∇∇ψ` would leave weight one,
  which is empty. The two orders agree by `derivSubmodule_mul_comm`. -/
lemma massWeightSubmodule_eight_eq :
    h.massWeightSubmodule 8 = h.derivSubmodule 0 * h.derivSubmodule 1 := by
  rw [h.massWeightSubmodule_eq_iSup_mul 8 (by norm_num),
    show (Finset.range 9).filter (fun n => 3 + 2 * n ≤ 8) = {0, 1, 2} from by decide,
    Finset.iSup_insert, Finset.iSup_insert, Finset.iSup_singleton]
  simp [h.massWeightSubmodule_five_eq, h.massWeightSubmodule_three_eq,
    h.massWeightSubmodule_one_eq, h.derivSubmodule_mul_comm 1 0]

end IsFermionSector

end StandardModel
