/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.Basic
public import Mathlib.LinearAlgebra.Eigenspace.Basic
/-!
# `SU(2)` permutation decompositions

## i. Overview

An **`SU(2)` permutation decomposition** of a submodule `V` is a `ZMod 4`-indexed family of
subspaces whose supremum is `V`, the grade-`k` piece scaled by `i ^ k` under the `SU(2)`
element

  `su2Perm = !![0, -1; 1, 0]`,

the Weyl reflection of `SU(2)`. On a doublet it sends `(a, b)` to `(-b, a)`, exchanging the
two isospin components and so exchanging the isospin weights `+1` and `-1` that the third
coordinate of a `GaugeWeight` records.

`su2Perm` squares to `-1`, so it has order four in `SU(2)` and `rep gaugeSU2Perm` satisfies
`T ^ 4 = 1`. Its spectrum is therefore contained in the fourth roots of unity, and the index
group is `ZMod 4` with eigenvalue `i ^ k` — multiplicative in `k`, which is what makes the
grading add under multiplication, exactly as gauge weights do in `GaugeWeightDecomposition`.
Because `ZMod 4` is finite there is no support field: the finiteness that
`GaugeWeightDecomposition.supp` has to record is automatic here.

The four grades split by Higgs degree. On a product of an even number of Higgs symbols
`su2Perm` acts as an involution, so only the grades `0` and `2` occur — the eigenvalues `±1`
— and the `SU(2)` invariants sit in grade `0`. The grades `1` and `3`, at `±i`, are where the
odd-degree terms live: the Higgs doublet itself is spanned by `H⁰ - i H¹` in grade `1` and
`H⁰ + i H¹` in grade `3`. A `ZMod 2` version of this file would have nothing to say about
those sectors, and so nothing to say about the Yukawa terms.

## ii. A warning: grade zero is weaker than invariance

Like the isospin weight, this is a *sieve* rather than a characterization.
`mem_zero_of_invariant` says an invariant element has grade zero, and there is no converse.
What it buys is a genuine sharpening of the isospin weight in `GaugeWeightDecomposition`,
whose weight-zero piece cannot separate the isospin singlet from the neutral component of a
higher multiplet. Because `su2Perm` exchanges the two isospin components it acts on the
isospin-zero subspace, and its grade-`2` part is thrown away by this sieve.

The sieve cannot be pushed further by grading alone. A grading sees only the abelian
subgroup generated by the elements it uses, and for any abelian subgroup of `SU(2)` the
invariants of that subgroup are strictly larger than the `SU(2)` invariants in high isospin —
the square of the neutral triplet component survives every such sieve. Cutting that down
needs the continuous symmetry, not another grading.

## iii. Key results

- `su2Perm` : the `SU(2)` Weyl element `!![0, -1; 1, 0]`, and `gaugeSU2Perm` its image in
  the gauge group.
- `su2PermSign` : the character `k ↦ i ^ k` on `ZMod 4`, injective and multiplicative.
- `SU2PermDecomposition` : a `ZMod 4`-graded family of pure-sign subspaces with supremum `V`.
- `SU2PermDecomposition.sup` : two decompositions combine gradewise into one of `V ⊔ V'`.
- `SU2PermDecomposition.mul` : grades add under multiplication, decomposing `V * V'`.
- `SU2PermDecomposition.mem_zero_of_invariant` : a gauge-invariant element has grade zero.

## iv. Table of contents

- A. The `SU(2)` Weyl element
- B. The sign character of `ZMod 4`
- C. `SU(2)` permutation decompositions
- D. Joins
- E. Products
- F. Invariants

-/

@[expose] public section

namespace StandardModel

open Matrix

/-!

## A. The `SU(2)` Weyl element

-/

/-- The `SU(2)` Weyl element `!![0, -1; 1, 0]`. On a doublet it sends `(a, b)` to `(-b, a)`,
  exchanging the two isospin components; it squares to `-1`, so it has order four in
  `SU(2)`. -/
noncomputable def su2Perm : specialUnitaryGroup (Fin 2) ℂ :=
  ⟨!![0, -1; 1, 0], by
    rw [Matrix.mem_specialUnitaryGroup_iff]
    refine ⟨?_, ?_⟩
    · rw [Matrix.mem_unitaryGroup_iff]
      ext a b
      fin_cases a <;> fin_cases b <;>
        simp [Matrix.mul_apply, Fin.sum_univ_two, star_eq_conjTranspose,
          Matrix.conjTranspose_apply]
    · simp [Matrix.det_fin_two_of]⟩

lemma su2Perm_coe : (su2Perm : specialUnitaryGroup (Fin 2) ℂ).1 = !![0, -1; 1, 0] := rfl

/-- The inverse Weyl element is `!![0, 1; -1, 0]`. -/
lemma su2Perm_inv_coe :
    (su2Perm⁻¹ : specialUnitaryGroup (Fin 2) ℂ).1 = !![0, 1; -1, 0] := by
  rw [← Matrix.star_eq_inv, Matrix.specialUnitaryGroup.coe_star, su2Perm_coe]
  ext a b
  fin_cases a <;> fin_cases b <;> simp

/-- The Weyl element as a gauge transformation: trivial on colour and hypercharge. -/
noncomputable def gaugeSU2Perm : GaugeGroupI := ⟨1, su2Perm, 1⟩

/-!

## B. The sign character of `ZMod 4`

-/

/-- The fourth root of unity `i ^ k` attached to a grade `k : ZMod 4`: the eigenvalue of the
  Weyl element on the `k` piece of a decomposition. -/
noncomputable def su2PermSign (k : ZMod 4) : ℂ :=
  if k = 0 then 1 else if k = 1 then Complex.I else if k = 2 then -1 else -Complex.I

@[simp] lemma su2PermSign_zero : su2PermSign 0 = 1 := rfl

@[simp] lemma su2PermSign_one : su2PermSign 1 = Complex.I := rfl

@[simp] lemma su2PermSign_two : su2PermSign 2 = -1 := rfl

@[simp] lemma su2PermSign_three : su2PermSign 3 = -Complex.I := rfl

/-- The sign is a character: grades **add** under multiplication because the fourth roots of
  unity multiply. -/
lemma su2PermSign_add (k l : ZMod 4) :
    su2PermSign (k + l) = su2PermSign k * su2PermSign l := by
  have hcases : ∀ j : ZMod 4, j = 0 ∨ j = 1 ∨ j = 2 ∨ j = 3 := by decide
  rcases hcases k with rfl | rfl | rfl | rfl <;> rcases hcases l with rfl | rfl | rfl | rfl <;>
    simp [show (1 + 1 : ZMod 4) = 2 from by decide,
      show (1 + 2 : ZMod 4) = 3 from by decide, show (1 + 3 : ZMod 4) = 0 from by decide,
      show (2 + 1 : ZMod 4) = 3 from by decide, show (2 + 2 : ZMod 4) = 0 from by decide,
      show (2 + 3 : ZMod 4) = 1 from by decide, show (3 + 1 : ZMod 4) = 0 from by decide,
      show (3 + 2 : ZMod 4) = 1 from by decide, show (3 + 3 : ZMod 4) = 2 from by decide,
      Complex.I_mul_I]

lemma su2PermSign_ne_zero (k : ZMod 4) : su2PermSign k ≠ 0 := by
  have hcases : ∀ j : ZMod 4, j = 0 ∨ j = 1 ∨ j = 2 ∨ j = 3 := by decide
  rcases hcases k with rfl | rfl | rfl | rfl <;> simp

/-- The four fourth roots of unity are distinct, so the pieces of a decomposition sit in
  eigenspaces at distinct eigenvalues and are automatically independent. -/
lemma su2PermSign_injective : Function.Injective su2PermSign := by
  have hcases : ∀ j : ZMod 4, j = 0 ∨ j = 1 ∨ j = 2 ∨ j = 3 := by decide
  intro k l hkl
  rcases hcases k with rfl | rfl | rfl | rfl <;> rcases hcases l with rfl | rfl | rfl | rfl <;>
    simp_all [Complex.ext_iff] <;> norm_num at hkl

/-!

## C. `SU(2)` permutation decompositions

-/

variable {B : Type*} [Ring B] [Algebra ℂ B]

/-- An **`SU(2)` permutation decomposition** of a submodule `V`: a `ZMod 4`-graded family of
  subspaces of pure sign under the Weyl element `gaugeSU2Perm`, whose supremum is `V`.

  Unlike `GaugeWeightDecomposition` there is no support field — `ZMod 4` is finite, so the
  finiteness condition is automatic. The four grades carry the four fourth roots of unity;
  even-degree terms occupy grades `0` and `2`, odd-degree terms grades `1` and `3`. -/
structure SU2PermDecomposition (rep : Representation ℂ GaugeGroupI B)
    (V : Submodule ℂ B) where
  /-- The grade `k` piece of the decomposition. -/
  piece : ZMod 4 → Submodule ℂ B
  /-- Each piece is of pure sign under the Weyl element. -/
  piece_le : ∀ k, ∀ x, x ∈ piece k → rep gaugeSU2Perm x = su2PermSign k • x
  /-- The pieces exhaust `V`. -/
  iSup_piece : (⨆ k, piece k) = V

namespace SU2PermDecomposition

variable {rep : Representation ℂ GaugeGroupI B} {V V' : Submodule ℂ B}

/-- The grade-`k` piece lies in the `su2PermSign k` eigenspace of the Weyl element. This is
  `piece_le` phrased as an inequality of submodules. -/
lemma piece_le_eigenspace (d : SU2PermDecomposition rep V) (k : ZMod 4) :
    d.piece k ≤ Module.End.eigenspace (rep gaugeSU2Perm) (su2PermSign k) :=
  fun _ hy => Module.End.mem_eigenspace_iff.mpr (d.piece_le k _ hy)

/-- Transport a decomposition along an equality of submodules. -/
def copy (d : SU2PermDecomposition rep V) (W : Submodule ℂ B) (hW : W = V) :
    SU2PermDecomposition rep W where
  piece := d.piece
  piece_le := d.piece_le
  iSup_piece := by rw [d.iSup_piece, hW]

@[simp]
lemma copy_piece (d : SU2PermDecomposition rep V) (W : Submodule ℂ B) (hW : W = V) :
    (d.copy W hW).piece = d.piece := rfl

/-- The zero submodule carries the trivial decomposition, with every grade empty. This is
  the unit for `sup`, and the decomposition of every submodule that turns out to vanish. -/
def bot : SU2PermDecomposition rep (⊥ : Submodule ℂ B) where
  piece _ := ⊥
  piece_le k x hx := by
    rw [Submodule.mem_bot] at hx
    subst hx
    simp
  iSup_piece := by simp

@[simp]
lemma bot_piece (k : ZMod 4) : (bot (rep := rep)).piece k = ⊥ := rfl

/-!

## D. Joins

-/

/-- The join of two decompositions: the pieces and suprema combine gradewise, decomposing
  `V ⊔ V'`. -/
noncomputable def sup (d : SU2PermDecomposition rep V) (d' : SU2PermDecomposition rep V') :
    SU2PermDecomposition rep (V ⊔ V') where
  piece k := d.piece k ⊔ d'.piece k
  piece_le k x hx :=
    Module.End.mem_eigenspace_iff.mp
      (sup_le (d.piece_le_eigenspace k) (d'.piece_le_eigenspace k) hx)
  iSup_piece := by
    rw [iSup_sup_eq, d.iSup_piece, d'.iSup_piece]

@[simp]
lemma sup_piece (d : SU2PermDecomposition rep V) (d' : SU2PermDecomposition rep V')
    (k : ZMod 4) : (d.sup d').piece k = d.piece k ⊔ d'.piece k := rfl

/-!

## E. Products

-/

/-- The product of two decompositions: grades **add** under multiplication, so the grade-`k`
  piece of `V * V'` is spanned by the products of pieces whose grades sum to `k`.

  Multiplicativity of the representation is a hypothesis rather than a field: a
  `Representation` records only a linear action. -/
noncomputable def mul (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU2PermDecomposition rep V) (d' : SU2PermDecomposition rep V') :
    SU2PermDecomposition rep (V * V') where
  piece k := ⨆ k₁, ⨆ k₂, ⨆ _ : k₁ + k₂ = k, d.piece k₁ * d'.piece k₂
  piece_le k x hx := by
    have key : (⨆ k₁, ⨆ k₂, ⨆ _ : k₁ + k₂ = k, d.piece k₁ * d'.piece k₂)
        ≤ Module.End.eigenspace (rep gaugeSU2Perm) (su2PermSign k) := by
      refine iSup_le fun k₁ => iSup_le fun k₂ => iSup_le fun hk => ?_
      refine Submodule.mul_le.mpr fun m hm n hn => ?_
      refine Module.End.mem_eigenspace_iff.mpr ?_
      rw [hmul, d.piece_le k₁ m hm, d'.piece_le k₂ n hn, smul_mul_smul_comm,
        ← su2PermSign_add, hk]
    exact Module.End.mem_eigenspace_iff.mp (key hx)
  iSup_piece := by
    refine le_antisymm (iSup_le fun k => iSup_le fun k₁ => iSup_le fun k₂ =>
      iSup_le fun _ => ?_) ?_
    · exact mul_le_mul' ((le_iSup d.piece k₁).trans d.iSup_piece.le)
        ((le_iSup d'.piece k₂).trans d'.iSup_piece.le)
    · have hV : (⨆ k₁, d.piece k₁) * (⨆ k₂, d'.piece k₂) = V * V' := by
        rw [d.iSup_piece, d'.iSup_piece]
      rw [← hV, Submodule.iSup_mul]
      refine iSup_le fun k₁ => ?_
      rw [Submodule.mul_iSup]
      refine iSup_le fun k₂ => ?_
      exact le_iSup_of_le (k₁ + k₂)
        (le_iSup_of_le k₁ (le_iSup_of_le k₂ (le_iSup_of_le rfl le_rfl)))

lemma mul_piece (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU2PermDecomposition rep V) (d' : SU2PermDecomposition rep V') (k : ZMod 4) :
    (d.mul hmul d').piece k = ⨆ k₁, ⨆ k₂, ⨆ _ : k₁ + k₂ = k, d.piece k₁ * d'.piece k₂ := rfl

/-- The grade-`k` piece of a product, with the second grade solved for: the double join
  collapses to a single one. -/
lemma mul_piece_eq_sub
    (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU2PermDecomposition rep V) (d' : SU2PermDecomposition rep V') (k : ZMod 4) :
    (d.mul hmul d').piece k = ⨆ k₁, d.piece k₁ * d'.piece (k - k₁) := by
  rw [mul_piece]
  refine le_antisymm (iSup_le fun k₁ => iSup_le fun k₂ => iSup_le fun hk => ?_) ?_
  · exact le_iSup_of_le k₁ (by rw [eq_sub_of_add_eq' hk])
  · exact iSup_le fun k₁ =>
      le_iSup_of_le k₁ (le_iSup_of_le (k - k₁) (le_iSup_of_le (add_sub_cancel k₁ k) le_rfl))

/-- **The grade-`k` piece of a product, written out.** `ZMod 4` has four elements, so the
  join is a four-term one. -/
lemma mul_piece_eq (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU2PermDecomposition rep V) (d' : SU2PermDecomposition rep V') (k : ZMod 4) :
    (d.mul hmul d').piece k
      = d.piece 0 * d'.piece k ⊔ d.piece 1 * d'.piece (k - 1)
        ⊔ d.piece 2 * d'.piece (k - 2) ⊔ d.piece 3 * d'.piece (k - 3) := by
  have hcases : ∀ j : ZMod 4, j = 0 ∨ j = 1 ∨ j = 2 ∨ j = 3 := by decide
  rw [mul_piece_eq_sub]
  refine le_antisymm (iSup_le fun k₁ => ?_) (sup_le (sup_le (sup_le ?_ ?_) ?_) ?_)
  · rcases hcases k₁ with rfl | rfl | rfl | rfl
    · rw [sub_zero]
      exact le_sup_of_le_left (le_sup_of_le_left le_sup_left)
    · exact le_sup_of_le_left (le_sup_of_le_left le_sup_right)
    · exact le_sup_of_le_left le_sup_right
    · exact le_sup_right
  · exact le_iSup_of_le 0 (by rw [sub_zero])
  · exact le_iSup_of_le 1 le_rfl
  · exact le_iSup_of_le 2 le_rfl
  · exact le_iSup_of_le 3 le_rfl

/-- The unit submodule has grade zero: the identity of `B` is fixed by every gauge
  transformation, provided the representation preserves the unit. -/
noncomputable def one (hone : ∀ g : GaugeGroupI, rep g 1 = 1) :
    SU2PermDecomposition rep (1 : Submodule ℂ B) where
  piece k := if k = 0 then 1 else ⊥
  piece_le := by
    intro k x hx
    rcases eq_or_ne k 0 with rfl | hk
    · rw [if_pos rfl, Submodule.one_eq_span, Submodule.mem_span_singleton] at hx
      obtain ⟨c, rfl⟩ := hx
      rw [map_smul, hone, su2PermSign_zero, one_smul]
    · rw [if_neg hk, Submodule.mem_bot] at hx
      subst hx
      simp
  iSup_piece := by
    refine le_antisymm (iSup_le fun k => ?_) (le_iSup_of_le 0 (le_of_eq (if_pos rfl).symm))
    by_cases hk : k = 0
    · rw [if_pos hk]
    · rw [if_neg hk]
      exact bot_le

@[simp]
lemma one_piece (hone : ∀ g : GaugeGroupI, rep g 1 = 1) (k : ZMod 4) :
    (one (B := B) (rep := rep) hone).piece k = if k = 0 then 1 else ⊥ := rfl

/-- Powers of a decomposed submodule: grades add, so `V ^ n` inherits a decomposition, built
  by iterating `mul` from `one`. -/
noncomputable def pow (hone : ∀ g : GaugeGroupI, rep g 1 = 1)
    (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU2PermDecomposition rep V) :
    (n : ℕ) → SU2PermDecomposition rep (V ^ n)
  | 0 => (one hone).copy _ (pow_zero V)
  | (n + 1) => ((pow hone hmul d n).mul hmul d).copy _ (pow_succ V n)

@[simp]
lemma pow_zero_piece (hone : ∀ g : GaugeGroupI, rep g 1 = 1)
    (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU2PermDecomposition rep V) (k : ZMod 4) :
    (d.pow hone hmul 0).piece k = if k = 0 then 1 else ⊥ := rfl

@[simp]
lemma pow_succ_piece (hone : ∀ g : GaugeGroupI, rep g 1 = 1)
    (hmul : ∀ (g : GaugeGroupI) (x y : B), rep g (x * y) = rep g x * rep g y)
    (d : SU2PermDecomposition rep V) (n : ℕ) (k : ZMod 4) :
    (d.pow hone hmul (n + 1)).piece k
      = ⨆ k₁, ⨆ k₂, ⨆ _ : k₁ + k₂ = k, (d.pow hone hmul n).piece k₁ * d.piece k₂ := rfl

/-!

## F. Invariants

-/

/-- **A gauge-invariant element has grade zero.** Only invariance under the single Weyl
  element `gaugeSU2Perm` is used: the other pieces lie in eigenspaces at `i`, `-1` and `-i`,
  all distinct from `1`.

  There is no converse; see the warning in the module docstring. -/
lemma mem_zero_of_invariant (d : SU2PermDecomposition rep V) {x : B} (hx : x ∈ V)
    (hV : ∀ g : GaugeGroupI, rep g x = x) : x ∈ d.piece 0 := by
  have hdisj : Disjoint
      (Module.End.eigenspace (rep gaugeSU2Perm) (su2PermSign 0))
      (⨆ k, ⨆ _ : k ≠ (0 : ZMod 4), d.piece k) :=
    (((Module.End.eigenspaces_iSupIndep (rep gaugeSU2Perm : Module.End ℂ B)).comp
      su2PermSign_injective) 0).mono_right (iSup₂_mono fun k _ => d.piece_le_eigenspace k)
  have key : (⨆ k, d.piece k)
      ⊓ Module.End.eigenspace (rep gaugeSU2Perm) (su2PermSign 0) ≤ d.piece 0 := by
    rw [iSup_split_single d.piece 0, sup_inf_assoc_of_le _ (d.piece_le_eigenspace 0)]
    exact sup_le le_rfl (hdisj.symm.le_bot.trans bot_le)
  refine key ⟨?_, Module.End.mem_eigenspace_iff.mpr ?_⟩
  · rw [d.iSup_piece]
    exact hx
  · rw [su2PermSign_zero, one_smul]
    exact hV _

end SU2PermDecomposition
end StandardModel
