/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.Matter.JetComponentSpace.Basic
public import Physlib.Particles.StandardModel.GaugeGroup.MaurerCartan.Truncation
public import Physlib.Particles.StandardModel.Matter.JetComponentSpace.CovariantDeriv
/-!
# The infinitesimal action underlying a matter representation

## i. Overview

The covariant derivative `∇_ρ F = [∂_ρ F] + A_ρ · F` of a matter family is built from
an action `act : GaugeAlgebra →ₗ[ℝ] V →ₗ[ℂ] V` of the gauge algebra on the value
space. For the covariant derivative to transform covariantly, `act` must be the
*infinitesimal action* underlying the representation `rep` of the jet gauge group in
which the family transforms — the physicists' statement that the matrices `i dρ(T^a)`
generate `ρ`. This file packages that compatibility as the structure
`IsInfinitesimalActionOf`, and proves the theorem it exists for: the covariant
derivative preserves the gauge tensors, `TransformsIn.covDerivAction`.

## ii. Key results

- `GaugeAlgebra.IsInfinitesimalActionOf` : `act` is the infinitesimal action underlying
  `rep`.
- `TransformsIn.covDerivAction` : the covariant derivative preserves `TransformsIn`.

## iii. Table of contents

- A. The infinitesimal action underlying a representation
- B. The covariant derivative preserves `TransformsIn`
- C. The conjugate action and the conjugate representation

-/

@[expose] public section

namespace StandardModel
open Matrix MatrixGroups TensorProduct MvPowerSeries
variable {B : Type} [Ring B] [Algebra ℂ B]
variable {V : Type} [AddCommGroup V] [Module ℂ V]

namespace GaugeAlgebra

open IsGaugeField

variable {repLorentz : Representation ℂ SL(2,ℂ) B}
variable {repGauge : Representation ℂ JetGaugeGroupI B}
variable {A : Multiset (Fin 1 ⊕ Fin 3) → (Fin 1 ⊕ Fin 3) → Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B}

/-!

## A. The infinitesimal action underlying a representation

-/

/-- `act` is the *infinitesimal action* of the gauge algebra underlying the
  representation `rep` of the jet gauge group, when the base-point Taylor
  coefficients of `rep` satisfy the two laws forced by `rep` being generated by
  `act`:

  * `repCoeff_cons` — the Leibniz rule in the Maurer–Cartan form: differentiating
    the representation once produces minus the action of the Maurer–Cartan form,
    with the remaining derivatives distributed over the antidiagonal (for the
    adjoint representation this is `adjointDualCoeff_cons`);
  * `repCoeff_act` — the transports of `rep` intertwine `act` with the adjoint
    transports, as an antidiagonal convolution (for the adjoint representation this
    is `adjointTransport_bracket`); at `x = 0` it is the classical equivariance
    `rep(U)|₀ ∘ act c = act (Ad(U) c)|₀ ∘ rep(U)|₀`.

  These are exactly the identities consumed by the proof that the covariant
  derivative `covDerivAction` preserves `TransformsIn`. -/
structure IsInfinitesimalActionOf (act : GaugeAlgebra →ₗ[ℝ] V →ₗ[ℂ] V)
    (rep : Representation ℂ JetGaugeGroupI (JetRing ⊗[ℂ] V)) : Prop where
  repCoeff_cons : ∀ (U : JetGaugeGroupI) (μ : Fin 1 ⊕ Fin 3)
      (x : Multiset (Fin 1 ⊕ Fin 3)),
    repCoeff rep U (μ ::ₘ x) =
      -((x.antidiagonal.map fun p =>
        act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv p.1
          (maurerCartanForm U μ))) ∘ₗ repCoeff rep U p.2).sum)
  repCoeff_act : ∀ (U : JetGaugeGroupI) (x : Multiset (Fin 1 ⊕ Fin 3))
      (c : GaugeAlgebra),
    repCoeff rep U x ∘ₗ act c =
      ((x.antidiagonal.map fun p =>
        act (adjointCoeff U p.1 c) ∘ₗ repCoeff rep U p.2).sum)

/-- The dual form of the Leibniz law: the once-more-derived dual coefficient is
  minus the antidiagonal convolution of dual coefficients against `act` of the
  derived Maurer–Cartan form — the analogue of `adjointDualCoeff_cons`. -/
lemma IsInfinitesimalActionOf.repDualCoeff_cons
    {act : GaugeAlgebra →ₗ[ℝ] V →ₗ[ℂ] V}
    {rep : Representation ℂ JetGaugeGroupI (JetRing ⊗[ℂ] V)}
    (h : IsInfinitesimalActionOf act rep) (U : JetGaugeGroupI) (μ : Fin 1 ⊕ Fin 3)
    (x : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ V) :
    repDualCoeff rep U (μ ::ₘ x) φ =
      -((x.antidiagonal.map fun p =>
        repDualCoeff rep U p.2 (φ ∘ₗ act (JetGaugeAlgebra.eval
          (JetGaugeAlgebra.iteratedDeriv p.1 (maurerCartanForm U μ))))).sum) := by
  refine LinearMap.ext fun v => ?_
  have h1 := LinearMap.congr_fun (h.repCoeff_cons U μ x) v
  simp only [LinearMap.neg_apply, Multiset.sum_linearMap_apply, Multiset.map_map,
    Function.comp_apply, LinearMap.coe_comp] at h1
  simp only [repDualCoeff, LinearMap.dualMap_apply, LinearMap.neg_apply,
    Multiset.sum_linearMap_apply, Multiset.map_map, Function.comp_apply,
    LinearMap.coe_comp]
  rw [h1, map_neg, map_multiset_sum, Multiset.map_map]
  exact congrArg Neg.neg (congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => rfl))

/-!

## B. The covariant derivative preserves `TransformsIn`

-/

section MatterCovariance

variable {rep : Representation ℂ JetGaugeGroupI (JetRing ⊗[ℂ] V)}
variable {act : GaugeAlgebra →ₗ[ℝ] V →ₗ[ℂ] V}
variable [FiniteDimensional ℂ V]

/-- The action of families against the dual representation coefficients: the
  antidiagonal convolution mixing the adjoint transport on the field slot with the
  representation transport on the matter slot — the family-level form of
  `IsInfinitesimalActionOf.repCoeff_act`, and the analogue of
  `bracketFam_adjointDualCoeff`. -/
lemma IsInfinitesimalActionOf.actionFam_repDualCoeff
    (h : IsInfinitesimalActionOf act rep) (U : JetGaugeGroupI)
    (x : Multiset (Fin 1 ⊕ Fin 3)) (f : Module.Dual ℝ GaugeAlgebra →ₗ[ℝ] B)
    (g : Module.Dual ℂ V →ₗ[ℂ] B) (φ : Module.Dual ℂ V) :
    actionFam act f g (repDualCoeff rep U x φ) =
      (x.antidiagonal.map fun p =>
        actionFam act (f ∘ₗ adjointDualCoeff U p.1)
          (g ∘ₗ repDualCoeff rep U p.2) φ).sum := by
  have hT : ∀ (c : GaugeAlgebra) (v : V), repCoeff rep U x (act c v) =
      (x.antidiagonal.map fun p =>
        act (adjointCoeff U p.1 c) (repCoeff rep U p.2 v)).sum := by
    intro c v
    have h1 := LinearMap.congr_fun (h.repCoeff_act U x c) v
    simpa [Multiset.sum_linearMap_apply, Multiset.map_map, LinearMap.coe_comp,
      Function.comp_apply] using h1
  rw [show repDualCoeff rep U x = (repCoeff rep U x).dualMap from rfl,
    show actionFam act f g ((repCoeff rep U x).dualMap φ) =
      dualPairEquivC ((TensorProduct.map LinearMap.id (repCoeff rep U x))
        (tensorAction act (dualPairEquiv.symm f) (dualPairEquivC.symm g))) φ from
      (dualPairEquivC_map_right (repCoeff rep U x) _ φ).symm,
    ← tensorAction_map_right_antidiagonal act (adjointCoeff U) (repCoeff rep U) x hT,
    map_multiset_sum, Multiset.map_map, Multiset.sum_linearMap_apply, Multiset.map_map]
  refine congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => ?_)
  simp only [Function.comp_apply]
  rw [← symm_comp_right, ← symm_comp_right_C]
  rfl

omit [FiniteDimensional ℂ V] in
/-- If `F` transforms in `rep`, so do its `κ ::ₘ s`-derived symbols, with the extra
  derivative traced through `IsInfinitesimalActionOf.repDualCoeff_cons`: the Leibniz
  splittings where `κ` stays a derivative, minus the convolution where `κ` hits the
  representation — `act` of the derived Maurer–Cartan form. -/
lemma _root_.StandardModel.TransformsIn.repGauge_cons
    {F : Multiset (Fin 1 ⊕ Fin 3) → Module.Dual ℂ V →ₗ[ℂ] B}
    (hF : TransformsIn repGauge rep F)
    (hact : IsInfinitesimalActionOf act rep)
    (U : JetGaugeGroupI) (κ : Fin 1 ⊕ Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ V) :
    repGauge U (F (κ ::ₘ s) φ) =
      (s.antidiagonal.map fun p =>
        F (κ ::ₘ p.2) (repDualCoeff rep U⁻¹ p.1 φ)).sum
      - (s.antidiagonal.map fun p =>
          (p.1.antidiagonal.map fun q =>
            F p.2 (repDualCoeff rep U⁻¹ q.2
              (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv q.1
                (maurerCartanForm U⁻¹ κ)))))).sum).sum := by
  rw [hF U φ (κ ::ₘ s)]
  simp only [Multiset.antidiagonal_cons, Multiset.map_add, Multiset.sum_add,
    Multiset.map_map, Function.comp_apply, Prod.map_fst, Prod.map_snd, id_eq]
  have hsec : (Multiset.map (fun p =>
        F p.2 (repDualCoeff rep U⁻¹ (κ ::ₘ p.1) φ)) s.antidiagonal).sum =
      -(s.antidiagonal.map fun p =>
          (p.1.antidiagonal.map fun q =>
            F p.2 (repDualCoeff rep U⁻¹ q.2
              (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv q.1
                (maurerCartanForm U⁻¹ κ)))))).sum).sum := by
    rw [← Multiset.sum_map_neg'']
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => ?_)
    rw [hact.repDualCoeff_cons U⁻¹ κ p.1 φ, map_neg, map_multiset_sum, Multiset.map_map]
    exact congrArg Neg.neg (congrArg Multiset.sum (Multiset.map_congr rfl fun q hq => rfl))
  rw [hsec, sub_eq_add_neg]

set_option maxHeartbeats 2000000 in
/-- The all-orders gauge transformation of the derived action `A_ρ · F` for `F`
  transforming in `rep`: since `F` transforms homogeneously, only one cross-term
  convolution through `act` survives — the analogue of
  `TransformsInAdjoint.repGauge_bracketFamConv` with a matter field in the second
  slot. -/
lemma _root_.StandardModel.TransformsIn.repGauge_actionFamConv
    (hA : IsGaugeField repLorentz repGauge A)
    {F : Multiset (Fin 1 ⊕ Fin 3) → Module.Dual ℂ V →ₗ[ℂ] B}
    (hF : TransformsIn repGauge rep F)
    (hact : IsInfinitesimalActionOf act rep)
    (U : JetGaugeGroupI) (s : Multiset (Fin 1 ⊕ Fin 3)) (ρ : Fin 1 ⊕ Fin 3)
    (φ : Module.Dual ℂ V) :
    repGauge U (actionFamConv A act ρ F s φ) =
      (s.antidiagonal.map fun p =>
        actionFamConv A act ρ F p.2 (repDualCoeff rep U⁻¹ p.1 φ)).sum
      + (s.antidiagonal.map fun p =>
          (p.2.antidiagonal.map fun r =>
            F r.2 (repDualCoeff rep U⁻¹ r.1
              (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv p.1
                (maurerCartanForm U⁻¹ ρ)))))).sum).sum := by
  have hAlaw : ∀ (u : Multiset (Fin 1 ⊕ Fin 3)) (ψ : Module.Dual ℝ GaugeAlgebra),
      repGauge U (A u ρ ψ) =
        ((u.antidiagonal.map fun q => A q.2 ρ ∘ₗ adjointDualCoeff U⁻¹ q.1).sum) ψ
        + algebraMap ℂ B (ψ (JetGaugeAlgebra.eval
            (JetGaugeAlgebra.iteratedDeriv u (maurerCartanForm U⁻¹ ρ)))) := by
    intro u ψ
    rw [hA.gauge_apply_deriv U u ρ ψ, Multiset.sum_linearMap_apply, Multiset.map_map]
    congr 1
  have hFlaw : ∀ (u : Multiset (Fin 1 ⊕ Fin 3)) (ψ : Module.Dual ℂ V),
      repGauge U (F u ψ) =
        ((u.antidiagonal.map fun r => F r.2 ∘ₗ repDualCoeff rep U⁻¹ r.1).sum) ψ := by
    intro u ψ
    rw [hF U ψ u, Multiset.sum_linearMap_apply, Multiset.map_map]
    congr 1
  have hMa : (s.antidiagonal.map fun p =>
      actionFam act ((p.1.antidiagonal.map fun q =>
          A q.2 ρ ∘ₗ adjointDualCoeff U⁻¹ q.1).sum)
        ((p.2.antidiagonal.map fun r =>
          F r.2 ∘ₗ repDualCoeff rep U⁻¹ r.1).sum) φ).sum =
      (s.antidiagonal.map fun p =>
        (p.1.antidiagonal.map fun q =>
          (p.2.antidiagonal.map fun r =>
            actionFam act (A q.2 ρ ∘ₗ adjointDualCoeff U⁻¹ q.1)
              (F r.2 ∘ₗ repDualCoeff rep U⁻¹ r.1) φ).sum).sum).sum := by
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => ?_)
    rw [actionFam_sum_left, Multiset.sum_linearMap_apply, Multiset.map_map,
      Multiset.map_map]
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun q hq => ?_)
    simp only [Function.comp_apply]
    rw [actionFam_sum_right, Multiset.sum_linearMap_apply, Multiset.map_map,
      Multiset.map_map]
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun r hr => ?_)
    simp only [Function.comp_apply]
  have hMc : (s.antidiagonal.map fun p =>
      actionFamConv A act ρ F p.2 (repDualCoeff rep U⁻¹ p.1 φ)).sum =
      (s.antidiagonal.map fun p =>
        (p.1.antidiagonal.map fun q =>
          (p.2.antidiagonal.map fun r =>
            actionFam act (A r.1 ρ ∘ₗ adjointDualCoeff U⁻¹ q.1)
              (F r.2 ∘ₗ repDualCoeff rep U⁻¹ q.2) φ).sum).sum).sum := by
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => ?_)
    rw [actionFamConv, Multiset.sum_linearMap_apply, Multiset.map_map,
      Multiset.map_congr rfl (fun r hr => by
        rw [Function.comp_apply,
          hact.actionFam_repDualCoeff U⁻¹ p.1 (A r.1 ρ) (F r.2) φ]),
      Multiset.sum_map_sum_map]
  have hM := hMa.trans ((Multiset.sum_antidiagonal_exchange s fun a b c d =>
      actionFam act (A b ρ ∘ₗ adjointDualCoeff U⁻¹ a)
        (F d ∘ₗ repDualCoeff rep U⁻¹ c) φ).trans hMc.symm)
  have hCg : ∀ p : Multiset (Fin 1 ⊕ Fin 3) × Multiset (Fin 1 ⊕ Fin 3),
      ((p.2.antidiagonal.map fun r => F r.2 ∘ₗ repDualCoeff rep U⁻¹ r.1).sum)
        (φ ∘ₗ act (JetGaugeAlgebra.eval
          (JetGaugeAlgebra.iteratedDeriv p.1 (maurerCartanForm U⁻¹ ρ)))) =
      (p.2.antidiagonal.map fun r =>
        F r.2 (repDualCoeff rep U⁻¹ r.1
          (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv p.1
            (maurerCartanForm U⁻¹ ρ)))))).sum := by
    intro p
    rw [Multiset.sum_linearMap_apply, Multiset.map_map]
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun r hr => ?_)
    simp only [Function.comp_apply, LinearMap.coe_comp]
  rw [actionFamConv, Multiset.sum_linearMap_apply, Multiset.map_map, map_multiset_sum,
    Multiset.map_map,
    Multiset.map_congr rfl (fun p hp => by
      rw [Function.comp_apply, Function.comp_apply,
        repGauge_actionFam hA U (hAlaw p.1) (hFlaw p.2) φ, hCg p]),
    Multiset.sum_map_add, hM]

set_option maxHeartbeats 2000000 in
/-- **The covariant derivative preserves `TransformsIn`**: if `F` transforms in the
  representation `rep` and `act` is the infinitesimal action underlying `rep`, then
  `∇_ρ F = [∂_ρ F] + A_ρ · F` transforms in `rep`. The single inhomogeneous
  convolution of `[∂_{ρ ::ₘ s} F]` cancels the single `act` cross-term convolution of
  `A_ρ · F` through the coassociativity of the antidiagonal — the matter-field
  analogue of `TransformsInAdjoint.covDerivAdjoint`. -/
theorem _root_.StandardModel.TransformsIn.covDerivAction
    (hA : IsGaugeField repLorentz repGauge A)
    {F : Multiset (Fin 1 ⊕ Fin 3) → Module.Dual ℂ V →ₗ[ℂ] B}
    (hF : TransformsIn repGauge rep F)
    (hact : IsInfinitesimalActionOf act rep) (ρ : Fin 1 ⊕ Fin 3) :
    TransformsIn repGauge rep (IsGaugeField.covDerivAction A act F ρ) := by
  intro U φ s
  have hL : repGauge U (IsGaugeField.covDerivAction A act F ρ s φ) =
      repGauge U (F (ρ ::ₘ s) φ) + repGauge U (actionFamConv A act ρ F s φ) := by
    rw [covDerivAction_apply, map_add]
  have hR : (s.antidiagonal.map fun p =>
      IsGaugeField.covDerivAction A act F ρ p.2 (repDualCoeff rep U⁻¹ p.1 φ)).sum =
      (s.antidiagonal.map fun p =>
        F (ρ ::ₘ p.2) (repDualCoeff rep U⁻¹ p.1 φ)).sum
      + (s.antidiagonal.map fun p =>
        actionFamConv A act ρ F p.2 (repDualCoeff rep U⁻¹ p.1 φ)).sum := by
    rw [← Multiset.sum_map_add]
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => ?_)
    rw [covDerivAction_apply]
  have hcancel : (s.antidiagonal.map fun p =>
      (p.1.antidiagonal.map fun q =>
        F p.2 (repDualCoeff rep U⁻¹ q.2
          (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv q.1
            (maurerCartanForm U⁻¹ ρ)))))).sum).sum =
    (s.antidiagonal.map fun p =>
      (p.2.antidiagonal.map fun r =>
        F r.2 (repDualCoeff rep U⁻¹ r.1
          (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv p.1
            (maurerCartanForm U⁻¹ ρ)))))).sum).sum :=
    Multiset.sum_antidiagonal_assoc s (fun a b c =>
      F c (repDualCoeff rep U⁻¹ b
        (φ ∘ₗ act (JetGaugeAlgebra.eval (JetGaugeAlgebra.iteratedDeriv a
          (maurerCartanForm U⁻¹ ρ))))))
  rw [hL, hF.repGauge_cons hact U ρ s φ, hF.repGauge_actionFamConv hA hact U s ρ φ,
    hR, hcancel]
  abel

/-- **Every iterated covariant derivative preserves `TransformsIn`**: if `F` transforms
  in `rep` and `act` is the infinitesimal action underlying `rep`, then
  `∇_{l 0} ⋯ ∇_{l (n-1)} F` transforms in `rep` — the recursion of
  `TransformsIn.covDerivAction` over the tuple of directions. -/
theorem _root_.StandardModel.TransformsIn.covDerivIter
    (hA : IsGaugeField repLorentz repGauge A)
    {F : Multiset (Fin 1 ⊕ Fin 3) → Module.Dual ℂ V →ₗ[ℂ] B}
    (hF : TransformsIn repGauge rep F)
    (hact : IsInfinitesimalActionOf act rep)
    (n : ℕ) (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    TransformsIn repGauge rep (IsGaugeField.covDerivIter A act F n l) := by
  induction n with
  | zero => exact hF
  | succ n ih =>
      exact TransformsIn.covDerivAction hA (ih fun i => l i.succ) hact (l 0)

omit [FiniteDimensional ℂ V] in
/-- **Matter gauge tensors whose zeroth representation coefficient is trivial on pure
  jets are fixed by pure jets**: for a family transforming in `rep`, a gauge jet with
  trivial base-point value acts trivially on the underived symbol, provided the
  representation's zeroth Taylor coefficient is the identity on such jets. -/
lemma _root_.StandardModel.TransformsIn.repGauge_eq_of_mem_truncationKer_zero
    {F : Multiset (Fin 1 ⊕ Fin 3) → Module.Dual ℂ V →ₗ[ℂ] B}
    (hF : TransformsIn repGauge rep F)
    (hrep : ∀ {W : JetGaugeGroupI}, W.eval = 1 → repCoeff rep W 0 = LinearMap.id)
    (U : JetGaugeGroupI.truncationKer 0) (φ : Module.Dual ℂ V) :
    repGauge U.1 (F 0 φ) = F 0 φ := by
  have hinv : ((U.1)⁻¹).eval = 1 := by
    rw [map_inv, JetGaugeGroupI.mem_truncationKer_zero_iff.mp U.2, inv_one]
  have h1 := hF U.1 φ 0
  simp only [Multiset.antidiagonal_zero, Multiset.map_singleton,
    Multiset.sum_singleton] at h1
  rw [h1, show repDualCoeff rep (U.1)⁻¹ 0 = (repCoeff rep (U.1)⁻¹ 0).dualMap from rfl,
    hrep hinv]
  rfl

end MatterCovariance

/-!

## C. The conjugate action and the conjugate representation

-/

section ConjugateAction

/-- **The conjugate of an infinitesimal action**: the same maps, read on the conjugate
  module — the generators of the conjugate representation. -/
noncomputable def actionConj (act : GaugeAlgebra →ₗ[ℝ] V →ₗ[ℂ] V) :
    GaugeAlgebra →ₗ[ℝ] ConjModule V →ₗ[ℂ] ConjModule V where
  toFun c := ConjModule.endConj (act c)
  map_add' c₁ c₂ := by rw [map_add, ConjModule.endConj_add]
  map_smul' r c := by rw [map_smul, ConjModule.endConj_real_smul, RingHom.id_apply]

@[simp]
lemma actionConj_apply (act : GaugeAlgebra →ₗ[ℝ] V →ₗ[ℂ] V) (c : GaugeAlgebra) :
    actionConj act c = ConjModule.endConj (act c) := rfl

/-- The identification of the jets of a conjugate field with the conjugates of the
  jets: conjugation is monoidal, and the star of the jet-ring factor absorbs the
  twist — `conj (g ⊗ u) ↦ star g ⊗ conj u`. This is the equivalence along which
  `repConj` carries the conjugated representation. -/
noncomputable def conjJetEquiv :
    ConjModule (JetRing ⊗[ℂ] V) ≃ₗ[ℂ] JetRing ⊗[ℂ] ConjModule V :=
  (ConjModule.tensorEquiv (k := ℂ) (M := JetRing) (N := V)).symm.trans
    (TensorProduct.congr JetRing.starConjEquiv (LinearEquiv.refl ℂ (ConjModule V)))

lemma conjJetEquiv_conjEquiv_tmul (g : JetRing) (u : V) :
    conjJetEquiv (conjEquiv (k := ℂ) (M := JetRing ⊗[ℂ] V) (g ⊗ₜ[ℂ] u))
      = star g ⊗ₜ[ℂ] conjEquiv (k := ℂ) (M := V) u := by
  rw [conjJetEquiv, LinearEquiv.trans_apply, ConjModule.tensorEquiv_symm_conjEquiv_tmul,
    TensorProduct.congr_tmul, JetRing.starConjEquiv_apply, LinearEquiv.refl_apply,
    LinearEquiv.symm_apply_apply]

section ConjRep

variable {rep : Representation ℂ JetGaugeGroupI (JetRing ⊗[ℂ] V)}
variable {act : GaugeAlgebra →ₗ[ℝ] V →ₗ[ℂ] V}

/-- The conjugate representation acts through `conjJetEquiv` by the original maps. -/
lemma repConj_conjJetEquiv (rep : Representation ℂ JetGaugeGroupI (JetRing ⊗[ℂ] V))
    (U : JetGaugeGroupI) (w : JetRing ⊗[ℂ] V) :
    repConj rep U (conjJetEquiv (conjEquiv (k := ℂ) (M := JetRing ⊗[ℂ] V) w))
      = conjJetEquiv (conjEquiv (k := ℂ) (M := JetRing ⊗[ℂ] V) (rep U w)) := by
  show conjJetEquiv ((rep.conj U) (conjJetEquiv.symm
      (conjJetEquiv (conjEquiv (k := ℂ) (M := JetRing ⊗[ℂ] V) w)))) = _
  rw [LinearEquiv.symm_apply_apply, Representation.conj_apply,
    LinearEquiv.symm_apply_apply]

/-- **The base-point Taylor coefficients of the conjugate representation are the
  conjugated coefficients**: the derivative directions are real, so conjugation passes
  through `∂_x` and the base-point evaluation untouched. -/
lemma repCoeff_repConj (rep : Representation ℂ JetGaugeGroupI (JetRing ⊗[ℂ] V))
    (U : JetGaugeGroupI) (x : Multiset (Fin 1 ⊕ Fin 3)) :
    repCoeff (repConj rep) U x = ConjModule.endConj (repCoeff rep U x) := by
  have hE_tmul := conjJetEquiv_conjEquiv_tmul (V := V)
  -- conjugation intertwines the formal derivative
  have hderiv1 : ∀ (μ : Fin 1 ⊕ Fin 3) (w : JetRing ⊗[ℂ] V),
      jetDeriv μ (conjJetEquiv (conjEquiv (k := ℂ) (M := JetRing ⊗[ℂ] V) w))
        = conjJetEquiv (conjEquiv (k := ℂ) (M := JetRing ⊗[ℂ] V) (jetDeriv μ w)) := by
    intro μ w
    induction w using TensorProduct.induction_on with
    | zero => simp
    | tmul g u =>
        rw [hE_tmul, jetDeriv_tmul, jetDeriv_tmul, hE_tmul, JetRing.pderiv_star]
    | add a b ha hb =>
        rw [map_add, map_add, map_add, ha, hb, map_add, map_add, map_add]
  have hderiv : ∀ (s : Multiset (Fin 1 ⊕ Fin 3)) (w : JetRing ⊗[ℂ] V),
      jetIteratedDeriv s (conjJetEquiv (conjEquiv (k := ℂ) (M := JetRing ⊗[ℂ] V) w))
        = conjJetEquiv (conjEquiv (k := ℂ) (M := JetRing ⊗[ℂ] V)
            (jetIteratedDeriv s w)) := by
    intro s
    induction s using Multiset.induction_on with
    | empty => intro w; rw [jetIteratedDeriv_zero]; rfl
    | cons μ t ih =>
        intro w
        rw [jetIteratedDeriv_cons, LinearMap.comp_apply, ih, hderiv1,
          jetIteratedDeriv_cons, LinearMap.comp_apply]
  -- conjugation intertwines the base-point evaluation
  have heval : ∀ w : JetRing ⊗[ℂ] V,
      jetEval (conjJetEquiv (conjEquiv (k := ℂ) (M := JetRing ⊗[ℂ] V) w))
        = conjEquiv (k := ℂ) (M := V) (jetEval w) := by
    intro w
    induction w using TensorProduct.induction_on with
    | zero => simp
    | tmul g u =>
        rw [hE_tmul, jetEval_tmul, jetEval_tmul, JetRing.constantCoeff_star,
          map_smulₛₗ, starRingEnd_apply]
    | add a b ha hb => rw [map_add, map_add, map_add, ha, hb, map_add, map_add]
  refine LinearMap.ext fun v => ?_
  have hv : jetOfConstant v = conjJetEquiv (conjEquiv (k := ℂ) (M := JetRing ⊗[ℂ] V)
      (jetOfConstant ((conjEquiv (k := ℂ) (M := V)).symm v))) := by
    rw [jetOfConstant_apply, jetOfConstant_apply, hE_tmul, star_one,
      LinearEquiv.apply_symm_apply]
  show jetEval (jetIteratedDeriv x (repConj rep U (jetOfConstant v))) = _
  rw [hv, repConj_conjJetEquiv, hderiv, heval]
  rfl

/-- The base-point triviality of the zeroth Taylor coefficient passes to the
  conjugate representation. -/
lemma repCoeff_repConj_zero_eq_id {W : JetGaugeGroupI}
    (hrep : repCoeff rep W 0 = LinearMap.id) :
    repCoeff (repConj rep) W 0 = LinearMap.id := by
  rw [repCoeff_repConj, hrep, ConjModule.endConj_id]

/-- **The conjugate of an infinitesimal action underlies the conjugate
  representation**: conjugating the Taylor coefficients preserves both the
  Maurer–Cartan Leibniz law and the adjoint intertwining, since the gauge-algebra
  inputs are real. -/
theorem IsInfinitesimalActionOf.conj (h : IsInfinitesimalActionOf act rep) :
    IsInfinitesimalActionOf (actionConj act) (repConj rep) := by
  constructor
  · intro U μ x
    rw [repCoeff_repConj, h.repCoeff_cons U μ x, ConjModule.endConj_neg,
      ConjModule.endConj_multiset_sum, Multiset.map_map]
    refine congrArg Neg.neg (congrArg Multiset.sum
      (Multiset.map_congr rfl fun p hp => ?_))
    rw [Function.comp_apply, ConjModule.endConj_comp, repCoeff_repConj]
    rfl
  · intro U x c
    rw [repCoeff_repConj, show actionConj act c = ConjModule.endConj (act c) from rfl,
      ← ConjModule.endConj_comp, h.repCoeff_act U x c,
      ConjModule.endConj_multiset_sum, Multiset.map_map]
    refine congrArg Multiset.sum (Multiset.map_congr rfl fun p hp => ?_)
    rw [Function.comp_apply, ConjModule.endConj_comp, repCoeff_repConj]
    rfl

end ConjRep

end ConjugateAction

end GaugeAlgebra

end StandardModel
