/-
Copyright (c) 2026 Nathaneal Sajan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathaneal Sajan
-/
module

public import Physlib.ClassicalFieldTheory.GaugeTheory.LocalFieldAlgebra.TransformsIn
public import Physlib.Mathematics.AlgebraRepresentation
/-!
# The ordinary sector algebras of the local field algebra

## i. Overview

A sector is a finite set of `GaugeFieldData.FieldCategory`, chosen among `fermion`, `gauge`
and `scalar`. It selects ordinary generator families of the local field algebra `J(T)` of a
field datum: the derivative symbols `∂_s ψ` of every fermionic species and their conjugates
for `fermion`, those of every bosonic species and their conjugates for `scalar`, and the
connection symbols `∂_s A_μ` for `gauge`. The ordinary sector algebra `T.SectorAlgebra S`
is the complex unital subalgebra of `J(T)` generated by the selected families.

The category `scalar` names the bosonic species `T.BosonSpecies` of the datum; a bosonic
`MatterField` need not be a Lorentz scalar, and the selection does not assert that it is.
A sector selects generator families only: no multiplicity of fields, mass dimension, gauge
invariance or Lagrangian term is encoded.

## ii. Key results

- `GaugeFieldData.FieldCategory` : the three categories of fields.
- `GaugeFieldData.SectorAlgebra` : the ordinary sector algebra of a sector, with
  `SectorAlgebra.induction` and `SectorAlgebra.algHom_ext`.
- `SectorAlgebra.mono`, `SectorAlgebra.empty`, `SectorAlgebra.univ`,
  `SectorAlgebra.union` : the lattice laws of the selection.
- `SectorAlgebra.repJet`, `SectorAlgebra.repLorentzGroup` : the restricted actions.

## iii. Table of contents

- A. Field categories and their ordinary generators
- B. The ordinary sector algebra
  - B.1. Membership of the selected families
  - B.2. Generation
  - B.3. The lattice laws of the selection
- C. Stability under the actions
- D. The restricted actions

-/

@[expose] public section

open TensorProduct Matrix MatrixGroups

namespace GaugeFieldData

/-!

## A. Field categories and their ordinary generators

-/

/-- The categories of fields a sector may select. -/
inductive FieldCategory where
  /-- The fermionic species. -/
  | fermion : FieldCategory
  /-- The gauge bosons. -/
  | gauge : FieldCategory
  /-- The bosonic species. -/
  | scalar : FieldCategory
deriving DecidableEq

/-- The three categories exhaust `FieldCategory`. -/
instance : Fintype FieldCategory where
  elems := {FieldCategory.fermion, FieldCategory.gauge, FieldCategory.scalar}
  complete := fun c => by cases c <;> decide

variable {G₀ : Type} [Group G₀] {𝔤 : Type} [LieRing 𝔤] [LieAlgebra ℝ 𝔤] [Module.Finite ℝ 𝔤]
  {GJ : Type} [Group GJ] {𝔤J : Type} [LieRing 𝔤J] [LieAlgebra ℝ 𝔤J]
  {jets : LocalGaugeData G₀ 𝔤 GJ 𝔤J} (T : GaugeFieldData jets)

/-- The ordinary generators of one field category. -/
def categoryGenerators : FieldCategory → Set T.LocalFieldAlgebra
  | .fermion => Set.range T.ιFermionTotal
  | .gauge => Set.range T.ιConnection
  | .scalar => Set.range T.ιBosonTotal

/-- The ordinary generators selected by a sector. -/
def sectorGenerators (S : Finset FieldCategory) : Set T.LocalFieldAlgebra :=
  ⋃ c ∈ S, T.categoryGenerators c

lemma sectorGenerators_mono {S S' : Finset FieldCategory} (h : S ⊆ S') :
    T.sectorGenerators S ⊆ T.sectorGenerators S' :=
  Set.iUnion₂_subset fun _ hc => Finset.subset_set_biUnion_of_mem (h hc)

@[simp]
lemma sectorGenerators_empty : T.sectorGenerators ∅ = ∅ := by
  simp [sectorGenerators]

lemma sectorGenerators_union (S S' : Finset FieldCategory) :
    T.sectorGenerators (S ∪ S') = T.sectorGenerators S ∪ T.sectorGenerators S' :=
  Finset.set_biUnion_union S S' _

/-- The full sector selects the generators of the local field algebra. -/
lemma sectorGenerators_univ : T.sectorGenerators Finset.univ = T.generators := by
  ext x
  simp only [sectorGenerators, Finset.mem_univ, Set.iUnion_true, Set.mem_iUnion]
  constructor
  · rintro ⟨c, hc⟩
    cases c
    · exact Or.inl (Or.inl hc)
    · exact Or.inr hc
    · exact Or.inl (Or.inr hc)
  · rintro ((h | h) | h)
    exacts [⟨.fermion, h⟩, ⟨.scalar, h⟩, ⟨.gauge, h⟩]

/-!

## B. The ordinary sector algebra

-/

/-- The ordinary sector algebra of a sector `S`: the subalgebra of the local field algebra
  generated by the ordinary generators of the selected categories. -/
noncomputable def SectorAlgebra (S : Finset FieldCategory) : Subalgebra ℂ T.LocalFieldAlgebra :=
  Algebra.adjoin ℂ (T.sectorGenerators S)

namespace SectorAlgebra

variable {T} {S : Finset FieldCategory}

/-!

### B.1. Membership of the selected families

-/

lemma ιFermionTotal_mem (hS : FieldCategory.fermion ∈ S) (v : T.FermionGenerators) :
    T.ιFermionTotal v ∈ T.SectorAlgebra S :=
  Algebra.subset_adjoin
    (Finset.subset_set_biUnion_of_mem (f := T.categoryGenerators) hS ⟨v, rfl⟩)

lemma ιFermion_mem (hS : FieldCategory.fermion ∈ S) (i : T.FermionSpecies)
    (x : JetComponentSpace (T.fermion i)) : T.ιFermion i x ∈ T.SectorAlgebra S :=
  ιFermionTotal_mem hS _

lemma fermionSymbol_mem (hS : FieldCategory.fermion ∈ S) (i : T.FermionSpecies)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (T.FermionValue i)) :
    T.fermionSymbol i s φ ∈ T.SectorAlgebra S :=
  ιFermion_mem hS i _

lemma conjFermionSymbol_mem (hS : FieldCategory.fermion ∈ S) (i : T.FermionSpecies)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule (T.FermionValue i))) :
    T.conjFermionSymbol i s φ ∈ T.SectorAlgebra S :=
  ιFermion_mem hS i _

lemma ιBosonTotal_mem (hS : FieldCategory.scalar ∈ S) (v : T.BosonGenerators) :
    T.ιBosonTotal v ∈ T.SectorAlgebra S :=
  Algebra.subset_adjoin
    (Finset.subset_set_biUnion_of_mem (f := T.categoryGenerators) hS ⟨v, rfl⟩)

lemma ιBoson_mem (hS : FieldCategory.scalar ∈ S) (j : T.BosonSpecies)
    (y : JetComponentSpace (T.boson j)) : T.ιBoson j y ∈ T.SectorAlgebra S :=
  ιBosonTotal_mem hS _

lemma bosonSymbol_mem (hS : FieldCategory.scalar ∈ S) (j : T.BosonSpecies)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (T.BosonValue j)) :
    T.bosonSymbol j s φ ∈ T.SectorAlgebra S :=
  ιBoson_mem hS j _

lemma conjBosonSymbol_mem (hS : FieldCategory.scalar ∈ S) (j : T.BosonSpecies)
    (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule (T.BosonValue j))) :
    T.conjBosonSymbol j s φ ∈ T.SectorAlgebra S :=
  ιBoson_mem hS j _

lemma ιConnection_mem (hS : FieldCategory.gauge ∈ S) (v : GaugeBoson.JetComponentSpace 𝔤) :
    T.ιConnection v ∈ T.SectorAlgebra S :=
  Algebra.subset_adjoin
    (Finset.subset_set_biUnion_of_mem (f := T.categoryGenerators) hS ⟨v, rfl⟩)

/-!

### B.2. Generation

-/

/-- Case analysis on the generators of a sector. -/
lemma sectorGenerators_cases {P : T.LocalFieldAlgebra → Prop} {b : T.LocalFieldAlgebra}
    (hb : b ∈ T.sectorGenerators S)
    (hf : FieldCategory.fermion ∈ S → ∀ v, P (T.ιFermionTotal v))
    (hs : FieldCategory.scalar ∈ S → ∀ v, P (T.ιBosonTotal v))
    (hg : FieldCategory.gauge ∈ S → ∀ v, P (T.ιConnection v)) : P b := by
  simp only [sectorGenerators, Set.mem_iUnion, exists_prop] at hb
  obtain ⟨c, hc, hbc⟩ := hb
  cases c with
  | fermion => obtain ⟨v, rfl⟩ := hbc; exact hf hc v
  | gauge => obtain ⟨v, rfl⟩ := hbc; exact hg hc v
  | scalar => obtain ⟨v, rfl⟩ := hbc; exact hs hc v

/-- A property holding on the selected generators and the scalars and closed under sums
  and products holds on the sector algebra. -/
lemma induction {P : T.LocalFieldAlgebra → Prop} {x : T.LocalFieldAlgebra}
    (hx : x ∈ T.SectorAlgebra S)
    (hf : FieldCategory.fermion ∈ S → ∀ v, P (T.ιFermionTotal v))
    (hs : FieldCategory.scalar ∈ S → ∀ v, P (T.ιBosonTotal v))
    (hg : FieldCategory.gauge ∈ S → ∀ v, P (T.ιConnection v))
    (halg : ∀ z : ℂ, P (z • (1 : T.LocalFieldAlgebra)))
    (hadd : ∀ x y, P x → P y → P (x + y))
    (hmul : ∀ x y, P x → P y → P (x * y)) : P x := by
  induction hx using Algebra.adjoin_induction with
  | mem b hb => exact sectorGenerators_cases hb hf hs hg
  | algebraMap z =>
    rw [Algebra.algebraMap_eq_smul_one]
    exact halg z
  | add a b _ _ ha hb => exact hadd a b ha hb
  | mul a b _ _ ha hb => exact hmul a b ha hb

/-- Two algebra maps out of a sector algebra agreeing on the selected generators are
  equal. This is uniqueness only: a sector algebra is not free on its generators. -/
lemma algHom_ext {B : Type} [Semiring B] [Algebra ℂ B]
    {f g : ↥(T.SectorAlgebra S) →ₐ[ℂ] B}
    (hf : ∀ (hS : FieldCategory.fermion ∈ S) (v : T.FermionGenerators),
      f ⟨T.ιFermionTotal v, ιFermionTotal_mem hS v⟩ = g ⟨T.ιFermionTotal v, ιFermionTotal_mem hS v⟩)
    (hs : ∀ (hS : FieldCategory.scalar ∈ S) (v : T.BosonGenerators),
      f ⟨T.ιBosonTotal v, ιBosonTotal_mem hS v⟩ = g ⟨T.ιBosonTotal v, ιBosonTotal_mem hS v⟩)
    (hg : ∀ (hS : FieldCategory.gauge ∈ S) (v : GaugeBoson.JetComponentSpace 𝔤),
      f ⟨T.ιConnection v, ιConnection_mem hS v⟩ = g ⟨T.ιConnection v, ιConnection_mem hS v⟩) :
    f = g := by
  refine AlgHom.ext_of_eq_adjoin rfl fun b hb => ?_
  refine sectorGenerators_cases (P := fun b => ∀ hb' : b ∈ T.SectorAlgebra S,
    f ⟨b, hb'⟩ = g ⟨b, hb'⟩) hb ?_ ?_ ?_ (Algebra.subset_adjoin hb)
  · intro hS v _
    exact hf hS v
  · intro hS v _
    exact hs hS v
  · intro hS v _
    exact hg hS v

/-!

### B.3. The lattice laws of the selection

-/

variable (T)

lemma mono {S S' : Finset FieldCategory} (h : S ⊆ S') :
    T.SectorAlgebra S ≤ T.SectorAlgebra S' :=
  Algebra.adjoin_mono (sectorGenerators_mono T h)

/-- The empty sector algebra is the image of the scalars. -/
@[simp]
lemma empty : T.SectorAlgebra ∅ = ⊥ := by
  unfold SectorAlgebra
  rw [sectorGenerators_empty, Algebra.adjoin_empty]

@[simp]
lemma univ : T.SectorAlgebra Finset.univ = ⊤ := by
  unfold SectorAlgebra
  rw [sectorGenerators_univ, adjoin_generators_eq_top]

lemma union (S S' : Finset FieldCategory) :
    T.SectorAlgebra (S ∪ S') = T.SectorAlgebra S ⊔ T.SectorAlgebra S' := by
  unfold SectorAlgebra
  rw [sectorGenerators_union, Algebra.adjoin_union]

TODO (lines := 259-262) (date := 2026-09-22) "Add an `Add` instance on `GaugeFieldData`
  and the companion of this lemma, here and for `CovSectorAlgebra`, for a sum of data: a
  sector of `F + G` as the parts from `F`, from `G` and the words mixing the two, so that
  `invariantsLE` of an extension reduces to the mixed part."

variable {T}

/-!

## C. Stability under the actions

Each generator law of `J(T)` stays inside the family of the generator it acts on, the
connection law up to a scalar shift, so both actions preserve every sector algebra.

-/

lemma repJet_mem (U : GJ) {x : T.LocalFieldAlgebra} (hx : x ∈ T.SectorAlgebra S) :
    T.repJet U x ∈ T.SectorAlgebra S := by
  refine Algebra.apply_mem_of_mem_adjoin (T.repJetAlgHom U) (fun b hb => ?_) hx
  refine sectorGenerators_cases (P := fun b => T.repJetAlgHom U b ∈ T.SectorAlgebra S) hb
    (fun hS v => ?_) (fun hS v => ?_) (fun hS v => ?_)
  · refine DirectSum.mem_of_lof (F := (T.repJetAlgHom U).toLinearMap ∘ₗ T.ιFermionTotal)
      (fun i x => ?_) v
    show T.repJet U (T.ιFermion i x) ∈ _
    rw [repJet_ιFermion]
    exact ιFermion_mem hS i _
  · refine DirectSum.mem_of_lof (F := (T.repJetAlgHom U).toLinearMap ∘ₗ T.ιBosonTotal)
      (fun j y => ?_) v
    show T.repJet U (T.ιBoson j y) ∈ _
    rw [repJet_ιBoson]
    exact ιBoson_mem hS j _
  · rw [← repJet_apply, repJet_ιConnection_affine]
    exact add_mem (ιConnection_mem hS _) (Subalgebra.smul_mem _ (one_mem _) _)

lemma repLorentzGroup_mem (Λ : SL(2,ℂ)) {x : T.LocalFieldAlgebra} (hx : x ∈ T.SectorAlgebra S) :
    T.repLorentzGroup Λ x ∈ T.SectorAlgebra S := by
  refine Algebra.apply_mem_of_mem_adjoin (T.repLorentzAlgHom Λ) (fun b hb => ?_) hx
  refine sectorGenerators_cases (P := fun b => T.repLorentzAlgHom Λ b ∈ T.SectorAlgebra S) hb
    (fun hS v => ?_) (fun hS v => ?_) (fun hS v => ?_)
  · refine DirectSum.mem_of_lof (F := (T.repLorentzAlgHom Λ).toLinearMap ∘ₗ T.ιFermionTotal)
      (fun i x => ?_) v
    show T.repLorentzGroup Λ (T.ιFermion i x) ∈ _
    rw [repLorentzGroup_ιFermion]
    exact ιFermion_mem hS i _
  · refine DirectSum.mem_of_lof (F := (T.repLorentzAlgHom Λ).toLinearMap ∘ₗ T.ιBosonTotal)
      (fun j y => ?_) v
    show T.repLorentzGroup Λ (T.ιBoson j y) ∈ _
    rw [repLorentzGroup_ιBoson]
    exact ιBoson_mem hS j _
  · rw [← repLorentzGroup_apply, repLorentzGroup_ιConnection_eq]
    exact ιConnection_mem hS _

/-!

## D. The restricted actions

The restricted actions of two nested sectors agree along `Subalgebra.inclusion`.

-/

variable (T S)

/-- The jet gauge group acting on a sector algebra, by restriction. -/
noncomputable def repJet : Representation ℂ GJ (T.SectorAlgebra S) :=
  T.repJet.restrictSubalgebra (T.SectorAlgebra S) fun U _ hx => repJet_mem U hx

/-- The Lorentz group acting on a sector algebra, by restriction. -/
noncomputable def repLorentzGroup : Representation ℂ SL(2,ℂ) (T.SectorAlgebra S) :=
  T.repLorentzGroup.restrictSubalgebra (T.SectorAlgebra S) fun Λ _ hx => repLorentzGroup_mem Λ hx

variable {T S}

@[simp]
lemma coe_repJet (U : GJ) (x : T.SectorAlgebra S) :
    (repJet T S U x : T.LocalFieldAlgebra) = T.repJet U x := rfl

lemma repJet_apply_mul (U : GJ) (x y : T.SectorAlgebra S) :
    repJet T S U (x * y) = repJet T S U x * repJet T S U y :=
  Subtype.ext (GaugeFieldData.repJet_apply_mul U (x : T.LocalFieldAlgebra) y)

@[simp]
lemma coe_repLorentzGroup (Λ : SL(2,ℂ)) (x : T.SectorAlgebra S) :
    (repLorentzGroup T S Λ x : T.LocalFieldAlgebra) = T.repLorentzGroup Λ x := rfl

lemma repLorentzGroup_apply_mul (Λ : SL(2,ℂ)) (x y : T.SectorAlgebra S) :
    repLorentzGroup T S Λ (x * y) = repLorentzGroup T S Λ x * repLorentzGroup T S Λ y :=
  Subtype.ext (GaugeFieldData.repLorentzGroup_apply_mul Λ (x : T.LocalFieldAlgebra) y)

lemma inclusion_repJet {S' : Finset FieldCategory} (h : S ⊆ S') (U : GJ) (x : T.SectorAlgebra S) :
    Subalgebra.inclusion (mono T h) (repJet T S U x)
      = repJet T S' U (Subalgebra.inclusion (mono T h) x) := by
  -- `rfl` unfolds the ambient action through its universal property and times out.
  unfold repJet
  exact Representation.inclusion_restrictSubalgebra T.repJet (mono T h) _ _ U x

lemma inclusion_repLorentzGroup {S' : Finset FieldCategory} (h : S ⊆ S') (Λ : SL(2,ℂ))
    (x : T.SectorAlgebra S) :
    Subalgebra.inclusion (mono T h) (repLorentzGroup T S Λ x)
      = repLorentzGroup T S' Λ (Subalgebra.inclusion (mono T h) x) := by
  unfold repLorentzGroup
  exact Representation.inclusion_restrictSubalgebra T.repLorentzGroup (mono T h) _ _ Λ x

end SectorAlgebra

end GaugeFieldData
