/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module
public import Physlib.Mathematics.SubalgebraRestriction
public import Physlib.Particles.StandardModel.JetAlgebra.CovJetAlgebra.Basic
/-!
# The covariant jet algebra of the Higgs field

## i. Overview

The Higgs sector of the Standard Model is written in the covariant towers `∇_l H` and
`∇_l H̄` alone. Inside `CovJetAlgebra` those towers generate a subalgebra, and this file
gives it: `CovHiggsJetAlgebra`, the covariant jet algebra of the Higgs field.

Everything the sector needs is inherited. The global gauge action carries a Higgs tower to
a Higgs tower at a rotated value index, the Lorentz action carries one to a slot-mixing sum
of Higgs towers, and the mass-weight polynomial makes each an eigenvector whose eigenvector
is the tower itself. Each of the three therefore preserves the subalgebra, and restricting
them gives it a gauge action, a Lorentz action and a mass-weight grading of its own,
together with the two towers.

`CovHiggsJetAlgebra` is to the Higgs sector what `CovJetAlgebra` is to the Standard Model:
the object every Higgs sector receives its fields from, which is the content of
`HiggsAlgebraCovRealization`.

## ii. Key results

- `StandardModel.CovHiggsJetAlgebra` : the covariant jet algebra of the Higgs field.
- `StandardModel.CovHiggsJetAlgebra.repGaugeGroupI`,
  `StandardModel.CovHiggsJetAlgebra.repLorentzGroup`,
  `StandardModel.CovHiggsJetAlgebra.massWeightPoly` : its gauge action, Lorentz action and
  mass-weight polynomial.
- `StandardModel.CovHiggsJetAlgebra.higgsField`,
  `StandardModel.CovHiggsJetAlgebra.conjHiggsField` : its two covariant towers.

## iii. Table of contents

- A. The Higgs subalgebra of the covariant jet algebra
- B. The subalgebra is closed under the actions
  - B.1. The mass-weight polynomial
- C. The covariant jet algebra of the Higgs field
- D. The laws of the Higgs towers

-/

@[expose] public section

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 1000000
set_option synthInstance.maxSize 2048
set_option maxRecDepth 8000

namespace StandardModel

open TensorProduct Matrix MatrixGroups Lorentz

namespace CovJetAlgebra

/-!

## A. The Higgs subalgebra of the covariant jet algebra

-/

/-- The covariant towers of the Higgs field and of its conjugate, as a subset of the
  covariant jet algebra. -/
noncomputable def higgsGenerators : Set CovJetAlgebra :=
  ⋃ (n : ℕ) (l : Fin n → Fin 1 ⊕ Fin 3),
    Set.range (higgsField l) ∪ Set.range (conjHiggsField l)

/-- The subalgebra of the covariant jet algebra generated by the Higgs towers. -/
noncomputable def higgsSubalgebra : Subalgebra ℂ CovJetAlgebra := Algebra.adjoin ℂ higgsGenerators

/-- The Higgs tower lies in the Higgs subalgebra. -/
lemma higgsField_mem_higgsSubalgebra {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ HiggsVec) : higgsField l φ ∈ higgsSubalgebra :=
  Algebra.subset_adjoin <| Set.mem_iUnion_of_mem n <| Set.mem_iUnion_of_mem l <|
    Or.inl ⟨φ, rfl⟩

/-- The conjugate Higgs tower lies in the Higgs subalgebra. -/
lemma conjHiggsField_mem_higgsSubalgebra {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule HiggsVec)) : conjHiggsField l φ ∈ higgsSubalgebra :=
  Algebra.subset_adjoin <| Set.mem_iUnion_of_mem n <| Set.mem_iUnion_of_mem l <|
    Or.inr ⟨φ, rfl⟩

/-- Membership of the Higgs subalgebra transported along an equation, stated at variable
  endpoints so that the substitution never abstracts a pattern out of a goal mentioning the
  covariant jet algebra. -/
private lemma mem_higgsSubalgebra_of_eq {x y : CovJetAlgebra} (h : x = y)
    (hx : x ∈ higgsSubalgebra) : y ∈ higgsSubalgebra := h ▸ hx

/-- The same, for the polynomials over the Higgs subalgebra. -/
private lemma mem_polyRange_of_eq {p q : Polynomial CovJetAlgebra} (h : p = q)
    (hp : p ∈ higgsSubalgebra.polyRange) : q ∈ higgsSubalgebra.polyRange := h ▸ hp

/-- A property that holds of both Higgs towers holds of every Higgs generator. -/
lemma higgsGenerators_induction {P : CovJetAlgebra → Prop}
    (hH : ∀ {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ HiggsVec),
      P (higgsField l φ))
    (hBarH : ∀ {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
      (φ : Module.Dual ℂ (ConjModule HiggsVec)), P (conjHiggsField l φ)) :
    ∀ x ∈ higgsGenerators, P x := by
  rintro x hx
  rw [higgsGenerators] at hx
  simp only [Set.mem_iUnion] at hx
  obtain ⟨n, l, hx⟩ := hx
  rcases hx with ⟨φ, rfl⟩ | ⟨φ, rfl⟩
  · exact hH l φ
  · exact hBarH l φ

/-!

## B. The subalgebra is closed under the actions

-/

/-- A unital multiplicative endomorphism carrying the Higgs towers into the Higgs
  subalgebra carries the whole subalgebra into itself. -/
lemma mapsTo_higgsSubalgebra {f : CovJetAlgebra →ₗ[ℂ] CovJetAlgebra} (hone : f 1 = 1)
    (hmul : ∀ b₁ b₂ : CovJetAlgebra, f (b₁ * b₂) = f b₁ * f b₂)
    (hgen : ∀ x ∈ higgsGenerators, f x ∈ higgsSubalgebra)
    {x : CovJetAlgebra} (hx : x ∈ higgsSubalgebra) : f x ∈ higgsSubalgebra := by
  induction hx using Algebra.adjoin_induction with
  | mem b hb => exact hgen b hb
  | algebraMap c =>
    exact mem_higgsSubalgebra_of_eq
      ((congrArg f (Algebra.algebraMap_eq_smul_one c)).trans
        ((map_smul f c 1).trans (congrArg (fun z : CovJetAlgebra => c • z) hone))).symm
      (Subalgebra.smul_mem _ (one_mem _) c)
  | add a b _ _ iha ihb =>
    exact mem_higgsSubalgebra_of_eq (map_add f a b).symm (add_mem iha ihb)
  | mul a b _ _ iha ihb =>
    exact mem_higgsSubalgebra_of_eq (hmul a b).symm (mul_mem iha ihb)

/-- A Lorentz slot-mixing sum of Higgs towers lies in the Higgs subalgebra. -/
lemma sum_smul_mem_higgsSubalgebra {n : ℕ} {c : (Fin n → (Fin 1 ⊕ Fin 3)) → ℂ}
    {G : (Fin n → (Fin 1 ⊕ Fin 3)) → CovJetAlgebra} (hG : ∀ p, G p ∈ higgsSubalgebra) :
    ∑ p : Fin n → (Fin 1 ⊕ Fin 3), c p • G p ∈ higgsSubalgebra :=
  Subalgebra.sum_mem _ fun p _ => Subalgebra.smul_mem _ (hG p) _

/-- The global gauge action preserves the Higgs subalgebra. -/
lemma repGaugeGroupI_mem_higgsSubalgebra (g : GaugeGroupI) {x : CovJetAlgebra}
    (hx : x ∈ higgsSubalgebra) : repGaugeGroupI g x ∈ higgsSubalgebra := by
  refine mapsTo_higgsSubalgebra ?_ (repGaugeGroupI_mul g) ?_ hx
  · exact Subtype.ext (AlgebraRealization.id.repGlobal_one g)
  · refine higgsGenerators_induction (fun l φ => ?_) (fun l φ => ?_)
    · exact mem_higgsSubalgebra_of_eq
        (Subtype.ext (AlgebraRealization.id.repGlobal_covDerivH g l φ)).symm
        (higgsField_mem_higgsSubalgebra _ _)
    · exact mem_higgsSubalgebra_of_eq
        (Subtype.ext (AlgebraRealization.id.repGlobal_covDerivBarH g l φ)).symm
        (conjHiggsField_mem_higgsSubalgebra _ _)

/-- The Lorentz action preserves the Higgs subalgebra. -/
lemma repLorentzGroup_mem_higgsSubalgebra (Λ : SL(2,ℂ)) {x : CovJetAlgebra}
    (hx : x ∈ higgsSubalgebra) : repLorentzGroup Λ x ∈ higgsSubalgebra := by
  refine mapsTo_higgsSubalgebra ?_ (repLorentzGroup_mul Λ) ?_ hx
  · exact Subtype.ext (AlgebraRealization.id.repLorentz_one Λ)
  · refine higgsGenerators_induction (fun l φ => ?_) (fun l φ => ?_)
    · exact mem_higgsSubalgebra_of_eq (isLorentzCovDerivTransforms_of
          (fun Λ n l φ => AlgebraRealization.id.repLorentz_covDerivH Λ n l φ) Λ _ l φ).symm
        (sum_smul_mem_higgsSubalgebra fun _ => higgsField_mem_higgsSubalgebra _ _)
    · exact mem_higgsSubalgebra_of_eq (isLorentzCovDerivTransforms_of
          (fun Λ n l φ => AlgebraRealization.id.repLorentz_covDerivBarH Λ n l φ)
          Λ _ l φ).symm
        (sum_smul_mem_higgsSubalgebra fun _ => conjHiggsField_mem_higgsSubalgebra _ _)

/-!

### B.1. The mass-weight polynomial

-/

/-- The mass-weight polynomial carries the Higgs subalgebra into the polynomials with
  coefficients in it: each Higgs tower is an eigenvector whose eigenvector is the tower
  itself, and the mass-weight polynomial is an algebra map. -/
lemma massWeightPoly_mem_polyRange (x : higgsSubalgebra) :
    massWeightPoly (x : CovJetAlgebra) ∈ higgsSubalgebra.polyRange :=
  higgsSubalgebra.mem_range_mapAlgHom_of_adjoin
    (higgsGenerators_induction
      (fun l φ => mem_polyRange_of_eq
        (massWeightPoly_eq_monomial
          (AlgebraRealization.id.massWeight_covDerivH l φ)).symm
        (Subalgebra.monomial_mem_polyRange (higgsField_mem_higgsSubalgebra l φ)))
      (fun l φ => mem_polyRange_of_eq
        (massWeightPoly_eq_monomial
          (AlgebraRealization.id.massWeight_covDerivBarH l φ)).symm
        (Subalgebra.monomial_mem_polyRange (conjHiggsField_mem_higgsSubalgebra l φ))))
    x.2

/-!

## C. The covariant jet algebra of the Higgs field

-/

end CovJetAlgebra

/-- The covariant jet algebra of the Higgs field: the subalgebra of the covariant jet
  algebra of the Standard Model generated by the covariant towers of the Higgs field and of
  its conjugate. Its elements are exactly the polynomial expressions in `∇_l H` and
  `∇_l H̄`. -/
abbrev CovHiggsJetAlgebra : Type := ↥CovJetAlgebra.higgsSubalgebra

/-- The covariant jet algebra of the Higgs field is a ring. The instance is given
  explicitly because the generic `Subalgebra.toRing` is not found by instance search at this
  concrete algebra. -/
noncomputable instance : Ring CovHiggsJetAlgebra :=
  @Subalgebra.toRing ℂ CovJetAlgebra _ _ _ CovJetAlgebra.higgsSubalgebra

/-- The covariant jet algebra of the Higgs field is a complex algebra, stated at the ring
  instance just given. -/
noncomputable instance : Algebra ℂ CovHiggsJetAlgebra :=
  @Subalgebra.algebra ℂ CovJetAlgebra _ _ _ CovJetAlgebra.higgsSubalgebra

namespace CovHiggsJetAlgebra

open CovJetAlgebra

/-- The action of the global gauge group on the covariant jet algebra of the Higgs
  field. -/
noncomputable def repGaugeGroupI : Representation ℂ GaugeGroupI CovHiggsJetAlgebra :=
  CovJetAlgebra.repGaugeGroupI.restrictSubalgebra CovJetAlgebra.higgsSubalgebra
    fun g _ hx => CovJetAlgebra.repGaugeGroupI_mem_higgsSubalgebra g hx

@[simp]
lemma coe_repGaugeGroupI (g : GaugeGroupI) (x : CovHiggsJetAlgebra) :
    (repGaugeGroupI g x : CovJetAlgebra) = CovJetAlgebra.repGaugeGroupI g (x : CovJetAlgebra) :=
  rfl

/-- The action of the Lorentz group on the covariant jet algebra of the Higgs field. -/
noncomputable def repLorentzGroup : Representation ℂ SL(2,ℂ) CovHiggsJetAlgebra :=
  CovJetAlgebra.repLorentzGroup.restrictSubalgebra CovJetAlgebra.higgsSubalgebra
    fun Λ _ hx => CovJetAlgebra.repLorentzGroup_mem_higgsSubalgebra Λ hx

@[simp]
lemma coe_repLorentzGroup (Λ : SL(2,ℂ)) (x : CovHiggsJetAlgebra) :
    (repLorentzGroup Λ x : CovJetAlgebra)
      = CovJetAlgebra.repLorentzGroup Λ (x : CovJetAlgebra) := rfl

/-- The mass-weight polynomial of the covariant jet algebra of the Higgs field. -/
noncomputable def massWeightPoly :
    CovHiggsJetAlgebra →ₐ[ℂ] Polynomial CovHiggsJetAlgebra :=
  CovJetAlgebra.higgsSubalgebra.polyRestrict CovJetAlgebra.massWeightPoly
    CovJetAlgebra.massWeightPoly_mem_polyRange

/-- A mass-weight eigenvalue equation in the covariant jet algebra of the Higgs field is
  the covariant jet algebra's own. -/
lemma massWeightPoly_eq_monomial {n : ℕ} {x : CovHiggsJetAlgebra}
    (hx : CovJetAlgebra.massWeightPoly (x : CovJetAlgebra)
      = Polynomial.monomial n (x : CovJetAlgebra)) :
    massWeightPoly x = Polynomial.monomial n x :=
  (Subalgebra.polyRestrict_eq_monomial_iff _ x).mpr hx

/-- In the covariant jet algebra of the Higgs field, the tower of covariant derivatives of
  the Higgs field. -/
noncomputable def higgsField {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ HiggsVec →ₗ[ℂ] CovHiggsJetAlgebra where
  toFun φ := ⟨CovJetAlgebra.higgsField l φ, higgsField_mem_higgsSubalgebra l φ⟩
  map_add' φ ψ := Subtype.ext (map_add _ φ ψ)
  map_smul' c φ := Subtype.ext (map_smul _ c φ)

@[simp]
lemma coe_higgsField {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ HiggsVec) :
    (higgsField l φ : CovJetAlgebra) = CovJetAlgebra.higgsField l φ := rfl

/-- In the covariant jet algebra of the Higgs field, the tower of covariant derivatives of
  the conjugate Higgs field. -/
noncomputable def conjHiggsField {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3)) :
    Module.Dual ℂ (ConjModule HiggsVec) →ₗ[ℂ] CovHiggsJetAlgebra where
  toFun φ := ⟨CovJetAlgebra.conjHiggsField l φ, conjHiggsField_mem_higgsSubalgebra l φ⟩
  map_add' φ ψ := Subtype.ext (map_add _ φ ψ)
  map_smul' c φ := Subtype.ext (map_smul _ c φ)

@[simp]
lemma coe_conjHiggsField {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule HiggsVec)) :
    (conjHiggsField l φ : CovJetAlgebra) = CovJetAlgebra.conjHiggsField l φ := rfl

/-!

## D. The laws of the Higgs towers

The nine laws the Higgs sector is written in, at the covariant jet algebra of the Higgs
field: the gauge equivariance of the two towers, their commutation, their mass weights and
their Lorentz transformation. Each is the covariant jet algebra's own law, which is in turn
the jet algebra's own, read on the subalgebra.

-/

/-- The global gauge action on the covariant jet algebra of the Higgs field is
  multiplicative. -/
lemma repGaugeGroupI_mul (g : GaugeGroupI) (x y : CovHiggsJetAlgebra) :
    repGaugeGroupI g (x * y) = repGaugeGroupI g x * repGaugeGroupI g y :=
  Subtype.ext (CovJetAlgebra.repGaugeGroupI_mul g (x : CovJetAlgebra) (y : CovJetAlgebra))

/-- The Lorentz action on the covariant jet algebra of the Higgs field is
  multiplicative. -/
lemma repLorentzGroup_mul (Λ : SL(2,ℂ)) (x y : CovHiggsJetAlgebra) :
    repLorentzGroup Λ (x * y) = repLorentzGroup Λ x * repLorentzGroup Λ y :=
  Subtype.ext (CovJetAlgebra.repLorentzGroup_mul Λ (x : CovJetAlgebra) (y : CovJetAlgebra))

/-- A Lorentz law of the covariant jet algebra, for a family valued in the covariant jet
  algebra of the Higgs field, is a Lorentz law there. -/
lemma isLorentzCovDerivTransforms_of {V : Type} [AddCommGroup V] [Module ℂ V]
    {rep : Representation ℂ SL(2,ℂ) V}
    {G : {n : ℕ} → (Fin n → (Fin 1 ⊕ Fin 3)) → Module.Dual ℂ V →ₗ[ℂ] CovHiggsJetAlgebra}
    (hG : ∀ (Λ : SL(2,ℂ)) (n : ℕ) (l : Fin n → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ V),
      CovJetAlgebra.repLorentzGroup Λ ((G l φ : CovHiggsJetAlgebra) : CovJetAlgebra) =
        ∑ p : Fin n → (Fin 1 ⊕ Fin 3),
          (∏ i, (((SL2C.toLorentzGroup Λ).1 (p i) (l i) : ℝ) : ℂ)) •
            ((G p (rep.dual Λ φ) : CovHiggsJetAlgebra) : CovJetAlgebra)) :
    IsLorentzCovDerivTransforms repLorentzGroup rep G := fun Λ n l φ =>
  Subtype.ext <| by
    simp only [coe_repLorentzGroup, AddSubmonoidClass.coe_finsetSum, SetLike.val_smul]
    exact hG Λ n l φ

/-- The Higgs tower is equivariant for the global gauge group. -/
lemma repGaugeGroupI_higgsField (g : GaugeGroupI) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ HiggsVec) :
    repGaugeGroupI g (higgsField l φ) = higgsField l (HiggsVec.repGaugeGroupI.dual g φ) :=
  Subtype.ext (Subtype.ext (AlgebraRealization.id.repGlobal_covDerivH g l φ))

/-- The conjugate Higgs tower is equivariant for the global gauge group. -/
lemma repGaugeGroupI_conjHiggsField (g : GaugeGroupI) {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule HiggsVec)) :
    repGaugeGroupI g (conjHiggsField l φ)
      = conjHiggsField l (HiggsVec.repGaugeGroupI.conj.dual g φ) :=
  Subtype.ext (Subtype.ext (AlgebraRealization.id.repGlobal_covDerivBarH g l φ))

/-- Two Higgs towers commute. -/
lemma commute_higgsField_higgsField {n m : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (l' : Fin m → (Fin 1 ⊕ Fin 3)) (φ ψ : Module.Dual ℂ HiggsVec) :
    Commute (higgsField l φ) (higgsField l' ψ) :=
  Subtype.ext (Subtype.ext (AlgebraRealization.id.covH_comm_covH l l' φ ψ))

/-- A Higgs tower commutes with a conjugate Higgs tower. -/
lemma commute_higgsField_conjHiggsField {n m : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (l' : Fin m → (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ HiggsVec)
    (ψ : Module.Dual ℂ (ConjModule HiggsVec)) :
    Commute (higgsField l φ) (conjHiggsField l' ψ) :=
  Subtype.ext (Subtype.ext (AlgebraRealization.id.covH_comm_covBarH l l' φ ψ))

/-- Two conjugate Higgs towers commute. -/
lemma commute_conjHiggsField_conjHiggsField {n m : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (l' : Fin m → (Fin 1 ⊕ Fin 3)) (φ ψ : Module.Dual ℂ (ConjModule HiggsVec)) :
    Commute (conjHiggsField l φ) (conjHiggsField l' ψ) :=
  Subtype.ext (Subtype.ext (AlgebraRealization.id.covBarH_comm_covBarH l l' φ ψ))

/-- The mass weight of the Higgs tower is `2 * (1 + n)`. -/
lemma massWeightPoly_higgsField {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ HiggsVec) :
    massWeightPoly (higgsField l φ)
      = Polynomial.monomial (2 * (1 + n)) (higgsField l φ) :=
  massWeightPoly_eq_monomial
    (CovJetAlgebra.massWeightPoly_eq_monomial (AlgebraRealization.id.massWeight_covDerivH l φ))

/-- The mass weight of the conjugate Higgs tower is `2 * (1 + n)`. -/
lemma massWeightPoly_conjHiggsField {n : ℕ} (l : Fin n → (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule HiggsVec)) :
    massWeightPoly (conjHiggsField l φ)
      = Polynomial.monomial (2 * (1 + n)) (conjHiggsField l φ) :=
  massWeightPoly_eq_monomial (CovJetAlgebra.massWeightPoly_eq_monomial
    (AlgebraRealization.id.massWeight_covDerivBarH l φ))

/-- The Higgs tower transforms as the covariant derivatives of a Lorentz scalar. -/
lemma isLorentzCovDerivTransforms_higgsField :
    IsLorentzCovDerivTransforms repLorentzGroup
      (Representation.trivial ℂ SL(2,ℂ) HiggsVec) (fun {_n} l => higgsField l) :=
  isLorentzCovDerivTransforms_of fun Λ n l φ =>
    CovJetAlgebra.isLorentzCovDerivTransforms_of
      (fun Λ n l φ => AlgebraRealization.id.repLorentz_covDerivH Λ n l φ) Λ n l φ

/-- The conjugate Higgs tower transforms as the covariant derivatives of a Lorentz
  scalar. -/
lemma isLorentzCovDerivTransforms_conjHiggsField :
    IsLorentzCovDerivTransforms repLorentzGroup
      (Representation.trivial ℂ SL(2,ℂ) HiggsVec).conj (fun {_n} l => conjHiggsField l) :=
  isLorentzCovDerivTransforms_of fun Λ n l φ =>
    CovJetAlgebra.isLorentzCovDerivTransforms_of
      (fun Λ n l φ => AlgebraRealization.id.repLorentz_covDerivBarH Λ n l φ) Λ n l φ

end CovHiggsJetAlgebra

end StandardModel
