/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.ClassicalFieldTheory.GaugeTheory.MatterField.JetComponentSpace.GaugeAction
public import Physlib.Particles.StandardModel.GaugeGroup.LocalGaugeData
public import Physlib.Mathematics.SymmetricAlgebra
/-!
# The bosonic algebra of a matter field

## i. Overview

For a bosonic matter field valued in a complex vector space `V`, the *bosonic algebra* is
the symmetric algebra on the jet component space `JetComponentSpace M`. It is the algebra
in which the `V`-part of a Lagrangian lives: the generators are the component functions
`∂_s φ_α` and their conjugates `∂_s φ̄_α`, and the symmetric product implements the
commutativity of bosonic fields. It is the bosonic mirror of `FermionicAlgebra`, with the
symmetric algebra in place of the exterior algebra.

Everything the component space carries lifts to the bosonic algebra by functoriality of
the symmetric algebra: the Lorentz action (`BosonicAlgebra.repLorentzGroup`), the jet
gauge action (`BosonicAlgebra.repJetGaugeGroupI`), and the formal total derivative
(`BosonicAlgebra.jetDeriv`), which extends as a derivation rather than by functoriality.
Those live in the sibling files `LorentzAction`, `GaugeAction` and `JetDeriv`.

## ii. Key results

- `BosonicAlgebra` : the symmetric algebra on the jet component space.
- `BosonicAlgebra.adjoin_ι_eq_top` : the algebra is generated by the component functions.
- `BosonicAlgebra.ofField`, `BosonicAlgebra.ofConjField` : the field and its conjugate.
- `BosonicAlgebra.comap` : the inclusion of a species, contravariant in the target space.

## iii. Table of contents

- A. The bosonic algebra
  - A.1. The generators of the bosonic algebra
  - A.2. The field and its conjugate
  - A.3. Inclusion of a species

-/

@[expose] public section

namespace StandardModel

open TensorProduct

variable {G₀ : Type} [Group G₀] {𝔤 : Type} [LieRing 𝔤] [LieAlgebra ℝ 𝔤]
  {GJ : Type} [Group GJ] {𝔤J : Type} [LieRing 𝔤J] [LieAlgebra ℝ 𝔤J]
  {jets : LocalGaugeData G₀ 𝔤 GJ 𝔤J} {M : MatterField jets}

/-!

## A. The bosonic algebra

-/

/-- The bosonic algebra of the matter field `M`: the symmetric algebra on the space
  of component functions `∂_s φ_α` and `∂_s φ̄_α`. The symmetric product is the product of
  bosonic fields, its commutativity the Bose statistics. -/
abbrev BosonicAlgebra (M : MatterField jets) : Type :=
  SymmetricAlgebra ℂ (JetComponentSpace M)

namespace BosonicAlgebra

/-!

### A.1. The generators of the bosonic algebra

-/

/-- **The bosonic algebra is generated by the component functions.** Every element is a
  polynomial in the degree-one elements — the symbols `∂_s φ_α` and `∂_s φ̄_α` themselves.
  This is the algebraic form of "every Lagrangian term is a polynomial in the component
  functions". -/
@[simp]
lemma adjoin_ι_eq_top :
    Algebra.adjoin ℂ (Set.range (SymmetricAlgebra.ι ℂ (JetComponentSpace M))) = ⊤ :=
  SymmetricAlgebra.adjoin_range_ι

/-- Two component functions commute: Bose statistics. -/
lemma ι_mul_ι_comm (x y : JetComponentSpace M) :
    (SymmetricAlgebra.ι ℂ _ x * SymmetricAlgebra.ι ℂ _ y : BosonicAlgebra M)
      = SymmetricAlgebra.ι ℂ _ y * SymmetricAlgebra.ι ℂ _ x :=
  mul_comm _ _

/-!

### A.2. The field and its conjugate

The undifferentiated component functions sit inside the bosonic algebra as the two
inclusions below. A component function is a *covector* on the target space: `ofField φ` is
the component of the field `ψ` along `φ`, the element written `ψ_α` when `φ` is the `α`-th
coordinate. The conjugate field is a covector on `ConjModule M.V`, whose scalar action is
twisted by complex conjugation — that twist is exactly the statement that `ψ̄` transforms
by the conjugate of the representation carried by `ψ`.

Every other generator of the algebra is an iterated derivative of one of these, which is
the content of `BosonicAlgebra.adjoin_iteratedJetDeriv_eq_top`.

-/

/-- **The component function `ψ_φ` of the matter field** along the covector `φ` on `V`: the
  undifferentiated generator, sitting at the empty derivative label in the unconjugated half
  of the component space. -/
noncomputable def ofField : Module.Dual ℂ M.V →ₗ[ℂ] BosonicAlgebra M :=
  (SymmetricAlgebra.ι ℂ _).comp
    ((LinearMap.inl ℂ (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ M.V)
        (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ (ConjModule M.V))).comp
      (TensorProduct.mk ℂ DerivAlgebraComplex (Module.Dual ℂ M.V) 1))

/-- **The component function `ψ̄_φ` of the conjugate matter field** along the covector `φ`
  on `ConjModule M.V`: the undifferentiated generator in the conjugate half of the component
  space. -/
noncomputable def ofConjField : Module.Dual ℂ (ConjModule M.V) →ₗ[ℂ] BosonicAlgebra M :=
  (SymmetricAlgebra.ι ℂ _).comp
    ((LinearMap.inr ℂ (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ M.V)
        (DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ (ConjModule M.V))).comp
      (TensorProduct.mk ℂ DerivAlgebraComplex (Module.Dual ℂ (ConjModule M.V)) 1))

lemma ofField_apply (φ : Module.Dual ℂ M.V) :
    ofField φ = SymmetricAlgebra.ι ℂ _
      (((1 : DerivAlgebraComplex) ⊗ₜ[ℂ] φ, 0) : JetComponentSpace M) := rfl

lemma ofConjField_apply (φ : Module.Dual ℂ (ConjModule M.V)) :
    ofConjField φ = SymmetricAlgebra.ι ℂ _
      ((0, (1 : DerivAlgebraComplex) ⊗ₜ[ℂ] φ) : JetComponentSpace M) := rfl

/-!

### A.3. Inclusion of a species

A field valued in `V` that is one *species* among several — i.e. `V` is a summand of a
larger target space `W` — has its bosonic algebra sitting inside the bosonic algebra of
`W`. The inclusion is induced by the *projection* `W →ₗ[ℂ] V`, because component functions
are covectors on the target and therefore transpose. `comap` is that induced map, and it is
functorial and compatible with everything the algebra carries.

-/

variable {N : MatterField jets}

/-- **The bosonic algebra is contravariant in the target space.** A linear map
  `f : V →ₗ[ℂ] W` induces an algebra homomorphism `BosonicAlgebra N →ₐ[ℂ] BosonicAlgebra M`
  by pulling back component functions. Applied to a *projection* out of a multi-species
  target space, this is the inclusion of one species' algebra into the whole. -/
noncomputable def comap (f : M.V →ₗ[ℂ] N.V) : BosonicAlgebra N →ₐ[ℂ] BosonicAlgebra M :=
  SymmetricAlgebra.map (JetComponentSpace.comap f)

@[simp]
lemma comap_ι (f : M.V →ₗ[ℂ] N.V) (x : JetComponentSpace N) :
    comap f (SymmetricAlgebra.ι ℂ _ x)
      = SymmetricAlgebra.ι ℂ _ (JetComponentSpace.comap f x) :=
  SymmetricAlgebra.map_apply_ι _ x

@[simp]
lemma comap_id : comap (LinearMap.id : M.V →ₗ[ℂ] M.V) = AlgHom.id ℂ (BosonicAlgebra M) := by
  rw [comap, JetComponentSpace.comap_id, SymmetricAlgebra.map_id]

/-- Functoriality: the order reverses, as it must for a contravariant construction. -/
lemma comap_comp {P : MatterField jets} (f : M.V →ₗ[ℂ] N.V) (g : N.V →ₗ[ℂ] P.V) :
    comap (g.comp f) = (comap f).comp (comap g) := by
  rw [comap, comap, comap, JetComponentSpace.comap_comp, ← SymmetricAlgebra.map_comp_map]

/-- The inclusion sends a component function of the species to the corresponding component
  function of the whole. -/
@[simp]
lemma comap_ofField (f : M.V →ₗ[ℂ] N.V) (φ : Module.Dual ℂ N.V) :
    comap f (ofField φ) = ofField (φ ∘ₗ f) := by
  rw [ofField_apply, comap_ι, ofField_apply]
  congr 1

/-- The inclusion sends a conjugate component function of the species to the corresponding
  conjugate component function of the whole. -/
@[simp]
lemma comap_ofConjField (f : M.V →ₗ[ℂ] N.V) (φ : Module.Dual ℂ (ConjModule N.V)) :
    comap f (ofConjField φ) = ofConjField (φ ∘ₗ ConjModule.map f) := by
  rw [ofConjField_apply, comap_ι, ofConjField_apply]
  congr 1

end BosonicAlgebra

end StandardModel
