/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.StandardModel.Matter.BosonicAlgebra.Basic
public import Physlib.Relativity.IsLorentzDeriv
/-!
# The formal total derivative on the bosonic algebra

## i. Overview

The formal total spacetime derivative extends from the component functions to the whole
bosonic algebra as a derivation: it is `SymmetricAlgebra.derivationOfLinear` applied to the
shift `∂_s φ_α ↦ ∂_{s + {μ}} φ_α` on the jet component space.

The four directional derivatives commute, so they iterate along a *multiset* of directions
through `Lorentz.iteratedD`. On a component function the iterate is multiplication by the
derivative symbol `∂_s` in the `DerivAlgebraComplex` factor, and on a product it obeys the
all-orders Leibniz rule over the antidiagonal of the multiset.

## ii. Key results

- `BosonicAlgebra.jetDeriv` : the formal total spacetime derivative.
- `BosonicAlgebra.jetDeriv_mul` : the Leibniz rule.
- `BosonicAlgebra.jetDeriv_comm` : total derivatives commute.
- `BosonicAlgebra.iteratedJetDeriv` : the iterated derivative along a multiset.
- `BosonicAlgebra.iteratedJetDeriv_mul` : the all-orders Leibniz rule.
- `BosonicAlgebra.adjoin_iteratedJetDeriv_eq_top` : the algebra is generated by the field,
  its conjugate, and their derivatives.
- `BosonicAlgebra.comap_jetDeriv` : the inclusion of a species commutes with the
  derivative.

## iii. Table of contents

- A. The formal total derivative on the bosonic algebra
- B. The iterated total derivative
- C. Generation by the field and its derivatives
- D. Compatibility with the inclusion of a species

-/

@[expose] public section

namespace StandardModel

namespace BosonicAlgebra

open TensorProduct

variable {V : Type} [AddCommGroup V] [Module ℂ V]

/-!

## A. The formal total derivative on the bosonic algebra

-/

/-- The formal total spacetime derivative on the bosonic algebra of a `V`-valued matter
  field in the direction `μ`: the derivation extending the shift
  `∂_s φ_α ↦ ∂_{s + {μ}} φ_α` of the component functions. -/
noncomputable def jetDeriv (μ : Fin 1 ⊕ Fin 3) :
    BosonicAlgebra V →ₗ[ℂ] BosonicAlgebra V :=
  SymmetricAlgebra.derivationOfLinear (JetComponentSpace.jetDeriv μ)

/-- On a component function the total derivative is the shift of the derivative label. -/
@[simp]
lemma jetDeriv_ι (μ : Fin 1 ⊕ Fin 3) (x : JetComponentSpace V) :
    jetDeriv μ (SymmetricAlgebra.ι ℂ _ x) =
      SymmetricAlgebra.ι ℂ _ (JetComponentSpace.jetDeriv μ x) :=
  SymmetricAlgebra.derivationOfLinear_ι _ x

@[simp]
lemma jetDeriv_one (μ : Fin 1 ⊕ Fin 3) : jetDeriv (V := V) μ (1 : BosonicAlgebra V) = 0 :=
  SymmetricAlgebra.derivationOfLinear_one _

@[simp]
lemma jetDeriv_algebraMap (μ : Fin 1 ⊕ Fin 3) (r : ℂ) :
    jetDeriv (V := V) μ (algebraMap ℂ (BosonicAlgebra V) r) = 0 :=
  SymmetricAlgebra.derivationOfLinear_algebraMap _ r

/-- The total derivative is a derivation: the Leibniz rule holds on the bosonic
  algebra. -/
lemma jetDeriv_mul (μ : Fin 1 ⊕ Fin 3) (x y : BosonicAlgebra V) :
    jetDeriv μ (x * y) = jetDeriv μ x * y + x * jetDeriv μ y :=
  SymmetricAlgebra.derivationOfLinear_mul _ x y

/-- **Mixed partials agree.** The derivative labels live in a *symmetric* algebra, so the
  total derivatives in different directions commute. -/
lemma jetDeriv_comm_apply (μ ν : Fin 1 ⊕ Fin 3) (x : BosonicAlgebra V) :
    jetDeriv μ (jetDeriv ν x) = jetDeriv ν (jetDeriv μ x) :=
  SymmetricAlgebra.derivationOfLinear_comm_apply
    (JetComponentSpace.jetDeriv_comm μ ν) x

lemma jetDeriv_comm (μ ν : Fin 1 ⊕ Fin 3) :
    (jetDeriv (V := V) μ).comp (jetDeriv ν) = (jetDeriv (V := V) ν).comp (jetDeriv μ) :=
  LinearMap.ext fun x => jetDeriv_comm_apply μ ν x

/-!

## B. The iterated total derivative

-/

/-- The iterated total derivative `∂_s = ∂_{ν₁} ⋯ ∂_{νₙ}` along a multiset `s` of
  directions. It is well defined on a multiset — i.e. independent of the order in which the
  directions are listed — because the directional derivatives commute. -/
noncomputable def iteratedJetDeriv (s : Multiset (Fin 1 ⊕ Fin 3)) :
    BosonicAlgebra V →ₗ[ℂ] BosonicAlgebra V :=
  Lorentz.iteratedD jetDeriv jetDeriv_comm s

@[simp]
lemma iteratedJetDeriv_zero :
    iteratedJetDeriv (0 : Multiset (Fin 1 ⊕ Fin 3))
      = LinearMap.id (R := ℂ) (M := BosonicAlgebra V) :=
  Lorentz.iteratedD_zero jetDeriv jetDeriv_comm

lemma iteratedJetDeriv_cons (μ : Fin 1 ⊕ Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    iteratedJetDeriv (V := V) (μ ::ₘ s) = (jetDeriv μ).comp (iteratedJetDeriv s) :=
  Lorentz.iteratedD_cons jetDeriv jetDeriv_comm μ s

/-- The companion of `iteratedJetDeriv_cons`, peeling the extra derivative on the inside. -/
lemma iteratedJetDeriv_cons' (μ : Fin 1 ⊕ Fin 3) (s : Multiset (Fin 1 ⊕ Fin 3)) :
    iteratedJetDeriv (V := V) (μ ::ₘ s) = (iteratedJetDeriv s).comp (jetDeriv μ) :=
  Lorentz.iteratedD_cons' jetDeriv jetDeriv_comm μ s

@[simp]
lemma iteratedJetDeriv_singleton (μ : Fin 1 ⊕ Fin 3) :
    iteratedJetDeriv (V := V) {μ} = jetDeriv μ :=
  Lorentz.iteratedD_singleton jetDeriv jetDeriv_comm μ

/-- The iterated derivative is additive in the multiset of directions: differentiating
  along `s + t` is differentiating along `t` and then along `s`. -/
lemma iteratedJetDeriv_add (s t : Multiset (Fin 1 ⊕ Fin 3)) :
    iteratedJetDeriv (V := V) (s + t)
      = (iteratedJetDeriv s).comp (iteratedJetDeriv t) :=
  Lorentz.iteratedD_add jetDeriv jetDeriv_comm s t

/-- **The all-orders Leibniz rule.** The iterated derivative of a product distributes over
  the antidiagonal of the multiset of directions: each way of splitting the derivatives
  between the two factors contributes one term. -/
lemma iteratedJetDeriv_mul (s : Multiset (Fin 1 ⊕ Fin 3)) (x y : BosonicAlgebra V) :
    iteratedJetDeriv s (x * y) =
      (s.antidiagonal.map fun p =>
        iteratedJetDeriv p.1 x * iteratedJetDeriv p.2 y).sum :=
  Lorentz.iteratedD_mul jetDeriv jetDeriv_comm jetDeriv_mul s x y

/-- A nonempty iterated derivative kills the constants. -/
lemma iteratedJetDeriv_one_of_ne_zero {s : Multiset (Fin 1 ⊕ Fin 3)} (hs : s ≠ 0) :
    iteratedJetDeriv (V := V) s (1 : BosonicAlgebra V) = 0 := by
  obtain ⟨μ, hμ⟩ := Multiset.exists_mem_of_ne_zero hs
  obtain ⟨t, rfl⟩ := Multiset.exists_cons_of_mem hμ
  rw [iteratedJetDeriv_cons', LinearMap.comp_apply, jetDeriv_one, map_zero]

/-- **On a component function the iterated derivative is the derivative symbol `∂_s`.**
  Both halves of the component space — the field and its conjugate — are multiplied by the
  degree-`|s|` element `∂_s` of `DerivAlgebraComplex` in their derivative-label factor,
  with the target index untouched. -/
lemma iteratedJetDeriv_ι (s : Multiset (Fin 1 ⊕ Fin 3)) (x : JetComponentSpace V) :
    iteratedJetDeriv s (SymmetricAlgebra.ι ℂ _ x) =
      SymmetricAlgebra.ι ℂ _
        (TensorProduct.map (LinearMap.mulRight ℂ (DerivAlgebraComplex.basis s))
            LinearMap.id x.1,
          TensorProduct.map (LinearMap.mulRight ℂ (DerivAlgebraComplex.basis s))
            LinearMap.id x.2) := by
  have hmul : ∀ t u : Multiset (Fin 1 ⊕ Fin 3),
      (LinearMap.mulRight ℂ (DerivAlgebraComplex.basis t)).comp
        (LinearMap.mulRight ℂ (DerivAlgebraComplex.basis u))
        = LinearMap.mulRight ℂ (DerivAlgebraComplex.basis (u + t)) := fun t u =>
    LinearMap.ext fun a => by
      simp only [LinearMap.coe_comp, Function.comp_apply, LinearMap.mulRight_apply, mul_assoc,
        DerivAlgebraComplex.basis_mul]
  have hone : LinearMap.mulRight ℂ (1 : DerivAlgebraComplex) = LinearMap.id :=
    LinearMap.ext fun a => mul_one a
  have hnil : DerivAlgebraComplex.basis (0 : Multiset (Fin 1 ⊕ Fin 3)) = 1 :=
    DerivAlgebraComplex.basis_nil
  induction s using Multiset.induction_on with
  | empty =>
    rw [iteratedJetDeriv_zero, LinearMap.id_apply, hnil, hone]
    simp only [TensorProduct.map_id, LinearMap.id_apply]
  | cons μ s ih =>
    have hs : s + ({μ} : Multiset (Fin 1 ⊕ Fin 3)) = μ ::ₘ s := by
      rw [add_comm, Multiset.singleton_add]
    rw [iteratedJetDeriv_cons, LinearMap.comp_apply, ih, jetDeriv_ι]
    congr 1
    refine Prod.ext ?_ ?_
    · rw [JetComponentSpace.jetDeriv_fst, ← LinearMap.comp_apply, ← TensorProduct.map_comp,
        LinearMap.id_comp, hmul, hs]
    · rw [JetComponentSpace.jetDeriv_snd, ← LinearMap.comp_apply, ← TensorProduct.map_comp,
        LinearMap.id_comp, hmul, hs]

/-!

## C. Generation by the field and its derivatives

-/

/-- The iterated derivative of the field is the generator carrying the derivative symbol
  `∂_s`: applying `∂_s` to `ψ_φ` writes the label `s` into the derivative factor. -/
@[simp]
lemma iteratedJetDeriv_ofField (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ V) :
    iteratedJetDeriv s (ofField φ) =
      SymmetricAlgebra.ι ℂ _
        ((DerivAlgebraComplex.basis s ⊗ₜ[ℂ] φ, 0) : JetComponentSpace V) := by
  rw [ofField_apply, iteratedJetDeriv_ι]
  congr 1
  refine Prod.ext ?_ ?_
  · rw [TensorProduct.map_tmul, LinearMap.mulRight_apply, one_mul, LinearMap.id_apply]
  · rw [map_zero]

/-- The iterated derivative of the conjugate field is the conjugate generator carrying the
  derivative symbol `∂_s`. -/
@[simp]
lemma iteratedJetDeriv_ofConjField (s : Multiset (Fin 1 ⊕ Fin 3))
    (φ : Module.Dual ℂ (ConjModule V)) :
    iteratedJetDeriv s (ofConjField φ) =
      SymmetricAlgebra.ι ℂ _
        ((0, DerivAlgebraComplex.basis s ⊗ₜ[ℂ] φ) : JetComponentSpace V) := by
  rw [ofConjField_apply, iteratedJetDeriv_ι]
  congr 1
  refine Prod.ext ?_ ?_
  · rw [map_zero]
  · rw [TensorProduct.map_tmul, LinearMap.mulRight_apply, one_mul, LinearMap.id_apply]

/-- **The bosonic algebra is generated by the field, its conjugate, and their
  derivatives.** As a `ℂ`-algebra, `BosonicAlgebra V` is the algebra adjoined by the
  iterated total derivatives `∂_s ψ_φ` and `∂_s ψ̄_φ` of the undifferentiated component
  functions. Physically: every Lagrangian term for a `V`-valued bosonic matter field is a
  polynomial in the field, its conjugate, and their spacetime derivatives — nothing else is
  available to write down. -/
theorem adjoin_iteratedJetDeriv_eq_top :
    Algebra.adjoin ℂ
      (⋃ s : Multiset (Fin 1 ⊕ Fin 3),
        Set.range (fun φ : Module.Dual ℂ V => iteratedJetDeriv s (ofField φ)) ∪
          Set.range (fun φ : Module.Dual ℂ (ConjModule V) =>
            iteratedJetDeriv s (ofConjField φ)))
      = (⊤ : Subalgebra ℂ (BosonicAlgebra V)) := by
  set S : Set (BosonicAlgebra V) :=
    ⋃ s : Multiset (Fin 1 ⊕ Fin 3),
      Set.range (fun φ : Module.Dual ℂ V => iteratedJetDeriv s (ofField φ)) ∪
        Set.range (fun φ : Module.Dual ℂ (ConjModule V) =>
          iteratedJetDeriv s (ofConjField φ)) with hS
  /- The two half-inclusions of the component space into the bosonic algebra. -/
  let gField : DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ V →ₗ[ℂ] BosonicAlgebra V :=
    (SymmetricAlgebra.ι ℂ _).comp (LinearMap.inl ℂ _ _)
  let gConj : DerivAlgebraComplex ⊗[ℂ] Module.Dual ℂ (ConjModule V) →ₗ[ℂ]
      BosonicAlgebra V :=
    (SymmetricAlgebra.ι ℂ _).comp (LinearMap.inr ℂ _ _)
  /- On a derivative monomial each half-inclusion is one of the adjoined generators. -/
  have hbasisField : ∀ (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ V),
      gField (DerivAlgebraComplex.basis s ⊗ₜ[ℂ] φ) ∈ Algebra.adjoin ℂ S := by
    intro s φ
    have h : gField (DerivAlgebraComplex.basis s ⊗ₜ[ℂ] φ) = iteratedJetDeriv s (ofField φ) :=
      (iteratedJetDeriv_ofField s φ).symm
    rw [h, hS]
    exact Algebra.subset_adjoin (Set.mem_iUnion.mpr ⟨s, Or.inl ⟨φ, rfl⟩⟩)
  have hbasisConj : ∀ (s : Multiset (Fin 1 ⊕ Fin 3)) (φ : Module.Dual ℂ (ConjModule V)),
      gConj (DerivAlgebraComplex.basis s ⊗ₜ[ℂ] φ) ∈ Algebra.adjoin ℂ S := by
    intro s φ
    have h : gConj (DerivAlgebraComplex.basis s ⊗ₜ[ℂ] φ)
        = iteratedJetDeriv s (ofConjField φ) := (iteratedJetDeriv_ofConjField s φ).symm
    rw [h, hS]
    exact Algebra.subset_adjoin (Set.mem_iUnion.mpr ⟨s, Or.inr ⟨φ, rfl⟩⟩)
  /- The derivative monomials span, so each half-inclusion lands in the adjoined algebra. -/
  have hhalf : ∀ {W : Type} [AddCommGroup W] [Module ℂ W]
      (g : DerivAlgebraComplex ⊗[ℂ] W →ₗ[ℂ] BosonicAlgebra V),
      (∀ (s : Multiset (Fin 1 ⊕ Fin 3)) (w : W),
        g (DerivAlgebraComplex.basis s ⊗ₜ[ℂ] w) ∈ Algebra.adjoin ℂ S) →
      ∀ y, g y ∈ Algebra.adjoin ℂ S := by
    intro W _ _ g hg y
    induction y using TensorProduct.induction_on with
    | zero => rw [map_zero]; exact zero_mem _
    | add y z hy hz => rw [map_add]; exact add_mem hy hz
    | tmul a w =>
      have ha : a ∈ Submodule.span ℂ (Set.range DerivAlgebraComplex.basis) := by
        rw [DerivAlgebraComplex.basis.span_eq]; trivial
      induction ha using Submodule.span_induction with
      | mem b hb => obtain ⟨s, rfl⟩ := hb; exact hg s w
      | zero => rw [TensorProduct.zero_tmul, map_zero]; exact zero_mem _
      | add b c _ _ hb hc => rw [TensorProduct.add_tmul, map_add]; exact add_mem hb hc
      | smul c b _ hb =>
        rw [← TensorProduct.smul_tmul', map_smul]
        exact Subalgebra.smul_mem _ hb c
  /- Every component function is a sum of its two halves. -/
  refine top_le_iff.mp ?_
  rw [← adjoin_ι_eq_top (V := V)]
  refine Algebra.adjoin_le ?_
  rintro _ ⟨x, rfl⟩
  have hx : x = LinearMap.inl ℂ _ _ x.1 + LinearMap.inr ℂ _ _ x.2 := by
    refine Prod.ext ?_ ?_ <;> simp
  rw [hx, map_add]
  exact add_mem (hhalf gField hbasisField x.1) (hhalf gConj hbasisConj x.2)

/-!

## D. Compatibility with the inclusion of a species

-/

variable {W : Type} [AddCommGroup W] [Module ℂ W]

/-- **The inclusion of a species is a map of differential algebras.** Pulling back along a
  map of target spaces commutes with the total derivative: the two act on different labels
  of a component function. -/
lemma comap_jetDeriv (f : V →ₗ[ℂ] W) (μ : Fin 1 ⊕ Fin 3) (x : BosonicAlgebra W) :
    comap f (jetDeriv μ x) = jetDeriv μ (comap f x) := by
  induction x using SymmetricAlgebra.induction with
  | algebraMap r =>
    rw [jetDeriv_algebraMap, map_zero, AlgHom.commutes, jetDeriv_algebraMap]
  | ι v =>
    rw [jetDeriv_ι, comap_ι, comap_ι, jetDeriv_ι]
    exact congrArg (SymmetricAlgebra.ι ℂ _)
      (DFunLike.congr_fun (JetComponentSpace.comap_jetDeriv f μ) v)
  | mul a b ha hb => simp only [jetDeriv_mul, map_add, map_mul, ha, hb]
  | add a b ha hb => simp only [map_add, ha, hb]

/-- The inclusion of a species commutes with the iterated total derivative. -/
lemma comap_iteratedJetDeriv (f : V →ₗ[ℂ] W) (s : Multiset (Fin 1 ⊕ Fin 3))
    (x : BosonicAlgebra W) :
    comap f (iteratedJetDeriv s x) = iteratedJetDeriv s (comap f x) := by
  induction s using Multiset.induction_on generalizing x with
  | empty => rw [iteratedJetDeriv_zero, LinearMap.id_apply, iteratedJetDeriv_zero,
      LinearMap.id_apply]
  | cons μ s ih =>
    rw [iteratedJetDeriv_cons, LinearMap.comp_apply, comap_jetDeriv, ih,
      iteratedJetDeriv_cons, LinearMap.comp_apply]

end BosonicAlgebra

end StandardModel
