/-
Copyright (c) 2026 Nathaneal Sajan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nathaneal Sajan
-/
module

public import Mathlib.Algebra.Algebra.Operations
public import Mathlib.Algebra.Polynomial.AlgebraMap
public import Mathlib.RingTheory.Adjoin.Basic
/-!
# Subalgebras generated by homogeneous submodules

## i. Overview

Let `f : B →ₐ[R] B[X]` be an algebra map into the polynomials over a possibly
noncommutative algebra `B`. The degree-`w` part of a subalgebra `A` is the submodule
`A.homogeneousSubmodule f w` of elements `x ∈ A` with `f x = monomial w x`. Nothing
requires `f` to be a grading of `B`: the pieces need not span `B`, and `f x` need not
determine `x`.

Suppose that `A` is generated by a family of submodules `D n`, and that `f` is the monomial
`X ^ deg n` on `D n`. Then the degree-`w` part of `A` is spanned by the products
`D n₁ * ⋯ * D nₖ`, in every order of the factors, whose degrees add up to `w`
(`homogeneousSubmodule_eq_productsOfDegree`). The empty product is `1`, so degree zero
contains the scalars. This is a spanning statement. It gives no unique decomposition, and
it assumes neither that the generators commute nor that their products are nonzero.

Everything else is read off from it.

- Removing the leftmost factor of each product: the degree-`w` part, for `w` positive, is
  spanned by the products `D k * A_(w - deg k)` (`homogeneousSubmodule_eq_iSup_mul`). This
  needs no positivity. When some `deg k` vanishes, the right-hand side contains the term
  `D k * A_w` of the same degree, so the equality holds without giving a decreasing
  recursion.
- If every generator has positive degree, degree zero is exactly the scalar submodule `1`
  (`homogeneousSubmodule_zero_eq_one`), the image of `R` in `B`, which need not be a copy
  of `R`.
- If moreover `n < deg n`, the degree-`i` part is spanned by the generators of degree `i`
  and the products of two parts of smaller positive degree
  (`homogeneousSubmodule_eq_sup_iSup_mul`). The bound makes the index ranges finite.
- A property of degrees holding at zero and at every generator degree, and closed under
  addition, holds at every degree with a nonzero part (`homogeneousSubmodule_eq_bot`).
  This only proves vanishing: a degree with the property may still have zero part.

## ii. Key results

- `Subalgebra.homogeneousSubmodule` : the degree-`w` part of a subalgebra.
- `Submodule.productsOfDegree` : the span of the products of generators of total degree `w`.
- `Subalgebra.coeff_mem_homogeneousSubmodule` : the coefficients of `f x` are homogeneous.
- `Subalgebra.homogeneousSubmodule_eq_productsOfDegree` : spanning by products.
- `Subalgebra.homogeneousSubmodule_eq_iSup_mul` : removing the leftmost generator.
- `Subalgebra.homogeneousSubmodule_zero_eq_one` : degree zero is the scalars.
- `Subalgebra.homogeneousSubmodule_eq_sup_iSup_mul` : the binary recursion.
- `Subalgebra.homogeneousSubmodule_eq_bot` : unreachable degrees vanish.

## iii. Table of contents

- A. The homogeneous submodules of a subalgebra
- B. Products of generators of a given total degree
- C. Subalgebras generated by homogeneous submodules
  - C.1. Generators and coefficients
  - C.2. Spanning by products of generators
  - C.3. Removing the leftmost generator
  - C.4. Degree zero and the binary recursion
  - C.5. Unreachable degrees

-/

@[expose] public section

variable {R B : Type*} [CommSemiring R] [Ring B] [Algebra R B]

namespace Subalgebra

/-!

## A. The homogeneous submodules of a subalgebra

-/

/-- The degree-`w` part of `A` for `f`: the elements `x ∈ A` with `f x = monomial w x`. -/
noncomputable def homogeneousSubmodule (A : Subalgebra R B) (f : B →ₐ[R] Polynomial B)
    (w : ℕ) : Submodule R B :=
  A.toSubmodule
    ⊓ LinearMap.ker (f.toLinearMap
      - (Polynomial.monomial w : B →ₗ[B] Polynomial B).restrictScalars R)

variable {A : Subalgebra R B} {f : B →ₐ[R] Polynomial B}

lemma mem_homogeneousSubmodule_iff {w : ℕ} {x : B} :
    x ∈ A.homogeneousSubmodule f w ↔ x ∈ A ∧ f x = Polynomial.monomial w x := by
  simp only [homogeneousSubmodule, Submodule.mem_inf, Subalgebra.mem_toSubmodule,
    LinearMap.mem_ker, LinearMap.sub_apply, AlgHom.toLinearMap_apply,
    LinearMap.coe_restrictScalars, sub_eq_zero]

/-- The scalars have degree zero. -/
lemma one_le_homogeneousSubmodule_zero : (1 : Submodule R B) ≤ A.homogeneousSubmodule f 0 :=
  Submodule.one_le.mpr (mem_homogeneousSubmodule_iff.mpr ⟨A.one_mem, by simp⟩)

/-- Degrees add under multiplication. -/
lemma homogeneousSubmodule_mul_le (m n : ℕ) :
    A.homogeneousSubmodule f m * A.homogeneousSubmodule f n
      ≤ A.homogeneousSubmodule f (m + n) :=
  Submodule.mul_le.mpr fun x hx y hy => by
    obtain ⟨hxA, hxf⟩ := mem_homogeneousSubmodule_iff.mp hx
    obtain ⟨hyA, hyf⟩ := mem_homogeneousSubmodule_iff.mp hy
    exact mem_homogeneousSubmodule_iff.mpr ⟨A.mul_mem hxA hyA,
      by rw [map_mul, hxf, hyf, Polynomial.monomial_mul_monomial]⟩

end Subalgebra

/-!

## B. Products of generators of a given total degree

-/

namespace Submodule

/-- The span of the products `D n₁ * ⋯ * D nₖ` whose degrees `deg n₁ + ⋯ + deg nₖ` add up
  to `w`. Every order of the factors occurs separately, and the empty product is `1`. -/
noncomputable def productsOfDegree (D : ℕ → Submodule R B) (deg : ℕ → ℕ) (w : ℕ) :
    Submodule R B :=
  ⨆ (l : List ℕ) (_ : (l.map deg).sum = w), (l.map D).prod

variable {D : ℕ → Submodule R B} {deg : ℕ → ℕ}

lemma list_prod_le_productsOfDegree (l : List ℕ) :
    (l.map D).prod ≤ productsOfDegree D deg (l.map deg).sum :=
  le_iSup₂_of_le (f := fun (l' : List ℕ) (_ : (l'.map deg).sum = (l.map deg).sum) =>
    (l'.map D).prod) l rfl le_rfl

/-- Concatenating products adds their degrees. -/
lemma productsOfDegree_mul_le (a b : ℕ) :
    productsOfDegree D deg a * productsOfDegree D deg b ≤ productsOfDegree D deg (a + b) := by
  unfold productsOfDegree
  rw [Submodule.iSup_mul]
  refine iSup_le fun l => ?_
  rw [Submodule.iSup_mul]
  refine iSup_le fun hl => ?_
  rw [Submodule.mul_iSup]
  refine iSup_le fun l' => ?_
  rw [Submodule.mul_iSup]
  refine iSup_le fun hl' => ?_
  refine le_iSup₂_of_le (l ++ l') (by simp [hl, hl']) ?_
  rw [List.map_append, List.prod_append]

end Submodule

namespace Subalgebra

open Submodule

/-!

## C. Subalgebras generated by homogeneous submodules

Throughout, `A` is generated by the submodules `D n` (`hA`), and `f` is the monomial
`X ^ deg n` on `D n` (`hD`).

-/

variable {A : Subalgebra R B} {f : B →ₐ[R] Polynomial B}
  {D : ℕ → Submodule R B} {deg : ℕ → ℕ}
  (hA : A = Algebra.adjoin R (⋃ n, (D n : Set B)))
  (hD : ∀ n, ∀ x ∈ D n, f x = Polynomial.monomial (deg n) x)

/-!

### C.1. Generators and coefficients

-/

include hA hD in
/-- A generator in `D n` has degree `deg n`. -/
lemma le_homogeneousSubmodule (n : ℕ) : D n ≤ A.homogeneousSubmodule f (deg n) :=
  fun x hx => mem_homogeneousSubmodule_iff.mpr
    ⟨hA ▸ Algebra.subset_adjoin (Set.mem_iUnion.mpr ⟨n, hx⟩), hD n x hx⟩

include hA hD in
/-- A product of generators has the sum of their degrees. -/
lemma list_prod_le_homogeneousSubmodule (l : List ℕ) :
    (l.map D).prod ≤ A.homogeneousSubmodule f (l.map deg).sum := by
  induction l with
  | nil => simpa using one_le_homogeneousSubmodule_zero
  | cons n l ih =>
    simp only [List.map_cons, List.prod_cons, List.sum_cons]
    exact (mul_le_mul' (le_homogeneousSubmodule hA hD n) ih).trans
      (homogeneousSubmodule_mul_le _ _)

include hA hD in
/-- The products of generators of total degree `w` lie in the degree-`w` part of `A`. -/
lemma productsOfDegree_le_homogeneousSubmodule (w : ℕ) :
    productsOfDegree D deg w ≤ A.homogeneousSubmodule f w :=
  iSup₂_le fun l hl => hl ▸ list_prod_le_homogeneousSubmodule hA hD l

include hA hD in
/-- Every coefficient of `f x`, for `x ∈ A`, is a sum of products of generators: the one
  induction over the generation of `A`. -/
lemma coeff_mem_productsOfDegree {x : B} (hx : x ∈ A) (m : ℕ) :
    (f x).coeff m ∈ productsOfDegree D deg m := by
  subst hA
  induction hx using Algebra.adjoin_induction generalizing m with
  | mem y hy =>
    obtain ⟨n, hn⟩ := Set.mem_iUnion.mp hy
    rw [hD n y hn, Polynomial.coeff_monomial]
    split_ifs with hw
    · exact hw ▸ list_prod_le_productsOfDegree [n] (by simpa using hn)
    · exact zero_mem _
  | algebraMap r =>
    rw [AlgHom.commutes, Polynomial.algebraMap_apply, Polynomial.coeff_C]
    split_ifs with hm
    · exact hm ▸ list_prod_le_productsOfDegree (D := D) (deg := deg) []
        (by simp [Submodule.algebraMap_mem r])
    · exact zero_mem _
  | add x y _ _ ihx ihy =>
    rw [map_add, Polynomial.coeff_add]
    exact add_mem (ihx m) (ihy m)
  | mul x y _ _ ihx ihy =>
    rw [map_mul, Polynomial.coeff_mul]
    refine sum_mem fun p hp => ?_
    rw [← Finset.mem_antidiagonal.mp hp]
    exact productsOfDegree_mul_le _ _ (mul_mem_mul (ihx p.1) (ihy p.2))

include hA hD in
/-- The coefficient of `X ^ m` in `f x`, for `x ∈ A`, lies in the degree-`m` part of `A`. -/
lemma coeff_mem_homogeneousSubmodule {x : B} (hx : x ∈ A) (m : ℕ) :
    (f x).coeff m ∈ A.homogeneousSubmodule f m :=
  productsOfDegree_le_homogeneousSubmodule hA hD m (coeff_mem_productsOfDegree hA hD hx m)

/-!

### C.2. Spanning by products of generators

-/

include hA hD in
/-- The degree-`w` part of `A` is spanned by the products of generators, in every order,
  whose degrees add up to `w`. -/
lemma homogeneousSubmodule_eq_productsOfDegree (w : ℕ) :
    A.homogeneousSubmodule f w = productsOfDegree D deg w := by
  refine le_antisymm (fun x hx => ?_) (productsOfDegree_le_homogeneousSubmodule hA hD w)
  obtain ⟨hxA, hxf⟩ := mem_homogeneousSubmodule_iff.mp hx
  simpa [hxf] using coeff_mem_productsOfDegree hA hD hxA w

/-!

### C.3. Removing the leftmost generator

-/

include hA hD in
/-- For positive `w`, the degree-`w` part of `A` is spanned by the products of a generator
  `D k` of degree at most `w` with the part of the remaining degree. The bound `n ≤ deg n`
  only makes the range of `k` finite. -/
lemma homogeneousSubmodule_eq_iSup_mul (hle : ∀ n, n ≤ deg n) {w : ℕ} (hw : 0 < w) :
    A.homogeneousSubmodule f w
      = ⨆ k ∈ (Finset.range (w + 1)).filter (fun k => deg k ≤ w),
          D k * A.homogeneousSubmodule f (w - deg k) := by
  refine le_antisymm ?_ (iSup₂_le fun k hk => ?_)
  · rw [homogeneousSubmodule_eq_productsOfDegree hA hD w]
    refine iSup₂_le fun l hl => ?_
    cases l with
    | nil => simp at hl; omega
    | cons n l =>
      simp only [List.map_cons, List.sum_cons] at hl
      have hn : n ∈ (Finset.range (w + 1)).filter (fun k => deg k ≤ w) :=
        Finset.mem_filter.mpr ⟨Finset.mem_range.mpr (by have := hle n; omega), by omega⟩
      refine le_iSup₂_of_le (f := fun k (_ : k ∈ (Finset.range (w + 1)).filter
        (fun k => deg k ≤ w)) => D k * A.homogeneousSubmodule f (w - deg k)) n hn ?_
      rw [List.map_cons, List.prod_cons, show w - deg n = (l.map deg).sum by omega]
      exact mul_le_mul' le_rfl (list_prod_le_homogeneousSubmodule hA hD l)
  · have hk := (Finset.mem_filter.mp hk).2
    refine (mul_le_mul' (le_homogeneousSubmodule hA hD k) le_rfl).trans ?_
    exact (homogeneousSubmodule_mul_le _ _).trans (le_of_eq (by congr 1; omega))

/-!

### C.4. Degree zero and the binary recursion

-/

include hA hD in
/-- If every generator has positive degree, degree zero is the scalar submodule. -/
lemma homogeneousSubmodule_zero_eq_one (hpos : ∀ n, 0 < deg n) :
    A.homogeneousSubmodule f 0 = 1 := by
  refine le_antisymm ?_ one_le_homogeneousSubmodule_zero
  rw [homogeneousSubmodule_eq_productsOfDegree hA hD 0]
  refine iSup₂_le fun l hl => ?_
  cases l with
  | nil => simp
  | cons n l =>
    have := hpos n
    simp only [List.map_cons, List.sum_cons] at hl
    omega

include hA hD in
/-- If `n < deg n` for every `n`, the degree-`i` part of `A`, for positive `i`, is spanned
  by the generators of degree `i` and the products of two parts of positive degrees adding
  up to `i`. It follows from removing the leftmost generator: a generator of degree `i`
  leaves degree zero, which is the scalars. -/
lemma homogeneousSubmodule_eq_sup_iSup_mul (hlt : ∀ n, n < deg n) (i : ℕ) (hi : 0 < i) :
    A.homogeneousSubmodule f i
      = (⨆ k ∈ Finset.univ.filter (fun k : Fin i => deg k = i), D k)
        ⊔ (⨆ p ∈ Finset.univ.filter (fun p : Fin i × Fin i => (p.1 : ℕ) + (p.2 : ℕ) = i),
            A.homogeneousSubmodule f p.1 * A.homogeneousSubmodule f p.2) := by
  refine le_antisymm ?_ (sup_le (iSup₂_le fun k hk => ?_) (iSup₂_le fun p hp => ?_))
  · rw [homogeneousSubmodule_eq_iSup_mul hA hD (fun n => (hlt n).le) hi]
    refine iSup₂_le fun k hk => ?_
    rcases (Finset.mem_filter.mp hk).2.eq_or_lt with hki | hki
    · rw [hki, Nat.sub_self, homogeneousSubmodule_zero_eq_one hA hD
        (fun n => Nat.zero_lt_of_lt (hlt n)), mul_one]
      refine le_sup_of_le_left (le_iSup₂_of_le (f := fun (k : Fin i)
        (_ : k ∈ Finset.univ.filter (fun k : Fin i => deg k = i)) => D k)
        ⟨k, hki ▸ hlt k⟩ (by simpa using hki) le_rfl)
    · refine le_sup_of_le_right (le_iSup₂_of_le (f := fun (p : Fin i × Fin i)
        (_ : p ∈ Finset.univ.filter (fun p : Fin i × Fin i => (p.1 : ℕ) + (p.2 : ℕ) = i)) =>
        A.homogeneousSubmodule f p.1 * A.homogeneousSubmodule f p.2)
        (⟨deg k, hki⟩, ⟨i - deg k, by have := hlt k; omega⟩) (by simp; omega) ?_)
      exact mul_le_mul' (le_homogeneousSubmodule hA hD k) le_rfl
  · exact (le_homogeneousSubmodule hA hD k).trans (le_of_eq (by rw [(Finset.mem_filter.mp hk).2]))
  · exact (homogeneousSubmodule_mul_le _ _).trans (le_of_eq (by rw [(Finset.mem_filter.mp hp).2]))

/-!

### C.5. Unreachable degrees

-/

include hA hD in
/-- If a set of degrees contains `0` and every `deg n` and is closed under addition, a
  degree outside it has zero part. This proves vanishing only: a degree in the set may
  still have zero part. -/
lemma homogeneousSubmodule_eq_bot (P : ℕ → Prop) (h0 : P 0) (hP : ∀ n, P (deg n))
    (hadd : ∀ a b, P a → P b → P (a + b)) {w : ℕ} (hw : ¬ P w) :
    A.homogeneousSubmodule f w = ⊥ := by
  have hl : ∀ l : List ℕ, P (l.map deg).sum := fun l => by
    induction l with
    | nil => simpa using h0
    | cons n l ih => simpa using hadd _ _ (hP n) ih
  rw [homogeneousSubmodule_eq_productsOfDegree hA hD w, eq_bot_iff]
  exact iSup₂_le fun l hw' => absurd (hw' ▸ hl l) hw

end Subalgebra
