/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Mathlib.Algebra.MvPolynomial.Funext
public import Mathlib.Algebra.MvPolynomial.Monad
public import Mathlib.Algebra.MvPolynomial.Supported
/-!
# Polynomials invariant under fiberwise translations of variables

Let `π` be an idempotent map on the index type of a multivariate polynomial ring
over an infinite integral domain, thought of as assigning to each variable a
canonical representative of its fiber. A polynomial that is invariant under
simultaneously translating, for each fiber, all the variables in that fiber by a
common constant is a polynomial in the differences `X i - X (π i)`.

This is the algebraic heart of the statement that the gauge-invariant elements of
the jet algebra of an abelian gauge boson are generated by the derivatives of the
field strength: the Maurer–Cartan shift translates all jet coordinates with the
same symmetrized multi-index by a common amount, and the differences of such
coordinates are the derivatives of the field strength.

-/

@[expose] public section

namespace MvPolynomial

variable {R : Type*} [CommRing R] [IsDomain R] [Infinite R]
variable {I : Type*} [DecidableEq I]

omit [IsDomain R] [Infinite R] [DecidableEq I] in
/-- Evaluation of a substitution of a multivariate polynomial: substitution followed
  by evaluation is evaluation at the evaluated substituents. -/
lemma eval_aeval (x : I → R) (g : I → MvPolynomial I R) (p : MvPolynomial I R) :
    eval x (aeval g p) = eval (fun i => eval x (g i)) p := by
  induction p using MvPolynomial.induction_on with
  | C a => simp
  | add p q hp hq => simp only [map_add, hp, hq]
  | mul_X p i hp => simp only [map_mul, aeval_X, hp, eval_X]

/-- A polynomial invariant under all translations of a fixed variable is unchanged
  by setting that variable to zero. -/
lemma aeval_update_zero_eq_of_forall_aeval_add_eq (Q : MvPolynomial I R) (j : I)
    (hQ : ∀ r : R, aeval (fun i => X i + C (if i = j then r else 0)) Q = Q) :
    aeval (fun i => if i = j then 0 else X i) Q = Q := by
  refine MvPolynomial.funext fun x => ?_
  have h := congrArg (eval x) (hQ (-(x j)))
  rw [eval_aeval] at h
  rw [eval_aeval]
  have hpt : (fun i => eval x ((if i = j then 0 else X i) : MvPolynomial I R)) =
      fun i => eval x (X i + C (if i = j then -(x j) else 0)) := by
    funext i
    by_cases hi : i = j
    · simp [hi]
    · simp [hi]
  rw [hpt]
  exact h

/-- A polynomial invariant under all translations of a fixed variable does not
  involve that variable. -/
lemma notMem_vars_of_forall_aeval_add_eq (Q : MvPolynomial I R) (j : I)
    (hQ : ∀ r : R, aeval (fun i => X i + C (if i = j then r else 0)) Q = Q) :
    j ∉ Q.vars := by
  intro hjv
  have h2 := vars_bind₁ (fun i => if i = j then 0 else X i) Q
    (by rw [show bind₁ (fun i => if i = j then (0 : MvPolynomial I R) else X i) Q =
        aeval (fun i => if i = j then 0 else X i) Q from rfl,
      aeval_update_zero_eq_of_forall_aeval_add_eq Q j hQ]
        exact hjv)
  obtain ⟨i, hiQ, hji⟩ := Finset.mem_biUnion.mp h2
  by_cases hij : i = j
  · rw [if_pos hij, vars_0] at hji
    simp at hji
  · rw [if_neg hij, vars_X] at hji
    exact hij (Finset.mem_singleton.mp hji).symm

/-- A multivariate polynomial over an infinite integral domain that is invariant
  under simultaneously translating, for every fiber of an idempotent map `π` on the
  variables, all the variables in that fiber by a common constant, is a polynomial
  in the differences `X i - X (π i)`. -/
theorem mem_adjoin_range_X_sub_X_of_forall_aeval_add_eq (π : I → I)
    (hπ : ∀ i, π (π i) = π i) (P : MvPolynomial I R)
    (hP : ∀ (i₀ : I) (r : R),
      aeval (fun i => X i + C (if π i = π i₀ then r else 0)) P = P) :
    P ∈ Algebra.adjoin R (Set.range fun i => (X i - X (π i) : MvPolynomial I R)) := by
  have hcompHom : (aeval (fun i => if π i = i then (X i : MvPolynomial I R)
      else X i - X (π i))).comp
      (aeval (fun i => if π i = i then (X i : MvPolynomial I R) else X i + X (π i))) =
      AlgHom.id R (MvPolynomial I R) := by
    apply algHom_ext
    intro i
    simp only [AlgHom.comp_apply, aeval_X, AlgHom.id_apply]
    by_cases hi : π i = i
    · rw [if_pos hi, aeval_X, if_pos hi]
    · rw [if_neg hi, map_add, aeval_X, aeval_X, if_neg hi, if_pos (hπ i)]
      ring
  have hcomp : ∀ p : MvPolynomial I R,
      aeval (fun i => if π i = i then (X i : MvPolynomial I R) else X i - X (π i))
        (aeval (fun i => if π i = i then (X i : MvPolynomial I R)
          else X i + X (π i)) p) = p := by
    intro p
    have h := DFunLike.congr_fun hcompHom p
    simpa using h
  have hQtrans : ∀ (j : I), π j = j → ∀ (r : R),
      aeval (fun i => (X i + C (if i = j then r else 0) : MvPolynomial I R))
        (aeval (fun i => if π i = i then (X i : MvPolynomial I R)
          else X i + X (π i)) P) =
      aeval (fun i => if π i = i then (X i : MvPolynomial I R)
        else X i + X (π i)) P := by
    intro j hj r
    have hkey : (aeval (fun i => X i + C (if i = j then r else 0))).comp
        (aeval (fun i => if π i = i then (X i : MvPolynomial I R)
          else X i + X (π i))) =
        (aeval (fun i => if π i = i then (X i : MvPolynomial I R)
          else X i + X (π i))).comp
          (aeval (fun i => X i + C (if π i = π j then r else 0))) := by
      apply algHom_ext
      intro i
      simp only [AlgHom.comp_apply, aeval_X]
      by_cases hi : π i = i
      · rw [if_pos hi]
        simp only [map_add, aeval_X, aeval_C, algebraMap_eq]
        rw [if_pos hi, if_congr (show (i = j) ↔ (π i = π j) from
          ⟨fun h => by rw [h], fun h => by rw [← hi, h, hj]⟩) rfl rfl]
      · rw [if_neg hi]
        simp only [map_add, aeval_X, aeval_C, algebraMap_eq]
        rw [if_neg hi, if_neg (show ¬i = j from fun h => hi (by rw [h, hj])),
          if_congr (show (π i = j) ↔ (π i = π j) from by rw [hj]) rfl rfl, C_0]
        ring
    have h1 := DFunLike.congr_fun hkey P
    simp only [AlgHom.comp_apply] at h1
    rw [hP j r] at h1
    exact h1
  have hQsupp : aeval (fun i => if π i = i then (X i : MvPolynomial I R)
      else X i + X (π i)) P ∈
      supported R {i : I | π i ≠ i} := by
    refine mem_supported.mpr fun j hj => ?_
    intro hjfix
    exact notMem_vars_of_forall_aeval_add_eq _ j (hQtrans j hjfix) (Finset.mem_coe.mp hj)
  rw [supported_eq_adjoin_X] at hQsupp
  have hmem : P ∈ (Algebra.adjoin R (X '' {i : I | π i ≠ i})).map
      (aeval (fun i => if π i = i then (X i : MvPolynomial I R)
        else X i - X (π i))) :=
    Subalgebra.mem_map.mpr ⟨_, hQsupp, hcomp P⟩
  rw [AlgHom.map_adjoin] at hmem
  refine Algebra.adjoin_mono ?_ hmem
  rintro _ ⟨_, ⟨i, hi, rfl⟩, rfl⟩
  refine ⟨i, ?_⟩
  simp only [aeval_X]
  rw [if_neg (Set.mem_setOf.mp hi)]

end MvPolynomial
