/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
public import Mathlib.RingTheory.TensorProduct.Maps
public import Mathlib.Algebra.TrivSqZeroExt.Basic
/-!
# Functoriality of the symmetric algebra

## i. Overview

Mathlib's `SymmetricAlgebra` carries the universal property `SymmetricAlgebra.lift` but no
functorial API. This file provides it: the algebra homomorphism induced by a linear map, the
algebra equivalence induced by a linear equivalence, generation by the degree-one elements,
and the decomposition of the symmetric algebra of a direct sum as a tensor product — the
bosonic analogue of `CliffordAlgebra.prodEquiv`, with the ordinary rather than the graded
tensor product because everything commutes.

## ii. Key results

- `SymmetricAlgebra.map` : the algebra homomorphism induced by a linear map.
- `SymmetricAlgebra.congr` : the algebra equivalence induced by a linear equivalence.
- `SymmetricAlgebra.adjoin_range_ι` : the symmetric algebra is generated by `ι`.
- `SymmetricAlgebra.prodEquiv` : the symmetric algebra of a direct sum is the tensor
  product of the symmetric algebras.

## iii. Table of contents

- A. Functoriality of the symmetric algebra
- B. Generation by the degree-one elements
- C. The symmetric algebra of a direct sum
- D. The derivation extending a linear endomorphism

-/

@[expose] public section

namespace SymmetricAlgebra

variable {R M N P : Type*} [CommRing R] [AddCommGroup M] [Module R M]
  [AddCommGroup N] [Module R N] [AddCommGroup P] [Module R P]

/-!

## A. Functoriality of the symmetric algebra

-/

/-- The algebra homomorphism between symmetric algebras induced by a linear map of the
  underlying modules. -/
def map (f : M →ₗ[R] N) : SymmetricAlgebra R M →ₐ[R] SymmetricAlgebra R N :=
  lift ((ι R N) ∘ₗ f)

@[simp]
lemma map_apply_ι (f : M →ₗ[R] N) (x : M) : map f (ι R M x) = ι R N (f x) :=
  lift_ι_apply _ x

@[simp]
lemma map_id : map (LinearMap.id : M →ₗ[R] M) = AlgHom.id R (SymmetricAlgebra R M) :=
  algHom_ext (LinearMap.ext fun x => by simp)

lemma map_comp_map (f : N →ₗ[R] P) (g : M →ₗ[R] N) :
    (map f).comp (map g) = map (f ∘ₗ g) :=
  algHom_ext (LinearMap.ext fun x => by simp)

/-- The algebra equivalence between symmetric algebras induced by a linear equivalence of
  the underlying modules. -/
def congr (e : M ≃ₗ[R] N) : SymmetricAlgebra R M ≃ₐ[R] SymmetricAlgebra R N :=
  AlgEquiv.ofAlgHom (map e.toLinearMap) (map e.symm.toLinearMap)
    (by rw [map_comp_map]; simp)
    (by rw [map_comp_map]; simp)

@[simp]
lemma congr_apply_ι (e : M ≃ₗ[R] N) (x : M) : congr e (ι R M x) = ι R N (e x) :=
  map_apply_ι _ x

/-!

## B. Generation by the degree-one elements

-/

/-- The symmetric algebra is generated, as an `R`-algebra, by the degree-one elements. -/
@[simp]
lemma adjoin_range_ι :
    Algebra.adjoin R (Set.range (ι R M)) = (⊤ : Subalgebra R (SymmetricAlgebra R M)) := by
  have h : ∀ x : SymmetricAlgebra R M, x ∈ Algebra.adjoin R (Set.range (ι R M)) := by
    intro x
    induction x using SymmetricAlgebra.induction with
    | algebraMap r => exact Subalgebra.algebraMap_mem _ r
    | ι x => exact Algebra.subset_adjoin ⟨x, rfl⟩
    | mul a b ha hb => exact mul_mem ha hb
    | add a b ha hb => exact add_mem ha hb
  exact top_le_iff.mp fun x _ => h x

/-!

## C. The symmetric algebra of a direct sum

The symmetric algebra of `M × N` is the tensor product of the symmetric algebras of the
summands. Unlike the exterior-algebra analogue this is the *ordinary* tensor product: the
generators of the two factors commute, as bosonic generators must.

-/

open TensorProduct

/-- The forward half of `prodEquiv`: a generator `(m, n)` is sent to
  `ι m ⊗ 1 + 1 ⊗ ι n`. -/
noncomputable def prodToTensor :
    SymmetricAlgebra R (M × N) →ₐ[R] SymmetricAlgebra R M ⊗[R] SymmetricAlgebra R N :=
  lift (LinearMap.coprod
    ((Algebra.TensorProduct.includeLeft.toLinearMap : SymmetricAlgebra R M →ₗ[R] _) ∘ₗ ι R M)
    ((Algebra.TensorProduct.includeRight.toLinearMap : SymmetricAlgebra R N →ₗ[R] _) ∘ₗ ι R N))

@[simp]
lemma prodToTensor_ι (x : M × N) :
    prodToTensor (ι R (M × N) x)
      = ι R M x.1 ⊗ₜ[R] 1 + (1 : SymmetricAlgebra R M) ⊗ₜ[R] ι R N x.2 :=
  lift_ι_apply _ x

/-- The backward half of `prodEquiv`: the two inclusions of the factors, multiplied
  together. -/
noncomputable def tensorToProd :
    SymmetricAlgebra R M ⊗[R] SymmetricAlgebra R N →ₐ[R] SymmetricAlgebra R (M × N) :=
  Algebra.TensorProduct.lift (map (LinearMap.inl R M N)) (map (LinearMap.inr R M N))
    fun _ _ => Commute.all _ _

@[simp]
lemma tensorToProd_tmul (a : SymmetricAlgebra R M) (b : SymmetricAlgebra R N) :
    tensorToProd (a ⊗ₜ[R] b) = map (LinearMap.inl R M N) a * map (LinearMap.inr R M N) b :=
  Algebra.TensorProduct.lift_tmul _ _ _ _ _

/-- **The symmetric algebra of a direct sum is the tensor product of the symmetric
  algebras.** Two bosonic fields taken together are one field valued in the direct sum of
  their target spaces; their generators commute, so the ordinary tensor product suffices —
  no grading is needed, in contrast to the exterior-algebra analogue. -/
noncomputable def prodEquiv :
    SymmetricAlgebra R (M × N) ≃ₐ[R] SymmetricAlgebra R M ⊗[R] SymmetricAlgebra R N :=
  AlgEquiv.ofAlgHom prodToTensor tensorToProd
    (Algebra.TensorProduct.ext
      (algHom_ext (LinearMap.ext fun m => by
        simp [Algebra.TensorProduct.includeLeft_apply]))
      (algHom_ext (LinearMap.ext fun n => by
        simp [Algebra.TensorProduct.includeRight_apply])))
    (algHom_ext (LinearMap.ext fun x => by
      have hx : ((x.1, (0 : N)) : M × N) + ((0 : M), x.2) = x := by
        refine Prod.ext ?_ ?_ <;> simp
      calc (tensorToProd.comp prodToTensor) (ι R (M × N) x)
          = tensorToProd (ι R M x.1 ⊗ₜ[R] 1 + (1 : SymmetricAlgebra R M) ⊗ₜ[R] ι R N x.2) := by
            rw [AlgHom.comp_apply, prodToTensor_ι]
        _ = ι R (M × N) (x.1, 0) + ι R (M × N) (0, x.2) := by
            rw [map_add, tensorToProd_tmul, tensorToProd_tmul, map_one, map_one, mul_one,
              one_mul, map_apply_ι, map_apply_ι]
            rfl
        _ = ι R (M × N) x := by rw [← map_add, hx]
        _ = (AlgHom.id R (SymmetricAlgebra R (M × N))) (ι R (M × N) x) := rfl))

@[simp]
lemma prodEquiv_ι (x : M × N) :
    prodEquiv (ι R (M × N) x)
      = ι R M x.1 ⊗ₜ[R] 1 + (1 : SymmetricAlgebra R M) ⊗ₜ[R] ι R N x.2 :=
  prodToTensor_ι x

/-!

## D. The derivation extending a linear endomorphism

A linear endomorphism `d` of `M` extends uniquely to a derivation of the symmetric algebra:
the map obeying the Leibniz rule whose value on a generator `ι x` is `ι (d x)`. It is built
by lifting the generator map `ι x ↦ (ι x, ι (d x))` to an algebra homomorphism into the
trivial square-zero extension and taking the second component.

-/

section Derivation

variable (d : M →ₗ[R] M)

/-- The lift of the derivation extending `d` to the trivial square-zero extension of the
  symmetric algebra: the algebra homomorphism `x ↦ (x, derivationOfLinear d x)`. -/
noncomputable def derivationHom :
    SymmetricAlgebra R M →ₐ[R]
      TrivSqZeroExt (SymmetricAlgebra R M) (SymmetricAlgebra R M) :=
  lift
    { toFun := fun x => (ι R M x, ι R M (d x))
      map_add' := fun x y => by simp only [map_add]; rfl
      map_smul' := fun c x => by simp only [map_smul, RingHom.id_apply]; rfl }

@[simp]
lemma derivationHom_ι (x : M) :
    derivationHom d (ι R M x) = (ι R M x, ι R M (d x)) :=
  lift_ι_apply _ x

/-- The first component of the square-zero lift is the identity. -/
@[simp]
lemma derivationHom_fst (x : SymmetricAlgebra R M) : (derivationHom d x).fst = x := by
  have h : (TrivSqZeroExt.fstHom R (SymmetricAlgebra R M) (SymmetricAlgebra R M)).comp
      (derivationHom d) = AlgHom.id R (SymmetricAlgebra R M) :=
    algHom_ext (LinearMap.ext fun x => by simp; rfl)
  exact DFunLike.congr_fun h x

/-- **The derivation of the symmetric algebra extending a linear endomorphism** `d` of `M`:
  the map obeying the Leibniz rule whose value on a generator `ι x` is `ι (d x)`. -/
noncomputable def derivationOfLinear : SymmetricAlgebra R M →ₗ[R] SymmetricAlgebra R M where
  toFun x := (derivationHom d x).snd
  map_add' x y := congrArg TrivSqZeroExt.snd (map_add (derivationHom d) x y)
  map_smul' c x := congrArg TrivSqZeroExt.snd (map_smul (derivationHom d) c x)

@[simp]
lemma derivationOfLinear_ι (x : M) :
    derivationOfLinear d (ι R M x) = ι R M (d x) := by
  rw [show derivationOfLinear d (ι R M x) = (derivationHom d (ι R M x)).snd from rfl,
    derivationHom_ι]
  rfl

@[simp]
lemma derivationOfLinear_one : derivationOfLinear d (1 : SymmetricAlgebra R M) = 0 :=
  congrArg TrivSqZeroExt.snd (map_one (derivationHom d))

@[simp]
lemma derivationOfLinear_algebraMap (r : R) :
    derivationOfLinear d (algebraMap R (SymmetricAlgebra R M) r) = 0 := by
  rw [Algebra.algebraMap_eq_smul_one, map_smul, derivationOfLinear_one, smul_zero]

/-- The Leibniz rule for the derivation extending `d`. -/
lemma derivationOfLinear_mul (x y : SymmetricAlgebra R M) :
    derivationOfLinear d (x * y)
      = derivationOfLinear d x * y + x * derivationOfLinear d y := by
  have h : derivationOfLinear d (x * y) =
      (derivationHom d x).fst * derivationOfLinear d y
        + derivationOfLinear d x * (derivationHom d y).fst :=
    congrArg TrivSqZeroExt.snd (map_mul (derivationHom d) x y)
  rw [derivationHom_fst, derivationHom_fst] at h
  exact h.trans (add_comm _ _)

/-- Derivations extending commuting endomorphisms commute. -/
lemma derivationOfLinear_comm_apply {d₁ d₂ : M →ₗ[R] M} (h : d₁ ∘ₗ d₂ = d₂ ∘ₗ d₁)
    (x : SymmetricAlgebra R M) :
    derivationOfLinear d₁ (derivationOfLinear d₂ x)
      = derivationOfLinear d₂ (derivationOfLinear d₁ x) := by
  induction x using SymmetricAlgebra.induction with
  | algebraMap r => simp
  | ι v =>
    simp only [derivationOfLinear_ι]
    exact congrArg (ι R M) (DFunLike.congr_fun h v)
  | mul x y hx hy =>
    simp only [derivationOfLinear_mul, map_add, hx, hy]
    exact add_add_add_comm _ _ _ _
  | add x y hx hy => simp only [map_add, hx, hy]

end Derivation

end SymmetricAlgebra
