/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.ProbabilisticTheory.JordanOrderUnit.Power.Associative

/-!

# The subalgebra generated by one observable

## i. Overview

The span `J[a]` of the powers of an observable `a` contains `1` and `a` and is closed under the
Jordan product.

## ii. Key results

- `JordanAlgebra.generatedByOne` : the span of the powers of `a`.
- `JordanAlgebra.mul_mem_generatedByOne` : it is closed under the Jordan product.

## iii. Table of contents

- A. The generated submodule
- B. Closure under the Jordan product

-/

@[expose] public section

namespace ProbabilisticTheory

namespace JordanAlgebra

variable {E : Type*} [NonAssocCommRing E] [Module ℝ E] [SMulCommClass ℝ E E]
  [IsScalarTower ℝ E E] [IsCommJordan E]

open scoped JordanAlgebra

/-! ## A. The generated submodule -/

/-- The subalgebra generated by `1` and `a`, as an ℝ-submodule: the span of all Jordan powers of
`a` (which already includes `a^{[0]} = 1`). -/
def generatedByOne (a : E) : Submodule ℝ E := Submodule.span ℝ (Set.range (jpow a))

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
lemma jpow_mem_generatedByOne (a : E) (n : ℕ) : a ^[n] ∈ generatedByOne a :=
  Submodule.subset_span ⟨n, rfl⟩

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
lemma one_mem_generatedByOne (a : E) : (1 : E) ∈ generatedByOne a := by
  have h := jpow_mem_generatedByOne a 0
  rwa [jpow_zero] at h

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
lemma self_mem_generatedByOne (a : E) : a ∈ generatedByOne a := by
  have h := jpow_mem_generatedByOne a 1
  rwa [jpow_one] at h

/-! ## B. Closure under the Jordan product -/

/-- `J[a]` is closed under the Jordan product. -/
lemma mul_mem_generatedByOne (a : E) {x y : E} (hx : x ∈ generatedByOne a)
    (hy : y ∈ generatedByOne a) : x * y ∈ generatedByOne a := by
  induction hx, hy using Submodule.span_induction₂ with
  | mem_mem x y hx hy =>
      obtain ⟨m, rfl⟩ := hx
      obtain ⟨n, rfl⟩ := hy
      exact pow_add a m n ▸ jpow_mem_generatedByOne a (m + n)
  | zero_left => simp
  | zero_right => simp
  | add_left _ _ _ _ _ _ ihx ihy => simpa [add_mul] using (generatedByOne a).add_mem ihx ihy
  | add_right _ _ _ _ _ _ ihy ihz => simpa [mul_add] using (generatedByOne a).add_mem ihy ihz
  | smul_left r _ _ _ _ ih => simpa [smul_mul_assoc] using (generatedByOne a).smul_mem r ih
  | smul_right r _ _ _ _ ih => simpa [mul_smul_comm] using (generatedByOne a).smul_mem r ih

end JordanAlgebra

end ProbabilisticTheory
